In [1]:
import os

MB_DIR = r"../data_raw/musicbrainz/mbdump/mbdump"
TABLES = ["artist", "artist_credit_name", "medium"]

def check_table(path: str, delimiter: str = "\t", n_lines: int = 50):
    name = os.path.basename(path)
    print(f"\n--- Checking {name} ---")
    with open(path, "r", encoding="utf-8") as f:
        first = f.readline().rstrip("\n")
        cols_first = first.split(delimiter)
        expected = len(cols_first)
        print(f"✅ Read first line")
        print(f"📊 Column count (line 1): {expected}")

        mismatches = 0
        last_i = 1
        for i in range(2, n_lines + 1):
            line = f.readline()
            if not line:
                last_i = i - 1
                break
            cols = line.rstrip("\n").split(delimiter)
            if len(cols) != expected:
                mismatches += 1
                if mismatches <= 3:
                    print(f"⚠️ Mismatch at line {i}: got {len(cols)} expected {expected}")
            last_i = i

        if mismatches == 0:
            print(f"✅ Column count consistent for first {last_i} lines")
        else:
            print(f"⚠️ Total mismatches in first {min(n_lines, last_i)} lines: {mismatches}")

        if "\\N" in cols_first:
            print("⚠️ Found '\\N' in line 1 (NULL marker present)")
        else:
            print("ℹ️ No '\\N' in line 1 (still use nullstr='\\\\N' when loading)")

for t in TABLES:
    fp = os.path.join(MB_DIR, t)
    if not os.path.exists(fp):
        print(f"\n❌ File not found: {fp}")
        continue
    check_table(fp)

--- Checking artist ---
✅ Read first line
📊 Column count (line 1): 19
✅ Column count consistent for first 50 lines
⚠️ Found '\N' in line 1 (NULL marker present)

--- Checking artist_credit_name ---
✅ Read first line
📊 Column count (line 1): 5
✅ Column count consistent for first 50 lines
ℹ️ No '\N' in line 1 (still use nullstr='\\N' when loading)

--- Checking medium ---
✅ Read first line
📊 Column count (line 1): 9
✅ Column count consistent for first 50 lines
ℹ️ No '\N' in line 1 (still use nullstr='\\N' when loading)

In [11]:
import duckdb

# Connect to the existing DuckDB database file.
# This creates a "working copy" database in data_processed/ and keeps the raw MusicBrainz dump immutable.
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

print("Importing MusicBrainz 'artist' (19 columns)...")

# Ingest the MusicBrainz "artist" dump file into DuckDB.
# Important details:
# - header=false because MusicBrainz TSV dumps have no header row.
# - delim='\t' because the dumps are tab-separated.
# - nullstr='\\N' because MusicBrainz uses the PostgreSQL NULL marker \N in its TSV exports.
# - columns={...} explicitly defines the schema (names + types) so the 19 fields are aligned correctly.
#   This prevents silent column shifts and enables correct type casting (INTEGER/BOOLEAN/TIMESTAMP).

con.execute("""
    CREATE OR REPLACE TABLE mb_artist AS
    SELECT * FROM read_csv(
        '../data_raw/musicbrainz/mbdump/mbdump/artist',
        header = false,
        delim = '\t',
        nullstr = '\\N',

        columns = {
            'id': 'INTEGER',
            'gid': 'VARCHAR',
            'name': 'VARCHAR',
            'sort_name': 'VARCHAR',
            'begin_date_year': 'INTEGER',
            'begin_date_month': 'INTEGER',
            'begin_date_day': 'INTEGER',
            'end_date_year': 'INTEGER',
            'end_date_month': 'INTEGER',
            'end_date_day': 'INTEGER',
            'type': 'INTEGER',
            'area': 'INTEGER',
            'gender': 'INTEGER',
            'comment': 'VARCHAR',
            'edits_pending': 'INTEGER',
            'last_updated': 'TIMESTAMP',
            'ended': 'BOOLEAN',
            'begin_area': 'INTEGER',
            'end_area': 'INTEGER'
        }
    );
""")

print("✅ mb_artist table created!")

# Quick proof
print("\n--- Preview ---")
print(con.execute("SELECT id, name, sort_name, type, area FROM mb_artist LIMIT 5").fetchdf())

print("\n--- Row count (optional but useful) ---")
print(con.execute("SELECT COUNT(*) AS n FROM mb_artist").fetchdf())
# Sanity check: preview a few rows to confirm parsing worked and key columns look reasonable.
# We also print a row count to confirm the table is populated.

Connected ✅
Importing MusicBrainz 'artist' (19 columns)...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

✅ mb_artist table created!

--- Preview ---
        id           name      sort_name  type  area
0  2252039  Доктор Сатана  Доктор Сатана  <NA>  <NA>
1   371203    Pete Moutso   Moutso, Pete     1  <NA>
2  3087346           UNlT           UNlT  <NA>  <NA>
3  2851271      Babyglock      Babyglock  <NA>  <NA>
4   145773   Aric Leavitt  Leavitt, Aric  <NA>  <NA>

--- Row count (optional but useful) ---
         n
0  2807098

In [4]:
import duckdb

# Always connect
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

print("Importing MusicBrainz 'artist_credit_name' (5 columns)...")

con.execute("""
    CREATE OR REPLACE TABLE mb_artist_credit_name AS
    SELECT * FROM read_csv(
        '../data_raw/musicbrainz/mbdump/mbdump/artist_credit_name',
        header = false,
        delim = '\t',
        nullstr = '\\N',
        columns = {
            'artist_credit': 'INTEGER',
            'position': 'INTEGER',
            'artist': 'INTEGER',
            'name': 'VARCHAR',
            'join_phrase': 'VARCHAR'
        }
    );
""")

print("✅ mb_artist_credit_name table created!")

# Proof / sanity check
print("\n--- Preview ---")
print(con.execute("""
    SELECT artist_credit, position, artist, name, join_phrase
    FROM mb_artist_credit_name
    ORDER BY artist_credit, position
    LIMIT 10
""").fetchdf())

print("\n--- Row count ---")
print(con.execute("SELECT COUNT(*) AS n FROM mb_artist_credit_name").fetchdf())

Connected ✅
Importing MusicBrainz 'artist_credit_name' (5 columns)...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

✅ mb_artist_credit_name table created!

--- Preview ---
   artist_credit  position  artist                  name join_phrase
0              1         0       1       Various Artists
1              4         0       4        Massive Attack
2              6         0       6          Apartment 26
3              7         0       7              Dr. Evil
4              9         0       9          Robert Miles
5             10         0      10         Vincent Gallo
6             11         0      11  Squirrel Nut Zippers
7             12         0      12            Giant Sand
8             15         0      15            Éric Serra
9             16         0      16  William S. Burroughs

--- Row count ---
         n
0  6642750

In [10]:
import duckdb

# Always connect
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

print("Importing MusicBrainz 'medium' (9 columns) with corrected schema...")

con.execute("""
    CREATE OR REPLACE TABLE mb_medium AS
    SELECT * FROM read_csv(
        '../data_raw/musicbrainz/mbdump/mbdump/medium',
        header = false,
        delim = '\t',
        nullstr = '\\N',
        columns = {
            'id': 'BIGINT',
            'release': 'BIGINT',
            'position': 'BIGINT',
            'format': 'BIGINT',
            'name': 'VARCHAR',
            'edits_pending': 'BIGINT',
            'last_updated': 'TIMESTAMPTZ',
            'track_count': 'BIGINT',
            'tracklist': 'VARCHAR'
        }
    );
""")

print("✅ mb_medium table created!")

# Proof / sanity check
print("\n--- Preview ---")
print(con.execute("""
    SELECT id, release, position, format, name, track_count, tracklist, last_updated
    FROM mb_medium
    LIMIT 10
""").fetchdf())

print("\n--- Row count ---")
print(con.execute("SELECT COUNT(*) AS n FROM mb_medium").fetchdf())

Connected ✅
Importing MusicBrainz 'medium' (9 columns) with corrected schema...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

✅ mb_medium table created!

--- Preview ---
        id  release  position  format name  track_count  \
0  3316155  3046812         1       8                 8
1  5434234  4997020         1      12                 1
2  5500452  5059003         1      12                 1
3  5648581  5196850         1      12                 1
4  5439958  5002457         1      29                 2
5  5506285  5064328         1      12                 1
6  5570073  5123945         1      12                 2
7  5653374  5201344         1      12                 1
8  5738436  5281321         1      12                 1
9  5511562  5069293         1       1                 8

                              tracklist                     last_updated
0  4ecb0d23-669b-33cd-911d-dd12c42dfb67 2026-02-02 16:00:52.332103+01:00
1  9560d0bb-b9e8-4050-8c1b-f4740304c056 2025-05-19 20:02:17.904703+02:00
2  bb6dabf2-25aa-43b7-a8d1-226ba17d42ab 2025-06-24 02:57:19.742813+02:00
3  445a31f3-84b8-4a28-90ef-d91ecee907bc 2025-09-07 18:58:38.535280+02:00
4  134424ae-5eef-4109-a343-c88b69fc2eac 2025-05-23 00:04:09.852148+02:00
5  0d7fb736-ab84-45bb-85fd-41cdf16d8c5d 2025-06-27 13:20:01.740625+02:00
6  7fee2645-7bfa-4263-b553-05f57dfa24a5 2025-07-31 10:24:17.198998+02:00
7  4e2d1650-0fe7-4903-a311-90dc1be0e32d 2025-09-10 02:57:10.689946+02:00
8  5da4e502-9493-43a9-b01a-1cc027656253 2025-10-20 05:20:32.620173+02:00
9  db386ecc-4df4-4be2-9a21-c704a878cd65 2025-06-30 02:59:41.481649+02:00

--- Row count ---
         n
0  5847659

In [1]:
import duckdb

# Always connect
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

path = "../data_raw/musicbrainz/mbdump/mbdump/artist_credit"

# 1) Column count (line 1)
with open(path, "r", encoding="utf-8") as f:
    first = f.readline().rstrip("\n")
col_count = len(first.split("\t"))
print(f"artist_credit column count (line 1): {col_count}")

print("Importing artist_credit safely as VARCHAR columns (so it never fails)...")

# 2) Build a dynamic columns mapping: c1..cN as VARCHAR
cols_map = ",\n            ".join([f"'c{i}': 'VARCHAR'" for i in range(1, col_count + 1)])

con.execute(f"""
    CREATE OR REPLACE TABLE mb_artist_credit_raw AS
    SELECT * FROM read_csv(
        '{path}',
        header = false,
        delim = '\\t',
        nullstr = '\\\\N',
        columns = {{
            {cols_map}
        }}
    );
""")

print("✅ mb_artist_credit_raw created!")

# 3) Create the core table we actually need (id + full credit name)
# Assumption (based on MB schema and your screenshot): column 1 = id, column 2 = name
con.execute("""
    CREATE OR REPLACE TABLE mb_artist_credit_core AS
    SELECT
        CAST(c1 AS BIGINT) AS id,
        c2 AS name
    FROM mb_artist_credit_raw;
""")

print("✅ mb_artist_credit_core (id, name) created!")

print("\n--- Preview core ---")
print(con.execute("SELECT * FROM mb_artist_credit_core LIMIT 10").fetchdf())

print("\n--- Row count core ---")
print(con.execute("SELECT COUNT(*) AS n FROM mb_artist_credit_core").fetchdf())

Connected ✅

OSError: [Errno 22] Invalid argument

In [12]:
import duckdb
con = duckdb.connect("../data_processed/thesis.duckdb")

# This lists all tables currently in your database
print("Tables currently in your database:")
print(con.execute("SHOW TABLES").fetchdf())

con.close()

Tables currently in your database:
                    name
0              mb_artist
1  mb_artist_credit_core
2  mb_artist_credit_name
3   mb_artist_credit_raw
4              mb_medium
5             mb_release

In [11]:
import duckdb

# Always connect
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

print("Building mb_release_features (title + full artist credit + main artist + total tracks)...")

con.execute("""
    CREATE OR REPLACE TABLE mb_release_features AS
    WITH main_artist AS (
        -- Main artist = first entry in the artist credit list (position = 0)
        SELECT
            acn.artist_credit,
            a.name AS main_artist_name
        FROM mb_artist_credit_name acn
        JOIN mb_artist a
            ON a.id = acn.artist
        WHERE acn.position = 0
    ),
    tracks AS (
        -- Total tracks per release = sum of track_count across all media (CD1+CD2+...)
        SELECT
            release AS release_id,
            SUM(track_count) AS total_tracks
        FROM mb_medium
        GROUP BY release
    )
    SELECT
        r.id AS release_id,
        r.name AS release_title,
        r.barcode,
        r.artist_credit AS artist_credit_id,
        ac.name AS artist_credit_full,
        ma.main_artist_name,
        EXTRACT(YEAR FROM r.last_updated) AS mb_year,
        t.total_tracks
    FROM mb_release r
    LEFT JOIN mb_artist_credit_core ac
        ON ac.id = r.artist_credit
    LEFT JOIN main_artist ma
        ON ma.artist_credit = r.artist_credit
    LEFT JOIN tracks t
        ON t.release_id = r.id;
""")

print("✅ mb_release_features created!")

print("\n--- Preview ---")
print(con.execute("""
    SELECT release_id, release_title, artist_credit_full, main_artist_name, total_tracks, barcode, mb_year
    FROM mb_release_features
    WHERE main_artist_name IS NOT NULL
    LIMIT 10
""").fetchdf())

print("\n--- Row count ---")
print(con.execute("SELECT COUNT(*) AS n FROM mb_release_features").fetchdf())

print("\n--- Missing values check ---")
print(con.execute("""
    SELECT
      SUM(CASE WHEN artist_credit_full IS NULL THEN 1 ELSE 0 END) AS missing_artist_credit_full,
      SUM(CASE WHEN main_artist_name IS NULL THEN 1 ELSE 0 END) AS missing_main_artist,
      SUM(CASE WHEN mb_year IS NULL THEN 1 ELSE 0 END) AS missing_mb_year,
      SUM(CASE WHEN total_tracks IS NULL THEN 1 ELSE 0 END) AS missing_total_tracks
    FROM mb_release_features
""").fetchdf())

Connected ✅
Building mb_release_features (title + full artist credit + main artist + total tracks)...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

✅ mb_release_features created!

--- Preview ---
   release_id                         release_title           artist_credit_full main_artist_name  total_tracks        barcode  mb_year
0      178087  Blechdance: Ritter Rost zum Abtanzen  Jörg Hilbert & Felix Janosa     Jörg Hilbert          11.0  9783898351300     2010
1      178088                                 Verte                        Judy4            Judy4          11.0           None     <NA>
2      178097                             Egouality                          WaK              WaK          14.0           None     <NA>
3      178098                             Egouality                          WaK              WaK          14.0           None     <NA>
4      178100                             Démo 2005                          WaK              WaK           4.0           None     <NA>
5      178101                             Démo 2005                          WaK              WaK           4.0           None     <NA>
6     1210603           The Greatest Hits, Volume 2              Jerry Lee Lewis  Jerry Lee Lewis          18.0  5010946684023     2014
7      178107                            Encounter!                 Pepper Adams     Pepper Adams           8.0           None     <NA>
8      178109                               Popcore                   Mike Tichy       Mike Tichy          11.0           None     <NA>
9      319607                                  DUNK                         鈴木雅之             鈴木雅之           2.0  4988010384616     2011

--- Row count ---
         n
0  5309878

--- Missing values check ---
   missing_artist_credit_full  missing_main_artist  missing_mb_year  missing_total_tracks
0                         0.0                  0.0         100307.0                4440.0

In [15]:
#deletes the old CSVs, then writes the new ones.
import duckdb
import os

# Connect
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# Output folder
out_dir = "../data_processed/exports"
os.makedirs(out_dir, exist_ok=True)

tables = [
    "mb_release_features",   
]

for table in tables:
    out_path = os.path.join(out_dir, f"{table}.csv")

    # Delete old CSV if it already exists
    if os.path.exists(out_path):
        os.remove(out_path)
        print(f"🗑️ Deleted old file: {out_path}")

    # Export fresh CSV
    con.execute(f"""
        COPY (
            SELECT *
            FROM {table}
        ) TO '{out_path}'
        (HEADER, DELIMITER ',');
    """)
    print(f"✅ Exported new file: {out_path}")

con.close()
print("Done ✅")

Connected ✅
🗑️ Deleted old file: ../data_processed/exports\mb_release_features.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

✅ Exported new file: ../data_processed/exports\mb_release_features.csv
Done ✅

In [144]:
import duckdb

# Always connect
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

print("Loading CDS (cds_clean.tsv) into DuckDB (tracks kept as TEXT)...")

# ----------------------------
# Step A: Load CDS clean TSV safely
# ----------------------------
# Comments:
# - The CDS column called "tracks" is actually a tracklist (TEXT), not a numeric track count.
# - Therefore we do NOT cast it to BIGINT.
# - We cast only cds_id and cds_year (safe numeric fields).
# - We keep the tracklist in a column called cds_tracklist for clarity.
# - We use read_csv with explicit column names/types because read_csv_auto
#   failed to detect the TSV dialect reliably.
# - strict_mode=false / ignore_errors=true / null_padding=true make loading
#   more robust for messy TSV rows.
con.execute(r"""
    CREATE OR REPLACE TABLE cds AS
    SELECT
        artist,
        category,
        genre,
        TRY_CAST(id AS BIGINT) AS cds_id,
        title,
        tracks,
        TRY_CAST(year AS INTEGER) AS cds_year
    FROM read_csv(
        '../data_raw/hpi_cd/cds_clean.tsv',
        delim='\t',
        header=true,
        columns={
            'artist': 'VARCHAR',
            'category': 'VARCHAR',
            'genre': 'VARCHAR',
            'id': 'VARCHAR',
            'title': 'VARCHAR',
            'tracks': 'VARCHAR',
            'year': 'VARCHAR'
        },
        quote='"',
        escape='"',
        null_padding=true,
        ignore_errors=true,
        strict_mode=false
    );
""")

print("✅ cds table created!")

print("\n--- CDS preview ---")
print(con.execute("""
    SELECT cds_id, artist, title, cds_year, substr(tracks, 1, 80) AS tracks
    FROM cds
    LIMIT 10
""").fetchdf())

print("\n--- CDS row count ---")
print(con.execute("SELECT COUNT(*) AS n FROM cds").fetchdf())

# ----------------------------
# Step B: Normalized view for matching
# ----------------------------
# Comments:
# - We build normalized keys for artist and title to reduce differences from punctuation/case.
# - This is a high-precision baseline before fuzzy matching.
con.execute(r"""
    CREATE OR REPLACE VIEW cds_norm AS
    SELECT
        *,
        lower(trim(coalesce(artist, ''))) AS artist_clean,
        lower(trim(coalesce(title,  ''))) AS title_clean,

        lower(regexp_replace(coalesce(artist, ''), '[^a-zA-Z0-9]+', '', 'g')) AS artist_key,
        lower(regexp_replace(coalesce(title,  ''), '[^a-zA-Z0-9]+', '', 'g')) AS title_key
    FROM cds;
""")
 

print("\n✅ cds_norm view created!")

print("\n--- Normalization preview ---")
print(con.execute("""
    SELECT artist, title, artist_key, title_key
    FROM cds_norm
    LIMIT 10
""").fetchdf())

Connected ✅
Loading CDS (cds_clean.tsv) into DuckDB (tracks kept as TEXT)...
✅ cds table created!

--- CDS preview ---
   cds_id                       artist  \
0   10000              backstreet boys
1  100001                      various
2  100002                    no return
3  100003      ã â â ã â ã â ºâ ã â å
4  100004                      emanuel
5  100005  ã å â ã â ºâ ã â ºâ ºã â â
6  100006             luv lite massive
7  100007              various artists
8  100008                         dmbq
9  100009                       4 p m

                                                                        title  \
0                                                                  millennium
1                                                 frankfurt trance vol 04 cd1
2                                                             self mutilation
3                                       ã æ â³ã â žã â âºã â ã â ¹ã â ã â šâ
4                                                                  felicidade
5  catsã â â ã â šâªã æ âªã â šâ ã æ å ã æ â ã â½â ã â šâ ã æ â ã â šâ¹ã æ ë
6                                                                    one love
7                                                                   nop pop 2
8                                                                        dmbq
9                                                                  sweet soul

   cds_year  \
0      <NA>
1      <NA>
2      <NA>
3      1989
4      1998
5      <NA>
6      <NA>
7      2002
8      2002
9      2001

                                                                             tracks
0  larger than life i want it that way show me the meaning of being lonely it s got
1  dj tom stevens vs fridge outface 2000 radio mix alice deejay better off alone si
2  do or die truth and reality lost soul extractor sadistic desire the true way fan
3  ã â ºâ ã â â ã â šå ã â žã â ã â ¹ã â â ã â ã â¼å ã â ã å ã âªã â šâ ã â â ã â ã
4  felicidade quando o telefone toca vem bailar o tic tic quero que sejas minha e d
5  ã æ â ã æ â ã æ âªã æ â¼ ã â šâªã æ â¼ã æ â ã â šâ ã æ ã æ â ã â šâ ã â šâ ã â š
6  temple of dehli from naw till a mornin shock afghani lick you bad freestyle fiki
7  golden boy miss kittin rippin kittin norther lite treat me better peaches lovert
8  small hours rock a cola ohh baby teenage limbo little leaf i movement little lea
9  miagetegoran yoruno hoshio woman cherish tears in heaven so much in love christm

--- CDS row count ---
      n
0  9763

✅ cds_norm view created!

--- Normalization preview ---
                        artist  \
0              backstreet boys
1                      various
2                    no return
3      ã â â ã â ã â ºâ ã â å
4                      emanuel
5  ã å â ã â ºâ ã â ºâ ºã â â
6             luv lite massive
7              various artists
8                         dmbq
9                       4 p m

                                                                        title  \
0                                                                  millennium
1                                                 frankfurt trance vol 04 cd1
2                                                             self mutilation
3                                       ã æ â³ã â žã â âºã â ã â ¹ã â ã â šâ
4                                                                  felicidade
5  catsã â â ã â šâªã æ âªã â šâ ã æ å ã æ â ã â½â ã â šâ ã æ â ã â šâ¹ã æ ë
6                                                                    one love
7                                                                   nop pop 2
8                                                                        dmbq
9                                                                  sweet soul

       artist_key                title_key
0  backstreetboys               millennium
1         various  frankfurttrancevol04cd1
2        noreturn           selfmutilation
3
4         emanuel               felicidade
5                                     cats
6  luvlitemassive                  onelove
7  variousartists                  noppop2
8            dmbq                     dmbq
9             4pm                sweetsoul

In [ ]:
#I used a deterministic exact matching method based on normalized artist and title fields. Both datasets were preprocessed by lowercasing
#and removing non-alphanumeric characters,
#and records were linked only when the normalized artist and normalized title matched exactly

In [205]:
import duckdb
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# STEP 0: Create normalized MB view for matching
# ------------------------------------------------------------
print("Creating mb_norm view...")

con.execute("""
    CREATE OR REPLACE VIEW mb_norm AS
    SELECT
        release_id,
        release_title,
        artist_credit_full,
        main_artist_name,
        total_tracks,
        barcode,
        mb_year,

        lower(trim(coalesce(main_artist_name, ''))) AS artist_clean,
        lower(trim(coalesce(release_title, '')))    AS title_clean,

        lower(regexp_replace(coalesce(main_artist_name, ''), '[^a-zA-Z0-9]+', '', 'g')) AS artist_key,
        lower(regexp_replace(coalesce(release_title, ''),   '[^a-zA-Z0-9]+', '', 'g')) AS title_key
    FROM mb_release_features;
""")

print("✅ mb_norm created!")

# ------------------------------------------------------------
# STEP 1: Create exact candidate matches between CDS and MB
# ------------------------------------------------------------
print("Creating cds_to_mb_exact_matches...")

con.execute("""
    CREATE OR REPLACE TABLE cds_to_mb_exact_matches AS
    SELECT
        c.cds_id,
        c.artist,
        c.title,
        c.cds_year,
        c.category,
        c.genre,
        c.tracks,
        c.artist_clean AS cds_artist_clean,
        c.title_clean  AS cds_title_clean,
        c.artist_key   AS cds_artist_key,
        c.title_key    AS cds_title_key,

        m.release_id,
        m.release_title,
        m.main_artist_name,
        m.artist_credit_full,
        m.total_tracks,
        m.barcode,
        m.mb_year,
        m.artist_clean AS mb_artist_clean,
        m.title_clean  AS mb_title_clean,
        m.artist_key   AS mb_artist_key,
        m.title_key    AS mb_title_key
    FROM cds_norm c
    JOIN mb_norm m
      ON c.artist_key = m.artist_key
     AND c.title_key  = m.title_key
    WHERE
        length(c.artist_key) >= 4
        AND length(c.title_key) >= 4
        AND length(m.artist_key) >= 4
        AND length(m.title_key) >= 4
        AND c.artist IS NOT NULL
        AND c.title IS NOT NULL
        AND c.artist NOT LIKE '%Ã%'
        AND c.artist NOT LIKE '%â%'
        AND c.title  NOT LIKE '%Ã%'
        AND c.title  NOT LIKE '%â%';
""")

print("✅ cds_to_mb_exact_matches created!")

print("\n--- Exact candidate stats ---")
print(con.execute("""
    WITH per_cds AS (
        SELECT cds_id, COUNT(*) AS candidate_count
        FROM cds_to_mb_exact_matches
        GROUP BY cds_id
    )
    SELECT
        (SELECT COUNT(*) FROM cds) AS cds_total,
        (SELECT COUNT(DISTINCT cds_id) FROM cds_to_mb_exact_matches) AS cds_records_with_candidates,
        (SELECT COUNT(*) FROM cds_to_mb_exact_matches) AS total_candidate_pairs,
        (SELECT COUNT(*) FROM per_cds WHERE candidate_count = 1) AS cds_records_matched_uniquely,
        (SELECT COUNT(*) FROM per_cds WHERE candidate_count > 1) AS cds_records_ambiguous
""").fetchdf())

print("\n--- Sample exact candidates ---")
print(con.execute("""
    SELECT
        cds_id, artist, title, cds_year, category, genre,
        release_id, main_artist_name, release_title, mb_year
    FROM cds_to_mb_exact_matches
    LIMIT 20
""").fetchdf())

Connected ✅
Creating mb_norm view...
✅ mb_norm created!
Creating cds_to_mb_exact_matches...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

✅ cds_to_mb_exact_matches created!

--- Exact candidate stats ---
   cds_total  cds_records_with_candidates  total_candidate_pairs  cds_records_matched_uniquely  cds_records_ambiguous
0       9763                         3482                  17203                          1584                   1898

--- Sample exact candidates ---
    cds_id          artist                       title  cds_year   category        genre  release_id main_artist_name               release_title  mb_year
0   108204    guns n roses    appetite for destruction      1987      blues    hard rock      743465    Guns N’ Roses    Appetite for Destruction     2024
1     7599       kraftwerk                     the mix      1991       rock   electronic     4212910        Kraftwerk                     The Mix     2024
2    10293       kraftwerk                     the mix      1991     newage     synthpop     4212910        Kraftwerk                     The Mix     2024
3   107724    don williams              borrowed tales      1995    country      country     4213012     Don Williams              Borrowed Tales     2024
4   105854   joni mitchell             court and spark      1974       rock         folk        7775    Joni Mitchell             Court and Spark     2025
5   104408          hifana         fresh push breakin       2003       misc   ã â ã ëœå½     4214672           HIFANA         Fresh Push Breakin’     2025
6   106091            beck                 mellow gold      1994       rock         None     4204614             Beck                 Mellow Gold     2025
7   108986           stump            a fierce pancake      <NA>  classical         None      889000            Stump            A Fierce Pancake     2024
8     7599       kraftwerk                     the mix      1991       rock   electronic      336944        Kraftwerk                     The Mix     2024
9   101174     ronnie laws                   deep soul      <NA>       jazz         None     1120746      Ronnie Laws                   Deep Soul     2024
10   10293       kraftwerk                     the mix      1991     newage     synthpop      336944        Kraftwerk                     The Mix     2024
11  102308        bob dyer  river runs outside my door      2001       misc         folk     4217050         Bob Dyer  River Runs Outside My Door     2024
12  107433    phil collins        dance into the light      <NA>       rock         rock     4688135     Phil Collins        Dance Into the Light     2024
13  106646       sepultura                       arise      <NA>       rock  trash metal     3999946        Sepultura                       Arise     2024
14    8990           ac dc                 ballbreaker      <NA>       rock         rock     4218028            AC/DC                 Ballbreaker     2024
15  107069  jennifer lopez                    on the 6      <NA>       rock          pop     4218224   Jennifer Lopez                    On the 6     2025
16  104903    peter maffay        du bist wie ein lied      <NA>       rock         None      479351     Peter Maffay        Du bist wie ein Lied     2024
17    6690       kate bush             the kick inside      1978       rock          pop     4676412        Kate Bush             The Kick Inside     2024
18    6690       kate bush             the kick inside      1978       rock          pop     4676420        Kate Bush             The Kick Inside     2024
19    6690       kate bush             the kick inside      1978       rock          pop     4676424        Kate Bush             The Kick Inside     2024

In [ ]:
# previous result is good because now we know: exact matching works, but we need a tie-breaker to
#choose one “best” MB release per CDS row

In [200]:
import duckdb

# Always connect
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Step 1: Choose ONE "best" exact match per CDS record
# ------------------------------------------------------------
# Comments:
# - Exact matches often return multiple MB releases (different editions).
# - We rank candidates per cds_id using a simple, explainable tie-breaker:
#   1) barcode present first (more specific release)
#   2) higher total_tracks next (often more complete release)
#   3) lowest release_id last (stable deterministic tie-break)
print("Creating cds_to_mb_best_exact (one best match per CDS)...")

con.execute("""
    CREATE OR REPLACE TABLE cds_to_mb_best_exact AS
    WITH ranked AS (
        SELECT
            *,
            row_number() OVER (
                PARTITION BY cds_id
                ORDER BY
                     CASE
                        WHEN barcode IS NOT NULL AND trim(barcode) <> '' THEN 1
                        ELSE 0
                    END DESC,
                    total_tracks DESC NULLS LAST,
                    release_id ASC
            ) AS rn
        FROM cds_to_mb_exact_matches
    )
    SELECT
        cds_id,
        artist,
        title,
        cds_year,
        release_id,
        release_title,
        main_artist_name,
        artist_credit_full,
        total_tracks,
        barcode
    FROM ranked
    WHERE rn = 1;
""")

print("✅ cds_to_mb_best_exact created!")

# ------------------------------------------------------------
# Step 2: Report coverage after tie-breaking
# ------------------------------------------------------------
# Comments:
# - best_exact_rows: how many CDS items now have a single chosen MB release.
# - unmatched_rows: CDS items with no exact match (we'll handle these with fuzzy matching later).
print("\n--- Coverage after picking best match ---")
print(con.execute("""
    SELECT
        (SELECT COUNT(*) FROM cds) AS cds_total,
        (SELECT COUNT(*) FROM cds_to_mb_best_exact) AS best_exact_rows,
        (SELECT COUNT(*) FROM cds) - (SELECT COUNT(*) FROM cds_to_mb_best_exact) AS unmatched_rows
""").fetchdf())

# ------------------------------------------------------------
# Step 3: How much ambiguity did we resolve?
# ------------------------------------------------------------
# Comments:
# - Shows how many CDS rows had multiple candidates originally.
# - After ranking, each cds_id becomes 1 row in cds_to_mb_best_exact.
print("\n--- Ambiguity diagnostic (top 15 most ambiguous) ---")
print(con.execute("""
    SELECT cds_id, artist, title, COUNT(*) AS candidates
    FROM cds_to_mb_exact_matches
    GROUP BY cds_id, artist, title
    HAVING COUNT(*) > 1
    ORDER BY candidates DESC
    LIMIT 20
""").fetchdf())

# ------------------------------------------------------------
# Step 4: Preview chosen best matches
# ------------------------------------------------------------
print("\n--- Preview best matches ---")
print(con.execute("""
    SELECT cds_id, artist, title, release_id, main_artist_name, release_title, total_tracks, barcode
    FROM cds_to_mb_best_exact
    LIMIT 20
""").fetchdf())

Connected ✅
Creating cds_to_mb_best_exact (one best match per CDS)...
✅ cds_to_mb_best_exact created!

--- Coverage after picking best match ---
   cds_total  best_exact_rows  unmatched_rows
0       9763             3482            6281

--- Ambiguity diagnostic (top 15 most ambiguous) ---
    cds_id             artist                                 title  candidates
0   105307  bruce springsteen                    born in the u s a          263
1     4266          kate bush                       the kick inside         120
2     3678          kate bush                       the kick inside         120
3     6690          kate bush                       the kick inside         120
4   108908      georges bizet                                carmen          98
5     4905     britney spears                               britney          88
6     4291     britney spears                               britney          88
7     3670            nirvana                             nevermind          86
8     4441            nirvana                             nevermind          86
9     7769            nirvana                             nevermind          86
10    7515            nirvana                             nevermind          86
11    8151            nirvana                             nevermind          86
12  104676      fleetwood mac                               rumours          73
13  108204       guns n roses              appetite for destruction          71
14  106058        the beatles  sgt pepper s lonely hearts club band          69
15    7859  bruce springsteen                              nebraska          68
16    9798  bruce springsteen                              nebraska          68
17  103057     britney spears                           in the zone          68
18  105284         pink floyd                         the final cut          63
19    9695               bush                         sixteen stone          62

--- Preview best matches ---
    cds_id                           artist                       title  release_id            main_artist_name           release_title  total_tracks        barcode
0     3722                        radiohead                   the bends      516927                   Radiohead               The Bends          55.0  5099969361722
1     4190                             aqua                    aquarius     3826351                        Aqua                Aquarius          14.0   602557189308
2     5542               voodoo glow skulls         the band geek mafia       61797          Voodoo Glow Skulls     The Band Geek Mafia          14.0   045778653522
3     6547                           magnum                sleepwalking       17104                      Magnum            Sleepwalking          11.0   077778088127
4     7087                        rammstein                   sehnsucht       12428                   Rammstein               Sehnsucht          18.0  0731454961721
5     7562                    savage garden               savage garden     1628352               Savage Garden           Savage Garden          23.0  9398710117325
6     7671                            yello              solid pleasure      252340                       Yello          Solid Pleasure          19.0  0602498309049
7     8410                    alkaline trio      from here to infirmary       11610               Alkaline Trio  From Here to Infirmary          14.0  5055052800929
8     8664                  backstreet boys                  millennium       38645             Backstreet Boys              Millennium          14.0  4988064951185
9   100015                            keedy            chase the clouds       85239                       Keedy        Chase the Clouds          10.0   078221864121
10  100019                       bill evans                       alone      100846                  Bill Evans                   Alone          12.0   731458931928
11  100102                 justin mcroberts           reason for living      922331            Justin McRoberts       Reason for Living          12.0   657022524429
12  100119                 rebecca st james                        pray      198751           Rebecca St. James                    Pray          11.0   724382518921
13  100146                      david olney               top to bottom      722017                 David Olney           Top to Bottom          12.0
14  100260                           ghymes               smaragdvã ros       24344                      Ghymes            Smaragdváros          11.0           None
15  100297                           ghymes  az ifjãºsã g sã³lyommadã r      691853                      Ghymes  Az ifjúság sólyommadár          12.0           None
16  100343                      out of eden           this is your life      879730                 Out of Eden       This Is Your Life          13.0   669447285021
17  100408  ãˆ ã ã ã ã ã ã ã ã ã farlanders                     moments      140060  Инна Желанная и Farlanders                 Moments          12.0           None
18  100484                             flap              away from home     1738457                        Flap          Away From Home          13.0
19  100545                   the walkabouts              trail of stars      974608              The Walkabouts          Trail of Stars          13.0  4030433045022

In [147]:
import duckdb

con = duckdb.connect("../data_processed/thesis.duckdb")

print(con.execute("""
    SELECT COUNT(*) AS n
    FROM mb_release_features
    WHERE release_title = 'The Kick Inside'
      AND main_artist_name = 'Kate Bush'
""").fetchdf())

     n
0  120

In [152]:
import duckdb

con = duckdb.connect("../data_processed/thesis.duckdb")

print(con.execute("""
    SELECT COUNT(*) AS n
    FROM cds_norm
    WHERE lower(title) = 'the kick inside'
      AND lower(artist) = 'kate bush'
""").fetchdf())

   n
0  3

In [168]:
import duckdb

con = duckdb.connect("../data_processed/thesis.duckdb")

print(con.execute("""
    SELECT COUNT(*) AS n
    FROM cds_to_mb_exact_matches
    WHERE lower(title) = 'the kick inside'
      AND lower(artist) = 'kate bush'
""").fetchdf())

     n
0  360

In [ ]:
#delete this cell

In [169]:
import duckdb

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# STEP 1: Build per-CDS match counts from exact candidate matches
# ------------------------------------------------------------
# This tells us whether each CDS record has:
# - 0 exact matches (not present in this table)
# - 1 exact match  -> unique
# - >1 exact match -> ambiguous
print("Building match diagnostics...")

con.execute("""
    CREATE OR REPLACE TABLE cds_match_counts AS
    SELECT
        cds_id,
        MIN(artist) AS artist,
        MIN(title) AS title,
        COUNT(*) AS candidate_count
    FROM cds_to_mb_exact_matches
    GROUP BY cds_id;
""")

print("✅ cds_match_counts created!")

# ------------------------------------------------------------
# STEP 2: Keep only uniquely matched CDS records
# ------------------------------------------------------------
# These are the safest automatic enrichment links:
# one CDS record -> exactly one MB release
print("Creating cds_to_mb_unique_exact...")

con.execute("""
    CREATE OR REPLACE TABLE cds_to_mb_unique_exact AS
    SELECT m.*
    FROM cds_to_mb_exact_matches m
    JOIN cds_match_counts c
      ON m.cds_id = c.cds_id
    WHERE c.candidate_count = 1;
""")

print("✅ cds_to_mb_unique_exact created!")

# ------------------------------------------------------------
# STEP 3: Build a best-match table for ambiguous cases
# ------------------------------------------------------------
# This keeps one best MB release per CDS record using explainable rules:
# 1) barcode present first
# 2) higher total_tracks next
# 3) lowest release_id last
print("Creating cds_to_mb_best_exact...")

con.execute("""
    CREATE OR REPLACE TABLE cds_to_mb_best_exact AS
    WITH ranked AS (
        SELECT
            *,
            ROW_NUMBER() OVER (
                PARTITION BY cds_id
                ORDER BY
                    CASE
                        WHEN barcode IS NOT NULL AND trim(barcode) <> '' THEN 1
                        ELSE 0
                    END DESC,
                    total_tracks DESC NULLS LAST,
                    release_id ASC
            ) AS rn
        FROM cds_to_mb_exact_matches
    )
    SELECT
        cds_id,
        artist,
        title,
        cds_year,
        category,
        genre,
        tracks,
        release_id,
        release_title,
        main_artist_name,
        artist_credit_full,
        total_tracks,
        barcode,
        mb_year
    FROM ranked
    WHERE rn = 1;
""")

print("✅ cds_to_mb_best_exact created!")

# ------------------------------------------------------------
# STEP 4: Create enriched MB table using UNIQUE exact matches only
# ------------------------------------------------------------
# This is the conservative enrichment table for the thesis:
# only high-confidence links are used automatically.
print("Creating mb_enriched_from_cds_unique...")

con.execute("""
    CREATE OR REPLACE TABLE mb_enriched_from_cds_unique AS
    SELECT
        u.release_id,
        u.release_title,
        u.main_artist_name,
        u.artist_credit_full,
        u.mb_year,
        u.total_tracks,
        u.barcode,

        u.cds_id,
        u.cds_year,
        u.category AS cds_category,
        u.genre AS cds_genre,
        u.tracks AS cds_tracklist,

        'CDS' AS enrichment_source,
        'exact_unique' AS match_type
    FROM cds_to_mb_unique_exact u;
""")

print("✅ mb_enriched_from_cds_unique created!")

# ------------------------------------------------------------
# STEP 5: Main thesis metrics
# ------------------------------------------------------------
print("\n--- Main integration / enrichment metrics ---")
print(con.execute("""
    WITH
    cds_total AS (
        SELECT COUNT(*) AS n FROM cds
    ),
    mb_total AS (
        SELECT COUNT(*) AS n FROM mb_release_features
    ),
    matched_cds AS (
        SELECT COUNT(DISTINCT cds_id) AS n
        FROM cds_to_mb_exact_matches
    ),
    unique_cds AS (
        SELECT COUNT(DISTINCT cds_id) AS n
        FROM cds_match_counts
        WHERE candidate_count = 1
    ),
    ambiguous_cds AS (
        SELECT COUNT(DISTINCT cds_id) AS n
        FROM cds_match_counts
        WHERE candidate_count > 1
    ),
    enriched_mb AS (
        SELECT COUNT(DISTINCT release_id) AS n
        FROM mb_enriched_from_cds_unique
    ),
    enriched_with_new_metadata AS (
        SELECT COUNT(DISTINCT release_id) AS n
        FROM mb_enriched_from_cds_unique
        WHERE cds_category IS NOT NULL
           OR cds_genre IS NOT NULL
           OR cds_year IS NOT NULL
    )
    SELECT
        (SELECT n FROM cds_total) AS cds_total,
        (SELECT n FROM matched_cds) AS cds_records_with_candidates,
        (SELECT n FROM unique_cds) AS cds_records_matched_uniquely,
        (SELECT n FROM ambiguous_cds) AS cds_records_ambiguous,
        (SELECT n FROM cds_total) - (SELECT n FROM matched_cds) AS cds_records_unmatched,

        (SELECT n FROM enriched_mb) AS mb_releases_enriched,
        (SELECT n FROM enriched_with_new_metadata) AS mb_releases_with_new_metadata,

        ROUND(
            100.0 * (SELECT n FROM enriched_with_new_metadata) / (SELECT n FROM mb_total),
            4
        ) AS pct_of_mb_with_new_metadata
""").fetchdf())

# ------------------------------------------------------------
# STEP 6: Ambiguity diagnostics
# ------------------------------------------------------------
print("\n--- Top 20 most ambiguous CDS records ---")
print(con.execute("""
    SELECT cds_id, artist, title, candidate_count
    FROM cds_match_counts
    WHERE candidate_count > 1
    ORDER BY candidate_count DESC, cds_id
    LIMIT 20
""").fetchdf())

# ------------------------------------------------------------
# STEP 7: Preview high-confidence enrichment rows
# ------------------------------------------------------------
print("\n--- Preview enriched MB releases (unique exact only) ---")
print(con.execute("""
    SELECT
        release_id, release_title, main_artist_name, mb_year,
        cds_id, cds_year, cds_category, cds_genre, enrichment_source, match_type
    FROM mb_enriched_from_cds_unique
    LIMIT 20
""").fetchdf())

# ------------------------------------------------------------
# STEP 8: Prepare evaluation sample for match accuracy
# ------------------------------------------------------------
# IMPORTANT:
# True accuracy cannot be computed automatically from these tables alone.
# We therefore create a sample for manual verification.
print("\nCreating evaluation sample for manual accuracy checking...")

con.execute("""
    CREATE OR REPLACE TABLE match_eval_sample AS
    (
        SELECT
            'unique_exact' AS sample_type,
            cds_id, artist, title, cds_year,
            release_id, main_artist_name, release_title, mb_year,
            barcode, total_tracks
        FROM cds_to_mb_unique_exact
        USING SAMPLE 50 ROWS
    )
    UNION ALL
    (
        SELECT
            'best_exact_ambiguous' AS sample_type,
            b.cds_id, b.artist, b.title, b.cds_year,
            b.release_id, b.main_artist_name, b.release_title, b.mb_year,
            b.barcode, b.total_tracks
        FROM cds_to_mb_best_exact b
        JOIN cds_match_counts c
          ON b.cds_id = c.cds_id
        WHERE c.candidate_count > 1
        USING SAMPLE 50 ROWS
    );
""")

print("✅ match_eval_sample created!")

print("\n--- Evaluation sample preview ---")
print(con.execute("""
    SELECT *
    FROM match_eval_sample
    LIMIT 20
""").fetchdf())

print("\nNOTE:")
print("- 'How accurate are the matches?' requires manual labeling of match_eval_sample.")
print("- Add a column like manual_label with values: correct / incorrect / uncertain.")
print("- Then compute precision from the labeled sample.")

Connected ✅
Building match diagnostics...
✅ cds_match_counts created!
Creating cds_to_mb_unique_exact...
✅ cds_to_mb_unique_exact created!
Creating cds_to_mb_best_exact...
✅ cds_to_mb_best_exact created!
Creating mb_enriched_from_cds_unique...
✅ mb_enriched_from_cds_unique created!

--- Main integration / enrichment metrics ---
   cds_total  cds_records_with_candidates  cds_records_matched_uniquely  \
0       9763                         3482                          1584

   cds_records_ambiguous  cds_records_unmatched  mb_releases_enriched  \
0                   1898                   6281                  1572

   mb_releases_with_new_metadata  pct_of_mb_with_new_metadata
0                           1572                       0.0296

--- Top 20 most ambiguous CDS records ---
    cds_id             artist                                 title  \
0   105307  bruce springsteen                    born in the u s a
1     3678          kate bush                       the kick inside
2     4266          kate bush                       the kick inside
3     6690          kate bush                       the kick inside
4   108908      georges bizet                                carmen
5     4291     britney spears                               britney
6     4905     britney spears                               britney
7     3670            nirvana                             nevermind
8     4441            nirvana                             nevermind
9     7515            nirvana                             nevermind
10    7769            nirvana                             nevermind
11    8151            nirvana                             nevermind
12  104676      fleetwood mac                               rumours
13  108204       guns n roses              appetite for destruction
14  106058        the beatles  sgt pepper s lonely hearts club band
15    7859  bruce springsteen                              nebraska
16    9798  bruce springsteen                              nebraska
17  103057     britney spears                           in the zone
18  105284         pink floyd                         the final cut
19    7134               bush                         sixteen stone

    candidate_count
0               263
1               120
2               120
3               120
4                98
5                88
6                88
7                86
8                86
9                86
10               86
11               86
12               73
13               71
14               69
15               68
16               68
17               68
18               63
19               62

--- Preview enriched MB releases (unique exact only) ---
    release_id                                        release_title  \
0      1012344                              Crazy 'Bout a Saxophone
1      1013682                                       Altered States
2      1014734                                  Man Versus Concrete
3      1015650          Szép szerelmem Magyarország #1 - Napfényfia
4      1017049                             The Weak and the Wounded
5      1017606                                          Eagle Cries
6      1019557                                Nothing but the Truth
7      2034792                                              Koleksi
8      1020575                                      Rose Water Moon
9      1020736                                        Raw Live Real
10     1023648                                    Gunnars Rekordbog
11     1024074                                      Tango del Fuego
12     1025962                                            Retrodyne
13     1026642                              Muddy Waters Blues Band
14     1026644                                           It's the L
15     1026747                                   Working Class Hero
16     1027440  The Benny Carter Sessions: The Blue Note Collection
17       90712                                  Building a Building
18     1030199                                           Truck Fist
19     1030668                                     The Phoenix Trap

                       main_artist_name  mb_year  cds_id  cds_year  \
0   Johnny Ferreira & The Swing Machine     2015  108097      <NA>
1                        Hypnolovewheel     2020  104900      <NA>
2                 The Matt Osborne Band     <NA>  104728      2001
3                         Tolcsvay Béla     <NA>  100563      <NA>
4                            Index Case     <NA>  105888      <NA>
5                     Joanne Shenandoah     2016  108243      2001
6                          Bob Carlisle     2024  106115      2000
7                       Katon Bagaskara     2018  107415      <NA>
8                         Sambodhi Prem     <NA>  107869      <NA>
9                        Rapunzel M.A.P     <NA>  106257      <NA>
10                          Ib Grønbech     <NA>  106970      1986
11                         James Galway     2015  104622      1998
12                      Alison Pipitone     <NA>  104697      2003
13                         Muddy Waters     2019  101324      <NA>
14                              Lexicon     2016  102291      2001
15                       Jerry Williams     2021  106040      <NA>
16                        Sarah Vaughan     2015  103363      <NA>
17                             Slowride     2012  106789      <NA>
18                          Daisycutter     <NA>  105865      <NA>
19                     The Phoenix Trap     2009  106683      2002

   cds_category               cds_genre enrichment_source    match_type
0         blues                    None               CDS  exact_unique
1          rock                    None               CDS  exact_unique
2          rock                alt rock               CDS  exact_unique
3          folk                    None               CDS  exact_unique
4          rock                    rock               CDS  exact_unique
5        newage         native american               CDS  exact_unique
6          rock  contemporary christian               CDS  exact_unique
7          rock                     pop               CDS  exact_unique
8         blues                    None               CDS  exact_unique
9          rock                    None               CDS  exact_unique
10         rock                   other               CDS  exact_unique
11         rock                   latin               CDS  exact_unique
12         rock                    rock               CDS  exact_unique
13         jazz                    None               CDS  exact_unique
14         misc     underground hip hop               CDS  exact_unique
15         rock               rock roll               CDS  exact_unique
16         misc                    None               CDS  exact_unique
17         rock                    None               CDS  exact_unique
18         rock                    None               CDS  exact_unique
19         rock                    rock               CDS  exact_unique

Creating evaluation sample for manual accuracy checking...
✅ match_eval_sample created!

--- Evaluation sample preview ---
     sample_type  cds_id                 artist                     title  \
0   unique_exact  100942            warren hill                     truth
1   unique_exact  100170      alexander scourby          king james bible
2   unique_exact  105190        forever changed     drifting into amazing
3   unique_exact  100399            nancy bryan                neon angel
4   unique_exact  101639               spacemen                  spacemen
5   unique_exact  101542              noise box            the bigginning
6   unique_exact  107360       olle ljungstrã m                      tack
7   unique_exact  102125        fernando mendes                   ao vivo
8   unique_exact  106322        waterson carthy           waterson carthy
9   unique_exact  103049            stan cuesta      le voyage intã rieur
10  unique_exact  107923         charles wilson           renaissance man
11  unique_exact  100840                 romane        swing in nashville
12  unique_exact  107428       oran juice jones             player s call
13  unique_exact  100689       dangaa khosbayar                     altai
14  unique_exact  100762             os morenos               pode chegar
15  unique_exact  105604            phil keaggy             beyond nature
16  unique_exact  101652      armand van helden  funk phenomena the album
17  unique_exact  102294  bã¼rger lars dietrich              dicke dinger
18  unique_exact  100168          sal solo band      through ancient eyes
19  unique_exact  102134                illegal          the untold truth

    cds_year  release_id      main_artist_name             release_title  \
0       <NA>     1038227           Warren Hill                     Truth
1       <NA>     1007028     Alexander Scourby          King James Bible
2       2002      980722       Forever Changed     Drifting Into Amazing
3       2000     1159790           Nancy Bryan                Neon Angel
4       1999     1129204              Spacemen                  Spacemen
5       <NA>      275054             Noise Box            The Bigginning
6       1995      723680       Olle Ljungström                     Tack.
7       1999     4381018       Fernando Mendes                   Ao Vivo
8       1994      317838       Waterson:Carthy           Waterson:Carthy
9       <NA>     3098403           Stan Cuesta       Le Voyage Intérieur
10      1999     2874115        Charles Wilson           Renaissance Man
11      1998      695397                Romane        Swing in Nashville
12      <NA>     1631899    Oran “Juice” Jones             Player’s Call
13      <NA>      889329      Dangaa Khosbayar                     Altai
14      <NA>     3879431            Os Morenos               Pode Chegar
15      <NA>       44754           Phil Keaggy             Beyond Nature
16      2002       46761     Armand van Helden  Funk Phenomena the Album
17      1996       52627  Bürger Lars Dietrich              Dicke Dinger
18      1999      153954         Sal Solo Band      Through Ancient Eyes
19      <NA>      891387               Illegal          The Untold Truth

    mb_year        barcode  total_tracks
0      2009           None          12.0
1      2011           None          70.0
2      2012           None          12.0
3      2012   753088201325          13.0
4      2012   742891103124          12.0
5      2012   741157992724          13.0
6      2016   706301224922          12.0
7      2024  5099749247123          14.0
8      2021  5016272475021          12.0
9      2021  3383005922896          12.0
10     2021   669910445426          12.0
11     2021  3464630019493          12.0
12     2021           None          13.0
13     2023   743217486723          12.0
14     2023   731454671026          14.0
15     2019   080688080129          12.0
16     2019   090204956487          12.0
17     2020   706301510025          12.0
18     2020           None          12.0
19     2025   754443700224          12.0

NOTE:
- 'How accurate are the matches?' requires manual labeling of match_eval_sample.
- Add a column like manual_label with values: correct / incorrect / uncertain.
- Then compute precision from the labeled sample.

In [ ]:
##############################
#remove cds_features
#remove cds_trackcount_est
#remove best_exact_v2
#remove best_exact_v3

In [201]:
import duckdb

# Always connect
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Step 1: Create a CDS helper view with an estimated track count
# ------------------------------------------------------------
# Comments:
# - CDS "tracks" is actually a tracklist text field.
# - We create a heuristic estimate of track count by counting common separators.
# - This is not perfect, but it helps avoid selecting huge box sets in MB.
print("Creating cds_features with heuristic track count...")

con.execute("""
    CREATE OR REPLACE VIEW cds_features AS
    SELECT
        *,
        -- heuristic separator counts (add 1 because N separators -> N+1 items)
        greatest(
            case when tracks is null or length(trim(tracks)) = 0 then NULL else (length(tracks) - length(replace(tracks, ' / ', ''))) / 3 + 1 end,
            case when tracks is null or length(trim(tracks)) = 0 then NULL else (length(tracks) - length(replace(tracks, ' - ', ''))) / 3 + 1 end,
            case when tracks is null or length(trim(tracks)) = 0 then NULL else (length(tracks) - length(replace(tracks, ';', ''))) + 1 end,
            case when tracks is null or length(trim(tracks)) = 0 then NULL else (length(tracks) - length(replace(tracks, '|', ''))) + 1 end,
            case when tracks is null or length(trim(tracks)) = 0 then NULL else (length(tracks) - length(replace(tracks, ',', ''))) + 1 end
        )::BIGINT AS cds_trackcount_est
    FROM cds;
""")

print("✅ cds_features view created!")

print("\n--- Heuristic trackcount preview ---")
print(con.execute("""
    SELECT cds_id, artist, title, cds_year, cds_trackcount_est, substr(tracks, 1, 60) AS tracklist_preview
    FROM cds_features
    LIMIT 15
""").fetchdf())

# ------------------------------------------------------------
# Step 2: Re-rank candidates using closeness to estimated track count
# ------------------------------------------------------------
# Comments:
# - We keep barcode preference.
# - Then we prefer candidates whose total_tracks is close to cds_trackcount_est.
# - This helps select "normal" album releases over large compilations/box sets.
print("\nRebuilding cds_to_mb_best_exact using trackcount heuristic...")

con.execute("""
    CREATE OR REPLACE TABLE cds_to_mb_best_exact_v2 AS
    WITH joined AS (
        SELECT
            e.*,
            f.cds_trackcount_est
        FROM cds_to_mb_exact_matches e
        LEFT JOIN cds_features f USING (cds_id)
    ),
    ranked AS (
        SELECT
            *,
            row_number() OVER (
                PARTITION BY cds_id
                ORDER BY
                     CASE
                        WHEN barcode IS NOT NULL AND trim(barcode) <> '' THEN 1
                        ELSE 0
                    END DESC,
                    -- prefer closer track counts (if we have an estimate)
                    CASE
                        WHEN cds_trackcount_est IS NULL OR total_tracks IS NULL THEN 999999
                        ELSE abs(total_tracks - cds_trackcount_est)
                    END ASC,
                    total_tracks ASC NULLS LAST,
                    release_id ASC
            ) AS rn
        FROM joined
    )
    SELECT
        cds_id, artist, title, cds_year, cds_trackcount_est,
        release_id, release_title, main_artist_name, artist_credit_full,
        total_tracks, barcode
    FROM ranked
    WHERE rn = 1;
""")

print("✅ cds_to_mb_best_exact_v2 created!")

print("\n--- Compare old vs new for a known ambiguous title (example: Let It Be) ---")
print(con.execute("""
    SELECT
      old.cds_id,
      old.artist,
      old.title,
      old.release_id AS old_release_id,
      old.release_title AS old_release_title,
      old.total_tracks AS old_total_tracks,
      v2.release_id  AS new_release_id,
      v2.release_title AS new_release_title,
      v2.total_tracks AS new_total_tracks,
      v2.cds_trackcount_est
    FROM cds_to_mb_best_exact old
    JOIN cds_to_mb_best_exact_v2 v2 USING (cds_id)
    WHERE lower(old.title) LIKE '%let it be%'
    LIMIT 20
""").fetchdf())

Connected ✅
Creating cds_features with heuristic track count...
✅ cds_features view created!

--- Heuristic trackcount preview ---
    cds_id                       artist                                                                       title  cds_year  cds_trackcount_est  \
0    10000              backstreet boys                                                                  millennium      <NA>                   1
1   100001                      various                                                 frankfurt trance vol 04 cd1      <NA>                   1
2   100002                    no return                                                             self mutilation      <NA>                   1
3   100003      ã â â ã â ã â ºâ ã â å                                        ã æ â³ã â žã â âºã â ã â ¹ã â ã â šâ       1989                   1
4   100004                      emanuel                                                                  felicidade      1998                   1
5   100005  ã å â ã â ºâ ã â ºâ ºã â â   catsã â â ã â šâªã æ âªã â šâ ã æ å ã æ â ã â½â ã â šâ ã æ â ã â šâ¹ã æ ë       <NA>                   1
6   100006             luv lite massive                                                                    one love      <NA>                   1
7   100007              various artists                                                                   nop pop 2      2002                   1
8   100008                         dmbq                                                                        dmbq      2002                   1
9   100009                       4 p m                                                                   sweet soul      2001                   1
10  100010                      various                                                 frankfurt trance vol 05 cd1      <NA>                   1
11  100011         â¾ã â â ã ãœ worship                                                          child praise vol 1      <NA>                   1
12  100012           rumania montevideo                                                            mo better tracks      <NA>                   1
13  100014               modern talking                                                                     univers      1997                   1
14  100015                        keedy                                                            chase the clouds      <NA>                   1

                                               tracklist_preview
0   larger than life i want it that way show me the meaning of b
1   dj tom stevens vs fridge outface 2000 radio mix alice deejay
2   do or die truth and reality lost soul extractor sadistic des
3   ã â ºâ ã â â ã â šå ã â žã â ã â ¹ã â â ã â ã â¼å ã â ã å ã
4   felicidade quando o telefone toca vem bailar o tic tic quero
5   ã æ â ã æ â ã æ âªã æ â¼ ã â šâªã æ â¼ã æ â ã â šâ ã æ ã æ â
6   temple of dehli from naw till a mornin shock afghani lick yo
7   golden boy miss kittin rippin kittin norther lite treat me b
8   small hours rock a cola ohh baby teenage limbo little leaf i
9   miagetegoran yoruno hoshio woman cherish tears in heaven so
10  dj tom stevens violet steam single cut liquid child diving f
11  ã ã â ã â³âªâ â â ã â â â½ãƒâ ã â ã ã ãš â³âªâ ã â¹ã ã â½ã â
12  i ll be with you hard rain free tender rain rain sleeper lif
13  tv makes the superstar iâ m no rockefeller mystery eyerybody
14  save some love wishing on the same star never neverland sorr

Rebuilding cds_to_mb_best_exact using trackcount heuristic...
✅ cds_to_mb_best_exact_v2 created!

--- Compare old vs new for a known ambiguous title (example: Let It Be) ---
   cds_id       artist      title  old_release_id old_release_title  old_total_tracks  new_release_id new_release_title  new_total_tracks  cds_trackcount_est
0    7460  the beatles  let it be         3213597         Let It Be              93.0         4273987         Let It Be               2.0                   1
1    6272  the beatles  let it be         3213597         Let It Be              93.0         4273987         Let It Be               2.0                   1

In [22]:
import duckdb

# Always connect
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Goal: Pick one "best" MB release per CDS record from the EXACT candidates
# ------------------------------------------------------------
# Comments:
# - Exact matches often return many MB candidates (editions, reissues, etc.).
# - Our previous attempt used a CDS trackcount heuristic, but it produced mostly "1",
#   which biased selection toward singles (2 tracks) and other tiny releases.
# - Here we use a safer, professional rule:
#   1) Prefer barcode (more specific release)
#   2) Prefer "album-like" track counts (6..40) by giving them a bonus
#   3) Prefer medium track counts (closer to ~12) as a weak tie-break
#   4) Deterministic fallback: smallest release_id
print("Creating cds_to_mb_best_exact_v3 (barcode + album-like track count preference)...")

con.execute("""
    CREATE OR REPLACE TABLE cds_to_mb_best_exact_v3 AS
    WITH ranked AS (
        SELECT
            *,
            row_number() OVER (
                PARTITION BY cds_id
                ORDER BY
                    -- 1) barcode present first
                    CASE
                        WHEN barcode IS NOT NULL AND trim(barcode) <> '' THEN 1
                        ELSE 0
                    END DESC,
                    -- 2) album-like total_tracks gets priority (EP/Album range)
                    CASE
                        WHEN total_tracks BETWEEN 6 AND 40 THEN 0
                        WHEN total_tracks IS NULL THEN 2
                        ELSE 1
                    END ASC,

                    -- 3) weak preference toward ~12 tracks (common album length)
                    CASE
                        WHEN total_tracks IS NULL THEN 999999
                        ELSE abs(total_tracks - 12)
                    END ASC,

                    -- 4) deterministic final tie-break
                    release_id ASC
            ) AS rn
        FROM cds_to_mb_exact_matches
    )
    SELECT
        cds_id, artist, title, cds_year,
        release_id, release_title, main_artist_name, artist_credit_full,
        total_tracks, barcode, mb_year
    FROM ranked
    WHERE rn = 1;
""")

print("✅ cds_to_mb_best_exact_v3 created!")

# ------------------------------------------------------------
# Quick quality check on the specific example: Let It Be
# ------------------------------------------------------------
# Comments:
# - We compare v1/v2/v3 for "let it be" to ensure v3 avoids extremes.
print("\n--- Compare v1 vs v2 vs v3 for 'let it be' ---")
print(con.execute("""
    SELECT
      old.cds_id,
      old.artist,
      old.title,
      old.release_id AS v1_release_id,
      old.total_tracks AS v1_tracks,
      v2.release_id  AS v2_release_id,
      v2.total_tracks AS v2_tracks,
      v3.release_id  AS v3_release_id,
      v3.total_tracks AS v3_tracks
    FROM cds_to_mb_best_exact old
    JOIN cds_to_mb_best_exact_v2 v2 USING (cds_id)
    JOIN cds_to_mb_best_exact_v3 v3 USING (cds_id)
    WHERE lower(old.title) LIKE '%let it be%'
    LIMIT 20
""").fetchdf())

# ------------------------------------------------------------
# Preview best matches
# ------------------------------------------------------------
print("\n--- Preview best matches (v3) ---")
print(con.execute("""
    SELECT cds_id, artist, title, release_id, release_title, total_tracks, barcode, mb_year
    FROM cds_to_mb_best_exact_v3
    LIMIT 20
""").fetchdf())

Connected ✅
Creating cds_to_mb_best_exact_v3 (barcode + album-like track count preference)...
✅ cds_to_mb_best_exact_v3 created!

--- Compare v1 vs v2 vs v3 for 'let it be' ---
   cds_id       artist      title  v1_release_id  v1_tracks  v2_release_id  v2_tracks  v3_release_id  v3_tracks
0    6272  the beatles  let it be        3213597       93.0        4273987        2.0         275837       12.0
1    7460  the beatles  let it be        3213597       93.0        4273987        2.0         275837       12.0

--- Preview best matches (v3) ---
    cds_id         artist                      title  release_id              release_title  total_tracks        barcode  mb_year
0     3475     rob zombie           hellbilly deluxe      455415           Hellbilly Deluxe          13.0   720642521212     2019
1     4441        nirvana                  nevermind        7518                  Nevermind          12.0  0720642442524     2022
2     4586       ministry           power department       16298           Power Department          13.0                    2017
3     4895      faithless              outrospective       32002              Outrospective          12.0   743218655524     2022
4     5185     spineshank  the height of callousness       38557  The Height of Callousness          11.0   016861856328     2017
5     5477       the cure             disintegration        2783             Disintegration          12.0   075596085526     2017
6     5830  silicon dream               time machine      514705               Time Machine          13.0   013321455312     2009
7     6756          finch         what it is to burn        6483         What It Is to Burn          13.0   042286099125     2025
8     6802        madonna               ray of light        8194               Ray of Light          13.0   093624684725     2017
9     6950        garbage           beautifulgarbage       20079           beautifulgarbage          13.0  5034644009520     2019
10    8063         estopa                 destrangis      197607                 Destrangis          13.0   743219026224     2024
11    8114          queen                   innuendo        2415                   Innuendo          12.0  0077779588725     2025
12    8311      crematory                    believe       40608                    Believe          12.0  4028466105745     2025
13    8754         krezip             days like this       19206             Days Like This          12.0   809274911926     2018
14    9060       therapy                  troublegum       16850                 Troublegum          14.0   731454019620     2015
15   10293      kraftwerk                    the mix       31945                    The Mix          11.0   077779665020     2019
16   11538     john barry                  king kong      662916                  King Kong          13.0   638558019825     2017
17  100035         gazebo         the best of gazebo     1883940         The Best of Gazebo          16.0  4988017610893     2024
18  100107   indigo girls         shaming of the sun       44017         Shaming of the Sun          12.0   074646789124     2022
19  100198  stacie orrico              stacie orrico          89              Stacie Orrico          12.0   724353258924     2013

In [206]:
#deletes the old CSVs, then writes the new ones.
import duckdb
import os

# Connect
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# Output folder
out_dir = "../data_processed/exports"
os.makedirs(out_dir, exist_ok=True)

tables = [

    "cds_to_mb_exact_matches"
]

for table in tables:
    out_path = os.path.join(out_dir, f"{table}.csv")

    # Delete old CSV if it already exists
    if os.path.exists(out_path):
        os.remove(out_path)
        print(f"🗑️ Deleted old file: {out_path}")

    # Export fresh CSV
    con.execute(f"""
        COPY (
            SELECT *
            FROM {table}
        ) TO '{out_path}'
        (HEADER, DELIMITER ',');
    """)
    print(f"✅ Exported new file: {out_path}")

con.close()
print("Done ✅")

Connected ✅
🗑️ Deleted old file: ../data_processed/exports\cds_to_mb_exact_matches.csv
✅ Exported new file: ../data_processed/exports\cds_to_mb_exact_matches.csv
Done ✅

In [211]:
import duckdb
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 220)

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

print("Creating cds_to_mb_exact_scored without year scoring...")

con.execute(r"""
CREATE OR REPLACE TABLE cds_to_mb_exact_scored AS
WITH params AS (
    SELECT
        26.0 AS w_barcode,
        24.0 AS w_title_raw_exact,
        24.0 AS w_artist_raw_exact,
         8.0 AS w_both_raw_exact,

        10.0 AS w_edition_penalty,
         8.0 AS w_various_artist_penalty
),
match_counts AS (
    SELECT
        cds_id,
        COUNT(*) AS n_candidates
    FROM cds_to_mb_exact_matches
    GROUP BY cds_id
),
features AS (
    SELECT
        e.*,
        mc.n_candidates,

        (NULLIF(trim(e.barcode), '') IS NOT NULL) AS has_real_barcode,

        (lower(trim(coalesce(e.artist, ''))) = lower(trim(coalesce(e.main_artist_name, '')))) AS artist_raw_exact,
        (lower(trim(coalesce(e.title,  ''))) = lower(trim(coalesce(e.release_title,   '')))) AS title_raw_exact,

        regexp_matches(lower(coalesce(e.release_title, '')), '(^|[^a-z0-9])remaster(ed)?([^a-z0-9]|$)') AS mb_has_remaster,
        regexp_matches(lower(coalesce(e.release_title, '')), '(^|[^a-z0-9])deluxe([^a-z0-9]|$)')        AS mb_has_deluxe,
        regexp_matches(lower(coalesce(e.release_title, '')), '(^|[^a-z0-9])anniversary([^a-z0-9]|$)')   AS mb_has_anniversary,
        regexp_matches(lower(coalesce(e.release_title, '')), '(^|[^a-z0-9])live([^a-z0-9]|$)')          AS mb_has_live,
        regexp_matches(lower(coalesce(e.release_title, '')), '(^|[^a-z0-9])bonus([^a-z0-9]|$)')         AS mb_has_bonus,
        regexp_matches(lower(coalesce(e.release_title, '')), '(^|[^a-z0-9])(disc|disk|cd)[ ]*[0-9]+([^a-z0-9]|$)') AS mb_has_discnum,
        regexp_matches(lower(coalesce(e.release_title, '')), '(^|[^a-z0-9])expanded([^a-z0-9]|$)')      AS mb_has_expanded,
        regexp_matches(lower(coalesce(e.release_title, '')), '(^|[^a-z0-9])limited([^a-z0-9]|$)')       AS mb_has_limited,
        regexp_matches(lower(coalesce(e.release_title, '')), '(^|[^a-z0-9])special([^a-z0-9]|$)')       AS mb_has_special,

        regexp_matches(lower(coalesce(e.title, '')), '(^|[^a-z0-9])remaster(ed)?([^a-z0-9]|$)') AS cds_has_remaster,
        regexp_matches(lower(coalesce(e.title, '')), '(^|[^a-z0-9])deluxe([^a-z0-9]|$)')        AS cds_has_deluxe,
        regexp_matches(lower(coalesce(e.title, '')), '(^|[^a-z0-9])anniversary([^a-z0-9]|$)')   AS cds_has_anniversary,
        regexp_matches(lower(coalesce(e.title, '')), '(^|[^a-z0-9])live([^a-z0-9]|$)')          AS cds_has_live,
        regexp_matches(lower(coalesce(e.title, '')), '(^|[^a-z0-9])bonus([^a-z0-9]|$)')         AS cds_has_bonus,
        regexp_matches(lower(coalesce(e.title, '')), '(^|[^a-z0-9])(disc|disk|cd)[ ]*[0-9]+([^a-z0-9]|$)') AS cds_has_discnum,
        regexp_matches(lower(coalesce(e.title, '')), '(^|[^a-z0-9])expanded([^a-z0-9]|$)')      AS cds_has_expanded,
        regexp_matches(lower(coalesce(e.title, '')), '(^|[^a-z0-9])limited([^a-z0-9]|$)')       AS cds_has_limited,
        regexp_matches(lower(coalesce(e.title, '')), '(^|[^a-z0-9])special([^a-z0-9]|$)')       AS cds_has_special
    FROM cds_to_mb_exact_matches e
    JOIN match_counts mc
      ON e.cds_id = mc.cds_id
),
scored AS (
    SELECT
        f.*,

        (
            (CASE WHEN f.mb_has_remaster    AND NOT f.cds_has_remaster    THEN 1 ELSE 0 END) +
            (CASE WHEN f.mb_has_deluxe      AND NOT f.cds_has_deluxe      THEN 1 ELSE 0 END) +
            (CASE WHEN f.mb_has_anniversary AND NOT f.cds_has_anniversary THEN 1 ELSE 0 END) +
            (CASE WHEN f.mb_has_live        AND NOT f.cds_has_live        THEN 1 ELSE 0 END) +
            (CASE WHEN f.mb_has_bonus       AND NOT f.cds_has_bonus       THEN 1 ELSE 0 END) +
            (CASE WHEN f.mb_has_discnum     AND NOT f.cds_has_discnum     THEN 1 ELSE 0 END) +
            (CASE WHEN f.mb_has_expanded    AND NOT f.cds_has_expanded    THEN 1 ELSE 0 END) +
            (CASE WHEN f.mb_has_limited     AND NOT f.cds_has_limited     THEN 1 ELSE 0 END) +
            (CASE WHEN f.mb_has_special     AND NOT f.cds_has_special     THEN 1 ELSE 0 END)
        ) AS edition_penalty,

        (
            p.w_barcode * CAST(f.has_real_barcode AS INTEGER)
            + p.w_title_raw_exact  * CAST(f.title_raw_exact AS INTEGER)
            + p.w_artist_raw_exact * CAST(f.artist_raw_exact AS INTEGER)
            + p.w_both_raw_exact   * CAST((f.title_raw_exact AND f.artist_raw_exact) AS INTEGER)

            - p.w_edition_penalty * (
                (CASE WHEN f.mb_has_remaster    AND NOT f.cds_has_remaster    THEN 1 ELSE 0 END) +
                (CASE WHEN f.mb_has_deluxe      AND NOT f.cds_has_deluxe      THEN 1 ELSE 0 END) +
                (CASE WHEN f.mb_has_anniversary AND NOT f.cds_has_anniversary THEN 1 ELSE 0 END) +
                (CASE WHEN f.mb_has_live        AND NOT f.cds_has_live        THEN 1 ELSE 0 END) +
                (CASE WHEN f.mb_has_bonus       AND NOT f.cds_has_bonus       THEN 1 ELSE 0 END) +
                (CASE WHEN f.mb_has_discnum     AND NOT f.cds_has_discnum     THEN 1 ELSE 0 END) +
                (CASE WHEN f.mb_has_expanded    AND NOT f.cds_has_expanded    THEN 1 ELSE 0 END) +
                (CASE WHEN f.mb_has_limited     AND NOT f.cds_has_limited     THEN 1 ELSE 0 END) +
                (CASE WHEN f.mb_has_special     AND NOT f.cds_has_special     THEN 1 ELSE 0 END)
              )

            - p.w_various_artist_penalty * CAST(
                regexp_matches(lower(coalesce(f.main_artist_name, '')), '(^|[^a-z])various')
                AS INTEGER
              )
        ) AS candidate_score
    FROM features f
    CROSS JOIN params p
),
ranked AS (
    SELECT
        s.*,

        ROW_NUMBER() OVER (
            PARTITION BY cds_id
            ORDER BY
                candidate_score DESC,
                has_real_barcode DESC,
                release_id ASC
        ) AS candidate_rank,

        LEAD(candidate_score) OVER (
            PARTITION BY cds_id
            ORDER BY
                candidate_score DESC,
                has_real_barcode DESC,
                release_id ASC
        ) AS second_best_score
    FROM scored s
)
SELECT
    *,
    (candidate_score - second_best_score) AS score_gap
FROM ranked;
""")

print("✅ cds_to_mb_exact_scored created!")

print("\n--- Scored candidate sample ---")
print(con.execute("""
SELECT
    cds_id, artist, title, cds_year,
    release_id, release_title, main_artist_name, mb_year,
    candidate_score, candidate_rank, second_best_score, score_gap,
    has_real_barcode, artist_raw_exact, title_raw_exact, edition_penalty
FROM cds_to_mb_exact_scored
ORDER BY candidate_score DESC, cds_id
LIMIT 20
""").fetchdf())

Connected ✅
Creating cds_to_mb_exact_scored without year scoring...
✅ cds_to_mb_exact_scored created!

--- Scored candidate sample ---
    cds_id         artist            title  cds_year  release_id    release_title main_artist_name  mb_year  candidate_score  candidate_rank  second_best_score  score_gap  has_real_barcode  artist_raw_exact  \
0     1884   leon redbone  up a lazy river      <NA>       25586  Up a Lazy River     Leon Redbone     2022             82.0               1               82.0        0.0              True              True
1     1884   leon redbone  up a lazy river      <NA>     2940444  Up a Lazy River     Leon Redbone     2021             82.0               2               82.0        0.0              True              True
2     1884   leon redbone  up a lazy river      <NA>     4939641  Up a Lazy River     Leon Redbone     2025             82.0               3               56.0       26.0              True              True
3     2026  alkaline trio       goddamnit       1998       30355        Goddamnit    Alkaline Trio     2016             82.0               1               82.0        0.0              True              True
4     2026  alkaline trio       goddamnit       1998       43486        Goddamnit    Alkaline Trio     2014             82.0               2               82.0        0.0              True              True
5     2026  alkaline trio       goddamnit       1998      410019        Goddamnit    Alkaline Trio     2018             82.0               3               82.0        0.0              True              True
6     2026  alkaline trio       goddamnit       1998     2864371        Goddamnit    Alkaline Trio     2025             82.0               4               56.0       26.0              True              True
7     2188         estopa       destrangis      <NA>      197607       Destrangis           Estopa     2024             82.0               1                NaN        NaN              True              True
8     2571       chayanne      simplemente      1999     2829549      Simplemente         Chayanne     2020             82.0               1               82.0        0.0              True              True
9     2571       chayanne      simplemente      1999     4668868      Simplemente         Chayanne     2024             82.0               2               82.0        0.0              True              True
10    2571       chayanne      simplemente      1999     5193351      Simplemente         Chayanne     2025             82.0               3               56.0       26.0              True              True
11    2813       corduroy      out of here      <NA>      947751      Out of Here         Corduroy     2022             82.0               1               82.0        0.0              True              True
12    2813       corduroy      out of here      <NA>     3486947      Out of Here         Corduroy     2022             82.0               2               82.0        0.0              True              True
13    2813       corduroy      out of here      <NA>     3645107      Out Of Here         Corduroy     2022             82.0               3               56.0       26.0              True              True
14    2819    peter white        promenade      1993      553063        Promenade      Peter White     2020             82.0               1               82.0        0.0              True              True
15    2819    peter white        promenade      1993     3558117        Promenade      Peter White     2022             82.0               2                NaN        NaN              True              True
16    2957        kenny g       the moment      <NA>      868930       The Moment          Kenny G     2022             82.0               2               82.0        0.0              True              True
17    2957        kenny g       the moment      <NA>      989957       The Moment          Kenny G     2017             82.0               3               82.0        0.0              True              True
18    2957        kenny g       the moment      <NA>     1597858       The Moment          Kenny G     2022             82.0               4               82.0        0.0              True              True
19    2957        kenny g       the moment      <NA>     1728926       The Moment          Kenny G     2022             82.0               5               82.0        0.0              True              True

    title_raw_exact  edition_penalty
0              True                0
1              True                0
2              True                0
3              True                0
4              True                0
5              True                0
6              True                0
7              True                0
8              True                0
9              True                0
10             True                0
11             True                0
12             True                0
13             True                0
14             True                0
15             True                0
16             True                0
17             True                0
18             True                0
19             True                0

In [ ]:
#cds_to_mb_exact_scored stores all exact CDS–MusicBrainz candidate pairs together with their heuristic ranking features and scores.
#In contrast, cds_to_mb_best_exact_v4 is the reduced output of this ranking step and contains only the top-ranked candidate (candidate_rank = 1) for each CDS record.

In [212]:
import duckdb
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 220)

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

print("Recreating cds_to_mb_best_exact_v4 without year-based confidence...")

con.execute("""
CREATE OR REPLACE TABLE cds_to_mb_best_exact_v4 AS
SELECT
    cds_id,
    artist,
    title,
    cds_year,
    category,
    genre,
    tracks,
    release_id,
    release_title,
    main_artist_name,
    artist_credit_full,
    total_tracks,
    barcode,
    mb_year,
    n_candidates,
    candidate_score,
    candidate_rank,
    second_best_score,
    score_gap,
    has_real_barcode,
    artist_raw_exact,
    title_raw_exact,
    edition_penalty,

    CASE
        WHEN n_candidates = 1 THEN 'high'
        WHEN n_candidates > 1
             AND candidate_score >= 60
             AND coalesce(score_gap, 0) >= 8 THEN 'high'
        WHEN n_candidates > 1
             AND candidate_score >= 45
             AND coalesce(score_gap, 0) >= 3 THEN 'medium'
        ELSE 'low'
    END AS match_confidence
FROM cds_to_mb_exact_scored
WHERE candidate_rank = 1;
""")

print("✅ cds_to_mb_best_exact created!")

print("\n--- Check schema ---")
print(con.execute("DESCRIBE cds_to_mb_best_exact_v4").fetchdf())

print("\n--- Best exact match stats ---")
print(con.execute("""
SELECT
    COUNT(*) AS total_best_matches,
    SUM(CASE WHEN match_confidence = 'high' THEN 1 ELSE 0 END) AS high_confidence,
    SUM(CASE WHEN match_confidence = 'medium' THEN 1 ELSE 0 END) AS medium_confidence,
    SUM(CASE WHEN match_confidence = 'low' THEN 1 ELSE 0 END) AS low_confidence
FROM cds_to_mb_best_exact_v4
""").fetchdf())

print("\n--- Preview ---")
print(con.execute("""
SELECT
    cds_id, artist, title, cds_year,
    release_id, release_title, main_artist_name, mb_year,
    candidate_score, score_gap, n_candidates, match_confidence
FROM cds_to_mb_best_exact_v4
ORDER BY candidate_score DESC, cds_id
LIMIT 20
""").fetchdf())

Connected ✅
Recreating cds_to_mb_best_exact_v4 without year-based confidence...
✅ cds_to_mb_best_exact created!

--- Check schema ---
           column_name    column_type null   key default extra
0               cds_id         BIGINT  YES  None    None  None
1               artist        VARCHAR  YES  None    None  None
2                title        VARCHAR  YES  None    None  None
3             cds_year        INTEGER  YES  None    None  None
4             category        VARCHAR  YES  None    None  None
5                genre        VARCHAR  YES  None    None  None
6               tracks        VARCHAR  YES  None    None  None
7           release_id        INTEGER  YES  None    None  None
8        release_title        VARCHAR  YES  None    None  None
9     main_artist_name        VARCHAR  YES  None    None  None
10  artist_credit_full        VARCHAR  YES  None    None  None
11        total_tracks        HUGEINT  YES  None    None  None
12             barcode        VARCHAR  YES  None    None  None
13             mb_year         BIGINT  YES  None    None  None
14        n_candidates         BIGINT  YES  None    None  None
15     candidate_score  DECIMAL(18,1)  YES  None    None  None
16      candidate_rank         BIGINT  YES  None    None  None
17   second_best_score  DECIMAL(18,1)  YES  None    None  None
18           score_gap  DECIMAL(18,1)  YES  None    None  None
19    has_real_barcode        BOOLEAN  YES  None    None  None
20    artist_raw_exact        BOOLEAN  YES  None    None  None
21     title_raw_exact        BOOLEAN  YES  None    None  None
22     edition_penalty        INTEGER  YES  None    None  None
23    match_confidence        VARCHAR  YES  None    None  None

--- Best exact match stats ---
   total_best_matches  high_confidence  medium_confidence  low_confidence
0                3482           1825.0               79.0          1578.0

--- Preview ---
    cds_id                 artist                  title  cds_year  release_id          release_title       main_artist_name  mb_year  candidate_score  score_gap  n_candidates match_confidence
0     1884           leon redbone        up a lazy river      <NA>       25586        Up a Lazy River           Leon Redbone     2022             82.0        0.0             4              low
1     2026          alkaline trio             goddamnit       1998       30355              Goddamnit          Alkaline Trio     2016             82.0        0.0             6              low
2     2188                 estopa             destrangis      <NA>      197607             Destrangis                 Estopa     2024             82.0        NaN             1             high
3     2571               chayanne            simplemente      1999     2829549            Simplemente               Chayanne     2020             82.0        0.0             4              low
4     2813               corduroy            out of here      <NA>      947751            Out of Here               Corduroy     2022             82.0        0.0             4              low
5     2819            peter white              promenade      1993      553063              Promenade            Peter White     2020             82.0        0.0             2              low
6     2957                kenny g             the moment      <NA>       26935             The Moment                Kenny G     2020             82.0        0.0            12              low
7     3086           the drifters    under the boardwalk      <NA>      116641    Under the Boardwalk           The Drifters     2020             82.0        0.0            12              low
8     3096  the philosopher kings  the philosopher kings      <NA>      180558  The Philosopher Kings  The Philosopher Kings     2009             82.0        0.0             3              low
9     3106                kenny g             the moment      1996       26935             The Moment                Kenny G     2020             82.0        0.0            12              low
10    3134              metallica              metallica      1991         328              Metallica              Metallica     2022             82.0        0.0            59              low
11    3155               corduroy            out of here      1995      947751            Out of Here               Corduroy     2022             82.0        0.0             4              low
12    3192       vanessa williams      the sweetest days      1995     2849032      The Sweetest Days       Vanessa Williams     2026             82.0        0.0             6              low
13    3296           james taylor          greatest hits      1976      288662          Greatest Hits           James Taylor     2022             82.0        0.0            13              low
14    3356         paul oakenfold                 bunkka      2002       58873                 Bunkka         Paul Oakenfold     2026             82.0        0.0             6              low
15    3475             rob zombie       hellbilly deluxe      <NA>      455415       Hellbilly Deluxe             Rob Zombie     2019             82.0        0.0             5              low
16    3539                   aqua               aquarius      2000       65183               Aquarius                   Aqua     2018             82.0        0.0            14              low
17    3670                nirvana              nevermind      <NA>        7518              Nevermind                Nirvana     2022             82.0        0.0            86              low
18    3678              kate bush        the kick inside      1978      246990        The Kick Inside              Kate Bush     2022             82.0        0.0           120              low
19    3722              radiohead              the bends      1995        1784              The Bends              Radiohead     2022             82.0        0.0            38              low

In [185]:
import duckdb

# Connect to the DuckDB database
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# Create a table containing all CDS rows that did NOT receive
# an exact match in cds_to_mb_best_exact_v4
con.execute("""
    CREATE OR REPLACE TABLE cds_unmatched_after_exact_v4 AS
    SELECT c.*
    FROM cds_norm c
    LEFT JOIN cds_to_mb_best_exact_v4 m
      ON c.cds_id = m.cds_id
    WHERE m.cds_id IS NULL;
""")

# Export the unmatched rows to CSV for inspection / reporting
con.execute("""
    COPY cds_unmatched_after_exact_v4
    TO '../data_processed/exports/cds_unmatched_after_exact_v4.csv'
    WITH (HEADER, DELIMITER ',')
""")

print("✅ Table created: cds_unmatched_after_exact_v4")
print("✅ Saved: ../data_processed/exports/cds_unmatched_after_exact_v4.csv")

# Show how many CDS rows are still unmatched after the exact stage
print(con.execute("""
    SELECT COUNT(*) AS unmatched_rows
    FROM cds_unmatched_after_exact_v4
""").fetchdf())

Connected ✅
✅ Table created: cds_unmatched_after_exact_v4
✅ Saved: ../data_processed/exports/cds_unmatched_after_exact_v4.csv
   unmatched_rows
0            6281

In [213]:
#deletes the old CSVs, then writes the new ones.
import duckdb
import os

# Connect
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# Output folder
out_dir = "../data_processed/exports"
os.makedirs(out_dir, exist_ok=True)

tables = [
    "cds_to_mb_exact_matches",
    "cds_to_mb_exact_scored",
    "cds_to_mb_best_exact_v4"
]

for table in tables:
    out_path = os.path.join(out_dir, f"{table}.csv")

    # Delete old CSV if it already exists
    if os.path.exists(out_path):
        os.remove(out_path)
        print(f"🗑️ Deleted old file: {out_path}")

    # Export fresh CSV
    con.execute(f"""
        COPY (
            SELECT *
            FROM {table}
        ) TO '{out_path}'
        (HEADER, DELIMITER ',');
    """)
    print(f"✅ Exported new file: {out_path}")

con.close()
print("Done ✅")

Connected ✅
🗑️ Deleted old file: ../data_processed/exports\cds_to_mb_exact_matches.csv
✅ Exported new file: ../data_processed/exports\cds_to_mb_exact_matches.csv
🗑️ Deleted old file: ../data_processed/exports\cds_to_mb_exact_scored.csv
✅ Exported new file: ../data_processed/exports\cds_to_mb_exact_scored.csv
🗑️ Deleted old file: ../data_processed/exports\cds_to_mb_best_exact_v4.csv
✅ Exported new file: ../data_processed/exports\cds_to_mb_best_exact_v4.csv
Done ✅

In [223]:
import duckdb
import os

# Connect
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")
print(con.execute("""
    SELECT
        COUNT(*) AS total_rows,
        COUNT(DISTINCT cds_id) AS distinct_cds_id,
        COUNT(*) - COUNT(DISTINCT cds_id) AS duplicate_cds_id_rows
    FROM cds_to_mb_best_exact_v4
""").fetchdf())

Connected ✅
   total_rows  distinct_cds_id  duplicate_cds_id_rows
0        3482             3482                      0

In [222]:
import duckdb
import os

# Connect
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")
print(con.execute("""
    SELECT
        COUNT(*) AS total_rows,
        COUNT(DISTINCT release_id) AS distinct_release_id,
        COUNT(*) - COUNT(DISTINCT release_id) AS repeated_release_rows
    FROM cds_to_mb_best_exact_v4
""").fetchdf())

Connected ✅
   total_rows  distinct_release_id  repeated_release_rows
0        3482                 3340                    142

In [220]:
import duckdb
import os

# Connect
con = duckdb.connect("../data_processed/thesis.duckdb")
print(con.execute("""
    SELECT
        release_id,
        release_title,
        main_artist_name,
        COUNT(*) AS cds_links
    FROM cds_to_mb_best_exact_v4
    GROUP BY release_id, release_title, main_artist_name
    HAVING COUNT(*) > 1
    ORDER BY cds_links DESC, release_id
    LIMIT 20
""").fetchdf())

    release_id      release_title   main_artist_name  cds_links
0         7518          Nevermind            Nirvana          5
1          678          ANThology     Alien Ant Farm          4
2         3827      Hybrid Theory        Linkin Park          4
3         8194       Ray of Light            Madonna          4
4         1784          The Bends          Radiohead          3
5         2783     Disintegration           The Cure          3
6         8006    Laundry Service            Shakira          3
7         8013             Let Go      Avril Lavigne          3
8         8417     We Can’t Dance            Genesis          3
9        13268  Money for Nothing       Dire Straits          3
10       18490       Whoa, Nelly!      Nelly Furtado          3
11       38994          Justified  Justin Timberlake          3
12       70115     Mental Jewelry               Live          3
13      246990    The Kick Inside          Kate Bush          3
14     1007028   King James Bible  Alexander Scourby          3
15          51       The X Factor        Iron Maiden          2
16          89      Stacie Orrico      Stacie Orrico          2
17         328          Metallica          Metallica          2
18         538     Shepherd Moons               Enya          2
19        1200           No Angel               Dido          2

In [235]:
import duckdb

# Connect to the DuckDB database
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# Create a profiled version of the unmatched table
# This adds quality flags and cleaned helper columns
con.execute(r"""
    CREATE OR REPLACE TABLE cds_unmatched_profiled_v4 AS
    SELECT
        *,

        -- -----------------------------
        -- Missingness indicators
        -- -----------------------------
        CASE WHEN artist IS NULL OR trim(artist) = '' THEN 1 ELSE 0 END AS missing_artist,
        CASE WHEN title  IS NULL OR trim(title)  = '' THEN 1 ELSE 0 END AS missing_title,
        CASE WHEN tracks IS NULL OR trim(tracks) = '' THEN 1 ELSE 0 END AS missing_tracks,
        CASE WHEN cds_year IS NULL THEN 1 ELSE 0 END AS missing_year,

        -- -----------------------------
        -- Weak / short text indicators
        -- Very short artist/title strings are high-risk for matching
        -- -----------------------------
        CASE WHEN length(trim(coalesce(artist, ''))) < 4 THEN 1 ELSE 0 END AS short_artist,
        CASE WHEN length(trim(coalesce(title,  ''))) < 4 THEN 1 ELSE 0 END AS short_title,

        -- -----------------------------
        -- Mojibake / encoding corruption markers
        -- These patterns often indicate broken text encoding
        -- -----------------------------
        CASE
            WHEN regexp_matches(coalesce(artist, ''), 'Ã|â|Â|�')
              OR regexp_matches(coalesce(title,  ''), 'Ã|â|Â|�')
              OR regexp_matches(coalesce(tracks, ''), 'Ã|â|Â|�')
            THEN 1 ELSE 0
        END AS is_mojibake,

        -- -----------------------------
        -- Various Artists markers
        -- These rows often need a special matching strategy
        -- -----------------------------
        CASE
            WHEN lower(trim(coalesce(artist, ''))) IN ('various', 'various artists', 'va', 'v a', 'v.a.')
            THEN 1 ELSE 0
        END AS is_various_artists,

        -- -----------------------------
        -- disc/cd/vol markers in title
        -- These often create noisy title variants
        -- -----------------------------
        CASE
            WHEN regexp_matches(lower(coalesce(title, '')), '(disc|cd|vol|volume)\s*0*\d+')
            THEN 1 ELSE 0
        END AS has_disc_cd_vol,

        -- -----------------------------
        -- Generic titles
        -- These are risky because they match too many releases
        -- -----------------------------
        CASE
            WHEN lower(trim(coalesce(title, ''))) IN (
                'greatest hits', 'live', 'best of', 'the best of', 'now', 'soundtrack', 'hits', 'mix', 'mixes'
            )
            THEN 1 ELSE 0
        END AS is_generic_title,

        -- -----------------------------
        -- Cleaned helper text
        -- Lowercase + normalized whitespace
        -- -----------------------------
        regexp_replace(lower(coalesce(artist, '')), '\s+', ' ', 'g') AS artist_clean,
        regexp_replace(lower(coalesce(title,  '')), '\s+', ' ', 'g') AS title_clean,

        -- Remove disc/cd/vol number patterns from title
        regexp_replace(
            regexp_replace(lower(coalesce(title, '')), '(disc|cd|vol|volume)\s*0*\d+', '', 'g'),
            '\s+', ' ', 'g'
        ) AS title_no_disc,

        -- -----------------------------
        -- Clean alphanumeric keys for later matching / grouping
        -- -----------------------------
        lower(regexp_replace(coalesce(artist, ''), '[^a-zA-Z0-9]+', '', 'g')) AS artist_key_clean,
        lower(regexp_replace(
            regexp_replace(
                regexp_replace(lower(coalesce(title, '')), '(disc|cd|vol|volume)\s*0*\d+', '', 'g'),
                '\b(remastered|remaster|deluxe|edition|bonus|expanded|reissue|live)\b', '', 'g'
            ),
            '[^a-zA-Z0-9]+', '', 'g'
        )) AS title_key_clean

    FROM cds_unmatched_after_exact_v4
""")

print("✅ Table created: cds_unmatched_profiled_v4")

Connected ✅
✅ Table created: cds_unmatched_profiled_v4

In [236]:
import duckdb

# Connect to the DuckDB database
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# Summarize the main data-quality issues in the unmatched set
print(con.execute("""
    SELECT
        COUNT(*) AS total_unmatched,
        SUM(missing_artist) AS missing_artist,
        SUM(missing_title) AS missing_title,
        SUM(missing_tracks) AS missing_tracks,
        SUM(missing_year) AS missing_year,
        SUM(short_artist) AS short_artist,
        SUM(short_title) AS short_title,
        SUM(is_mojibake) AS mojibake_rows,
        SUM(is_various_artists) AS various_artist_rows,
        SUM(has_disc_cd_vol) AS disc_cd_vol_rows,
        SUM(is_generic_title) AS generic_title_rows
    FROM cds_unmatched_profiled_v4
""").fetchdf())

Connected ✅
   total_unmatched  missing_artist  missing_title  missing_tracks  missing_year  short_artist  short_title  mojibake_rows  various_artist_rows  disc_cd_vol_rows  generic_title_rows
0             6281             7.0           11.0             1.0        3019.0         178.0        114.0          509.0               1087.0            1163.0                38.0

In [248]:
import duckdb
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 220)

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

print("Creating improved unmatched profiling with score + reason + priority...")

con.execute(r"""
CREATE OR REPLACE TABLE cds_unmatched_profiled_v5 AS
WITH scored AS (
    SELECT
        u.*,

        CASE
            WHEN missing_artist = 1 OR missing_title = 1 THEN 'missing_core_fields'
            WHEN is_mojibake = 1 THEN 'encoding_corruption'
            WHEN short_artist = 1 OR short_title = 1 THEN 'short_text'
            WHEN is_various_artists = 1 THEN 'various_artists_case'
            WHEN is_generic_title = 1 THEN 'generic_title_case'
            WHEN has_disc_cd_vol = 1 THEN 'disc_volume_variant'
            ELSE 'clean_but_unmatched'
        END AS primary_unmatched_reason,

        (
            5 * CAST((missing_artist = 1 OR missing_title = 1) AS INTEGER)
          + 4 * CAST(is_mojibake AS INTEGER)
          + 2 * CAST((short_artist = 1 OR short_title = 1) AS INTEGER)
          + 2 * CAST(is_various_artists AS INTEGER)
          + 2 * CAST(is_generic_title AS INTEGER)
          + 1 * CAST(has_disc_cd_vol AS INTEGER)
          + 1 * CAST(missing_year AS INTEGER)
          + 1 * CAST(missing_tracks AS INTEGER)
        ) AS unmatched_risk_score

    FROM cds_unmatched_profiled_v4 u
),
final AS (
    SELECT
        scored.*,
        CASE
            WHEN unmatched_risk_score >= 5 THEN 'low'     -- noisy / not worth much effort
            WHEN unmatched_risk_score >= 2 THEN 'medium'  -- special handling might help
            ELSE 'high'                                   -- clean candidates for next-step matching
        END AS next_step_priority
    FROM scored
)
SELECT * FROM final;
""")

print("✅ Table created: cds_unmatched_profiled_v5")

print("\n--- Row count ---")
print(con.execute("SELECT COUNT(*) AS n FROM cds_unmatched_profiled_v5").fetchdf())

print("\n--- Priority distribution ---")
print(con.execute("""
    SELECT next_step_priority, COUNT(*) AS n
    FROM cds_unmatched_profiled_v5
    GROUP BY next_step_priority
    ORDER BY
        CASE next_step_priority
            WHEN 'high' THEN 1
            WHEN 'medium' THEN 2
            ELSE 3
        END
""").fetchdf())

print("\n--- Main unmatched reasons ---")
print(con.execute("""
    SELECT primary_unmatched_reason, COUNT(*) AS n
    FROM cds_unmatched_profiled_v5
    GROUP BY primary_unmatched_reason
    ORDER BY n DESC
""").fetchdf())

print("\n--- Preview ---")
print(con.execute("""
    SELECT
        cds_id,
        artist,
        title,
        unmatched_risk_score,
        primary_unmatched_reason,
        next_step_priority
    FROM cds_unmatched_profiled_v5
    LIMIT 20
""").fetchdf())

Connected ✅
Creating improved unmatched profiling with score + reason + priority...
✅ Table created: cds_unmatched_profiled_v5

--- Row count ---
      n
0  6281

--- Priority distribution ---
  next_step_priority     n
0               high  4178
1             medium  1800
2                low   303

--- Main unmatched reasons ---
  primary_unmatched_reason     n
0      clean_but_unmatched  3799
1     various_artists_case  1002
2      disc_volume_variant   697
3      encoding_corruption   508
4               short_text   230
5       generic_title_case    28
6      missing_core_fields    17

--- Preview ---
    cds_id                        artist                                                                         title  unmatched_risk_score primary_unmatched_reason next_step_priority
0   100001                       various                                                   frankfurt trance vol 04 cd1                     4     various_artists_case             medium
1   100003       ã â â ã â ã â ºâ ã â å                                          ã æ â³ã â žã â âºã â ã â ¹ã â ã â šâ                      4      encoding_corruption             medium
2   100004                       emanuel                                                                    felicidade                     0      clean_but_unmatched               high
3   100005   ã å â ã â ºâ ã â ºâ ºã â â     catsã â â ã â šâªã æ âªã â šâ ã æ å ã æ â ã â½â ã â šâ ã æ â ã â šâ¹ã æ ë                      5      encoding_corruption                low
4   100007               various artists                                                                     nop pop 2                     2     various_artists_case             medium
5   100009                        4 p m                                                                     sweet soul                     0      clean_but_unmatched               high
6   100010                       various                                                   frankfurt trance vol 05 cd1                     4     various_artists_case             medium
7   100011          â¾ã â â ã ãœ worship                                                            child praise vol 1                     6      encoding_corruption                low
8   100014                modern talking                                                                       univers                     4      encoding_corruption             medium
9   100016                                                                                              subway express                     9      missing_core_fields                low
10  100017                       various                                                      micmac house dance party                     2     various_artists_case             medium
11  100025  variousce italiennes disc 1   la dolce vita les tubes dance italiens les chansons dance italiennes disc 1                      2      disc_volume_variant             medium
12  100027                           v a                                                               ãƒã âºâ¹ cd 09                      9      encoding_corruption                low
13  100028               jazz signatures                                                               jazz signatures                     0      clean_but_unmatched               high
14  100029           bernadã te bidã ude                                                                 pomme d amour                     1      clean_but_unmatched               high
15  100030          ã â â ã â ã â â¾ã âµ                                                 disc13 ã å â ã â ã â ¹ã â šå                      5      encoding_corruption                low
16  100032                         v8 5e                                                                         v8 5e                     1      clean_but_unmatched               high
17  100034       ã â šã å â ã å å ã â â¾                                                                          lucy                     4      encoding_corruption             medium
18  100036                      dj irish                                                         assorted trance vol 8                     1      disc_volume_variant               high
19  100038       rennie pilgrim presents                                                             nu skool breakz 2                     1      clean_but_unmatched               high

In [249]:
import duckdb

# Connect to the DuckDB database
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# Count how many unmatched rows fall into each priority bucket
print(con.execute("""
    SELECT next_step_priority, COUNT(*) AS n
    FROM cds_unmatched_profiled_v5
    GROUP BY next_step_priority
    ORDER BY n DESC
""").fetchdf())

Connected ✅
  next_step_priority     n
0               high  4178
1             medium  1800
2                low   303

In [250]:
import duckdb

# Connect to the DuckDB database
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# Export the profiled unmatched table to CSV
# This file is useful for manual review and thesis reporting
con.execute("""
    COPY cds_unmatched_profiled_v5
    TO '../data_processed/exports/cds_unmatched_profiled_v5.csv'
    WITH (HEADER, DELIMITER ',')
""")

print("✅ Saved: ../data_processed/exports/cds_unmatched_profiled_v5.csv")

Connected ✅
✅ Saved: ../data_processed/exports/cds_unmatched_profiled_v5.csv

In [251]:
import duckdb

# Connect to the DuckDB database
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# Show a sample of unmatched rows with the new quality flags
# Useful for sanity-checking the profiling logic
print(con.execute("""
    SELECT
        cds_id, artist, title, cds_year,
        is_mojibake, is_various_artists, has_disc_cd_vol, is_generic_title,
        next_step_priority
    FROM cds_unmatched_profiled_v5
    ORDER BY
        next_step_priority DESC,
        is_mojibake DESC,
        is_various_artists DESC,
        has_disc_cd_vol DESC
    LIMIT 50
""").fetchdf())

Connected ✅
    cds_id                                           artist                                                                                                       title  cds_year  is_mojibake  is_various_artists  \
0   100003                          ã â â ã â ã â ºâ ã â å                                                                        ã æ â³ã â žã â âºã â ã â ¹ã â ã â šâ       1989            1                   0
1   101581                                      hajime sato                                                                                         blue best 1998 2003      2003            1                   0
2   100034                          ã â šã å â ã å å ã â â¾                                                                                                        lucy      2001            1                   0
3   100051                  ã â â ã â å½ã â¾ã â ã â šë ã â                                                                                                         home      1997            1                   0
4   100071                                 â ã ã ãÿâ ã ãˆâ¹                                                                   â ãµâºâ â ã âµâµâ â ã â ã ã â ã ã â½â¾ã 6      2002            1                   0
5   100074                                   ã ã ã ã ã ã ãª                                                                                        absolutã ã ã ã ãˆã 2      2003            1                   0
6   100184                                      â ã â ã â j                                                                                             â sâ â â ã â ãº      1981            1                   0
7   100216                             â â¹â¼ã ã ã¼âµâµâ ãœ                                                                                                    ã ã â ã       1999            1                   0
8   100229                                 piotr szczepanik                                                                                         najwieksze przeboje      1991            1                   0
9   100338                                          â½â²âµ                                                                      â½â²âµ âªã â ã¹â lâ â³ã¼â â ã â²pâºqâ k      2001            1                   0
10  100368                           sevillanas histã³ricas                                                                            sevillanas histã³ricas volumen i      2002            1                   0
11  100379                                            junco                                                                                                       junco      2001            1                   0
12  100385  ãƒâ â dâ â ã ã ã â¼â â ã ã ã âªâ â ã ãžâºâ ã â                                                                                         ã ã â âºâµã ã ã â ã       1999            1                   0
13  100014                                   modern talking                                                                                                     univers      1997            1                   0
14  100525                     ã â â ã â â¾ã ë ã â â ã â â¹                                                                                              ã å ë ã â ã â       1993            1                   0
15  100679                         â³â â â ã ã ã ã â ã ã â                                                                                        â¹ãœâ ã â â ã ã ãšâ 1      2001            1                   0
16  100726                                         ã å ã â¾                                                                         ã â ã âºâ ã æ â ã æ â ã æ â¼ã æ â ž      2000            1                   0
17  100775               ã â šâµã â šâ ã â šâ²ã æ â³ã â šâ                                                                                                     saigenji      2002            1                   0
18  100796                                  alpentrio tirol                                                                                             made in austria      2002            1                   0
19  100808                      ãœã ã ãœã² ã ã ã ã ãÿã ã ã²                                                                               ã ã¹ãž ã ã ã ã ã ãµã ã ã ã ã       2003            1                   0
20  100809                                           varios                                                                              celtic moods volumen 1 disco 1      2001            1                   0
21  100885                         ã â²â ã â â ã å â³ã ëœå½                                                                                                        dear      2001            1                   0
22  100974                       â ã â mâ eâ g koji tamaki                                                                                          â sâ ãµâ ã âªâºâ ãÿ      1999            1                   0
23  101049                                     so wing hong                                                                                                 don t worry      2000            1                   0
24  101101                             ã â¾ã â â ã â â ã â                                                                               ã å â ã â â ã â å yubiwaã â å       2002            1                   0
25  101196                                     paul mauriat                                                                                     mamy blue the godfather      1971            1                   0
26  101222                             ã â¾ã â â ã â â ã â   ã æ â ã æ â ã æ â ã æ â¼ã æ â³ã æ â ã â šâ ã æ â³ã æ â ã æ â ã â šâ ã æ â ã â šâ ã æ â ã æ â ã â šâ ã æ â³      2002            1                   0
27  101345                     anna maria jopek pat metheny                                                                                                    upojenie      2002            1                   0
28  101391                                    lolo reinhard                                                                                               project noâ 1      2002            1                   0
29  101397                                     â³âªã â â¼â                                                                                                      reflect      2001            1                   0
30  101407              jim pepper â claudine francois trio                                                                                                    camargue      1989            1                   0
31  101429                                     william tang                                                                                                    movin on      1996            1                   0
32  101460                                        riri soft                                                                                                   nice lazy      2003            1                   0
33  101480                     ã ã ã ã ã ã ã ã ã ã ã ã ã ã                                                                                                   ã ã ã ãƒã       1996            1                   0
34  101505                                       â³â â¼zâ¼                                                                                    â ãƒâ â â oâ aâªâºâªbâ ã       1989            1                   0
35  101517                            ã å ã â½ ã å âªã â â                                                                                       ã â âºã â â³ã â ã â ëœ      1991            1                   0
36  101523       ã ã ã ã ã ã ã ã ã ã ã ã ã ã¾ã ã ã ã ã ã ã                                                                                                      ã â ã 9      2001            1                   0
37  101549                             ã â ã â ã â¾ã â ã â                                                                 ã æ â ã â šâ¹ã æ ë ã â¼â ã æ â ã â šâ¹ã æ ë       2003            1                   0
38  102062                            ã â ã â¾â žã â â¾ã â                                                    ã â¾ã â ã â š ã â¾ã â ã æ ã â ã for ã â ã â¾â žã â â¾ã â       2003            1                   0
39  101595                                     ã â â ã â²â                                                                                                i ll be there      2001            1                   0
40  101618                        ã â â ã â³â ã â ã â šâ ã                                                                       ã â å ã â ã â ã â ¹ã â â ã ë ã âªã â ž      1991            1                   0
41  101679                                     â¹ãšã â ã ã                                                                                                      forever      2001            1                   0
42  101738                                      â pâµã â â                                                                                                  â râªâºâ ãº      1996            1                   0
43  101747                                       â â â â ã                                                                                        â râ ãšâ aâ ãˆâ fâ ãœ      2000            1                   0
44  101762                                     ãƒã âµãºã ã                                                                                       â bâ¹ãšâ bâ ã â â â â       1988            1                   0
45  101790                         ã â â ã â³â ã â¾å½ã ëœâ                                                                                                         true      2002            1                   0
46  101856                          leif kronlunds storband                                                                                    big band dancing is back      1987            1                   0
47  101879                                     ã ã â¹ãºãˆã                                                                                                       leslie      1984            1                   0
48  101947                                     â ã â âµâµâ                                                                               â¹ã â ã ã ã â¼ã â â windsongs       1999            1                   0
49  100414                                 sebastian siegel                                                                     ich mã chtâ so gern dein teddybã r sein      1997            1                   0

    has_disc_cd_vol  is_generic_title next_step_priority
0                 0                 0             medium
1                 0                 0             medium
2                 0                 0             medium
3                 0                 0             medium
4                 0                 0             medium
5                 0                 0             medium
6                 0                 0             medium
7                 0                 0             medium
8                 0                 0             medium
9                 0                 0             medium
10                0                 0             medium
11                0                 0             medium
12                0                 0             medium
13                0                 0             medium
14                0                 0             medium
15                0                 0             medium
16                0                 0             medium
17                0                 0             medium
18                0                 0             medium
19                0                 0             medium
20                0                 0             medium
21                0                 0             medium
22                0                 0             medium
23                0                 0             medium
24                0                 0             medium
25                0                 0             medium
26                0                 0             medium
27                0                 0             medium
28                0                 0             medium
29                0                 0             medium
30                0                 0             medium
31                0                 0             medium
32                0                 0             medium
33                0                 0             medium
34                0                 0             medium
35                0                 0             medium
36                0                 0             medium
37                0                 0             medium
38                0                 0             medium
39                0                 0             medium
40                0                 0             medium
41                0                 0             medium
42                0                 0             medium
43                0                 0             medium
44                0                 0             medium
45                0                 0             medium
46                0                 0             medium
47                0                 0             medium
48                0                 0             medium
49                0                 0             medium

In [252]:
import duckdb

# Connect to the DuckDB database
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# Show the most frequent artist names in the unmatched set
# This can reveal repeated failure patterns such as Various Artists or noisy artist names
print(con.execute("""
    SELECT artist, COUNT(*) AS n
    FROM cds_unmatched_profiled_v5
    GROUP BY artist
    ORDER BY n DESC
    LIMIT 20
""").fetchdf())

Connected ✅
             artist    n
0           various  618
1   various artists  436
2            varios   38
3           diverse   18
4    various artist   15
5                va   14
6       compilation   14
7            mozart   12
8         bob dylan   11
9         metallica   10
10             v a    10
11          vã rios    9
12               u2    9
13       pink floyd    8
14      the beatles    8
15             bach    8
16    elvis presley    8
17          sampler    8
18  varios artistas    7
19         j s bach    7

In [247]:
import duckdb

# Connect to the DuckDB database
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# Show the most frequent titles in the unmatched set
# This helps identify generic titles such as "Greatest Hits" or "Live"
print(con.execute("""
    SELECT title, COUNT(*) AS n
    FROM cds_unmatched_profiled_v5
    GROUP BY title
    ORDER BY n DESC
    LIMIT 20
""").fetchdf())

Connected ✅
                     title   n
0                     live  11
1            greatest hits  10
2                     None   8
3                      now   6
4      greatest hits vol 2   3
5           the collection   3
6                 volume 1   3
7               soundtrack   3
8                            3
9   ã ã ã ã ã ã ã ã ã ã ã    3
10          grandes exitos   3
11                     ten   3
12              next world   3
13            instrumental   3
14                     cd2   3
15                       3   3
16                 best of   3
17          it s christmas   3
18                the best   3
19             the best of   3

In [366]:
import duckdb

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

print("Creating corrected cds_unmatched_for_enrichment...")

con.execute(r"""
CREATE OR REPLACE TABLE cds_unmatched_for_enrichment AS
SELECT
    cds_id,
    artist,
    title,
    cds_year,
    tracks,
    next_step_priority,
    is_mojibake,
    is_various_artists,
    has_disc_cd_vol,
    is_generic_title,

    trim(regexp_replace(lower(coalesce(artist, '')), '\s+', ' ', 'g')) AS artist_clean,
    trim(regexp_replace(lower(coalesce(title,  '')), '\s+', ' ', 'g')) AS title_clean,

    -- Extract disc/cd/vol number BEFORE removing it
    TRY_CAST(
        regexp_extract(lower(coalesce(title, '')), '(disc|disk|cd|vol|volume)\s*0*([0-9]+)', 2)
        AS INTEGER
    ) AS part_number,

    -- Core title without disc/cd/vol marker
    trim(regexp_replace(
        regexp_replace(lower(coalesce(title, '')), '(disc|disk|cd|vol|volume)\s*0*[0-9]+', '', 'g'),
        '\s+', ' ', 'g'
    )) AS title_core,

    lower(regexp_replace(coalesce(artist, ''), '[^a-zA-Z0-9]+', '', 'g')) AS artist_key_clean,

    lower(regexp_replace(
        regexp_replace(
            regexp_replace(lower(coalesce(title, '')), '(disc|disk|cd|vol|volume)\s*0*[0-9]+', '', 'g'),
            '\b(remastered|remaster|deluxe|edition|bonus|expanded|reissue|live)\b', '', 'g'
        ),
        '[^a-zA-Z0-9]+', '', 'g'
    )) AS title_key_clean

FROM cds_unmatched_profiled_v5
WHERE next_step_priority IN ('high', 'medium')
""")

print("✅ Table created: cds_unmatched_for_enrichment")

Connected ✅
Creating corrected cds_unmatched_for_enrichment...
✅ Table created: cds_unmatched_for_enrichment

In [367]:
import duckdb

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

print("Creating corrected mb_integration_view...")

con.execute(r"""
CREATE OR REPLACE VIEW mb_integration_view AS
SELECT
    release_id,
    release_title,
    main_artist_name,
    artist_credit_full,
    total_tracks,
    barcode,
    mb_year,

    trim(regexp_replace(lower(coalesce(main_artist_name, '')), '\s+', ' ', 'g')) AS artist_clean,
    trim(regexp_replace(lower(coalesce(release_title,  '')), '\s+', ' ', 'g')) AS title_clean,

    TRY_CAST(
        regexp_extract(lower(coalesce(release_title, '')), '(disc|disk|cd|vol|volume)\s*0*([0-9]+)', 2)
        AS INTEGER
    ) AS part_number,

    trim(regexp_replace(
        regexp_replace(lower(coalesce(release_title, '')), '(disc|disk|cd|vol|volume)\s*0*[0-9]+', '', 'g'),
        '\s+', ' ', 'g'
    )) AS title_core,

    lower(regexp_replace(coalesce(main_artist_name, ''), '[^a-zA-Z0-9]+', '', 'g')) AS artist_key_clean,

    lower(regexp_replace(
        regexp_replace(
            regexp_replace(lower(coalesce(release_title, '')), '(disc|disk|cd|vol|volume)\s*0*[0-9]+', '', 'g'),
            '\b(remastered|remaster|deluxe|edition|bonus|expanded|reissue|live)\b', '', 'g'
        ),
        '[^a-zA-Z0-9]+', '', 'g'
    )) AS title_key_clean
FROM mb_release_features
""")

print("✅ View created: mb_integration_view")

Connected ✅
Creating corrected mb_integration_view...
✅ View created: mb_integration_view

In [368]:
#deletes the old CSVs, then writes the new ones.
import duckdb
import os

# Connect
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# Output folder
out_dir = "../data_processed/exports"
os.makedirs(out_dir, exist_ok=True)

tables = [

    "mb_integration_view",
    "cds_unmatched_for_enrichment"
]

for table in tables:
    out_path = os.path.join(out_dir, f"{table}.csv")

    # Delete old CSV if it already exists
    if os.path.exists(out_path):
        os.remove(out_path)
        print(f"🗑️ Deleted old file: {out_path}")

    # Export fresh CSV
    con.execute(f"""
        COPY (
            SELECT *
            FROM {table}
        ) TO '{out_path}'
        (HEADER, DELIMITER ',');
    """)
    print(f"✅ Exported new file: {out_path}")

con.close()
print("Done ✅")

Connected ✅
🗑️ Deleted old file: ../data_processed/exports\mb_integration_view.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

✅ Exported new file: ../data_processed/exports\mb_integration_view.csv
🗑️ Deleted old file: ../data_processed/exports\cds_unmatched_for_enrichment.csv
✅ Exported new file: ../data_processed/exports\cds_unmatched_for_enrichment.csv
Done ✅

In [369]:
import duckdb

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

print("Creating corrected mb_candidate_pool_v2...")

con.execute("""
CREATE OR REPLACE TABLE mb_candidate_pool_v2 AS
SELECT
    release_id,
    release_title,
    main_artist_name,
    artist_credit_full,
    total_tracks,
    barcode,
    mb_year,
    artist_clean,
    title_clean,
    title_core,
    artist_key_clean,
    title_key_clean,
    part_number,
    substr(artist_key_clean, 1, 1) AS artist_first,
    substr(title_key_clean,  1, 1) AS title_first,
    length(artist_key_clean) AS artist_len,
    length(title_key_clean)  AS title_len
FROM mb_integration_view
WHERE
    artist_key_clean IS NOT NULL
    AND title_key_clean IS NOT NULL
    AND length(artist_key_clean) >= 4
    AND length(title_key_clean) >= 4
""")

print("✅ Table created: mb_candidate_pool_v2")

Connected ✅
Creating corrected mb_candidate_pool_v2...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

✅ Table created: mb_candidate_pool_v2

In [372]:
import duckdb

# Connect to the DuckDB database
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Step: Generate blocked candidate pairs for enrichment
# ------------------------------------------------------------
# Comments:
# - This creates plausible CDS–MB release candidate pairs before scoring.
# - We block on:
#     * same first artist-key letter
#     * same first title-key letter
#     * similar artist/title key lengths
# - We exclude the noisiest CDS rows here:
#     * mojibake
#     * Various Artists (handled separately)
# - Important correction:
#     * if both CDS and MB titles contain an explicit disc/cd/volume number,
#       they must agree (e.g. "Vol. 1" should NOT match "Vol. 3").
print("Creating corrected cds_mb_enrichment_pairs...")

con.execute("""
CREATE OR REPLACE TABLE cds_mb_enrichment_pairs AS
SELECT
    -- --------------------------------------------------------
    -- CDS side
    -- --------------------------------------------------------
    c.cds_id,
    c.artist,
    c.title,
    c.cds_year,
    c.tracks,
    c.artist_clean AS cds_artist_clean,
    c.title_core AS cds_title_core,
    c.artist_key_clean AS cds_artist_key,
    c.title_key_clean AS cds_title_key,
    c.part_number AS cds_part_number,

    -- --------------------------------------------------------
    -- MusicBrainz side
    -- --------------------------------------------------------
    m.release_id,
    m.main_artist_name,
    m.release_title,
    m.artist_credit_full,
    m.total_tracks,
    m.barcode,
    m.mb_year,
    m.artist_clean AS mb_artist_clean,
    m.title_core AS mb_title_core,
    m.artist_key_clean AS mb_artist_key,
    m.title_key_clean AS mb_title_key,
    m.part_number AS mb_part_number

FROM (
    SELECT
        *,
        substr(artist_key_clean, 1, 1) AS artist_first,
        substr(title_key_clean, 1, 1) AS title_first,
        length(artist_key_clean) AS artist_len,
        length(title_key_clean) AS title_len
    FROM cds_unmatched_for_enrichment
    WHERE
        is_mojibake = 0
        AND is_various_artists = 0
        AND artist_key_clean IS NOT NULL
        AND title_key_clean IS NOT NULL
        AND length(artist_key_clean) >= 4
        AND length(title_key_clean) >= 4
) c
JOIN mb_candidate_pool_v2 m
  ON m.artist_first = c.artist_first
 AND m.title_first = c.title_first
 AND m.artist_len BETWEEN c.artist_len - 3 AND c.artist_len + 3
 AND m.title_len BETWEEN c.title_len - 5 AND c.title_len + 5

 -- ----------------------------------------------------------
 -- Part-number compatibility rule
 -- If both sides explicitly have a part number, they must match.
 -- This prevents false links like:
 --   CDS: "Greatest Hits Vol. 1"
 --   MB : "Greatest Hits Vol. 3"
 -- ----------------------------------------------------------
 AND (
      c.part_number IS NULL
      OR m.part_number IS NULL
      OR c.part_number = m.part_number
 )
""")

print("✅ Table created: cds_mb_enrichment_pairs")

print("\n--- Pair count ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM cds_mb_enrichment_pairs
""").fetchdf())

print("\n--- Rows with explicit part-number agreement on both sides ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM cds_mb_enrichment_pairs
    WHERE cds_part_number IS NOT NULL
      AND mb_part_number IS NOT NULL
      AND cds_part_number = mb_part_number
""").fetchdf())

print("\n--- Preview ---")
print(con.execute("""
    SELECT
        cds_id,
        artist,
        title,
        cds_part_number,
        release_id,
        main_artist_name,
        release_title,
        mb_part_number
    FROM cds_mb_enrichment_pairs
    LIMIT 25
""").fetchdf())

Connected ✅
Creating corrected cds_mb_enrichment_pairs...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

✅ Table created: cds_mb_enrichment_pairs

--- Pair count ---
          n
0  11845921

--- Rows with explicit part-number agreement on both sides ---
      n
0  6357

--- Preview ---
    cds_id                artist                                title  cds_part_number  release_id        main_artist_name                    release_title  mb_part_number
0   109006  mela tenenbaum viola                   richard kapp piano             <NA>     2750291  Manic Street Preachers        Rip It Up 5 Track Sampler            <NA>
1     7072            spineshank             the height of callousnes             <NA>     4965994           She is Legend             This Game Needs Guns            <NA>
2     1823        carlos santana                               carlos             <NA>     2912117       Corpsefucking Art                          Corpsex            <NA>
3   109077   sir john barbirolli                           halle orch             <NA>     3237600         Solemn Assembly                      Humans Fall            <NA>
4   109602       assorted artist                  summer 2003 top ten             <NA>     2753425          Anton Bruckner                   Symphony no. 6            <NA>
5   105803               the who  no substitutes msg 7 18 1996 disc 1                1     2803555                  TAEMIN  Never Gonna Dance Again : Act 1            <NA>
6   109233         maksim mrvica                     the piano player             <NA>     2805193          Melissa Romero                      Todo pasará            <NA>
7    11531             metallica                          black album             <NA>     2801322               Meltberry                     Bedroom Eyes            <NA>
8   109667              publicom               adventures of phoneman             <NA>     2608380             Phoebe Snow                Against the Grain            <NA>
9   109710         swing sisters                     vores favoritter             <NA>     2608381           Sonny Rollins                 Vintage Sessions            <NA>
10  109521                limite                         instrumental             <NA>     4960580                Level 42              Live in Switzerland            <NA>
11  108914           wim mertens                       aren lezen cd3                3     2789958               WiziBeatz                            Alpha            <NA>
12  108677           tappa zukie                    from the archives             <NA>     2792349             Tokyo Blade                 Live From London            <NA>
13  108677           tappa zukie                    from the archives             <NA>     2792346             Tokyo Blade                 Live From London            <NA>
14    2110           frans bauer                        een ons geluk             <NA>     2798701           FELIX SANDMAN                 EVERY SINGLE DAY            <NA>
15  109667              publicom               adventures of phoneman             <NA>     2608384             Phoebe Snow                Against the Grain            <NA>
16  106019          eric clapton                     live in usa 1984             <NA>     2795619              Eileen Sol                      Iconoclasta            <NA>
17  109500            soundtrack                  dying young kenny g             <NA>     3281356          Septic Karnage             Dehumanization Decay            <NA>
18    7731            ben harper      the will to live live 2 cd cd 1                1     3078073               Balmorhea                         The Wind            <NA>
19  109701               s hygys                          remix album             <NA>      775023                 SCANDAL                   R-GIRL’s ROCK!            <NA>
20  109067        antonin dvorak                     dvorak in prague             <NA>     1845541          Atomic Rooster           Death Walks Behind You            <NA>
21  108677           tappa zukie                    from the archives             <NA>     4638284           Tim Schaufert                  find a way home            <NA>
22    9257               santana                          supernatura             <NA>     2775706               Sensorica                   Sunlight Again            <NA>
23  108075        eugene bridges                      born to be blue             <NA>     2793472            Elliot Lurie                       Better Man            <NA>
24  109500            soundtrack                  dying young kenny g             <NA>     2363612            Steven Brown             De doute et de grâce            <NA>

In [373]:
import duckdb
import pandas as pd
from rapidfuzz import fuzz

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 220)

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

print("Scoring corrected candidate pairs...")

con.execute("""
CREATE OR REPLACE VIEW cds_mb_enrichment_pairs_indexed AS
SELECT row_number() OVER () AS rid, *
FROM cds_mb_enrichment_pairs
""")

total_pairs = con.execute("SELECT COUNT(*) FROM cds_mb_enrichment_pairs").fetchone()[0]
print(f"Total candidate pairs to score: {total_pairs:,}")

CHUNK_SIZE = 250_000
KEEP_PER_CHUNK = 3
all_best = []

for start in range(1, total_pairs + 1, CHUNK_SIZE):
    end = min(start + CHUNK_SIZE - 1, total_pairs)

    df = con.execute("""
        SELECT *
        FROM cds_mb_enrichment_pairs_indexed
        WHERE rid BETWEEN ? AND ?
    """, [start, end]).fetchdf()

    if df.empty:
        continue

    artist_sims = []
    title_sims = []
    scores = []

    for _, row in df.iterrows():
        a_sim = fuzz.token_set_ratio(str(row["cds_artist_clean"]), str(row["mb_artist_clean"]))
        t_sim = fuzz.token_set_ratio(str(row["cds_title_core"]), str(row["mb_title_core"]))

        score = 0.4 * a_sim + 0.6 * t_sim

        artist_sims.append(a_sim)
        title_sims.append(t_sim)
        scores.append(score)

    df["artist_sim"] = artist_sims
    df["title_sim"] = title_sims
    df["score"] = scores

    df = (
        df.sort_values(["cds_id", "score"], ascending=[True, False])
          .groupby("cds_id")
          .head(KEEP_PER_CHUNK)
    )

    all_best.append(df)

best_df = pd.concat(all_best, ignore_index=True) if all_best else pd.DataFrame()

best_df = (
    best_df.sort_values(["cds_id", "score"], ascending=[True, False])
           .groupby("cds_id")
           .head(5)
)

con.register("best_df_view", best_df)

con.execute("""
CREATE OR REPLACE TABLE cds_to_mb_enrichment_candidates AS
SELECT * FROM best_df_view
""")

print("✅ Table created: cds_to_mb_enrichment_candidates")

Connected ✅
Scoring corrected candidate pairs...
Total candidate pairs to score: 11,845,921

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

✅ Table created: cds_to_mb_enrichment_candidates

In [375]:
import duckdb
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 220)

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

SCORE_TH = 90.0
TITLE_TH = 92.0

print(f"Creating cds_to_mb_best_enrichment with score >= {SCORE_TH} and title_sim >= {TITLE_TH}...")

con.execute(f"""
CREATE OR REPLACE TABLE cds_to_mb_best_enrichment AS
WITH filtered AS (
    SELECT *
    FROM cds_to_mb_enrichment_candidates
    WHERE score >= {SCORE_TH}
      AND title_sim >= {TITLE_TH}
),
ranked AS (
    SELECT
        *,
        ROW_NUMBER() OVER (
            PARTITION BY cds_id
            ORDER BY
                score DESC,
                title_sim DESC,
                artist_sim DESC,
                release_id ASC
        ) AS rn,
        LEAD(score) OVER (
            PARTITION BY cds_id
            ORDER BY
                score DESC,
                title_sim DESC,
                artist_sim DESC,
                release_id ASC
        ) AS second_best_score
    FROM filtered
),
cds_level AS (
    SELECT
        cds_id,
        COUNT(DISTINCT mb_artist_key) AS n_artist_keys,
        COUNT(DISTINCT mb_title_key) AS n_title_keys
    FROM filtered
    GROUP BY cds_id
)
SELECT
    r.cds_id,
    r.artist,
    r.title,
    r.cds_year,
    r.release_id,
    r.release_title,
    r.main_artist_name,
    r.artist_credit_full,
    r.total_tracks,
    r.barcode,
    r.mb_year,
    r.score,
    r.artist_sim,
    r.title_sim,
    r.second_best_score,
    (r.score - r.second_best_score) AS score_gap,
    CASE
        WHEN r.second_best_score IS NULL THEN 'high'
        WHEN c.n_artist_keys = 1 AND c.n_title_keys = 1 THEN 'high'
        WHEN (r.score - r.second_best_score) >= 5 THEN 'high'
        WHEN (r.score - r.second_best_score) >= 2 THEN 'medium'
        ELSE 'low'
    END AS enrichment_confidence
FROM ranked r
JOIN cds_level c
  ON r.cds_id = c.cds_id
WHERE r.rn = 1
""")

print("✅ Table created: cds_to_mb_best_enrichment")

Connected ✅
Creating cds_to_mb_best_enrichment with score >= 90.0 and title_sim >= 92.0...
✅ Table created: cds_to_mb_best_enrichment

In [376]:
import duckdb
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 220)

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

print("\n--- Low-confidence enrichment pairs ---")
low_df = con.execute("""
    SELECT
        cds_id,
        artist,
        title,
        cds_year,
        release_id,
        release_title,
        main_artist_name,
        mb_year,
        score,
        title_sim,
        artist_sim,
        second_best_score,
        score_gap,
        enrichment_confidence
    FROM cds_to_mb_best_enrichment
    WHERE enrichment_confidence = 'low'
    ORDER BY score DESC, score_gap ASC, cds_id
    LIMIT 50
""").fetchdf()

low_df

Connected ✅

--- Low-confidence enrichment pairs ---

,cds_id,artist,title,cds_year,release_id,release_title,main_artist_name,mb_year,score,title_sim,artist_sim,second_best_score,score_gap,enrichment_confidence
0,102424,armin van buuren,a state of trance 2004 cd2,2004,81056,A State of Trance 2004,Armin van Buuren,2023,100.000000,100.000000,100.000000,100.000000,0.000000,low
1,103702,peter rauhofer,live roxy cd1,2002,441999,Live @ Roxy 4,Peter Rauhofer,2024,100.000000,100.000000,100.000000,100.000000,0.000000,low
2,104080,roy orbison,roy orbison cd2,<NA>,621375,Roy Orbison,Roy Orbison,2025,100.000000,100.000000,100.000000,100.000000,0.000000,low
3,104673,butter 08,butter 08,<NA>,163082,Butter,Butter 08,2024,100.000000,100.000000,100.000000,100.000000,0.000000,low
4,104846,the beatles,the beatles vol 9,<NA>,212391,The Beatles,The Beatles,2020,100.000000,100.000000,100.000000,100.000000,0.000000,low
5,105070,the beatles,the black album disc 3,<NA>,861020,The Black Album,The Beatles,2016,100.000000,100.000000,100.000000,100.000000,0.000000,low
6,105433,new order,substance 1987 disc 1,1987,16498,Substance 1987,New Order,2022,100.000000,100.000000,100.000000,100.000000,0.000000,low
7,107480,armin van buuren,a state of trance 2004 cd1,2004,81056,A State of Trance 2004,Armin van Buuren,2023,100.000000,100.000000,100.000000,100.000000,0.000000,low
8,108846,joseph haydn,the 12 london symphonies cd 2 4,1972,365121,The 12 London Symphonies,Joseph Haydn,2024,100.000000,100.000000,100.000000,100.000000,0.000000,low
9,108885,johann sebastian bach,cantatas vol 5 cd 11,1996,1026137,Cantatas BWV 4-6,Johann Sebastian Bach,2022,100.000000,100.000000,100.000000,100.000000,0.000000,low
10,109049,leonard bernstein,bernstein conducts bernstein cd5,<NA>,1959019,Bernstein conducts Bernstein,Leonard Bernstein,2020,100.000000,100.000000,100.000000,100.000000,0.000000,low
11,109531,akira yamaoka,silent hill 2 ost,<NA>,800570,Silent Hill,Akira Yamaoka,2014,100.000000,100.000000,100.000000,100.000000,0.000000,low
12,103893,renato e seus blue caps,renato e seus blue caps,<NA>,21979,Renato e Seus Blue Caps (1996),Renato e Seus Blue Caps,2012,100.000000,100.000000,100.000000,98.723404,1.276596,low
13,108270,variouis artists,the seed variations on a theme by john kerr,<NA>,138168,The Seed - Variations on a Theme by John Kerr,Various Artists,2025,98.709677,100.000000,96.774194,98.709677,0.000000,low
14,11190,varius artists,mozart greatest hits,<NA>,2555196,Mozart Greatest Hits,Various Artists,2019,98.620690,100.000000,96.551724,98.620690,0.000000,low
15,101043,varios artistas,soul,<NA>,464838,Soul CD #08,Various Artists,2018,97.333333,100.000000,93.333333,97.333333,0.000000,low
16,103386,star academy 3,les singles,2004,3278136,Les Singles,Star Academy 2,2021,97.142857,100.000000,92.857143,97.142857,0.000000,low
17,105884,creedence clearwater revival,pround mary,1991,982622,Proud Mary,Creedence Clearwater Revival,2021,97.142857,95.238095,100.000000,97.142857,0.000000,low
18,106987,visage,fade to gray the best of visage,1993,230119,Fade to Grey: The Best of Visage,Visage,2021,97.142857,95.238095,100.000000,97.142857,0.000000,low
19,103344,various artist,space night vol vi cd 2,2001,203997,Space Night Vol. VI,Various Artists,2017,96.999068,97.297297,96.551724,95.287356,1.711712,low
20,109671,jose carreras,jose carreras sings andrew lloyd webber,<NA>,993790,Jose Carreras Sings Andrew Lloyd Webber,José Carreras,2013,96.923077,100.000000,92.307692,95.384615,1.538462,low
21,104798,abbacadabra,revival flight 2,1998,313126,Revival Flight Two,Abbacadabra,2022,96.000000,93.333333,100.000000,96.000000,0.000000,low
22,101685,rolf just nielsen,barnas viser 2,<NA>,1054093,Barnas viser 1,Rolf Just Nilsen,2018,94.502165,92.857143,96.969697,94.502165,0.000000,low
23,105654,johnny horton,greatest hits,<NA>,1130874,Greatest Hits,Johnny Tillotson,2012,90.344828,100.000000,75.862069,90.344828,0.000000,low

In [377]:
# 1) Inspect all candidates for one problematic cds_id, e.g. 1838
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

print(con.execute("""
    SELECT
        cds_id,
        release_id,
        mb_artist_key,
        mb_title_key,
        total_tracks,
        score
    FROM cds_to_mb_enrichment_candidates
    WHERE cds_id = 1838
    ORDER BY score DESC, release_id
""").fetchdf())

# 2) See how cds_level aggregates look for the same cds_id
print(con.execute("""
    SELECT *
    FROM (
        SELECT
            cds_id,
            MIN(score)  AS min_score,
            MAX(score)  AS max_score,
            COUNT(DISTINCT mb_artist_key) AS n_artist_keys,
            COUNT(DISTINCT mb_title_key)  AS n_title_keys,
            COUNT(DISTINCT total_tracks)  AS n_track_counts
        FROM cds_to_mb_enrichment_candidates
        WHERE score >= 90 AND title_sim >= 92
        GROUP BY cds_id
    )
    WHERE cds_id IN (1838, 2707, 6413, 100492)
""").fetchdf())

Connected ✅
   cds_id  release_id mb_artist_key  mb_title_key  total_tracks  score
0    1838      137707          2pac  greatesthits          25.0  100.0
1    1838     2208058          2pac  greatesthits          25.0  100.0
2    1838     2610338          2pac  greatesthits          25.0  100.0
3    1838     3303486          2pac  greatesthits          25.0  100.0
4    1838     3473055          2pac  greatesthits          25.0  100.0
   cds_id  min_score  max_score  n_artist_keys  n_title_keys  n_track_counts
0    6413      100.0      100.0              1             1               2
1  100492      100.0      100.0              1             1               2
2    1838      100.0      100.0              1             1               1
3    2707      100.0      100.0              1             1               3

In [378]:
import duckdb
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 220)

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

print("Creating corrected cds_to_mb_final_mapping_v5...")

con.execute("""
CREATE OR REPLACE TABLE cds_to_mb_final_mapping_v5 AS

SELECT
    x.cds_id,
    x.artist,
    x.title,
    x.cds_year,
    x.release_id,
    x.release_title,
    x.main_artist_name,
    x.artist_credit_full,
    x.total_tracks,
    x.barcode,
    x.mb_year,
    'exact' AS match_type,
    x.match_confidence AS confidence_label,
    x.candidate_score AS score,
    NULL::DOUBLE AS title_sim,
    NULL::DOUBLE AS artist_sim
FROM cds_to_mb_best_exact_v4 x

UNION ALL

SELECT
    e.cds_id,
    e.artist,
    e.title,
    e.cds_year,
    e.release_id,
    e.release_title,
    e.main_artist_name,
    e.artist_credit_full,
    e.total_tracks,
    e.barcode,
    e.mb_year,
    'fuzzy_second_pass' AS match_type,
    e.enrichment_confidence AS confidence_label,
    e.score,
    e.title_sim,
    e.artist_sim
FROM cds_to_mb_best_enrichment e
LEFT JOIN cds_to_mb_best_exact_v4 x
  ON x.cds_id = e.cds_id
WHERE x.cds_id IS NULL
  AND e.enrichment_confidence = 'high'
""")

print("✅ Table created: cds_to_mb_final_mapping_v5")

print(con.execute("""
    SELECT
        COUNT(*) AS total_rows,
        COUNT(DISTINCT cds_id) AS distinct_cds_id,
        COUNT(*) - COUNT(DISTINCT cds_id) AS duplicate_cds_id_rows
    FROM cds_to_mb_final_mapping_v5
""").fetchdf())

Connected ✅
Creating corrected cds_to_mb_final_mapping_v5...
✅ Table created: cds_to_mb_final_mapping_v5
   total_rows  distinct_cds_id  duplicate_cds_id_rows
0        4017             4017                      0

In [379]:
import duckdb

# Connect to the DuckDB database
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Step 8: Export useful outputs to CSV
# ------------------------------------------------------------
print("Exporting enrichment outputs...")

con.execute("""
    COPY cds_to_mb_best_enrichment
    TO '../data_processed/exports/cds_to_mb_best_enrichment.csv'
    WITH (HEADER, DELIMITER ',')
""")

con.execute("""
    COPY cds_to_mb_final_mapping_v5
    TO '../data_processed/exports/cds_to_mb_final_mapping_v5.csv'
    WITH (HEADER, DELIMITER ',')
""")

print("✅ Saved: ../data_processed/exports/cds_to_mb_best_enrichment.csv")
print("✅ Saved: ../data_processed/exports/cds_to_mb_final_mapping_v5.csv")

Connected ✅
Exporting enrichment outputs...
✅ Saved: ../data_processed/exports/cds_to_mb_best_enrichment.csv
✅ Saved: ../data_processed/exports/cds_to_mb_final_mapping_v5.csv

In [380]:
import duckdb
import pandas as pd

# Connect to DuckDB
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Thesis report table 1:
# Overall matching coverage after exact matching and enrichment
# ------------------------------------------------------------
report_coverage = con.execute("""
    SELECT
        (SELECT COUNT(*) FROM cds) AS cds_total,
        (SELECT COUNT(*) FROM cds_to_mb_best_exact_v4) AS exact_v4_matched,
        (SELECT COUNT(*) FROM cds_unmatched_after_exact_v4) AS unmatched_after_exact_v4,
        (SELECT COUNT(*) FROM cds_to_mb_best_enrichment) AS enrichment_added,
        (SELECT COUNT(*) FROM cds_to_mb_final_mapping_v5) AS total_matched_after_enrichment,
        (SELECT COUNT(*) FROM cds) - (SELECT COUNT(*) FROM cds_to_mb_final_mapping_v5) AS still_unmatched_after_enrichment
""").fetchdf()

print("\n--- Thesis Report: Coverage Summary ---")
print(report_coverage)

Connected ✅

--- Thesis Report: Coverage Summary ---
   cds_total  exact_v4_matched  unmatched_after_exact_v4  enrichment_added  total_matched_after_enrichment  still_unmatched_after_enrichment
0       9763              3482                      6281               564                            4017                              5746

In [381]:
import duckdb
import pandas as pd

# Connect to DuckDB
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Thesis report table 2:
# Data profiling of the unmatched CDS remainder after exact matching
# ------------------------------------------------------------
report_unmatched_profile = con.execute("""
    SELECT
        COUNT(*) AS total_unmatched,
        SUM(missing_artist) AS missing_artist,
        SUM(missing_title) AS missing_title,
        SUM(missing_tracks) AS missing_tracks,
        SUM(missing_year) AS missing_year,
        SUM(short_artist) AS short_artist,
        SUM(short_title) AS short_title,
        SUM(is_mojibake) AS mojibake_rows,
        SUM(is_various_artists) AS various_artist_rows,
        SUM(has_disc_cd_vol) AS disc_cd_vol_rows,
        SUM(is_generic_title) AS generic_title_rows
    FROM cds_unmatched_profiled_v4
""").fetchdf()

print("\n--- Thesis Report: Unmatched Data Profiling ---")
print(report_unmatched_profile)

Connected ✅

--- Thesis Report: Unmatched Data Profiling ---
   total_unmatched  missing_artist  missing_title  missing_tracks  missing_year  short_artist  short_title  mojibake_rows  various_artist_rows  disc_cd_vol_rows  generic_title_rows
0             6281             7.0           11.0             1.0        3019.0         178.0        114.0          509.0               1087.0            1163.0                38.0

In [293]:
import duckdb
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 220)

# Connect to DuckDB
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Step: Standardize and isolate Various Artists rows
# from the unmatched set for a title-driven matching pipeline
# ------------------------------------------------------------
print("Creating cds_various_unmatched_cleaned...")

con.execute(r"""
    CREATE OR REPLACE TABLE cds_various_unmatched_cleaned AS
    SELECT
        cds_id,
        artist,
        title,
        cds_year,
        tracks,
        next_step_priority,
        is_mojibake,
        has_disc_cd_vol,
        is_generic_title,

        -- Canonicalized artist label
        'various_artists' AS artist_canonical,

        -- Clean title text
        trim(regexp_replace(lower(coalesce(title, '')), '\s+', ' ', 'g')) AS title_clean,

        -- Remove disc/cd/vol number patterns
        trim(regexp_replace(
            regexp_replace(lower(coalesce(title, '')), '(disc|disk|cd|vol|volume)\s*0*\d+', '', 'g'),
            '\s+', ' ', 'g'
        )) AS title_no_disc,

        -- Title-only matching key
        lower(regexp_replace(
            regexp_replace(
                regexp_replace(lower(coalesce(title, '')), '(disc|disk|cd|vol|volume)\s*0*\d+', '', 'g'),
                '\b(remastered|remaster|deluxe|edition|bonus|expanded|reissue|live)\b', '', 'g'
            ),
            '[^a-zA-Z0-9]+', '', 'g'
        )) AS title_key_various

    FROM cds_unmatched_profiled_v5
    WHERE lower(trim(coalesce(artist, ''))) IN (
        'various', 'various artists', 'various artist',
        'va', 'v a', 'v.a.',
        'varios', 'varios artistas', 'vàrios'
    )
      AND coalesce(title, '') <> ''
      AND is_mojibake = 0
""")

print("✅ Table created: cds_various_unmatched_cleaned")

print("\n--- Preview: standardized Various Artists rows ---")
print(con.execute("""
    SELECT
        cds_id,
        artist,
        artist_canonical,
        title,
        title_no_disc,
        title_key_various,
        next_step_priority
    FROM cds_various_unmatched_cleaned
    LIMIT 20
""").fetchdf())

print("\n--- Count of standardized Various Artists rows ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM cds_various_unmatched_cleaned
""").fetchdf())

Connected ✅
Creating cds_various_unmatched_cleaned...
✅ Table created: cds_various_unmatched_cleaned

--- Preview: standardized Various Artists rows ---
    cds_id           artist artist_canonical                                            title                                    title_no_disc                         title_key_various next_step_priority
0   100001          various  various_artists                      frankfurt trance vol 04 cd1                                 frankfurt trance                           frankfurttrance             medium
1   100007  various artists  various_artists                                        nop pop 2                                        nop pop 2                                   noppop2             medium
2   100010          various  various_artists                      frankfurt trance vol 05 cd1                                 frankfurt trance                           frankfurttrance             medium
3   100017          various  various_artists                         micmac house dance party                         micmac house dance party                     micmachousedanceparty             medium
4   100039          various  various_artists                            salsaenlacalleocho 96                            salsaenlacalleocho 96                      salsaenlacalleocho96             medium
5   100044          various  various_artists                                  custom music cd                                  custom music cd                             custommusiccd             medium
6   100056  various artists  various_artists               essential selection winter 97 cd1                     essential selection winter 97                essentialselectionwinter97             medium
7   100060          various  various_artists                            windhamhillsampler 92                            windhamhillsampler 92                      windhamhillsampler92             medium
8   100063  various artists  various_artists  an audio cd of african american oral traditions  an audio cd of african american oral traditions  anaudiocdofafricanamericanoraltraditions             medium
9   100089  various artists  various_artists                                   dorival caymmi                                   dorival caymmi                             dorivalcaymmi             medium
10  100101          various  various_artists                            ich hab schlager lieb                            ich hab schlager lieb                        ichhabschlagerlieb             medium
11  100103           varios  various_artists                               time well spent 93                               time well spent 93                           timewellspent93               high
12  100135  various artists  various_artists                 populã re musik aus griechenland                 populã re musik aus griechenland               populremusikausgriechenland             medium
13  100164          various  various_artists                                 hollyday musik 2                                 hollyday musik 2                            hollydaymusik2             medium
14  100181  various artists  various_artists                                   tzlil mechuvan                                   tzlil mechuvan                             tzlilmechuvan             medium
15  100201  various artists  various_artists                   14 hollandse nieuwe gouwe cd12                        14 hollandse nieuwe gouwe                    14hollandsenieuwegouwe             medium
16  100212          various  various_artists                           grapevine a collection                           grapevine a collection                      grapevineacollection             medium
17  100240          various  various_artists                                hollandse kanjers                                hollandse kanjers                          hollandsekanjers             medium
18  100253  various artists  various_artists                                   made in greece                                   made in greece                              madeingreece             medium
19  100279  various artists  various_artists          um barquinho e um violã o vol 1 disco 2                um barquinho e um violã o disco 2                 umbarquinhoeumviolodisco2             medium

--- Count of standardized Various Artists rows ---
      n
0  1084

In [294]:
import duckdb
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 220)

# Connect to DuckDB
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Various Artists enrichment step:
# Build a MusicBrainz title-only integration view
# ------------------------------------------------------------
# Comments:
# - For Various Artists rows, artist is not discriminative enough.
# - So we prepare MusicBrainz release titles for title-only matching.
# - We apply similar cleaning:
#   * lowercase
#   * collapse whitespace
#   * remove disc/cd/vol numbers
#   * remove edition markers
#   * create a title-only key
print("Creating mb_various_title_integration_view...")

con.execute(r"""
    CREATE OR REPLACE VIEW mb_various_title_integration_view AS
    SELECT
        release_id,
        release_title,
        main_artist_name,
        artist_credit_full,
        total_tracks,
        barcode,
        mb_year,

        -- Clean title text
        trim(regexp_replace(lower(coalesce(release_title, '')), '\s+', ' ', 'g')) AS title_clean,

        -- Remove disc/cd/vol number patterns
        trim(regexp_replace(
            regexp_replace(lower(coalesce(release_title, '')), '(disc|disk|cd|vol|volume)\s*0*\d+', '', 'g'),
            '\s+', ' ', 'g'
        )) AS title_no_disc,

        -- Title-only matching key
        lower(regexp_replace(
            regexp_replace(
                regexp_replace(lower(coalesce(release_title, '')), '(disc|disk|cd|vol|volume)\s*0*\d+', '', 'g'),
                '\b(remastered|remaster|deluxe|edition|bonus|expanded|reissue|live)\b', '', 'g'
            ),
            '[^a-zA-Z0-9]+', '', 'g'
        )) AS title_key_various

    FROM mb_release_features
    WHERE coalesce(release_title, '') <> ''
""")

print("✅ View created: mb_various_title_integration_view")

print("\n--- Preview: MB title-only integration view ---")
print(con.execute("""
    SELECT
        release_id,
        release_title,
        title_no_disc,
        title_key_various
    FROM mb_various_title_integration_view
    WHERE title_key_various IS NOT NULL
      AND length(title_key_various) > 0
    LIMIT 20
""").fetchdf())

Connected ✅
Creating mb_various_title_integration_view...
✅ View created: mb_various_title_integration_view

--- Preview: MB title-only integration view ---
    release_id                         release_title                         title_no_disc                title_key_various
0       178087  Blechdance: Ritter Rost zum Abtanzen  blechdance: ritter rost zum abtanzen  blechdanceritterrostzumabtanzen
1       178088                                 Verte                                 verte                            verte
2       178097                             Egouality                             egouality                        egouality
3       178098                             Egouality                             egouality                        egouality
4       178100                             Démo 2005                             démo 2005                          dmo2005
5       178101                             Démo 2005                             démo 2005                          dmo2005
6      1210603           The Greatest Hits, Volume 2                    the greatest hits,                  thegreatesthits
7       178107                            Encounter!                            encounter!                        encounter
8       178109                               Popcore                               popcore                          popcore
9       319607                                  DUNK                                  dunk                             dunk
10      178113                          Generation X                          generation x                      generationx
11      178114                           Desipramine                           desipramine                      desipramine
12      178123                       Diario di bordo                       diario di bordo                    diariodibordo
13      178127                            Day by Day                            day by day                         daybyday
14      178133                    Lips Like Morphine                    lips like morphine                 lipslikemorphine
15     1438389                    My Favorite Things                    my favorite things                 myfavoritethings
16     1428730                          Moral Hazard                          moral hazard                      moralhazard
17      178124                  Tomorrow Is Too Late                  tomorrow is too late                tomorrowistoolate
18     4225835                    Living Dub, Vol. 5                    living dub, vol. 5                    livingdubvol5
19     1545397                              Partners                              partners                         partners

In [295]:
import duckdb
import pandas as pd

# Connect to DuckDB
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Various Artists enrichment step:
# Generate safe title-only candidate pairs
# ------------------------------------------------------------
# Comments:
# - We match CDS Various Artists rows to MB by cleaned title-only key.
# - This is safer than fuzzy matching on artist because artist is too generic here.
# - We require a minimum key length to reduce collisions.
# - We also exclude mojibake rows from this step.
print("Creating cds_various_candidate_pairs...")

con.execute("""
    CREATE OR REPLACE TABLE cds_various_candidate_pairs AS
    SELECT
        c.cds_id,
        c.artist,
        c.artist_canonical,
        c.title,
        c.title_no_disc,
        c.title_key_various,
        c.cds_year,
        c.next_step_priority,

        m.release_id,
        m.release_title,
        m.main_artist_name,
        m.artist_credit_full,
        m.total_tracks,
        m.barcode,
        m.mb_year,
        m.title_no_disc AS mb_title_no_disc

    FROM cds_various_unmatched_cleaned c
    JOIN mb_various_title_integration_view m
      ON c.title_key_various = m.title_key_various
    WHERE
        c.is_mojibake = 0
        AND c.title_key_various IS NOT NULL
        AND length(c.title_key_various) >= 8
""")

print("✅ Table created: cds_various_candidate_pairs")

print("\n--- Candidate pair count ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM cds_various_candidate_pairs
""").fetchdf())

print("\n--- Distinct CDS rows with candidates ---")
print(con.execute("""
    SELECT COUNT(DISTINCT cds_id) AS cds_rows_with_candidates
    FROM cds_various_candidate_pairs
""").fetchdf())

print("\n--- Preview: Various Artists candidate pairs ---")
print(con.execute("""
    SELECT
        cds_id,
        title,
        title_no_disc,
        release_id,
        release_title,
        mb_title_no_disc,
        total_tracks,
        barcode,
        mb_year,
        next_step_priority
    FROM cds_various_candidate_pairs
    LIMIT 20
""").fetchdf())

Connected ✅
Creating cds_various_candidate_pairs...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

✅ Table created: cds_various_candidate_pairs

--- Candidate pair count ---
      n
0  3817

--- Distinct CDS rows with candidates ---
   cds_rows_with_candidates
0                       388

--- Preview: Various Artists candidate pairs ---
    cds_id                          title                  title_no_disc  release_id                             release_title                mb_title_no_disc  total_tracks        barcode  mb_year next_step_priority
0   102701  disco pogo for punks in pumps  disco pogo for punks in pumps      179806  Disco Pogo for Punks in Pumps, Volume 11  disco pogo for punks in pumps,          12.0           None     2013             medium
1   102701  disco pogo for punks in pumps  disco pogo for punks in pumps      179809  Disco Pogo for Punks in Pumps, Volume 12  disco pogo for punks in pumps,          12.0           None     2013             medium
2   109704                    love song s                    love song s      180462                                Love Songs                      love songs          12.0           None     2022               high
3   101865                   on the beach                   on the beach      180753                              On the Beach                    on the beach          13.0           None     2014             medium
4   105779                born to be wild                born to be wild      181854                           Born to Be Wild                 born to be wild          12.0           None     <NA>             medium
5   101821             this is trance cd1                 this is trance      182135                           This Is Trance!                 this is trance!          17.0           None     2012             medium
6   109593           hollywood movie hits           hollywood movie hits     1293798                      Hollywood Movie Hits            hollywood movie hits          10.0   056775800925     2013               high
7   109704                    love song s                    love song s      184768                                Love Songs                      love songs          14.0           None     2012               high
8   103483                communicate cd1                    communicate      185632                              Communicate!                    communicate!          12.0           None     <NA>             medium
9   101865                   on the beach                   on the beach     2535654                              On the Beach                    on the beach          23.0  4943674302734     2019             medium
10  100010    frankfurt trance vol 05 cd1               frankfurt trance      190028                          Frankfurt Trance                frankfurt trance          22.0  4017866122667     2019             medium
11  109704                    love song s                    love song s      190559                                Love Songs                      love songs          15.0           None     <NA>               high
12  100001    frankfurt trance vol 04 cd1               frankfurt trance      190028                          Frankfurt Trance                frankfurt trance          22.0  4017866122667     2019             medium
13  105779                born to be wild                born to be wild      192629                           Born to Be Wild                 born to be wild          17.0           None     <NA>             medium
14  107469               house party vol5                    house party     2167333                               House Party                     house party           8.0                    2018             medium
15  106271       visions all areas vol 36              visions all areas      199884             VISIONS: All Areas, Volume 77             visions: all areas,          13.0           None     2009             medium
16  105975        visions all areas vol 3              visions all areas      199884             VISIONS: All Areas, Volume 77             visions: all areas,          13.0           None     2009             medium
17  105618       visions all areas vol 18              visions all areas      199884             VISIONS: All Areas, Volume 77             visions: all areas,          13.0           None     2009             medium
18  106888                    dance party                    dance party      202560                               Dance Party                     dance party          12.0           None     <NA>               high
19  109704                    love song s                    love song s      202714                                Love Songs                      love songs          12.0   077775725629     2025               high

In [297]:
import duckdb
import pandas as pd
from rapidfuzz import fuzz

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 220)

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

print("Scoring cds_various_candidate_pairs and creating cds_various_best_match...")

df = con.execute("""
    SELECT
        p.cds_id,
        p.artist,
        p.artist_canonical,
        p.title,
        p.title_no_disc,
        p.title_key_various,
        p.cds_year,
        p.next_step_priority,

        p.release_id,
        p.release_title,
        p.main_artist_name,
        p.artist_credit_full,
        p.total_tracks,
        p.barcode,
        p.mb_year,
        p.mb_title_no_disc,
        m.title_key_various AS mb_title_key_various
    FROM cds_various_candidate_pairs p
    LEFT JOIN mb_various_title_integration_view m
      ON p.release_id = m.release_id
""").fetchdf()

print(f"Candidate pairs loaded: {len(df):,}")

if df.empty:
    best_df = pd.DataFrame()
else:
    title_token_sims = []
    title_char_sims = []
    scores = []
    has_barcode = []

    for t1, k1, t2, k2, bc in zip(
        df["title_no_disc"],
        df["title_key_various"],
        df["mb_title_no_disc"],
        df["mb_title_key_various"],
        df["barcode"]
    ):
        t1 = "" if pd.isna(t1) else str(t1)
        k1 = "" if pd.isna(k1) else str(k1)
        t2 = "" if pd.isna(t2) else str(t2)
        k2 = "" if pd.isna(k2) else str(k2)

        token_sim = fuzz.token_set_ratio(t1, t2)
        char_sim = fuzz.ratio(k1, k2)

        # title-only score
        score = 0.7 * token_sim + 0.3 * char_sim

        title_token_sims.append(token_sim)
        title_char_sims.append(char_sim)
        scores.append(score)
        has_barcode.append(0 if pd.isna(bc) or str(bc).strip() == "" else 1)

    df["title_token_sim"] = title_token_sims
    df["title_char_sim"] = title_char_sims
    df["score"] = scores
    df["has_barcode"] = has_barcode

    # rank candidates per CDS row
    df = df.sort_values(
        ["cds_id", "score", "title_token_sim", "title_char_sim", "has_barcode", "release_id"],
        ascending=[True, False, False, False, False, True]
    ).copy()

    # second-best score per cds_id
    df["second_best_score"] = df.groupby("cds_id")["score"].shift(-1)
    df["score_gap"] = df["score"] - df["second_best_score"]

    # keep best row per cds_id
    best_df = df.groupby("cds_id", as_index=False).head(1).copy()

    # confidence rules
    def classify(row):
        if pd.isna(row["second_best_score"]):
            return "high"
        if row["score"] >= 98 and row["score_gap"] >= 2:
            return "high"
        if row["score"] >= 95 and row["score_gap"] >= 1:
            return "medium"
        return "low"

    best_df["various_confidence"] = best_df.apply(classify, axis=1)

con.register("best_various_df_view", best_df)

con.execute("""
    CREATE OR REPLACE TABLE cds_various_best_match AS
    SELECT * FROM best_various_df_view
""")

print("✅ Table created: cds_various_best_match")

print("\n--- Best Various Artists match count ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM cds_various_best_match
""").fetchdf())

print("\n--- Confidence distribution ---")
print(con.execute("""
    SELECT various_confidence, COUNT(*) AS n
    FROM cds_various_best_match
    GROUP BY various_confidence
    ORDER BY
        CASE various_confidence
            WHEN 'high' THEN 1
            WHEN 'medium' THEN 2
            ELSE 3
        END
""").fetchdf())

print("\n--- Preview best Various Artists matches ---")
print(con.execute("""
    SELECT
        cds_id,
        artist,
        title,
        release_id,
        release_title,
        main_artist_name,
        score,
        title_token_sim,
        title_char_sim,
        second_best_score,
        score_gap,
        various_confidence
    FROM cds_various_best_match
    ORDER BY score DESC, cds_id
    LIMIT 25
""").fetchdf())

Connected ✅
Scoring cds_various_candidate_pairs and creating cds_various_best_match...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Candidate pairs loaded: 3,817
✅ Table created: cds_various_best_match

--- Best Various Artists match count ---
     n
0  388

--- Confidence distribution ---
  various_confidence    n
0               high  184
1             medium   17
2                low  187

--- Preview best Various Artists matches ---
    cds_id           artist                                title  release_id                  release_title             main_artist_name  score  title_token_sim  title_char_sim  second_best_score  score_gap  \
0   100001          various          frankfurt trance vol 04 cd1      190028               Frankfurt Trance              Various Artists  100.0            100.0           100.0                NaN        NaN
1   100010          various          frankfurt trance vol 05 cd1      190028               Frankfurt Trance              Various Artists  100.0            100.0           100.0                NaN        NaN
2   100089  various artists                       dorival caymmi     5519190                 Dorival Caymmi               Dorival Caymmi  100.0            100.0           100.0                NaN        NaN
3   100253  various artists                       made in greece     1104836                 Made in Greece            Μιχάλης Ρακιντζής  100.0            100.0           100.0                NaN        NaN
4   100419  various artists                           swing city      135609                     Swing City   Roger Brown and Swing City  100.0            100.0           100.0                NaN        NaN
5   100432          various                      celtic heritage     1186775                Celtic Heritage              Various Artists  100.0            100.0           100.0         100.000000   0.000000
6   100600          various                children of the world      167800          Children of the World                     Bee Gees  100.0            100.0           100.0         100.000000   0.000000
7   100648           varios                   parranda vallenata     2070246             Parranda vallenata              Various Artists  100.0            100.0           100.0                NaN        NaN
8   100701          various       the best of folk music disc 1      2074362         The Best of Folk Music              Various Artists  100.0            100.0           100.0                NaN        NaN
9   100773  various artists                      celtic mystique      497351                Celtic Mystique                  Howard Baer  100.0            100.0           100.0         100.000000   0.000000
10  100783          various        irish beer drinking favorites      992626  Irish Beer Drinking Favorites              Various Artists  100.0            100.0           100.0                NaN        NaN
11  100793          various              pipes drums of scotland     2683017      Pipes & Drums of Scotland  Bun'ber E Pipe & Drum Corps  100.0            100.0           100.0         100.000000   0.000000
12  100862          various                         smooth moods      748266                   Smooth Moods              Various Artists  100.0            100.0           100.0                NaN        NaN
13  100863  various artists          hed kandi back to love cd2      2193551         Hed Kandi Back to Love              Various Artists  100.0            100.0           100.0         100.000000   0.000000
14  100869          various                           nu de lune      413734                     Nu De Lune              Various Artists  100.0            100.0           100.0                NaN        NaN
15  100968          various                   savoy jazz sampler     2367724             Savoy Jazz Sampler              Various Artists  100.0            100.0           100.0          98.108108   1.891892
16  100989          various                  how low can you go      2892115             How Low Can You Go                           LP  100.0            100.0           100.0         100.000000   0.000000
17  100996          various             jazz in the house 3 cd1       122194            Jazz in the House 3              Various Artists  100.0            100.0           100.0         100.000000   0.000000
18  101144          various              the cool school of jazz      977729        The Cool School of Jazz              Various Artists  100.0            100.0           100.0                NaN        NaN
19  101158          various                       trumpet summit      295332                 Trumpet Summit               Allen Vizzutti  100.0            100.0           100.0         100.000000   0.000000
20  101229  various artists                      jazz moods cd 2       82879                     Jazz Moods              Various Artists  100.0            100.0           100.0         100.000000   0.000000
21  101259          various                           jazz dance     2274197                   Jazz & Dance              Various Artists  100.0            100.0           100.0          66.842105  33.157895
22  101326          various                      jazz for lovers      512197                Jazz for Lovers              Various Artists  100.0            100.0           100.0         100.000000   0.000000
23  101438          various                    make jazz not war     1617258              Make Jazz Not War              Various Artists  100.0            100.0           100.0                NaN        NaN
24  101457          various  all time christmas favorites vol 2       864460   All Time Christmas Favorites              Various Artists  100.0            100.0           100.0          98.771930   1.228070

   various_confidence
0                high
1                high
2                high
3                high
4                high
5                 low
6                 low
7                high
8                high
9                 low
10               high
11                low
12               high
13                low
14               high
15             medium
16                low
17                low
18               high
19                low
20                low
21               high
22                low
23               high
24             medium

In [298]:
import duckdb
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 220)

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

print("\n--- Low-confidence Various Artists matches (187 rows) ---")
low_df = con.execute("""
    SELECT
        cds_id,
        artist,
        title,
        cds_year,
        release_id,
        release_title,
        main_artist_name,
        mb_year,
        score,
        title_token_sim,
        title_char_sim,
        second_best_score,
        score_gap,
        various_confidence
    FROM cds_various_best_match
    WHERE various_confidence = 'low'
    ORDER BY score DESC, cds_id
    LIMIT 50
""").fetchdf()

low_df

Connected ✅

--- Low-confidence Various Artists matches (187 rows) ---

,cds_id,artist,title,cds_year,release_id,release_title,main_artist_name,mb_year,score,title_token_sim,title_char_sim,second_best_score,score_gap,various_confidence
0,100432,various,celtic heritage,2000,1186775,Celtic Heritage,Various Artists,2012,100.0,100.0,100.0,100.0,0.0,low
1,100600,various,children of the world,1994,167800,Children of the World,Bee Gees,2014,100.0,100.0,100.0,100.0,0.0,low
2,100773,various artists,celtic mystique,<NA>,497351,Celtic Mystique,Howard Baer,2010,100.0,100.0,100.0,100.0,0.0,low
3,100793,various,pipes drums of scotland,<NA>,2683017,Pipes & Drums of Scotland,Bun'ber E Pipe & Drum Corps,2020,100.0,100.0,100.0,100.0,0.0,low
4,100863,various artists,hed kandi back to love cd2,1999,2193551,Hed Kandi Back to Love,Various Artists,2018,100.0,100.0,100.0,100.0,0.0,low
5,100989,various,how low can you go,<NA>,2892115,How Low Can You Go,LP,2020,100.0,100.0,100.0,100.0,0.0,low
6,100996,various,jazz in the house 3 cd1,1996,122194,Jazz in the House 3,Various Artists,2009,100.0,100.0,100.0,100.0,0.0,low
7,101158,various,trumpet summit,<NA>,295332,Trumpet Summit,Allen Vizzutti,2022,100.0,100.0,100.0,100.0,0.0,low
8,101229,various artists,jazz moods cd 2,<NA>,82879,Jazz Moods,Various Artists,2023,100.0,100.0,100.0,100.0,0.0,low
9,101326,various,jazz for lovers,2000,512197,Jazz for Lovers,Various Artists,2021,100.0,100.0,100.0,100.0,0.0,low
10,101470,various artists,best of love songs vol 2,<NA>,114169,Best of Love Songs,Various Artists,2022,100.0,100.0,100.0,100.0,0.0,low
11,101563,various artists,on the trail,<NA>,1031166,On the Trail,Frankie Laine,2016,100.0,100.0,100.0,100.0,0.0,low
12,101567,various,techno trance,<NA>,458054,Techno Trance,Various Artists,2025,100.0,100.0,100.0,100.0,0.0,low
13,101576,various,one hit wonders,2002,192977,One Hit Wonders,Various Artists,2019,100.0,100.0,100.0,100.0,0.0,low
14,101603,various artists,universal rhythm,1996,769249,Universal Rhythm,Ralph MacDonald,2018,100.0,100.0,100.0,100.0,0.0,low
15,101659,various artists,christmas favourites disc 2,<NA>,199655,Christmas Favourites,Various Artists,2016,100.0,100.0,100.0,100.0,0.0,low
16,101821,various artists,this is trance cd1,<NA>,1331541,This Is Trance,Various Artists,2023,100.0,100.0,100.0,100.0,0.0,low
17,101865,various,on the beach,<NA>,263324,On the Beach,Chris Rea,2012,100.0,100.0,100.0,100.0,0.0,low
18,101941,various,as we travel,<NA>,4510132,As We Travel,The Loose Strings Band,2024,100.0,100.0,100.0,100.0,0.0,low
19,102018,various artists,your disco needs you,2001,150863,Your Disco Needs You,Kylie Minogue,2023,100.0,100.0,100.0,100.0,0.0,low
20,102026,va,club anthems cd2,2001,271937,Club Anthems,ballboy,<NA>,100.0,100.0,100.0,100.0,0.0,low
21,102086,various artists,jungle boogie,1997,4530202,Jungle Boogie,Kohndo,2024,100.0,100.0,100.0,100.0,0.0,low
22,102133,various artists,latin mix usa vol 2,1999,25556,Latin Mix USA,Various Artists,2021,100.0,100.0,100.0,100.0,0.0,low
23,102241,various,across the water,<NA>,94456,Across the Water,Jadis,2025,100.0,100.0,100.0,100.0,0.0,low
24,102281,various artists,hits of the seventies volume 1 disc 2,1989,501570,Hits of the Seventies,Various Artists,2009,100.0,100.0,100.0,100.0,0.0,low
25,102287,various artists,songs for the journey vol 11,2003,2374391,Songs For The Journey,Sandi Patty,2019,100.0,100.0,100.0,100.0,0.0,low
26,102310,various,boogie wonderland disc 2,1978,656260,Boogie Wonderland,"Earth, Wind & Fire",2010,100.0,100.0,100.0,100.0,0.0,low
27,102425,various artists,spiritual life music cd2,2001,150700,Spiritual Life Music,Various Artists,2012,100.0,100.0,100.0,100.0,0.0,low
28,102467,various,the spirit of christmas,<NA>,395625,The Spirit of Christmas,Ray Charles,2020,100.0,100.0,100.0,100.0,0.0,low
29,102604,various artists,memories are made of this disc 2,2004,124041,Memories Are Made of This,Dean Martin,2023,100.0,100.0,100.0,100.0,0.0,low
30,102798,various artists,oldies but goodies vol 6 cd1,1994,160665,Oldies but Goodies,Various Artists,2025,100.0,100.0,100.0,100.0,0.0,low
31,102826,various artists,heart of christmas,1994,5338365,Heart of Christmas,SAAY,2025,100.0,100.0,100.0,100.0,0.0,low
32,102835,various artists,american music,2001,426013,American Music,The Blasters,2022,100.0,100.0,100.0,100.0,0.0,low
33,102916,various artists,rough mix volume 1 disc 2,1996,362432,Rough Mix,Pete Townshend,<NA>,100.0,100.0,100.0,100.0,0.0,low
34,102956,various,we come in peace,1998,1214430,We Come in Peace,D.O.A.,2012,100.0,100.0,100.0,100.0,0.0,low
35,102959,various,nu afrobeat experience,2002,2873126,Nu Afrobeat Experience,Various Artists,2020,100.0,100.0,100.0,100.0,0.0,low
36,103105,various,songs of the siren,1998,384964,Songs of the Siren,Various Artists,2023,100.0,100.0,100.0,100.0,0.0,low
37,103114,various,dance max 8 cd 1,<NA>,805357,Dance Max 8,Various Artists,2018,100.0,100.0,100.0,100.0,0.0,low
38,103155,various,in da jungle,<NA>,2789378,In da Jungle,Playboy,2020,100.0,100.0,100.0,100.0,0.0,low
39,103189,various,sax for lovers disc 3,<NA>,4868562,Sax for Lovers,The Marco Phillipe Orchestra,2025,100.0,100.0,100.0,100.0,0.0,low
40,103330,various,black power vol 1,<NA>,1800830,Black Power,The Peace,2016,100.0,100.0,100.0,100.0,0.0,low
41,103376,various,music box,<NA>,36529,Music Box,Mariah Carey,2012,100.0,100.0,100.0,100.0,0.0,low
42,103431,various,the art of song,2002,4284450,The Art of Song,Daron Aric Hagen,2024,100.0,100.0,100.0,100.0,0.0,low
43,103451,various,celtic dream disc 2,2000,2963939,Celtic Dream,Carrantuohill,2021,100.0,100.0,100.0,100.0,0.0,low
44,103483,various artists,communicate cd1,<NA>,60234,Communicate,Sasha & John Digweed,2024,100.0,100.0,100.0,100.0,0.0,low
45,103493,various artists,songs of christmas vol 1,<NA>,22260,Songs of Christmas,The Silver Bells Orchestra,2023,100.0,100.0,100.0,100.0,0.0,low
46,103534,various,hits of the fifties,<NA>,1344755,Hits of the Fifties,Various Artists,2013,100.0,100.0,100.0,100.0,0.0,low
47,103601,various artists,time warp,1984,222360,Time Warp,Erich Kunzel,2021,100.0,100.0,100.0,100.0,0.0,low
48,103686,various,art of acid trance disc 1,<NA>,1054249,Art of Acid Trance,Various Artists,2012,100.0,100.0,100.0,100.0,0.0,low
49,103825,various,star gazing,2003,406445,Star Gazing,Various Artists,2021,100.0,100.0,100.0,100.0,0.0,low

In [339]:
import duckdb
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 220)

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

print("Creating cds_to_mb_final_mapping_v6...")

con.execute("""
    CREATE OR REPLACE TABLE cds_to_mb_final_mapping_v6 AS

    -- 1) Exact-stage matches
    SELECT
        x.cds_id,
        x.artist,
        x.title,
        x.cds_year,
        x.release_id,
        x.release_title,
        x.main_artist_name,
        x.artist_credit_full,
        x.total_tracks,
        x.barcode,
        x.mb_year,
        'exact' AS match_type,
        x.match_confidence AS confidence_label,
        x.candidate_score AS score,
        NULL::DOUBLE AS title_sim,
        NULL::DOUBLE AS artist_sim
    FROM cds_to_mb_best_exact_v4 x

    UNION ALL

    -- 2) Second-pass fuzzy matches
    SELECT
        f.cds_id,
        f.artist,
        f.title,
        f.cds_year,
        f.release_id,
        f.release_title,
        f.main_artist_name,
        f.artist_credit_full,
        f.total_tracks,
        f.barcode,
        f.mb_year,
        'fuzzy_second_pass' AS match_type,
        f.enrichment_confidence AS confidence_label,
        f.score,
        f.title_sim,
        f.artist_sim
    FROM cds_to_mb_best_enrichment f
    LEFT JOIN cds_to_mb_best_exact_v4 x
      ON x.cds_id = f.cds_id
    WHERE x.cds_id IS NULL
      AND f.enrichment_confidence = 'high'

    UNION ALL

    -- 3) Various Artists title-only matches
    SELECT
        v.cds_id,
        v.artist,
        v.title,
        v.cds_year,
        v.release_id,
        v.release_title,
        v.main_artist_name,
        v.artist_credit_full,
        v.total_tracks,
        v.barcode,
        v.mb_year,
        'various_title_only' AS match_type,
        v.various_confidence AS confidence_label,
        v.score,
        v.title_token_sim AS title_sim,
        NULL::DOUBLE AS artist_sim
    FROM cds_various_best_match v
    LEFT JOIN cds_to_mb_best_exact_v4 x
      ON x.cds_id = v.cds_id
    LEFT JOIN cds_to_mb_best_enrichment f
      ON f.cds_id = v.cds_id
         AND f.enrichment_confidence = 'high'
    WHERE x.cds_id IS NULL
      AND f.cds_id IS NULL
      AND v.various_confidence = 'high'
""")

print("✅ Table created: cds_to_mb_final_mapping_v6")

print("\n--- Coverage report ---")
print(con.execute("""
    WITH
    exact_cte AS (
        SELECT COUNT(*) AS n
        FROM cds_to_mb_best_exact_v4
    ),
    fuzzy_high_cte AS (
        SELECT COUNT(*) AS n
        FROM cds_to_mb_best_enrichment f
        LEFT JOIN cds_to_mb_best_exact_v4 x
          ON x.cds_id = f.cds_id
        WHERE x.cds_id IS NULL
          AND f.enrichment_confidence = 'high'
    ),
    various_high_cte AS (
        SELECT COUNT(*) AS n
        FROM cds_various_best_match v
        LEFT JOIN cds_to_mb_best_exact_v4 x
          ON x.cds_id = v.cds_id
        LEFT JOIN cds_to_mb_best_enrichment f
          ON f.cds_id = v.cds_id
             AND f.enrichment_confidence = 'high'
        WHERE x.cds_id IS NULL
          AND f.cds_id IS NULL
          AND v.various_confidence = 'high'
    ),
    final_cte AS (
        SELECT COUNT(*) AS n
        FROM cds_to_mb_final_mapping_v6
    )
    SELECT
        (SELECT COUNT(*) FROM cds) AS cds_total,
        (SELECT n FROM exact_cte) AS exact_matched,
        (SELECT n FROM fuzzy_high_cte) AS fuzzy_high_added,
        (SELECT n FROM various_high_cte) AS various_high_added,
        (SELECT n FROM final_cte) AS total_matched,
        (SELECT COUNT(*) FROM cds) - (SELECT n FROM final_cte) AS still_unmatched
""").fetchdf())

print("\n--- Match type distribution ---")
print(con.execute("""
    SELECT match_type, COUNT(*) AS n
    FROM cds_to_mb_final_mapping_v6
    GROUP BY match_type
    ORDER BY n DESC
""").fetchdf())

print("\n--- Confidence distribution ---")
print(con.execute("""
    SELECT confidence_label, COUNT(*) AS n
    FROM cds_to_mb_final_mapping_v6
    GROUP BY confidence_label
    ORDER BY n DESC
""").fetchdf())

print("\n--- Uniqueness check by cds_id ---")
print(con.execute("""
    SELECT
        COUNT(*) AS total_rows,
        COUNT(DISTINCT cds_id) AS distinct_cds_id,
        COUNT(*) - COUNT(DISTINCT cds_id) AS duplicate_cds_id_rows
    FROM cds_to_mb_final_mapping_v6
""").fetchdf())

print("\n--- Preview final mapping ---")
print(con.execute("""
    SELECT
        cds_id,
        artist,
        title,
        cds_year,
        release_id,
        release_title,
        main_artist_name,
        mb_year,
        match_type,
        confidence_label,
        score,
        title_sim,
        artist_sim
    FROM cds_to_mb_final_mapping_v6
    ORDER BY cds_id
    LIMIT 25
""").fetchdf())

Connected ✅
Creating cds_to_mb_final_mapping_v6...
✅ Table created: cds_to_mb_final_mapping_v6

--- Coverage report ---
   cds_total  exact_matched  fuzzy_high_added  various_high_added  total_matched  still_unmatched
0       9763           3482               543                 183           4208             5555

--- Match type distribution ---
           match_type     n
0               exact  3482
1   fuzzy_second_pass   543
2  various_title_only   183

--- Confidence distribution ---
  confidence_label     n
0             high  2551
1              low  1578
2           medium    79

--- Uniqueness check by cds_id ---
   total_rows  distinct_cds_id  duplicate_cds_id_rows
0        4208             4208                      0

--- Preview final mapping ---
    cds_id                  artist                                title  cds_year  release_id                release_title       main_artist_name  mb_year         match_type confidence_label       score   title_sim  \
0     1818              pink floyd                      the wall disc 1      <NA>        6892                     The Wall             Pink Floyd     2023  fuzzy_second_pass             high  100.000000  100.000000
1     1828             frans bauer                          n ons geluk      2004      588145                 ’n Ons geluk            Frans Bauer     2020              exact              low   50.000000         NaN
2     1838                    2pac                   greatest hits cd1       1998      137707                Greatest Hits                   2Pac     2023  fuzzy_second_pass             high  100.000000  100.000000
3     1884            leon redbone                      up a lazy river      <NA>       25586              Up a Lazy River           Leon Redbone     2022              exact              low   82.000000         NaN
4     2026           alkaline trio                           goddamnit       1998       30355                    Goddamnit          Alkaline Trio     2016              exact              low   82.000000         NaN
5     2139            james taylor                  greatest hits vol 1      1976       92663                Greatest Hits           James Taylor     2017  fuzzy_second_pass             high  100.000000  100.000000
6     2188                  estopa                           destrangis      <NA>      197607                   Destrangis                 Estopa     2024              exact             high   82.000000         NaN
7     2317  vã mmã l spellmannslag                           vã mmã l n      1974      159343                     Vømmøl'n   Vømmøl Spellmannslag     2023              exact              low   26.000000         NaN
8     2406     francesco de gegori                      alice non lo sa      1973       17408              Alice non lo sa   Francesco De Gregori     2015  fuzzy_second_pass             high   98.927473  100.000000
9     2440              nando reis                            a letra a      2003      898632                 A: A letra a             Nando Reis     2017  fuzzy_second_pass             high   98.800000   98.000000
10    2571                chayanne                          simplemente      1999     2829549                  Simplemente               Chayanne     2020              exact              low   82.000000         NaN
11    2619           shane barnard                               psalms      2001      473506                       Psalms          Shane Barnard     2008              exact             high   56.000000         NaN
12    2707         bruce dickinson  the best of bruce dickinson disc 1       2001       19454  The Best of Bruce Dickinson        Bruce Dickinson     2022  fuzzy_second_pass             high  100.000000  100.000000
13    2807      combustible edison                         schizophonic      1996      332887                Schizophonic!     Combustible Edison     2009              exact             high   50.000000         NaN
14    2813                corduroy                          out of here      <NA>      947751                  Out of Here               Corduroy     2022              exact              low   82.000000         NaN
15    2819             peter white                            promenade      1993      553063                    Promenade            Peter White     2020              exact              low   82.000000         NaN
16    2823         the jazzmasters                     the jazzmasters4      <NA>     1302038              The Jazzmasters        The Jazzmasters     2020  fuzzy_second_pass             high   98.024472   96.707453
17    2950         eros ramazzotti                     donde hay musica      1996      955756             Donde hay música        Eros Ramazzotti     2024  fuzzy_second_pass             high   96.708333   94.513889
18    2957                 kenny g                           the moment      <NA>       26935                   The Moment                Kenny G     2020              exact              low   82.000000         NaN
19    3086            the drifters                  under the boardwalk      <NA>      116641          Under the Boardwalk           The Drifters     2020              exact              low   82.000000         NaN
20    3096   the philosopher kings                the philosopher kings      <NA>      180558        The Philosopher Kings  The Philosopher Kings     2009              exact              low   82.000000         NaN
21    3106                 kenny g                           the moment      1996       26935                   The Moment                Kenny G     2020              exact              low   82.000000         NaN
22    3125                   bjork                           vespertine      <NA>        8393                   Vespertine                  Björk     2022  fuzzy_second_pass             high   93.422222  100.000000
23    3134               metallica                            metallica      1991         328                    Metallica              Metallica     2022              exact              low   82.000000         NaN
24    3155                corduroy                          out of here      1995      947751                  Out of Here               Corduroy     2022              exact              low   82.000000         NaN

    artist_sim
0   100.000000
1          NaN
2   100.000000
3          NaN
4          NaN
5   100.000000
6          NaN
7          NaN
8    97.318681
9   100.000000
10         NaN
11         NaN
12  100.000000
13         NaN
14         NaN
15         NaN
16  100.000000
17  100.000000
18         NaN
19         NaN
20         NaN
21         NaN
22   83.555556
23         NaN
24         NaN

In [305]:
import duckdb
import pandas as pd

# Connect to DuckDB
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Thesis report table:
# Final coverage with percentages after all current matching steps
# ------------------------------------------------------------
report_percentages = con.execute("""
    SELECT
        (SELECT COUNT(*) FROM cds) AS cds_total,

        (SELECT COUNT(*) FROM cds_to_mb_best_exact_v4) AS exact_v4_n,
        ROUND(
            100.0 * (SELECT COUNT(*) FROM cds_to_mb_best_exact_v4)
            / (SELECT COUNT(*) FROM cds), 2
        ) AS exact_v4_pct,

        (SELECT COUNT(*) FROM cds_to_mb_best_enrichment) AS enrichment_fuzzy_n,
        ROUND(
            100.0 * (SELECT COUNT(*) FROM cds_to_mb_best_enrichment)
            / (SELECT COUNT(*) FROM cds), 2
        ) AS enrichment_fuzzy_pct,

        (SELECT COUNT(*) FROM cds_to_mb_final_mapping_v6 WHERE match_type = 'various_title_integration') AS various_title_n,
        ROUND(
            100.0 * (SELECT COUNT(*) FROM cds_to_mb_final_mapping_v6 WHERE match_type = 'various_title_integration')
            / (SELECT COUNT(*) FROM cds), 2
        ) AS various_title_pct,

        (SELECT COUNT(*) FROM cds_to_mb_final_mapping_v6) AS total_matched_n,
        ROUND(
            100.0 * (SELECT COUNT(*) FROM cds_to_mb_final_mapping_v6)
            / (SELECT COUNT(*) FROM cds), 2
        ) AS total_matched_pct,

        (SELECT COUNT(*) FROM cds) - (SELECT COUNT(*) FROM cds_to_mb_final_mapping_v6) AS still_unmatched_n,
        ROUND(
            100.0 * (
                (SELECT COUNT(*) FROM cds) - (SELECT COUNT(*) FROM cds_to_mb_final_mapping_v6)
            ) / (SELECT COUNT(*) FROM cds), 2
        ) AS still_unmatched_pct
""").fetchdf()

print("\n--- Thesis Report: Final Coverage with Percentages ---")
print(report_percentages)

Connected ✅

--- Thesis Report: Final Coverage with Percentages ---
   cds_total  exact_v4_n  exact_v4_pct  enrichment_fuzzy_n  enrichment_fuzzy_pct  various_title_n  various_title_pct  total_matched_n  total_matched_pct  still_unmatched_n  still_unmatched_pct
0       9763        3482         35.67                 565                  5.79                0                0.0             4208               43.1               5555                 56.9

In [306]:
import duckdb
import os

# Connect to DuckDB
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# Make sure exports folder exists
os.makedirs("../data_processed/exports", exist_ok=True)

# ------------------------------------------------------------
# Export new thesis/enrichment tables to CSV
# ------------------------------------------------------------
# Comments:
# - Only real tables are exported here.
# - Views are exported through SELECT * FROM view_name.
# - Existing files with the same name will be overwritten.
exports = [
    ("mb_integration_view", "../data_processed/exports/mb_integration_view.csv", "view"),
    ("mb_candidate_pool_v2", "../data_processed/exports/mb_candidate_pool_v2.csv", "table"),
    ("cds_mb_enrichment_pairs", "../data_processed/exports/cds_mb_enrichment_pairs.csv", "table"),
    ("cds_to_mb_enrichment_candidates", "../data_processed/exports/cds_to_mb_enrichment_candidates.csv", "table"),
    ("cds_to_mb_best_enrichment", "../data_processed/exports/cds_to_mb_best_enrichment.csv", "table"),

    ("cds_to_mb_final_mapping_v5", "../data_processed/exports/cds_to_mb_final_mapping_v5.csv", "table"),
    ("cds_to_mb_final_mapping_v6", "../data_processed/exports/cds_to_mb_final_mapping_v6.csv", "table"),

    ("cds_various_unmatched_cleaned", "../data_processed/exports/cds_various_unmatched_cleaned.csv", "table"),
    ("mb_various_title_integration_view", "../data_processed/exports/mb_various_title_integration_view.csv", "view"),
    ("cds_various_candidate_pairs", "../data_processed/exports/cds_various_candidate_pairs.csv", "table"),
    ("cds_various_best_match", "../data_processed/exports/cds_various_best_match.csv", "table"),
]

for obj_name, out_path, obj_type in exports:
    try:
        if obj_type == "table":
            con.execute(f"""
                COPY {obj_name}
                TO '{out_path}'
                WITH (HEADER, DELIMITER ',')
            """)
        else:
            con.execute(f"""
                COPY (SELECT * FROM {obj_name})
                TO '{out_path}'
                WITH (HEADER, DELIMITER ',')
            """)

        print(f"✅ Exported: {obj_name} -> {out_path}")

    except Exception as e:
        print(f"❌ Failed: {obj_name}")
        print("   ", type(e).__name__, e)

print("\nDone ✅")

Connected ✅

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

✅ Exported: mb_integration_view -> ../data_processed/exports/mb_integration_view.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

✅ Exported: mb_candidate_pool_v2 -> ../data_processed/exports/mb_candidate_pool_v2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

✅ Exported: cds_mb_enrichment_pairs -> ../data_processed/exports/cds_mb_enrichment_pairs.csv
✅ Exported: cds_to_mb_enrichment_candidates -> ../data_processed/exports/cds_to_mb_enrichment_candidates.csv
✅ Exported: cds_to_mb_best_enrichment -> ../data_processed/exports/cds_to_mb_best_enrichment.csv
✅ Exported: cds_to_mb_final_mapping_v5 -> ../data_processed/exports/cds_to_mb_final_mapping_v5.csv
✅ Exported: cds_to_mb_final_mapping_v6 -> ../data_processed/exports/cds_to_mb_final_mapping_v6.csv
✅ Exported: cds_various_unmatched_cleaned -> ../data_processed/exports/cds_various_unmatched_cleaned.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

✅ Exported: mb_various_title_integration_view -> ../data_processed/exports/mb_various_title_integration_view.csv
✅ Exported: cds_various_candidate_pairs -> ../data_processed/exports/cds_various_candidate_pairs.csv
✅ Exported: cds_various_best_match -> ../data_processed/exports/cds_various_best_match.csv

Done ✅

In [309]:
import duckdb
import pandas as pd

# Connect to DuckDB
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

print("Creating cds_to_mb_enrichment_ranked...")

con.execute("""
    CREATE OR REPLACE TABLE cds_to_mb_enrichment_ranked AS
    WITH ranked AS (
        SELECT
            *,
            ROW_NUMBER() OVER (
                PARTITION BY cds_id
                ORDER BY
                    score DESC,
                    title_sim DESC,
                    artist_sim DESC,
                    release_id ASC
            ) AS candidate_rank,

            FIRST_VALUE(score) OVER (
                PARTITION BY cds_id
                ORDER BY
                    score DESC,
                    title_sim DESC,
                    artist_sim DESC,
                    release_id ASC
            ) AS best_score,

            LEAD(score) OVER (
                PARTITION BY cds_id
                ORDER BY
                    score DESC,
                    title_sim DESC,
                    artist_sim DESC,
                    release_id ASC
            ) AS second_best_score

        FROM cds_to_mb_enrichment_candidates
    )
    SELECT
        *,
        CASE
            WHEN candidate_rank = 1 THEN (best_score - second_best_score)
            ELSE NULL
        END AS score_gap,

        CASE
            WHEN candidate_rank = 1
                 AND score >= 92
                 AND title_sim >= 94
                 AND ((best_score - second_best_score) >= 8 OR second_best_score IS NULL)
            THEN 'auto_accept'

            WHEN candidate_rank = 1
                 AND score >= 88
                 AND title_sim >= 90
            THEN 'review'

            ELSE 'reject'
        END AS confidence_class
    FROM ranked
""")

print("✅ Table created: cds_to_mb_enrichment_ranked")

print("\n--- Top-ranked enrichment candidates only ---")
print(con.execute("""
    SELECT
        cds_id,
        artist,
        title,
        release_id,
        main_artist_name,
        release_title,
        score,
        artist_sim,
        title_sim,
        best_score,
        second_best_score,
        score_gap,
        confidence_class
    FROM cds_to_mb_enrichment_ranked
    WHERE candidate_rank = 1
    ORDER BY score DESC, score_gap DESC NULLS LAST
    LIMIT 30
""").fetchdf())

print("\n--- Confidence class summary (top-ranked only) ---")
print(con.execute("""
    SELECT
        confidence_class,
        COUNT(*) AS n
    FROM cds_to_mb_enrichment_ranked
    WHERE candidate_rank = 1
    GROUP BY confidence_class
    ORDER BY n DESC
""").fetchdf())

Connected ✅
Creating cds_to_mb_enrichment_ranked...
✅ Table created: cds_to_mb_enrichment_ranked

--- Top-ranked enrichment candidates only ---
    cds_id                    artist                                      title  release_id          main_artist_name                                 release_title  score  artist_sim  title_sim  best_score  \
0   102089               101 strings              unforgettable melodies disc 1     1893295               101 Strings                        Unforgettable Melodies  100.0       100.0      100.0       100.0
1   101970                 tom waits             jockey full of bourbon disc 1      4816131                 Tom Waits                        Jockey Full of Bourbon  100.0       100.0      100.0       100.0
2   107708             vernon oxford                 keeper of the flame disc 4      863661             Vernon Oxford                           Keeper of the Flame  100.0       100.0      100.0       100.0
3   100556             john mogensen            der er noget galt i danmark cd1     1004718             John Mogensen                   Der er noget galt i Danmark  100.0       100.0      100.0       100.0
4   103852         sebastian haffner                von bismarck zu hitler cd 1     2557249         Sebastian Haffner                        Von Bismarck zu Hitler  100.0       100.0      100.0       100.0
5   103341         somatic responses                           adverts disc 01       119014         Somatic Responses                                       Adverts  100.0       100.0      100.0       100.0
6   105108                  wilmer x                           mambo feber cd 1       80810                  Wilmer X                                   Mambo feber  100.0       100.0      100.0       100.0
7   107733                brenda lee                  little miss dynamite cd 2      540596                Brenda Lee                          Little Miss Dynamite  100.0       100.0      100.0       100.0
8   107638              merle travis   guitar rags and a too fast past volume 3     1022226              Merle Travis               Guitar Rags and a Too Fast Past  100.0       100.0      100.0       100.0
9   102855  electric light orchestra                       eldorado remastered      2020616  Electric Light Orchestra                                      Eldorado  100.0       100.0      100.0       100.0
10  102140      de vliegende panters                               hype disc 2       664562      De Vliegende Panters                                          Hype  100.0       100.0      100.0       100.0
11  102588                 metallica            blitzkrieg on wembley live vol2      940148                 Metallica                         Blitzkrieg on Wembley  100.0       100.0      100.0       100.0
12  105817                      rush             experience to extremes disc 1       889740                      Rush                        Experience to Extremes  100.0       100.0      100.0       100.0
13  106550                      nena                        star boulevard cd 2     1154654                      Nena                                Star Boulevard  100.0       100.0      100.0       100.0
14  105642                 tori amos                    rhapsody in pink disc 2       22237                 Tori Amos                              Rhapsody in Pink  100.0       100.0      100.0       100.0
15  108914               wim mertens                             aren lezen cd3       15028               Wim Mertens                                    Aren Lezen  100.0       100.0      100.0       100.0
16  107538             tommy collins                             leonard disc 5     2935703             Tommy Collins                                       Leonard  100.0       100.0      100.0       100.0
17  104722            cheater slicks                        forgive thee disc 1      873533            Cheater Slicks                                  Forgive Thee  100.0       100.0      100.0       100.0
18  102301                    marduk                        blackcrowned disc 2       70759                    Marduk                                  Blackcrowned  100.0       100.0      100.0       100.0
19  107439         bruce springsteen                         living proof disc1     2103619         Bruce Springsteen                                  Living Proof  100.0       100.0      100.0       100.0
20  108328                 doc scott          mixmag live breakbeat experiments      179133                 Doc Scott  Mixmag Live Volume 22: Breakbeat Experiments  100.0       100.0      100.0       100.0
21  103739               luis miguel                          el concierto cd 2      639035               Luis Miguel                                  El concierto  100.0       100.0      100.0       100.0
22  102921    die fantastischen vier                  live in stuttgart disc 1        90225    Die Fantastischen Vier                             Live in Stuttgart  100.0       100.0      100.0       100.0
23  103443              muddy waters                take a walk with me disc 2      1536650              Muddy Waters                           Take a Walk With Me  100.0       100.0      100.0       100.0
24  104354                juan pardo                     sinceramente juan cd1      1519584                Juan Pardo                             Sinceramente Juan  100.0       100.0      100.0       100.0
25  105435             peter gabriel                         warming up disc 2      2601472             Peter Gabriel                                    Warming Up  100.0       100.0      100.0       100.0
26  105223                rough silk                         wheels of time cd1     1711129                Rough Silk                                Wheels of Time  100.0       100.0      100.0       100.0
27  105402         bruce springsteen                      hard land live disc 1     2103648         Bruce Springsteen                                     Hard Land  100.0       100.0      100.0       100.0
28  109037              helmut lotti                            love songs cd 2     1583870              Helmut Lotti                                    Love Songs  100.0       100.0      100.0       100.0
29  103845              peter freund  laura und das geheimnis von aventerra cd1     1795309              Peter Freund         Laura und das Geheimnis von Aventerra  100.0       100.0      100.0       100.0

    second_best_score  score_gap confidence_class
0           44.653589  55.346411      auto_accept
1           48.078316  51.921684      auto_accept
2           54.620922  45.379078      auto_accept
3           55.090110  44.909890      auto_accept
4           56.120437  43.879563      auto_accept
5           58.635294  41.364706      auto_accept
6           60.545455  39.454545      auto_accept
7           61.272727  38.727273      auto_accept
8           61.818182  38.181818      auto_accept
9           62.953347  37.046653      auto_accept
10          64.583843  35.416157      auto_accept
11          64.702439  35.297561      auto_accept
12          65.783784  34.216216      auto_accept
13          66.181818  33.818182      auto_accept
14          66.565913  33.434087      auto_accept
15          67.566434  32.433566      auto_accept
16          67.868132  32.131868      auto_accept
17          68.065158  31.934842      auto_accept
18          68.259740  31.740260      auto_accept
19          68.615385  31.384615      auto_accept
20          69.563636  30.436364      auto_accept
21          71.117605  28.882395      auto_accept
22          71.166667  28.833333      auto_accept
23          71.959503  28.040497      auto_accept
24          72.232114  27.767886      auto_accept
25          72.734300  27.265700      auto_accept
26          73.000000  27.000000      auto_accept
27          73.259177  26.740823      auto_accept
28          73.511111  26.488889      auto_accept
29          75.830116  24.169884      auto_accept

--- Confidence class summary (top-ranked only) ---
  confidence_class     n
0           reject  3685
1           review   384
2      auto_accept   238

In [ ]:
import duckdb
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 240)

# Connect to DuckDB
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

print("Creating mb_release_enriched_from_cds_v1...")

con.execute("""
    CREATE OR REPLACE TABLE mb_release_enriched_from_cds_v1 AS
    WITH ranked AS (
        SELECT
            m.*,

            ROW_NUMBER() OVER (
                PARTITION BY m.release_id
                ORDER BY
                    CASE m.match_type
                        WHEN 'exact' THEN 1
                        WHEN 'fuzzy_second_pass' THEN 2
                        WHEN 'various_title_only' THEN 3
                        ELSE 9
                    END ASC,
                    CASE m.confidence_label
                        WHEN 'high' THEN 1
                        WHEN 'auto_accept' THEN 1
                        WHEN 'medium' THEN 2
                        WHEN 'review' THEN 2
                        WHEN 'low' THEN 3
                        WHEN 'reject' THEN 4
                        ELSE 9
                    END ASC,
                    COALESCE(m.score, -1) DESC,
                    m.cds_id ASC
            ) AS rn,

            COUNT(*) OVER (PARTITION BY m.release_id) AS cds_links_to_release
        FROM cds_to_mb_final_mapping_v6 m
    )
    SELECT
        -- MB anchor
        r.release_id,
        r.release_title,
        r.main_artist_name,
        r.artist_credit_full,
        r.mb_year,
        r.barcode,
        r.total_tracks,

        -- CDS enrichment attributes
        r.cds_id,
        r.cds_year,

        -- Pull CDS metadata directly from the CDS table
        c.category AS cds_category,
        c.genre AS cds_genre,
        c.tracks AS cds_tracklist,

        -- Provenance / integration metadata
        r.match_type,
        r.confidence_label,
        r.score,
        r.title_sim,
        r.artist_sim,
        r.cds_links_to_release,
        'CDS' AS enrichment_source

    FROM ranked r
    LEFT JOIN cds c
      ON r.cds_id = c.cds_id
    WHERE r.rn = 1
""")

print("✅ Table created: mb_release_enriched_from_cds_v1")

print("\n--- Row count / uniqueness check ---")
print(con.execute("""
    SELECT
        COUNT(*) AS total_rows,
        COUNT(DISTINCT release_id) AS distinct_release_id,
        COUNT(*) - COUNT(DISTINCT release_id) AS duplicate_release_rows
    FROM mb_release_enriched_from_cds_v1
""").fetchdf())

print("\n--- Enrichment coverage report ---")
print(con.execute("""
    WITH mb_total AS (
        SELECT COUNT(*) AS n
        FROM mb_release_features
    ),
    enriched_total AS (
        SELECT COUNT(*) AS n
        FROM mb_release_enriched_from_cds_v1
    ),
    enriched_with_new_metadata AS (
        SELECT COUNT(*) AS n
        FROM mb_release_enriched_from_cds_v1
        WHERE cds_category IS NOT NULL
           OR cds_genre IS NOT NULL
           OR cds_year IS NOT NULL
    )
    SELECT
        (SELECT n FROM mb_total) AS mb_total_releases,
        (SELECT n FROM enriched_total) AS mb_releases_enriched,
        (SELECT n FROM enriched_with_new_metadata) AS mb_releases_with_new_metadata,
        ROUND(
            100.0 * (SELECT n FROM enriched_with_new_metadata) / (SELECT n FROM mb_total),
            4
        ) AS pct_of_mb_with_new_metadata
""").fetchdf())

print("\n--- Match type distribution in final MB enrichment table ---")
print(con.execute("""
    SELECT match_type, COUNT(*) AS n
    FROM mb_release_enriched_from_cds_v1
    GROUP BY match_type
    ORDER BY n DESC
""").fetchdf())

print("\n--- Confidence distribution in final MB enrichment table ---")
print(con.execute("""
    SELECT confidence_label, COUNT(*) AS n
    FROM mb_release_enriched_from_cds_v1
    GROUP BY confidence_label
    ORDER BY n DESC
""").fetchdf())

print("\n--- Releases with multiple CDS links before consolidation ---")
print(con.execute("""
    SELECT
        release_id,
        release_title,
        main_artist_name,
        cds_links_to_release,
        match_type,
        confidence_label,
        score,
        cds_id,
        cds_category,
        cds_genre
    FROM mb_release_enriched_from_cds_v1
    WHERE cds_links_to_release > 1
    ORDER BY cds_links_to_release DESC, COALESCE(score, -1) DESC, release_id
    LIMIT 20
""").fetchdf())

print("\n--- Preview final MusicBrainz-centered enrichment table ---")
print(con.execute("""
    SELECT
        release_id,
        release_title,
        main_artist_name,
        mb_year,
        barcode,
        total_tracks,
        cds_id,
        cds_year,
        cds_category,
        cds_genre,
        match_type,
        confidence_label,
        score,
        enrichment_source
    FROM mb_release_enriched_from_cds_v1
    LIMIT 25
""").fetchdf())

print("\nExporting CSV...")
con.execute("""
    COPY mb_release_enriched_from_cds_v1
    TO '../data_processed/exports/mb_release_enriched_from_cds_v1.csv'
    WITH (HEADER, DELIMITER ',')
""")
print("✅ CSV saved: ../data_processed/exports/mb_release_enriched_from_cds_v1.csv")

Connected ✅
Creating mb_release_enriched_from_cds_v1...

In [329]:
import duckdb
import pandas as pd

# Connect to DuckDB
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Create a new automatic enrichment table using only auto_accept rows
# ------------------------------------------------------------
# Comments:
# - We keep only candidate_rank = 1 and confidence_class = 'auto_accept'.
# - This is the ambiguity-controlled automatic enrichment subset.
print("Creating cds_to_mb_best_enrichment_auto...")

con.execute("""
    CREATE OR REPLACE TABLE cds_to_mb_best_enrichment_auto AS
    SELECT
        cds_id,
        artist,
        title,
        cds_year,
        release_id,
        release_title,
        main_artist_name,
        artist_credit_full,
        total_tracks,
        barcode,
        mb_year,
        score,
        artist_sim,
        title_sim,
        best_score,
        second_best_score,
        score_gap,
        confidence_class
    FROM cds_to_mb_enrichment_ranked
    WHERE candidate_rank = 1
      AND confidence_class = 'auto_accept'
""")

print("✅ Table created: cds_to_mb_best_enrichment_auto")

print("\n--- Count of auto-accepted enrichment matches ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM cds_to_mb_best_enrichment_auto
""").fetchdf())

# ------------------------------------------------------------
# Merge auto-accepted enrichment matches into a new final mapping version
# ------------------------------------------------------------
# Comments:
# - Keep exact_v4 matches
# - Add only ambiguity-controlled auto-accepted enrichment matches
# - Do not duplicate cds_ids already matched by exact_v4
print("\nCreating cds_to_mb_final_mapping_v7_auto...")

con.execute("""
    CREATE OR REPLACE TABLE cds_to_mb_final_mapping_v7_auto AS
    SELECT
        cds_id,
        artist,
        title,
        release_id,
        release_title,
        main_artist_name,
        artist_credit_full,
        total_tracks,
        barcode,
        mb_year,
        'exact_v4' AS match_type,
        NULL::DOUBLE AS score
    FROM cds_to_mb_best_exact_v4

    UNION ALL

    SELECT
        e.cds_id,
        e.artist,
        e.title,
        e.release_id,
        e.release_title,
        e.main_artist_name,
        e.artist_credit_full,
        e.total_tracks,
        e.barcode,
        e.mb_year,
        'enrichment_fuzzy_auto' AS match_type,
        e.score
    FROM cds_to_mb_best_enrichment_auto e
    LEFT JOIN cds_to_mb_best_exact_v4 x
      ON x.cds_id = e.cds_id
    WHERE x.cds_id IS NULL
""")

print("✅ Table created: cds_to_mb_final_mapping_v7_auto")

# ------------------------------------------------------------
# Coverage report for the ambiguity-controlled automatic version
# ------------------------------------------------------------
report_auto = con.execute("""
    SELECT
        (SELECT COUNT(*) FROM cds) AS cds_total,
        (SELECT COUNT(*) FROM cds_to_mb_best_exact_v4) AS exact_v4_matched,
        (SELECT COUNT(*) FROM cds_to_mb_best_enrichment_auto) AS enrichment_auto_added,
        (SELECT COUNT(*) FROM cds_to_mb_final_mapping_v7_auto) AS total_matched_v7_auto,
        (SELECT COUNT(*) FROM cds) - (SELECT COUNT(*) FROM cds_to_mb_final_mapping_v7_auto) AS still_unmatched_v7_auto
""").fetchdf()

print("\n--- Thesis Report: Ambiguity-Controlled Automatic Coverage ---")
print(report_auto)

print("\n--- Match type breakdown in v7_auto ---")
print(con.execute("""
    SELECT match_type, COUNT(*) AS n
    FROM cds_to_mb_final_mapping_v7_auto
    GROUP BY match_type
    ORDER BY n DESC
""").fetchdf())

Connected ✅
Creating cds_to_mb_best_enrichment_auto...
✅ Table created: cds_to_mb_best_enrichment_auto

--- Count of auto-accepted enrichment matches ---
     n
0  238

Creating cds_to_mb_final_mapping_v7_auto...
✅ Table created: cds_to_mb_final_mapping_v7_auto

--- Thesis Report: Ambiguity-Controlled Automatic Coverage ---
   cds_total  exact_v4_matched  enrichment_auto_added  total_matched_v7_auto  still_unmatched_v7_auto
0       9763              3482                    238                   3720                     6043

--- Match type breakdown in v7_auto ---
              match_type     n
0               exact_v4  3482
1  enrichment_fuzzy_auto   238

In [ ]:
import duckdb
import pandas as pd

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

comparison = con.execute("""
    SELECT 'v6_broader_mapping' AS version,
           (SELECT COUNT(*) FROM cds_to_mb_final_mapping_v6) AS matched_rows,
           ROUND(100.0 * (SELECT COUNT(*) FROM cds_to_mb_final_mapping_v6) / (SELECT COUNT(*) FROM cds), 2) AS matched_pct,
           (SELECT COUNT(*) FROM cds) - (SELECT COUNT(*) FROM cds_to_mb_final_mapping_v6) AS unmatched_rows,
           ROUND(100.0 * ((SELECT COUNT(*) FROM cds) - (SELECT COUNT(*) FROM cds_to_mb_final_mapping_v6)) / (SELECT COUNT(*) FROM cds), 2) AS unmatched_pct

    UNION ALL

    SELECT 'v7_auto_high_confidence' AS version,
           (SELECT COUNT(*) FROM cds_to_mb_final_mapping_v7_auto) AS matched_rows,
           ROUND(100.0 * (SELECT COUNT(*) FROM cds_to_mb_final_mapping_v7_auto) / (SELECT COUNT(*) FROM cds), 2) AS matched_pct,
           (SELECT COUNT(*) FROM cds) - (SELECT COUNT(*) FROM cds_to_mb_final_mapping_v7_auto) AS unmatched_rows,
           ROUND(100.0 * ((SELECT COUNT(*) FROM cds) - (SELECT COUNT(*) FROM cds_to_mb_final_mapping_v7_auto)) / (SELECT COUNT(*) FROM cds), 2) AS unmatched_pct
""").fetchdf()

print("\n--- Thesis Report: Comparison of Final Mapping Variants ---")
print(comparison)

In [331]:
import duckdb
import pandas as pd

# Connect to DuckDB
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Create the unmatched CDS remainder after v6
# ------------------------------------------------------------
# Comments:
# - v6 is the broader working mapping.
# - We now isolate the CDS rows that still remain unmatched after v6.
# - This will be the input for the next cleaning and enrichment cycle.
print("Creating cds_unmatched_after_v6...")

con.execute("""
    CREATE OR REPLACE TABLE cds_unmatched_after_v6 AS
    SELECT c.*
    FROM cds_norm c
    LEFT JOIN cds_to_mb_final_mapping_v6 m
      ON c.cds_id = m.cds_id
    WHERE m.cds_id IS NULL
""")

print("✅ Table created: cds_unmatched_after_v6")

print("\n--- Count of unmatched CDS rows after v6 ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM cds_unmatched_after_v6
""").fetchdf())

print("\n--- Preview: unmatched CDS rows after v6 ---")
print(con.execute("""
    SELECT
        cds_id, artist, title, cds_year, artist_key, title_key
    FROM cds_unmatched_after_v6
    LIMIT 20
""").fetchdf())

Connected ✅
Creating cds_unmatched_after_v6...
✅ Table created: cds_unmatched_after_v6

--- Count of unmatched CDS rows after v6 ---
      n
0  5555

--- Preview: unmatched CDS rows after v6 ---
    cds_id                        artist                                                                         title  cds_year                artist_key  \
0   100003       ã â â ã â ã â ºâ ã â å                                          ã æ â³ã â žã â âºã â ã â ¹ã â ã â šâ       1989
1   100004                       emanuel                                                                    felicidade      1998                   emanuel
2   100005   ã å â ã â ºâ ã â ºâ ºã â â     catsã â â ã â šâªã æ âªã â šâ ã æ å ã æ â ã â½â ã â šâ ã æ â ã â šâ¹ã æ ë       <NA>
3   100007               various artists                                                                     nop pop 2      2002            variousartists
4   100009                        4 p m                                                                     sweet soul      2001                       4pm
5   100011          â¾ã â â ã ãœ worship                                                            child praise vol 1      <NA>                   worship
6   100014                modern talking                                                                       univers      1997             moderntalking
7   100016                                                                                              subway express      <NA>
8   100017                       various                                                      micmac house dance party      1996                   various
9   100025  variousce italiennes disc 1   la dolce vita les tubes dance italiens les chansons dance italiennes disc 1       <NA>  variousceitaliennesdisc1
10  100027                           v a                                                               ãƒã âºâ¹ cd 09       2001                        va
11  100028               jazz signatures                                                               jazz signatures      1998            jazzsignatures
12  100029           bernadã te bidã ude                                                                 pomme d amour      <NA>            bernadtebidude
13  100030          ã â â ã â ã â â¾ã âµ                                                 disc13 ã å â ã â ã â ¹ã â šå       2003
14  100032                         v8 5e                                                                         v8 5e      <NA>                      v85e
15  100034       ã â šã å â ã å å ã â â¾                                                                          lucy      2001
16  100036                      dj irish                                                         assorted trance vol 8      2003                   djirish
17  100038       rennie pilgrim presents                                                             nu skool breakz 2      <NA>     renniepilgrimpresents
18  100041                   italo house                                                                   12 in mixes      <NA>                italohouse
19  100042                          deux                                                                       forever      <NA>                      deux

                                                          title_key
0
1                                                        felicidade
2                                                              cats
3                                                           noppop2
4                                                         sweetsoul
5                                                   childpraisevol1
6                                                           univers
7                                                     subwayexpress
8                                             micmachousedanceparty
9   ladolcevitalestubesdanceitaliensleschansonsdanceitaliennesdisc1
10                                                             cd09
11                                                   jazzsignatures
12                                                      pommedamour
13                                                           disc13
14                                                             v85e
15                                                             lucy
16                                               assortedtrancevol8
17                                                   nuskoolbreakz2
18                                                        12inmixes
19                                                          forever

In [332]:
import duckdb
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 220)

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

print("Creating cds_unmatched_profiled_v6...")

con.execute(r"""
    CREATE OR REPLACE TABLE cds_unmatched_profiled_v6 AS
    SELECT
        *,

        CASE WHEN artist IS NULL OR trim(artist) = '' THEN 1 ELSE 0 END AS missing_artist,
        CASE WHEN title  IS NULL OR trim(title)  = '' THEN 1 ELSE 0 END AS missing_title,
        CASE WHEN tracks IS NULL OR trim(tracks) = '' THEN 1 ELSE 0 END AS missing_tracks,
        CASE WHEN cds_year IS NULL THEN 1 ELSE 0 END AS missing_year,

        CASE WHEN length(trim(coalesce(artist, ''))) < 4 THEN 1 ELSE 0 END AS short_artist,
        CASE WHEN length(trim(coalesce(title,  ''))) < 4 THEN 1 ELSE 0 END AS short_title,

        CASE
            WHEN regexp_matches(coalesce(artist, ''), 'Ã|â|Â|�')
              OR regexp_matches(coalesce(title,  ''), 'Ã|â|Â|�')
              OR regexp_matches(coalesce(tracks, ''), 'Ã|â|Â|�')
            THEN 1 ELSE 0
        END AS is_mojibake,

        CASE
            WHEN lower(trim(coalesce(artist, ''))) IN (
                'various', 'various artists', 'various artist',
                'va', 'v a', 'v.a.',
                'varios', 'varios artistas', 'vàrios'
            )
            THEN 1 ELSE 0
        END AS is_various_artists,

        CASE
            WHEN regexp_matches(lower(coalesce(title, '')), '(disc|disk|cd|vol|volume)\s*0*\d+')
            THEN 1 ELSE 0
        END AS has_disc_cd_vol,

        CASE
            WHEN lower(trim(coalesce(title, ''))) IN (
                'live', 'greatest hits', 'best of', 'the best of',
                'hits', 'soundtrack', 'mix', 'mixes', 'now'
            )
            THEN 1 ELSE 0
        END AS is_generic_title,

        trim(regexp_replace(lower(coalesce(artist, '')), '\s+', ' ', 'g')) AS artist_clean,
        trim(regexp_replace(lower(coalesce(title,  '')), '\s+', ' ', 'g')) AS title_clean,

        trim(regexp_replace(
            regexp_replace(lower(coalesce(title, '')), '(disc|disk|cd|vol|volume)\s*0*\d+', '', 'g'),
            '\s+', ' ', 'g'
        )) AS title_no_disc,

        lower(regexp_replace(coalesce(artist, ''), '[^a-zA-Z0-9]+', '', 'g')) AS artist_key_clean,

        lower(regexp_replace(
            regexp_replace(
                regexp_replace(lower(coalesce(title, '')), '(disc|disk|cd|vol|volume)\s*0*\d+', '', 'g'),
                '\b(remastered|remaster|deluxe|edition|bonus|expanded|reissue|live)\b', '', 'g'
            ),
            '[^a-zA-Z0-9]+', '', 'g'
        )) AS title_key_clean

    FROM cds_unmatched_after_v6
""")

print("✅ Table created: cds_unmatched_profiled_v6")

print("\n--- Profiling summary for unmatched CDS after v6 ---")
print(con.execute("""
    SELECT
        COUNT(*) AS total_unmatched,
        SUM(missing_artist) AS missing_artist,
        SUM(missing_title) AS missing_title,
        SUM(missing_tracks) AS missing_tracks,
        SUM(missing_year) AS missing_year,
        SUM(short_artist) AS short_artist,
        SUM(short_title) AS short_title,
        SUM(is_mojibake) AS mojibake_rows,
        SUM(is_various_artists) AS various_artist_rows,
        SUM(has_disc_cd_vol) AS disc_cd_vol_rows,
        SUM(is_generic_title) AS generic_title_rows
    FROM cds_unmatched_profiled_v6
""").fetchdf())

Connected ✅
Creating cds_unmatched_profiled_v6...
✅ Table created: cds_unmatched_profiled_v6

--- Profiling summary for unmatched CDS after v6 ---
   total_unmatched  missing_artist  missing_title  missing_tracks  missing_year  short_artist  short_title  mojibake_rows  various_artist_rows  disc_cd_vol_rows  generic_title_rows
0             5555             7.0           11.0             1.0        2670.0         171.0        114.0          509.0                959.0             972.0                35.0

In [333]:
import duckdb
import pandas as pd

# Connect to DuckDB
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Create a cleaned working subset from the v6 unmatched remainder
# ------------------------------------------------------------
# Comments:
# - We build a reusable working table for the next enrichment cycle.
# - We assign priority classes:
#     high   = relatively clean and promising
#     medium = recoverable but needs special handling
#     low    = noisy / risky / weak
print("Creating cds_unmatched_working_v6...")

con.execute("""
    CREATE OR REPLACE TABLE cds_unmatched_working_v6 AS
    SELECT
        *,

        CASE
            WHEN missing_artist = 1 OR missing_title = 1 THEN 'low'
            WHEN is_mojibake = 1 THEN 'low'
            WHEN short_artist = 1 OR short_title = 1 THEN 'low'
            WHEN is_generic_title = 1 THEN 'medium'
            WHEN is_various_artists = 1 THEN 'medium'
            WHEN has_disc_cd_vol = 1 THEN 'medium'
            ELSE 'high'
        END AS enrichment_priority_v6

    FROM cds_unmatched_profiled_v6
""")

print("✅ Table created: cds_unmatched_working_v6")

print("\n--- Priority distribution in v6 remainder ---")
print(con.execute("""
    SELECT enrichment_priority_v6, COUNT(*) AS n
    FROM cds_unmatched_working_v6
    GROUP BY enrichment_priority_v6
    ORDER BY n DESC
""").fetchdf())

print("\n--- Preview: working unmatched rows after v6 ---")
print(con.execute("""
    SELECT
        cds_id, artist, title, cds_year,
        is_mojibake, is_various_artists, has_disc_cd_vol, is_generic_title,
        enrichment_priority_v6
    FROM cds_unmatched_working_v6
    LIMIT 25
""").fetchdf())

Connected ✅
Creating cds_unmatched_working_v6...
✅ Table created: cds_unmatched_working_v6

--- Priority distribution in v6 remainder ---
  enrichment_priority_v6     n
0                   high  3348
1                 medium  1459
2                    low   748

--- Preview: working unmatched rows after v6 ---
    cds_id                        artist                                                                         title  cds_year  is_mojibake  is_various_artists  has_disc_cd_vol  is_generic_title  \
0   100003       ã â â ã â ã â ºâ ã â å                                          ã æ â³ã â žã â âºã â ã â ¹ã â ã â šâ       1989            1                   0                0                 0
1   100004                       emanuel                                                                    felicidade      1998            0                   0                0                 0
2   100005   ã å â ã â ºâ ã â ºâ ºã â â     catsã â â ã â šâªã æ âªã â šâ ã æ å ã æ â ã â½â ã â šâ ã æ â ã â šâ¹ã æ ë       <NA>            1                   0                0                 0
3   100007               various artists                                                                     nop pop 2      2002            0                   1                0                 0
4   100009                        4 p m                                                                     sweet soul      2001            0                   0                0                 0
5   100011          â¾ã â â ã ãœ worship                                                            child praise vol 1      <NA>            1                   0                1                 0
6   100014                modern talking                                                                       univers      1997            1                   0                0                 0
7   100016                                                                                              subway express      <NA>            0                   0                0                 0
8   100017                       various                                                      micmac house dance party      1996            0                   1                0                 0
9   100025  variousce italiennes disc 1   la dolce vita les tubes dance italiens les chansons dance italiennes disc 1       <NA>            0                   0                1                 0
10  100027                           v a                                                               ãƒã âºâ¹ cd 09       2001            1                   1                1                 0
11  100028               jazz signatures                                                               jazz signatures      1998            0                   0                0                 0
12  100029           bernadã te bidã ude                                                                 pomme d amour      <NA>            0                   0                0                 0
13  100030          ã â â ã â ã â â¾ã âµ                                                 disc13 ã å â ã â ã â ¹ã â šå       2003            1                   0                1                 0
14  100032                         v8 5e                                                                         v8 5e      <NA>            0                   0                0                 0
15  100034       ã â šã å â ã å å ã â â¾                                                                          lucy      2001            1                   0                0                 0
16  100036                      dj irish                                                         assorted trance vol 8      2003            0                   0                1                 0
17  100038       rennie pilgrim presents                                                             nu skool breakz 2      <NA>            0                   0                0                 0
18  100041                   italo house                                                                   12 in mixes      <NA>            0                   0                0                 0
19  100042                          deux                                                                       forever      <NA>            1                   0                0                 0
20  100043                          v a                                                      beating surviver another       2002            1                   1                0                 0
21  100044                       various                                                               custom music cd      <NA>            0                   1                0                 0
22  100045               matsuka phonics                                                         let s study phonics 2      2002            0                   0                0                 0
23  100046                    kool savas                                                     euer bester freund mix cd      2004            0                   0                0                 0
24  100047                      robotika                                                                         dance      <NA>            0                   0                0                 0

   enrichment_priority_v6
0                     low
1                    high
2                     low
3                  medium
4                    high
5                     low
6                     low
7                     low
8                  medium
9                  medium
10                    low
11                   high
12                   high
13                    low
14                   high
15                    low
16                 medium
17                   high
18                   high
19                    low
20                    low
21                 medium
22                   high
23                   high
24                   high

In [383]:
import duckdb
import pandas as pd

# Connect to DuckDB
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Build the next cleaned enrichment subset from the v6 remainder
# ------------------------------------------------------------
# Comments:
# - Keep all high-priority rows
# - Also keep medium-priority rows that are not mojibake and not Various Artists
# - This gives us a cleaner subset for the next standard enrichment pass
# - Separate pipelines can later handle mojibake and Various Artists again
print("Creating cds_unmatched_for_enrichment_v6_round2...")

con.execute("""
    CREATE OR REPLACE TABLE cds_unmatched_for_enrichment_v6_round2 AS
    SELECT
        cds_id,
        artist,
        title,
        cds_year,
        tracks,
        artist_key,
        title_key,

        artist_clean,
        title_clean,
        title_no_disc,
        artist_key_clean,
        title_key_clean,

        is_mojibake,
        is_various_artists,
        has_disc_cd_vol,
        is_generic_title,
        enrichment_priority_v6

    FROM cds_unmatched_working_v6
    WHERE
        enrichment_priority_v6 = 'high'
        OR (
            enrichment_priority_v6 = 'medium'
            AND is_mojibake = 0
            AND is_various_artists = 0
        )
""")

print("✅ Table created: cds_unmatched_for_enrichment_v6_round2")

print("\n--- Count of rows selected for round-2 enrichment ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM cds_unmatched_for_enrichment_v6_round2
""").fetchdf())

print("\n--- Breakdown by priority in round-2 subset ---")
print(con.execute("""
    SELECT enrichment_priority_v6, COUNT(*) AS n
    FROM cds_unmatched_for_enrichment_v6_round2
    GROUP BY enrichment_priority_v6
    ORDER BY n DESC
""").fetchdf())

print("\n--- Preview: round-2 enrichment subset ---")
print(con.execute("""
    SELECT
        cds_id, artist, title, cds_year,
        is_mojibake, is_various_artists, has_disc_cd_vol, is_generic_title,
        enrichment_priority_v6
    FROM cds_unmatched_for_enrichment_v6_round2
    LIMIT 25
""").fetchdf())

Connected ✅
Creating cds_unmatched_for_enrichment_v6_round2...
✅ Table created: cds_unmatched_for_enrichment_v6_round2

--- Count of rows selected for round-2 enrichment ---
      n
0  3931

--- Breakdown by priority in round-2 subset ---
  enrichment_priority_v6     n
0                   high  3348
1                 medium   583

--- Preview: round-2 enrichment subset ---
    cds_id                        artist                                                                         title  cds_year  is_mojibake  is_various_artists  has_disc_cd_vol  is_generic_title  \
0   100004                       emanuel                                                                    felicidade      1998            0                   0                0                 0
1   100009                        4 p m                                                                     sweet soul      2001            0                   0                0                 0
2   100025  variousce italiennes disc 1   la dolce vita les tubes dance italiens les chansons dance italiennes disc 1       <NA>            0                   0                1                 0
3   100028               jazz signatures                                                               jazz signatures      1998            0                   0                0                 0
4   100029           bernadã te bidã ude                                                                 pomme d amour      <NA>            0                   0                0                 0
5   100032                         v8 5e                                                                         v8 5e      <NA>            0                   0                0                 0
6   100036                      dj irish                                                         assorted trance vol 8      2003            0                   0                1                 0
7   100038       rennie pilgrim presents                                                             nu skool breakz 2      <NA>            0                   0                0                 0
8   100041                   italo house                                                                   12 in mixes      <NA>            0                   0                0                 0
9   100045               matsuka phonics                                                         let s study phonics 2      2002            0                   0                0                 0
10  100046                    kool savas                                                     euer bester freund mix cd      2004            0                   0                0                 0
11  100047                      robotika                                                                         dance      <NA>            0                   0                0                 0
12  100049               johnny hallyday                                                                         vol 4      <NA>            0                   0                1                 0
13  100050                       phallus                                                                        reason      2003            0                   0                0                 0
14  100052                rolling stones                                                 giant stadium 17 08 1994 cd 2      1994            0                   0                1                 0
15  100054    ã ã ã ã ã ã ã¹ã ã ã ã ã ã                                                                   ã ã ã ã ã ã¹      <NA>            0                   0                0                 0
16  100055                       nakama1                                                              cd5 chapters 8 9      <NA>            0                   0                1                 0
17  100062            in vanity we trust                                                                          posh      1999            0                   0                0                 0
18  100068                  diversetion               zeitgeist the psychedelic shack future funk and beatsploitation       <NA>            0                   0                0                 0
19  100069             nikos hatzopoulos                                                             the aegean violin      1996            0                   0                0                 0
20  100072         various artistsry cd2                               ministry of sound sessions eight todd terry cd2      1997            0                   0                1                 0
21  100073                     les vamps                                                                    2 eme show      <NA>            0                   0                0                 0
22  100075                buster b jones                                                          ballads barn burners      1999            0                   0                0                 0
23  100076                        v rios                                                             folia de s o jo o      <NA>            0                   0                0                 0
24  100077                 franz lambert                                      franz lambert spielt beliebte evergreens      1977            0                   0                0                 0

   enrichment_priority_v6
0                    high
1                    high
2                  medium
3                    high
4                    high
5                    high
6                  medium
7                    high
8                    high
9                    high
10                   high
11                   high
12                 medium
13                   high
14                 medium
15                   high
16                 medium
17                   high
18                   high
19                   high
20                 medium
21                   high
22                   high
23                   high
24                   high

In [335]:
import duckdb
import pandas as pd

# Connect to DuckDB
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Build round-2 candidate pairs from the v6 cleaned enrichment subset
# ------------------------------------------------------------
# Comments:
# - We compare the cleaned CDS remainder against the cleaned MB pool.
# - Blocking is based on:
#     * first letter of artist_key_clean
#     * first letter of title_key_clean
#     * similar key lengths
# - This is the input for the next fuzzy scoring round.
print("Creating cds_mb_enrichment_pairs_v6_round2...")

con.execute("""
    CREATE OR REPLACE TABLE cds_mb_enrichment_pairs_v6_round2 AS
    SELECT
        c.cds_id,
        c.artist,
        c.title,
        c.cds_year,
        c.tracks,
        c.enrichment_priority_v6,

        c.artist_key_clean AS cds_artist_key,
        c.title_key_clean  AS cds_title_key,

        m.release_id,
        m.main_artist_name,
        m.release_title,
        m.artist_credit_full,
        m.total_tracks,
        m.barcode,
        m.mb_year,
        m.artist_key_clean AS mb_artist_key,
        m.title_key_clean  AS mb_title_key

    FROM (
        SELECT
            *,
            substr(artist_key_clean, 1, 1) AS artist_first,
            substr(title_key_clean,  1, 1) AS title_first,
            length(artist_key_clean) AS artist_len,
            length(title_key_clean)  AS title_len
        FROM cds_unmatched_for_enrichment_v6_round2
        WHERE
            artist_key_clean IS NOT NULL
            AND title_key_clean IS NOT NULL
            AND length(artist_key_clean) >= 4
            AND length(title_key_clean)  >= 4
    ) c

    JOIN mb_candidate_pool_v2 m
      ON m.artist_first = c.artist_first
     AND m.title_first  = c.title_first
     AND m.artist_len BETWEEN c.artist_len - 3 AND c.artist_len + 3
     AND m.title_len  BETWEEN c.title_len  - 5 AND c.title_len  + 5
""")

print("✅ Table created: cds_mb_enrichment_pairs_v6_round2")

print("\n--- Pair count for round-2 enrichment ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM cds_mb_enrichment_pairs_v6_round2
""").fetchdf())

print("\n--- Distinct CDS rows with candidate pairs in round 2 ---")
print(con.execute("""
    SELECT COUNT(DISTINCT cds_id) AS cds_rows_with_candidates
    FROM cds_mb_enrichment_pairs_v6_round2
""").fetchdf())

print("\n--- Preview: round-2 candidate pairs ---")
print(con.execute("""
    SELECT
        cds_id, artist, title,
        release_id, main_artist_name, release_title,
        cds_year, mb_year, total_tracks, barcode
    FROM cds_mb_enrichment_pairs_v6_round2
    LIMIT 20
""").fetchdf())

Connected ✅
Creating cds_mb_enrichment_pairs_v6_round2...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

✅ Table created: cds_mb_enrichment_pairs_v6_round2

--- Pair count for round-2 enrichment ---
         n
0  9818133

--- Distinct CDS rows with candidate pairs in round 2 ---
   cds_rows_with_candidates
0                      3707

--- Preview: round-2 candidate pairs ---
    cds_id                           artist                                    title  release_id               main_artist_name                                     release_title  cds_year  mb_year  total_tracks  \
0     3123                philosopher kings                    the philosopher kings     1468481                Parasite Single                                The Hunt (Remixed)      <NA>     2014           2.0
1   103412                 eisuke mochiduki                           waitin for you     1664976            Enrico Rava Quartet                                        Wild Dance      <NA>     2015          14.0
2   107234  gavin friday and the man seezer        each man kills the thing he loves     1720144  Gregory Pepper & His Problems                Escape From Crystal Skull Mountain      <NA>     2023          17.0
3   109454                   winter romance                    winter romance disc 1     1642689               Wide Mouth Mason                                  Wide Mouth Mason      1997     2015          12.0
4   106823                       john hiatt                             y all caught     1403665                  Janet Jackson                                        Young Love      1989     2015           2.0
5   108087                  hiroshi okazaki                neo standard living jazz      1633019           Harper and the Moths                                 Nighttime Tremors      2003     2015           1.0
6   109606                        bootfools                               soundtrack      803195                  Bleeker Ridge                                   Small Town Dead      1999     2015          15.0
7   109708                      sammy rodeo             sammy rodeo sound collection     1570219                   Sousa’s Band                         Stars And Stripes Forever      2003     2017           8.0
8   109177               franã ois couperin  troisiã me livre de piã ces de clavecin     1603338            Fairport Convention                The History of Fairport Convention      1988     2023          20.0
9   109700                      sound track                     the great white hype     2374486                      Shinedown                              The Sound of Madness      1996     2019          11.0
10    5681                     robert miles                      dreamland bvcp 993       782792                 Richard Wagner                                     Das Rheingold      1996     2015          30.0
11    5099                       disneyland     the haunted mansion 30th anniversary     1623668                 Douglas Armour  The Light of a Golden Day, The Arms of the Night      1999     2024          10.0
12   11190                   varius artists                     mozart greatest hits      804696                Various Artists                           Maxi Dance Sensation 21      <NA>     2017          38.0
13  109403                          britten                       albert herring cd1      308501                        Blondie                                      Autoamerican      2003     2018          15.0
14  109357                          bellini                                    norma      695990                        Blondie                                           No Exit      1989     2015          17.0
15   11190                   varius artists                     mozart greatest hits      577322                Various Artists                           Maxi Dance Sensation 11      <NA>     2019          25.0
16  109741                      compilation                           matrix trilogy     1981976                  Cody ChesnuTT                             My Love Divine Degree      <NA>     2017          14.0
17   11190                   varius artists                     mozart greatest hits      492117                Various Artists                           Maxi Dance Sensation 15      <NA>     2017          34.0
18   11190                   varius artists                     mozart greatest hits      491024                Various Artists                            Maxi Dance Sensation 8      <NA>     2019          22.0
19   11190                   varius artists                     mozart greatest hits     1347389                Various Artists                           Maxi Dance Sensation 23      <NA>     2019          38.0

          barcode
0            None
1            None
2    616892072140
3    706301732823
4
5    859714276351
6            None
7            None
8
9    075678989452
10  4011222230577
11   656605755120
12   743213794624
13   724353359522
14  5099750140826
15   743211676922
16           None
17   743212315424
18   743211155625
19   743213838922

In [47]:
import duckdb
import pandas as pd
from rapidfuzz import fuzz

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)

# Connect to DuckDB
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Score round-2 candidate pairs in chunks
# ------------------------------------------------------------
# Comments:
# - We score CDS vs MB using cleaned keys:
#     0.4 * artist similarity + 0.6 * title similarity
# - We process in chunks because the pair table is large.
# - Per chunk, we keep only the top few candidates per CDS row.
print("Preparing indexed view for round-2 scoring...")

con.execute("""
    CREATE OR REPLACE VIEW cds_mb_enrichment_pairs_v6_round2_indexed AS
    SELECT
        row_number() OVER () AS rid,
        *
    FROM cds_mb_enrichment_pairs_v6_round2
""")

total_pairs = con.execute("""
    SELECT COUNT(*) FROM cds_mb_enrichment_pairs_v6_round2
""").fetchone()[0]

print(f"Total round-2 pairs to score: {total_pairs:,}")

CHUNK_SIZE = 250_000
KEEP_PER_CHUNK = 3
all_best = []

print("Scoring round-2 candidate pairs in chunks...")

for start in range(1, total_pairs + 1, CHUNK_SIZE):
    end = min(start + CHUNK_SIZE - 1, total_pairs)
    print(f"  Processing rid {start:,} .. {end:,}")

    df = con.execute("""
        SELECT
            cds_id,
            artist,
            title,
            cds_year,
            enrichment_priority_v6,
            cds_artist_key,
            cds_title_key,
            release_id,
            main_artist_name,
            release_title,
            artist_credit_full,
            total_tracks,
            barcode,
            mb_year,
            mb_artist_key,
            mb_title_key
        FROM cds_mb_enrichment_pairs_v6_round2_indexed
        WHERE rid BETWEEN ? AND ?
    """, [start, end]).fetchdf()

    if df.empty:
        continue

    artist_sims = []
    title_sims = []
    scores = []

    for a1, t1, a2, t2 in zip(df["cds_artist_key"], df["cds_title_key"], df["mb_artist_key"], df["mb_title_key"]):
        a_sim = fuzz.token_set_ratio(a1, a2)
        t_sim = fuzz.token_set_ratio(t1, t2)
        score = 0.4 * a_sim + 0.6 * t_sim
        artist_sims.append(a_sim)
        title_sims.append(t_sim)
        scores.append(score)

    df["artist_sim"] = artist_sims
    df["title_sim"] = title_sims
    df["score"] = scores

    # Keep only the best few candidates per CDS row in this chunk
    df = (
        df.sort_values(["cds_id", "score"], ascending=[True, False])
          .groupby("cds_id")
          .head(KEEP_PER_CHUNK)
    )

    all_best.append(df)

best_df = pd.concat(all_best, ignore_index=True) if all_best else pd.DataFrame()

print("Combined candidates after chunk pruning:", len(best_df))

# Keep final top 5 per CDS row across all chunks
TOP_K = 5
best_df = (
    best_df.sort_values(["cds_id", "score"], ascending=[True, False])
           .groupby("cds_id")
           .head(TOP_K)
)

print("Final top candidates:", len(best_df))

con.register("best_df_round2", best_df)

con.execute("""
    CREATE OR REPLACE TABLE cds_to_mb_enrichment_candidates_v6_round2 AS
    SELECT *
    FROM best_df_round2
""")

print("✅ Table created: cds_to_mb_enrichment_candidates_v6_round2")

print("\n--- Preview: top round-2 enrichment candidates ---")
print(con.execute("""
    SELECT
        cds_id, artist, title,
        release_id, main_artist_name, release_title,
        score, artist_sim, title_sim,
        enrichment_priority_v6
    FROM cds_to_mb_enrichment_candidates_v6_round2
    ORDER BY score DESC
    LIMIT 25
""").fetchdf())

Connected ✅
Preparing indexed view for round-2 scoring...
Total round-2 pairs to score: 9,898,596
Scoring round-2 candidate pairs in chunks...
  Processing rid 1 .. 250,000

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  Processing rid 250,001 .. 500,000

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  Processing rid 500,001 .. 750,000

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  Processing rid 750,001 .. 1,000,000

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  Processing rid 1,000,001 .. 1,250,000

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  Processing rid 1,250,001 .. 1,500,000

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  Processing rid 1,500,001 .. 1,750,000

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  Processing rid 1,750,001 .. 2,000,000

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  Processing rid 2,000,001 .. 2,250,000

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  Processing rid 2,250,001 .. 2,500,000

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  Processing rid 2,500,001 .. 2,750,000

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  Processing rid 2,750,001 .. 3,000,000

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  Processing rid 3,000,001 .. 3,250,000

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  Processing rid 3,250,001 .. 3,500,000

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  Processing rid 3,500,001 .. 3,750,000

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  Processing rid 3,750,001 .. 4,000,000

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  Processing rid 4,000,001 .. 4,250,000

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  Processing rid 4,250,001 .. 4,500,000

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  Processing rid 4,500,001 .. 4,750,000

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  Processing rid 4,750,001 .. 5,000,000

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  Processing rid 5,000,001 .. 5,250,000

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  Processing rid 5,250,001 .. 5,500,000

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  Processing rid 5,500,001 .. 5,750,000

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  Processing rid 5,750,001 .. 6,000,000

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  Processing rid 6,000,001 .. 6,250,000

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  Processing rid 6,250,001 .. 6,500,000

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  Processing rid 6,500,001 .. 6,750,000

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  Processing rid 6,750,001 .. 7,000,000

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  Processing rid 7,000,001 .. 7,250,000

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  Processing rid 7,250,001 .. 7,500,000

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  Processing rid 7,500,001 .. 7,750,000

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  Processing rid 7,750,001 .. 8,000,000

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  Processing rid 8,000,001 .. 8,250,000

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  Processing rid 8,250,001 .. 8,500,000

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  Processing rid 8,500,001 .. 8,750,000

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  Processing rid 8,750,001 .. 9,000,000

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  Processing rid 9,000,001 .. 9,250,000

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  Processing rid 9,250,001 .. 9,500,000

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  Processing rid 9,500,001 .. 9,750,000

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  Processing rid 9,750,001 .. 9,898,596

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Combined candidates after chunk pruning: 392886
Final top candidates: 18189
✅ Table created: cds_to_mb_enrichment_candidates_v6_round2

--- Preview: top round-2 enrichment candidates ---
    cds_id                artist                                 title  release_id      main_artist_name                 release_title  score  artist_sim  title_sim enrichment_priority_v6
0     4348           frank zappa                  joe s garage disk 1      4387319           Frank Zappa                  Joe’s Garage  100.0       100.0      100.0                 medium
1   105572                 cream                wheels of fire disk 1       454410                 Cream                Wheels of Fire  100.0       100.0      100.0                 medium
2   101998           abbacadabra                     abbasalute disk 1     2748831           Abbacadabra                    Abbasalute  100.0       100.0      100.0                 medium
3   102027           jules verne  20 000 leagues under the sea disk 1       510942           Jules Verne  20,000 Leagues Under the Sea  100.0       100.0      100.0                 medium
4   102027           jules verne  20 000 leagues under the sea disk 1      3182102           Jules Verne  20,000 Leagues Under the Sea  100.0       100.0      100.0                 medium
5   102027           jules verne  20 000 leagues under the sea disk 1      3182112           Jules Verne  20,000 Leagues Under the Sea  100.0       100.0      100.0                 medium
6   102968           randy greif           alice in wonderland disk 1       250197           Randy Greif           Alice in Wonderland  100.0       100.0      100.0                 medium
7   101998           abbacadabra                     abbasalute disk 1      376867           Abbacadabra                    Abbasalute  100.0       100.0      100.0                 medium
8   103268  bone thugs n harmony                 the art of war disk 1     1867291  Bone Thugs‐n‐Harmony                The Art of War  100.0       100.0      100.0                 medium
9   103268  bone thugs n harmony                 the art of war disk 1      306517  Bone Thugs‐n‐Harmony                The Art of War  100.0       100.0      100.0                 medium
10  103268  bone thugs n harmony                 the art of war disk 1     3949373  Bone Thugs‐n‐Harmony                The Art of War  100.0       100.0      100.0                 medium
11  104027               jimeoin                          crack disk 1     3153251               Jimeoin                         Crack  100.0       100.0      100.0                 medium
12  104641            pink floyd                    prism disk 2 live       907959            Pink Floyd                         Prism  100.0       100.0      100.0                 medium
13  104641            pink floyd                    prism disk 2 live      2396465            Pink Floyd                         Prism  100.0       100.0      100.0                 medium
14  104819              hawkwind          golden void 1969 1979 disk 1      298862              Hawkwind         Golden Void 1969–1979  100.0       100.0      100.0                 medium
15  104831         peter hammill         room temperature live disk 2      1562871         Peter Hammill         Room Temperature Live  100.0       100.0      100.0                 medium
16  104831         peter hammill         room temperature live disk 2       101911         Peter Hammill         Room Temperature Live  100.0       100.0      100.0                 medium
17  105572                 cream                wheels of fire disk 1      1533402                 Cream                Wheels of Fire  100.0       100.0      100.0                 medium
18  105572                 cream                wheels of fire disk 1      1838327                 Cream                Wheels of Fire  100.0       100.0      100.0                 medium
19  105837                prince             do u wanna go home disk 1     4796059                Prince            Do U Wanna Go Home  100.0       100.0      100.0                 medium
20  105572                 cream                wheels of fire disk 1       454411                 Cream                Wheels of Fire  100.0       100.0      100.0                 medium
21  105572                 cream                wheels of fire disk 1       454412                 Cream                Wheels of Fire  100.0       100.0      100.0                 medium
22  105706                  skin             hasta la vista baby disk2       99416                  Skin         Hasta La Vista, Baby!  100.0       100.0      100.0                 medium
23  105706                  skin             hasta la vista baby disk2     1166544                  Skin         Hasta La Vista, Baby!  100.0       100.0      100.0                 medium
24  103268  bone thugs n harmony                 the art of war disk 1       28935  Bone Thugs‐n‐Harmony                The Art of War  100.0       100.0      100.0                 medium

In [365]:
import duckdb
import pandas as pd

# Connect to DuckDB
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Build ambiguity-aware ranking for round-2 enrichment candidates
# ------------------------------------------------------------
# Comments:
# - Input: cds_to_mb_enrichment_candidates_v6_round2
# - For each cds_id:
#     * rank candidates
#     * compute best_score
#     * compute second_best_score
#     * compute score_gap
# - Then assign confidence classes:
#     * auto_accept
#     * review
#     * reject
print("Creating cds_to_mb_enrichment_ranked_v6_round2...")

con.execute("""
    CREATE OR REPLACE TABLE cds_to_mb_enrichment_ranked_v6_round2 AS
    WITH ranked AS (
        SELECT
            *,
            row_number() OVER (
                PARTITION BY cds_id
                ORDER BY
                    score DESC,
                    title_sim DESC,
                    artist_sim DESC,
                    release_id ASC
            ) AS candidate_rank,
            

            first_value(score) OVER (
                PARTITION BY cds_id
                ORDER BY
                    score DESC,
                    title_sim DESC,
                    artist_sim DESC,
                    release_id ASC
            ) AS best_score,

            lead(score) OVER (
                PARTITION BY cds_id
                ORDER BY
                    score DESC,
                    title_sim DESC,
                    artist_sim DESC,
                    release_id ASC
            ) AS second_best_score
        FROM cds_to_mb_enrichment_candidates_v6_round2
    )
    SELECT
        *,
        (best_score - second_best_score) AS score_gap,

        CASE
            WHEN candidate_rank = 1
                 AND score >= 92
                 AND title_sim >= 94
                 AND (best_score - second_best_score >= 8 OR second_best_score IS NULL)
            THEN 'auto_accept'

            WHEN candidate_rank = 1
                 AND score >= 88
                 AND title_sim >= 90
            THEN 'review'

            ELSE 'reject'
        END AS confidence_class

    FROM ranked
""")

print("✅ Table created: cds_to_mb_enrichment_ranked_v6_round2")

print("\n--- Confidence class summary (top-ranked only, round 2) ---")
print(con.execute("""
    SELECT
        confidence_class,
        COUNT(*) AS n
    FROM cds_to_mb_enrichment_ranked_v6_round2
    WHERE candidate_rank = 1
    GROUP BY confidence_class
    ORDER BY n DESC
""").fetchdf())

print("\n--- Preview: top-ranked round-2 candidates ---")
print(con.execute("""
    SELECT
        cds_id,
        artist,
        title,
        release_id,
        main_artist_name,
        release_title,
        score,
        artist_sim,
        title_sim,
        best_score,
        second_best_score,
        score_gap,
        confidence_class,
        enrichment_priority_v6
    FROM cds_to_mb_enrichment_ranked_v6_round2
    WHERE candidate_rank = 1
    ORDER BY score DESC, score_gap DESC NULLS LAST
    LIMIT 30
""").fetchdf())

Connected ✅
Creating cds_to_mb_enrichment_ranked_v6_round2...
✅ Table created: cds_to_mb_enrichment_ranked_v6_round2

--- Confidence class summary (top-ranked only, round 2) ---
  confidence_class     n
0           reject  3611
1           review    64
2      auto_accept     5

--- Preview: top-ranked round-2 candidates ---
    cds_id                artist                                   title  release_id      main_artist_name                      release_title       score  artist_sim   title_sim  best_score  second_best_score  \
0   104819              hawkwind            golden void 1969 1979 disk 1      298862              Hawkwind              Golden Void 1969–1979  100.000000  100.000000  100.000000  100.000000          61.176471
1   102968           randy greif             alice in wonderland disk 1       250197           Randy Greif                Alice in Wonderland  100.000000  100.000000  100.000000  100.000000          61.443932
2   105837                prince               do u wanna go home disk 1     4796059                Prince                 Do U Wanna Go Home  100.000000  100.000000  100.000000  100.000000          67.692308
3   104027               jimeoin                            crack disk 1     3153251               Jimeoin                              Crack  100.000000  100.000000  100.000000  100.000000          74.545455
4     4348           frank zappa                    joe s garage disk 1      4387319           Frank Zappa                       Joe’s Garage  100.000000  100.000000  100.000000  100.000000          90.000000
5   103268  bone thugs n harmony                   the art of war disk 1       28935  Bone Thugs‐n‐Harmony                     The Art of War  100.000000  100.000000  100.000000  100.000000         100.000000
6   105572                 cream                  wheels of fire disk 1       454410                 Cream                     Wheels of Fire  100.000000  100.000000  100.000000  100.000000         100.000000
7   102027           jules verne    20 000 leagues under the sea disk 1       510942           Jules Verne       20,000 Leagues Under the Sea  100.000000  100.000000  100.000000  100.000000         100.000000
8   107890          bessie smith   the complete recordings vol 5 disk 1       770956          Bessie Smith  The Complete Recordings, Volume 1  100.000000  100.000000  100.000000  100.000000         100.000000
9   104831         peter hammill           room temperature live disk 2       101911         Peter Hammill              Room Temperature Live  100.000000  100.000000  100.000000  100.000000         100.000000
10  104641            pink floyd                      prism disk 2 live       907959            Pink Floyd                              Prism  100.000000  100.000000  100.000000  100.000000         100.000000
11  101998           abbacadabra                       abbasalute disk 1      376867           Abbacadabra                         Abbasalute  100.000000  100.000000  100.000000  100.000000         100.000000
12  105706                  skin               hasta la vista baby disk2       99416                  Skin              Hasta La Vista, Baby!  100.000000  100.000000  100.000000  100.000000         100.000000
13  101868       placido domingo                    songs of love disk 1      150707       Plácido Domingo                      Songs of Love   98.518519   96.296296  100.000000   98.518519          98.518519
14    2891         nat king cole                      en espanol disk 1      1076980         Nat King Cole                         En español   96.470588  100.000000   94.117647   96.470588          96.470588
15  108482                  enya   only time the collection disk 4 of 4         2770                  Enya          Only Time: The Collection   96.000000  100.000000   93.333333   96.000000          75.294118
16  109001     gioachino rossini    il barbiere di siviglia disk 3 of 3       657500     Gioachino Rossini            Il barbiere di Siviglia   95.813953  100.000000   93.023256   95.813953          95.813953
17  102025               orbital                    orbital green album      4353675               Orbital  Orbital: The Green Album Expanded   95.135135  100.000000   91.891892   95.135135          84.210526
18  103302            gary numan         living ornaments 81 disk 1 of 2       12114            Gary Numan               Living Ornaments ’81   95.135135  100.000000   91.891892   95.135135          95.135135
19  103576         wolf biermann              zu gast bei wolfgang neuss     1132751         Wolf Biermann  Zu Gast bei Wolfgang Neuss - West   95.000000  100.000000   91.666667   95.000000          48.000000
20  100911        nellie lutcher       nellie lutcher her rhythm 2 of 4       104582        Nellie Lutcher        Nellie Lutcher & Her Rhythm   95.000000  100.000000   91.666667   95.000000          50.026954
21  106896               cerrone                           best remixes       230081               Cerrone                    Best of Remixes   95.000000  100.000000   91.666667   95.000000          71.666667
22  101111         george benson                         jazz masters 21     2432954         George Benson                        Jazzmasters   95.000000  100.000000   91.666667   95.000000          73.600000
23    6858           linkin park                           hibrid theory       32975           Linkin Park                      Hybrid Theory   95.000000  100.000000   91.666667   95.000000          95.000000
24  101220       louis armstrong  the great chicago concert 1956 disc 2       484236       Louis Armstrong          The Great Chicago Concert   95.000000  100.000000   91.666667   95.000000          95.000000
25    7653           linkin park                           hybrid theroy       32975           Linkin Park                      Hybrid Theory   95.000000  100.000000   91.666667   95.000000          95.000000
26    5458          richard bona                          munia the tail      217116          Richard Bona                    Munia: The Tale   95.000000  100.000000   91.666667   95.000000          95.000000
27  103900         zã mbã³ jimmy             karã csony zã mbã³ jimmyvel       30967           Zámbó Jimmy                 Karácsony Jimmyvel   94.857143  100.000000   91.428571   94.857143          38.319328
28  106671         happy mondays   pills n thrills and bellyaches japan         1430         Happy Mondays   Pills ’n’ Thrills and Bellyaches   94.736842  100.000000   91.228070   94.736842          94.736842
29  107875          walter trout            no more fish jokes wtb live        39514          Walter Trout          No More Fish Jokes (live)   94.545455  100.000000   90.909091   94.545455          55.254658

    score_gap confidence_class enrichment_priority_v6
0   38.823529      auto_accept                 medium
1   38.556068      auto_accept                 medium
2   32.307692      auto_accept                 medium
3   25.454545      auto_accept                 medium
4   10.000000      auto_accept                 medium
5    0.000000           review                 medium
6    0.000000           review                 medium
7    0.000000           review                 medium
8    0.000000           review                 medium
9    0.000000           review                 medium
10   0.000000           review                 medium
11   0.000000           review                 medium
12   0.000000           review                 medium
13   0.000000           review                 medium
14   0.000000           review                 medium
15  20.705882           review                 medium
16   0.000000           review                 medium
17  10.924609           review                   high
18   0.000000           review                 medium
19  47.000000           review                   high
20  44.973046           review                   high
21  23.333333           review                   high
22  21.400000           review                   high
23   0.000000           review                   high
24   0.000000           review                 medium
25   0.000000           review                   high
26   0.000000           review                   high
27  56.537815           review                   high
28   0.000000           review                   high
29  39.290796           review                   high

In [344]:
import duckdb
import pandas as pd

# Connect to DuckDB
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Step 1: Create automatic round-2 enrichment table
# ------------------------------------------------------------
print("Creating cds_to_mb_best_enrichment_v6_round2_auto...")

con.execute("""
    CREATE OR REPLACE TABLE cds_to_mb_best_enrichment_v6_round2_auto AS
    SELECT
        cds_id,
        artist,
        title,
        cds_year,
        release_id,
        release_title,
        main_artist_name,
        artist_credit_full,
        total_tracks,
        barcode,
        mb_year,
        score,
        artist_sim,
        title_sim,
        best_score,
        second_best_score,
        score_gap,
        confidence_class,
        enrichment_priority_v6
    FROM cds_to_mb_enrichment_ranked_v6_round2
    WHERE candidate_rank = 1
      AND confidence_class = 'auto_accept'
""")

print("✅ Table created: cds_to_mb_best_enrichment_v6_round2_auto")

print("\n--- Count of round-2 auto-accepted matches ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM cds_to_mb_best_enrichment_v6_round2_auto
""").fetchdf())

# ------------------------------------------------------------
# Step 2: Merge round-2 auto matches into a new final mapping
# ------------------------------------------------------------
print("\nCreating cds_to_mb_final_mapping_v8...")

con.execute("""
    CREATE OR REPLACE TABLE cds_to_mb_final_mapping_v8 AS

    -- Existing v6 mapping
    SELECT
        cds_id,
        artist,
        title,
        cds_year,
        release_id,
        release_title,
        main_artist_name,
        artist_credit_full,
        total_tracks,
        barcode,
        mb_year,
        match_type,
        confidence_label,
        score,
        title_sim,
        artist_sim
    FROM cds_to_mb_final_mapping_v6

    UNION ALL

    -- New round-2 auto-accepted matches
    SELECT
        e.cds_id,
        e.artist,
        e.title,
        e.cds_year,
        e.release_id,
        e.release_title,
        e.main_artist_name,
        e.artist_credit_full,
        e.total_tracks,
        e.barcode,
        e.mb_year,
        'enrichment_round2_auto' AS match_type,
        e.confidence_class AS confidence_label,
        e.score,
        e.title_sim,
        e.artist_sim
    FROM cds_to_mb_best_enrichment_v6_round2_auto e
    LEFT JOIN cds_to_mb_final_mapping_v6 m
      ON m.cds_id = e.cds_id
    WHERE m.cds_id IS NULL
""")

print("✅ Table created: cds_to_mb_final_mapping_v8")

# ------------------------------------------------------------
# Step 3: Coverage report after round-2 automatic enrichment
# ------------------------------------------------------------
report_v8 = con.execute("""
    SELECT
        (SELECT COUNT(*) FROM cds) AS cds_total,
        (SELECT COUNT(*) FROM cds_to_mb_final_mapping_v6) AS matched_before_round2,
        (SELECT COUNT(*) FROM cds_to_mb_best_enrichment_v6_round2_auto) AS round2_auto_candidates,
        (SELECT COUNT(*) FROM cds_to_mb_final_mapping_v8) AS matched_after_round2,
        (SELECT COUNT(*) FROM cds_to_mb_final_mapping_v8)
          - (SELECT COUNT(*) FROM cds_to_mb_final_mapping_v6) AS newly_added_by_round2,
        (SELECT COUNT(*) FROM cds)
          - (SELECT COUNT(*) FROM cds_to_mb_final_mapping_v8) AS still_unmatched_after_round2
""").fetchdf()

print("\n--- Thesis Report: Coverage After Round-2 Automatic Enrichment ---")
print(report_v8)

print("\n--- Match type breakdown in v8 ---")
print(con.execute("""
    SELECT match_type, COUNT(*) AS n
    FROM cds_to_mb_final_mapping_v8
    GROUP BY match_type
    ORDER BY n DESC
""").fetchdf())

print("\n--- Uniqueness check by cds_id ---")
print(con.execute("""
    SELECT
        COUNT(*) AS total_rows,
        COUNT(DISTINCT cds_id) AS distinct_cds_id,
        COUNT(*) - COUNT(DISTINCT cds_id) AS duplicate_cds_id_rows
    FROM cds_to_mb_final_mapping_v8
""").fetchdf())

Connected ✅
Creating cds_to_mb_best_enrichment_v6_round2_auto...
✅ Table created: cds_to_mb_best_enrichment_v6_round2_auto

--- Count of round-2 auto-accepted matches ---
   n
0  5

Creating cds_to_mb_final_mapping_v8...
✅ Table created: cds_to_mb_final_mapping_v8

--- Thesis Report: Coverage After Round-2 Automatic Enrichment ---
   cds_total  matched_before_round2  round2_auto_candidates  matched_after_round2  newly_added_by_round2  still_unmatched_after_round2
0       9763                   4208                       5                  4211                      3                          5552

--- Match type breakdown in v8 ---
               match_type     n
0                   exact  3482
1       fuzzy_second_pass   543
2      various_title_only   183
3  enrichment_round2_auto     3

--- Uniqueness check by cds_id ---
   total_rows  distinct_cds_id  duplicate_cds_id_rows
0        4211             4211                      0

In [345]:
import duckdb
import os
import pandas as pd

# Connect
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

os.makedirs("../data_processed/exports", exist_ok=True)

# ------------------------------------------------------------
# Export round-2 review candidates for manual inspection
# ------------------------------------------------------------
# Comments:
# - These are the top-ranked round-2 candidates classified as "review"
# - They are not safe enough for auto-accept
# - But they are the best manual-review set for the thesis
print("Creating cds_to_mb_review_candidates_v6_round2...")

con.execute("""
    CREATE OR REPLACE TABLE cds_to_mb_review_candidates_v6_round2 AS
    SELECT
        cds_id,
        artist,
        title,
        cds_year,
        release_id,
        main_artist_name,
        release_title,
        artist_credit_full,
        total_tracks,
        barcode,
        mb_year,
        score,
        artist_sim,
        title_sim,
        best_score,
        second_best_score,
        score_gap,
        confidence_class,
        enrichment_priority_v6
    FROM cds_to_mb_enrichment_ranked_v6_round2
    WHERE candidate_rank = 1
      AND confidence_class = 'review'
""")

print("✅ Table created: cds_to_mb_review_candidates_v6_round2")

print("\n--- Count of review candidates ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM cds_to_mb_review_candidates_v6_round2
""").fetchdf())

# Export to CSV
out_path = "../data_processed/exports/cds_to_mb_review_candidates_v6_round2.csv"
con.execute(f"""
    COPY cds_to_mb_review_candidates_v6_round2
    TO '{out_path}'
    WITH (HEADER, DELIMITER ',')
""")

print(f"\n✅ Exported: {out_path}")

print("\n--- Preview: review candidates ---")
print(con.execute("""
    SELECT
        cds_id, artist, title,
        release_id, main_artist_name, release_title,
        score, artist_sim, title_sim, score_gap
    FROM cds_to_mb_review_candidates_v6_round2
    ORDER BY score DESC, score_gap DESC NULLS LAST
    LIMIT 25
""").fetchdf())

Connected ✅
Creating cds_to_mb_review_candidates_v6_round2...
✅ Table created: cds_to_mb_review_candidates_v6_round2

--- Count of review candidates ---
    n
0  64

✅ Exported: ../data_processed/exports/cds_to_mb_review_candidates_v6_round2.csv

--- Preview: review candidates ---
    cds_id                artist                                   title  release_id      main_artist_name                      release_title       score  artist_sim   title_sim  score_gap
0   101998           abbacadabra                       abbasalute disk 1      376867           Abbacadabra                         Abbasalute  100.000000  100.000000  100.000000   0.000000
1   107890          bessie smith   the complete recordings vol 5 disk 1       770956          Bessie Smith  The Complete Recordings, Volume 1  100.000000  100.000000  100.000000   0.000000
2   104641            pink floyd                      prism disk 2 live       907959            Pink Floyd                              Prism  100.000000  100.000000  100.000000   0.000000
3   104831         peter hammill           room temperature live disk 2       101911         Peter Hammill              Room Temperature Live  100.000000  100.000000  100.000000   0.000000
4   105706                  skin               hasta la vista baby disk2       99416                  Skin              Hasta La Vista, Baby!  100.000000  100.000000  100.000000   0.000000
5   103268  bone thugs n harmony                   the art of war disk 1       28935  Bone Thugs‐n‐Harmony                     The Art of War  100.000000  100.000000  100.000000   0.000000
6   105572                 cream                  wheels of fire disk 1       454410                 Cream                     Wheels of Fire  100.000000  100.000000  100.000000   0.000000
7   102027           jules verne    20 000 leagues under the sea disk 1       510942           Jules Verne       20,000 Leagues Under the Sea  100.000000  100.000000  100.000000   0.000000
8   101868       placido domingo                    songs of love disk 1      150707       Plácido Domingo                      Songs of Love   98.518519   96.296296  100.000000   0.000000
9     2891         nat king cole                      en espanol disk 1      1076980         Nat King Cole                         En español   96.470588  100.000000   94.117647   0.000000
10  108482                  enya   only time the collection disk 4 of 4         2770                  Enya          Only Time: The Collection   96.000000  100.000000   93.333333  20.705882
11  109001     gioachino rossini    il barbiere di siviglia disk 3 of 3       657500     Gioachino Rossini            Il barbiere di Siviglia   95.813953  100.000000   93.023256   0.000000
12  102025               orbital                    orbital green album      4353675               Orbital  Orbital: The Green Album Expanded   95.135135  100.000000   91.891892  10.924609
13  103302            gary numan         living ornaments 81 disk 1 of 2       12114            Gary Numan               Living Ornaments ’81   95.135135  100.000000   91.891892   0.000000
14  103576         wolf biermann              zu gast bei wolfgang neuss     1132751         Wolf Biermann  Zu Gast bei Wolfgang Neuss - West   95.000000  100.000000   91.666667  47.000000
15  100911        nellie lutcher       nellie lutcher her rhythm 2 of 4       104582        Nellie Lutcher        Nellie Lutcher & Her Rhythm   95.000000  100.000000   91.666667  44.973046
16  106896               cerrone                           best remixes       230081               Cerrone                    Best of Remixes   95.000000  100.000000   91.666667  23.333333
17  101111         george benson                         jazz masters 21     2432954         George Benson                        Jazzmasters   95.000000  100.000000   91.666667  21.400000
18  101220       louis armstrong  the great chicago concert 1956 disc 2       484236       Louis Armstrong          The Great Chicago Concert   95.000000  100.000000   91.666667   0.000000
19    7653           linkin park                           hybrid theroy       32975           Linkin Park                      Hybrid Theory   95.000000  100.000000   91.666667   0.000000
20    5458          richard bona                          munia the tail      217116          Richard Bona                    Munia: The Tale   95.000000  100.000000   91.666667   0.000000
21    6858           linkin park                           hibrid theory       32975           Linkin Park                      Hybrid Theory   95.000000  100.000000   91.666667   0.000000
22  103900         zã mbã³ jimmy             karã csony zã mbã³ jimmyvel       30967           Zámbó Jimmy                 Karácsony Jimmyvel   94.857143  100.000000   91.428571  56.537815
23  106671         happy mondays   pills n thrills and bellyaches japan         1430         Happy Mondays   Pills ’n’ Thrills and Bellyaches   94.736842  100.000000   91.228070   0.000000
24  107875          walter trout            no more fish jokes wtb live        39514          Walter Trout          No More Fish Jokes (live)   94.545455  100.000000   90.909091  39.290796

In [346]:
import duckdb
import os

# Connect to DuckDB
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# Make sure exports folder exists
os.makedirs("../data_processed/exports", exist_ok=True)

# Export final mapping v8
out_path = "../data_processed/exports/cds_to_mb_final_mapping_v8.csv"

con.execute(f"""
    COPY cds_to_mb_final_mapping_v8
    TO '{out_path}'
    WITH (HEADER, DELIMITER ',')
""")

print(f"✅ Exported: {out_path}")

# Quick check
print("\n--- Row count in cds_to_mb_final_mapping_v8 ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM cds_to_mb_final_mapping_v8
""").fetchdf())

Connected ✅
✅ Exported: ../data_processed/exports/cds_to_mb_final_mapping_v8.csv

--- Row count in cds_to_mb_final_mapping_v8 ---
      n
0  4211

In [347]:
import duckdb
import pandas as pd

# Connect to DuckDB
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Master status table for the full CDS source population
# ------------------------------------------------------------
# Comments:
# - This table is built from the whole CDS dataset.
# - It tracks, for every cds_id:
#     * whether it was matched
#     * by which route it was matched
#     * whether it is in the manual-review set
#     * whether it remains unmatched after v8
# - This is useful for thesis reporting because it proves that
#   the whole CDS source participated in the enrichment workflow.
print("Creating cds_enrichment_master_status...")

con.execute("""
    CREATE OR REPLACE TABLE cds_enrichment_master_status AS
    WITH base AS (
        SELECT
            c.cds_id,
            c.artist,
            c.title,
            c.cds_year,
            c.tracks,
            c.artist_key,
            c.title_key
        FROM cds_norm c
    ),

    final_match AS (
        SELECT
            cds_id,
            release_id,
            release_title,
            main_artist_name,
            artist_credit_full,
            total_tracks,
            barcode,
            mb_year,
            match_type,
            score
        FROM cds_to_mb_final_mapping_v8
    ),

    review AS (
        SELECT
            cds_id,
            release_id AS review_release_id,
            release_title AS review_release_title,
            main_artist_name AS review_main_artist_name,
            score AS review_score,
            artist_sim,
            title_sim,
            best_score,
            second_best_score,
            score_gap,
            confidence_class
        FROM cds_to_mb_review_candidates_v6_round2
    )

    SELECT
        b.cds_id,
        b.artist,
        b.title,
        b.cds_year,
        b.tracks,
        b.artist_key,
        b.title_key,

        -- Final automatic match information
        f.release_id,
        f.release_title,
        f.main_artist_name,
        f.artist_credit_full,
        f.total_tracks,
        f.barcode,
        f.mb_year,
        f.match_type,
        f.score AS final_score,

        -- Review candidate information
        r.review_release_id,
        r.review_release_title,
        r.review_main_artist_name,
        r.review_score,
        r.artist_sim AS review_artist_sim,
        r.title_sim AS review_title_sim,
        r.best_score AS review_best_score,
        r.second_best_score AS review_second_best_score,
        r.score_gap AS review_score_gap,
        r.confidence_class AS review_confidence_class,

        -- Master pipeline status
        CASE
            WHEN f.cds_id IS NOT NULL THEN 'matched_automatic'
            WHEN r.cds_id IS NOT NULL THEN 'review_candidate'
            ELSE 'still_unmatched'
        END AS pipeline_status

    FROM base b
    LEFT JOIN final_match f
      ON b.cds_id = f.cds_id
    LEFT JOIN review r
      ON b.cds_id = r.cds_id
""")

print("✅ Table created: cds_enrichment_master_status")

print("\n--- Master status breakdown ---")
print(con.execute("""
    SELECT pipeline_status, COUNT(*) AS n
    FROM cds_enrichment_master_status
    GROUP BY pipeline_status
    ORDER BY n DESC
""").fetchdf())

print("\n--- Match route breakdown (automatic only) ---")
print(con.execute("""
    SELECT match_type, COUNT(*) AS n
    FROM cds_enrichment_master_status
    WHERE pipeline_status = 'matched_automatic'
    GROUP BY match_type
    ORDER BY n DESC
""").fetchdf())

print("\n--- Preview: master status table ---")
print(con.execute("""
    SELECT
        cds_id,
        artist,
        title,
        pipeline_status,
        match_type,
        release_id,
        release_title,
        review_release_id,
        review_release_title
    FROM cds_enrichment_master_status
    LIMIT 30
""").fetchdf())

Connected ✅
Creating cds_enrichment_master_status...
✅ Table created: cds_enrichment_master_status

--- Master status breakdown ---
     pipeline_status     n
0    still_unmatched  5509
1  matched_automatic  4211
2   review_candidate    43

--- Match route breakdown (automatic only) ---
               match_type     n
0                   exact  3482
1       fuzzy_second_pass   543
2      various_title_only   183
3  enrichment_round2_auto     3

--- Preview: master status table ---
    cds_id                artist                            title    pipeline_status          match_type  release_id                  release_title  review_release_id review_release_title
0    10000       backstreet boys                       millennium  matched_automatic               exact        8069                     Millennium               <NA>                 None
1   100001               various      frankfurt trance vol 04 cd1  matched_automatic  various_title_only      190028               Frankfurt Trance               <NA>                 None
2   100002             no return                  self mutilation  matched_automatic               exact       12737                Self Mutilation               <NA>                 None
3   100006      luv lite massive                         one love  matched_automatic               exact     1032522                       One Love               <NA>                 None
4   100008                  dmbq                             dmbq  matched_automatic               exact     1383710                           DMBQ               <NA>                 None
5   100010               various      frankfurt trance vol 05 cd1  matched_automatic  various_title_only      190028               Frankfurt Trance               <NA>                 None
6   100012    rumania montevideo                 mo better tracks  matched_automatic               exact      510936              MO' BETTER TRACKS               <NA>                 None
7   100015                 keedy                 chase the clouds  matched_automatic               exact       85239               Chase the Clouds               <NA>                 None
8   100019            bill evans                            alone  matched_automatic               exact      100846                          Alone               <NA>                 None
9   100020      nature destroyed                           shades  matched_automatic               exact      210151                         Shades               <NA>                 None
10  100021             pearl jam                            yield  matched_automatic               exact        5053                          Yield               <NA>                 None
11  100022     dingdong avanzado    the best of dingdong avanzado  matched_automatic               exact     5132677  The Best Of Dingdong Avanzado               <NA>                 None
12  100024                  175r                            songs  matched_automatic               exact      435351                          Songs               <NA>                 None
13  100026    day after tomorrow                         elements  matched_automatic               exact       33014                       elements               <NA>                 None
14  100031               spartak                            golem  matched_automatic               exact      362682                          Golem               <NA>                 None
15  100035                gazebo               the best of gazebo  matched_automatic               exact     1883940             The Best of Gazebo               <NA>                 None
16  100037  sportfreunde stiller                   die gute seite  matched_automatic               exact       37684                 Die gute Seite               <NA>                 None
17  100039               various            salsaenlacalleocho 96  matched_automatic  various_title_only     2389539     Salsa en la calle Ocho '96               <NA>                 None
18  100040     barbara streisand                 a love like ours  matched_automatic   fuzzy_second_pass      667030               A Love Like Ours               <NA>                 None
19  100058             green day                           dookie  matched_automatic               exact        2576                         Dookie               <NA>                 None
20  100064                savage                          tonight  matched_automatic               exact     1055561                        Tonight               <NA>                 None
21  100065      atmo brtschitsch                 change your life  matched_automatic               exact       61536               Change Your Life               <NA>                 None
22  100066            del amitri                          twisted  matched_automatic               exact         506                        Twisted               <NA>                 None
23  100082         barry mcguire               eve of destruction  matched_automatic               exact     1346799             Eve of Destruction               <NA>                 None
24  100087         tschou zã me                         wã ge dir  matched_automatic               exact     2627500                       Wäge Dir               <NA>                 None
25  100088         clive gregson                  comfort and joy  matched_automatic               exact      180360                Comfort and Joy               <NA>                 None
26  100089       various artists                   dorival caymmi  matched_automatic  various_title_only     5519190                 Dorival Caymmi               <NA>                 None
27  100094            keri noble                         fearless  matched_automatic               exact       20216                       Fearless               <NA>                 None
28  100097           north cregg                summer at my feet  matched_automatic               exact     1193933              Summer At My Feet               <NA>                 None
29  100099    fabienne thibeault  les plus belles chansons cd 2 2  matched_automatic   fuzzy_second_pass     1017944       Les Plus Belles Chansons               <NA>                 None

In [348]:
import duckdb
import os

# Connect to DuckDB
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

os.makedirs("../data_processed/exports", exist_ok=True)

out_path = "../data_processed/exports/cds_enrichment_master_status.csv"

con.execute(f"""
    COPY cds_enrichment_master_status
    TO '{out_path}'
    WITH (HEADER, DELIMITER ',')
""")

print(f"✅ Exported: {out_path}")

Connected ✅
✅ Exported: ../data_processed/exports/cds_enrichment_master_status.csv

In [349]:
import duckdb
import pandas as pd

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

report_full_source = con.execute("""
    SELECT
        (SELECT COUNT(*) FROM cds_enrichment_master_status) AS cds_total,

        (SELECT COUNT(*) FROM cds_enrichment_master_status
         WHERE pipeline_status = 'matched_automatic') AS matched_automatic_n,
        ROUND(
            100.0 * (SELECT COUNT(*) FROM cds_enrichment_master_status
                     WHERE pipeline_status = 'matched_automatic')
            / (SELECT COUNT(*) FROM cds_enrichment_master_status), 2
        ) AS matched_automatic_pct,

        (SELECT COUNT(*) FROM cds_enrichment_master_status
         WHERE pipeline_status = 'review_candidate') AS review_candidate_n,
        ROUND(
            100.0 * (SELECT COUNT(*) FROM cds_enrichment_master_status
                     WHERE pipeline_status = 'review_candidate')
            / (SELECT COUNT(*) FROM cds_enrichment_master_status), 2
        ) AS review_candidate_pct,

        (SELECT COUNT(*) FROM cds_enrichment_master_status
         WHERE pipeline_status = 'still_unmatched') AS still_unmatched_n,
        ROUND(
            100.0 * (SELECT COUNT(*) FROM cds_enrichment_master_status
                     WHERE pipeline_status = 'still_unmatched')
            / (SELECT COUNT(*) FROM cds_enrichment_master_status), 2
        ) AS still_unmatched_pct
""").fetchdf()

print("\n--- Thesis Report: Full CDS Source Participation ---")
print(report_full_source)

Connected ✅

--- Thesis Report: Full CDS Source Participation ---
   cds_total  matched_automatic_n  matched_automatic_pct  review_candidate_n  review_candidate_pct  still_unmatched_n  still_unmatched_pct
0       9763                 4211                  43.13                  43                  0.44               5509                56.43

In [350]:
import duckdb
import pandas as pd

# Connect
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Professional curation of unmatched CDS after v6
# ------------------------------------------------------------
# Comments:
# - We do NOT delete from the source.
# - We create:
#     1) curated rows for active enrichment
#     2) excluded rows for documentation / audit trail
# - Exclusion is only for rows that are too damaged or too weak.
print("Creating curated and excluded unmatched tables...")

con.execute("""
    CREATE OR REPLACE TABLE cds_unmatched_curated_v1 AS
    SELECT
        *,
        CASE
            WHEN is_various_artists = 1 THEN 'special_various_route'
            WHEN has_disc_cd_vol = 1 THEN 'special_disc_cd_vol_route'
            WHEN enrichment_priority_v6 = 'high' THEN 'standard_enrichment'
            WHEN enrichment_priority_v6 = 'medium' THEN 'careful_enrichment'
            ELSE 'other'
        END AS curation_route
    FROM cds_unmatched_working_v6
    WHERE NOT (
        -- Exclude rows that are too damaged for trustworthy enrichment
        is_mojibake = 1
        OR missing_artist = 1
        OR missing_title = 1
        OR (short_artist = 1 AND short_title = 1)
        OR (
            is_generic_title = 1
            AND (artist IS NULL OR trim(artist) = '' OR lower(trim(artist)) IN (
                'various', 'various artists', 'various artist', 'va', 'v a', 'v.a.'
            ))
        )
    )
""")

con.execute("""
    CREATE OR REPLACE TABLE cds_unmatched_excluded_v1 AS
    SELECT
        *,
        CASE
            WHEN is_mojibake = 1 THEN 'unrecoverable_mojibake'
            WHEN missing_artist = 1 THEN 'missing_artist'
            WHEN missing_title = 1 THEN 'missing_title'
            WHEN short_artist = 1 AND short_title = 1 THEN 'too_short_artist_and_title'
            WHEN is_generic_title = 1
                 AND (artist IS NULL OR trim(artist) = '' OR lower(trim(artist)) IN (
                     'various', 'various artists', 'various artist', 'va', 'v a', 'v.a.'
                 ))
            THEN 'generic_and_weak_metadata'
            ELSE 'other_exclusion'
        END AS exclusion_reason
    FROM cds_unmatched_working_v6
    WHERE (
        is_mojibake = 1
        OR missing_artist = 1
        OR missing_title = 1
        OR (short_artist = 1 AND short_title = 1)
        OR (
            is_generic_title = 1
            AND (artist IS NULL OR trim(artist) = '' OR lower(trim(artist)) IN (
                'various', 'various artists', 'various artist', 'va', 'v a', 'v.a.'
            ))
        )
    )
""")

print("✅ Tables created: cds_unmatched_curated_v1, cds_unmatched_excluded_v1")

print("\n--- Curated vs excluded summary ---")
print(con.execute("""
    SELECT 'curated_for_enrichment' AS bucket, COUNT(*) AS n
    FROM cds_unmatched_curated_v1
    UNION ALL
    SELECT 'excluded_from_active_enrichment' AS bucket, COUNT(*) AS n
    FROM cds_unmatched_excluded_v1
""").fetchdf())

print("\n--- Exclusion reason breakdown ---")
print(con.execute("""
    SELECT exclusion_reason, COUNT(*) AS n
    FROM cds_unmatched_excluded_v1
    GROUP BY exclusion_reason
    ORDER BY n DESC
""").fetchdf())

print("\n--- Curation route breakdown ---")
print(con.execute("""
    SELECT curation_route, COUNT(*) AS n
    FROM cds_unmatched_curated_v1
    GROUP BY curation_route
    ORDER BY n DESC
""").fetchdf())

Connected ✅
Creating curated and excluded unmatched tables...
✅ Tables created: cds_unmatched_curated_v1, cds_unmatched_excluded_v1

--- Curated vs excluded summary ---
                            bucket     n
0           curated_for_enrichment  5015
1  excluded_from_active_enrichment   540

--- Exclusion reason breakdown ---
             exclusion_reason    n
0      unrecoverable_mojibake  509
1  too_short_artist_and_title   15
2               missing_title   10
3              missing_artist    6

--- Curation route breakdown ---
              curation_route     n
0        standard_enrichment  3348
1      special_various_route   896
2  special_disc_cd_vol_route   579
3                      other   167
4         careful_enrichment    25

In [351]:
import duckdb
import pandas as pd

# Connect
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Main curated enrichment subset
# ------------------------------------------------------------
# Comments:
# - This is the safest main route from the curated unmatched set.
# - We keep:
#     * standard_enrichment
#     * careful_enrichment
# - We leave special_various_route and special_disc_cd_vol_route
#   for dedicated strategies.
print("Creating cds_unmatched_curated_main_v1...")

con.execute("""
    CREATE OR REPLACE TABLE cds_unmatched_curated_main_v1 AS
    SELECT *
    FROM cds_unmatched_curated_v1
    WHERE curation_route IN ('standard_enrichment', 'careful_enrichment')
""")

print("✅ Table created: cds_unmatched_curated_main_v1")

print("\n--- Main curated enrichment subset ---")
print(con.execute("""
    SELECT curation_route, COUNT(*) AS n
    FROM cds_unmatched_curated_main_v1
    GROUP BY curation_route
    ORDER BY n DESC
""").fetchdf())

print("\n--- Count of rows in main curated enrichment subset ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM cds_unmatched_curated_main_v1
""").fetchdf())

print("\n--- Preview: main curated enrichment subset ---")
print(con.execute("""
    SELECT
        cds_id, artist, title, cds_year,
        artist_key_clean, title_key_clean,
        curation_route
    FROM cds_unmatched_curated_main_v1
    LIMIT 20
""").fetchdf())

Connected ✅
Creating cds_unmatched_curated_main_v1...
✅ Table created: cds_unmatched_curated_main_v1

--- Main curated enrichment subset ---
        curation_route     n
0  standard_enrichment  3348
1   careful_enrichment    25

--- Count of rows in main curated enrichment subset ---
      n
0  3373

--- Preview: main curated enrichment subset ---
    cds_id                             artist                                                             title  cds_year              artist_key_clean                                           title_key_clean  \
0   100004                            emanuel                                                        felicidade      1998                       emanuel                                                felicidade
1   100009                             4 p m                                                         sweet soul      2001                           4pm                                                 sweetsoul
2   100028                    jazz signatures                                                   jazz signatures      1998                jazzsignatures                                            jazzsignatures
3   100029                bernadã te bidã ude                                                     pomme d amour      <NA>                bernadtebidude                                               pommedamour
4   100032                              v8 5e                                                             v8 5e      <NA>                          v85e                                                      v85e
5   100038            rennie pilgrim presents                                                 nu skool breakz 2      <NA>         renniepilgrimpresents                                            nuskoolbreakz2
6   100041                        italo house                                                       12 in mixes      <NA>                    italohouse                                                 12inmixes
7   100045                    matsuka phonics                                             let s study phonics 2      2002                matsukaphonics                                         letsstudyphonics2
8   100046                         kool savas                                         euer bester freund mix cd      2004                     koolsavas                                     euerbesterfreundmixcd
9   100047                           robotika                                                             dance      <NA>                      robotika                                                     dance
10  100050                            phallus                                                            reason      2003                       phallus                                                    reason
11  100054         ã ã ã ã ã ã ã¹ã ã ã ã ã ã                                                       ã ã ã ã ã ã¹      <NA>
12  100062                 in vanity we trust                                                              posh      1999               invanitywetrust                                                      posh
13  100068                       diversetion   zeitgeist the psychedelic shack future funk and beatsploitation       <NA>                   diversetion  zeitgeistthepsychedelicshackfuturefunkandbeatsploitation
14  100069                  nikos hatzopoulos                                                 the aegean violin      1996              nikoshatzopoulos                                           theaegeanviolin
15  100073                          les vamps                                                        2 eme show      <NA>                      lesvamps                                                  2emeshow
16  100075                     buster b jones                                              ballads barn burners      1999                  busterbjones                                        balladsbarnburners
17  100076                             v rios                                                 folia de s o jo o      <NA>                         vrios                                              foliadesojoo
18  100077                      franz lambert                          franz lambert spielt beliebte evergreens      1977                  franzlambert                      franzlambertspieltbeliebteevergreens
19  100078  leon siu and david kawika kahiapo                                                  slack key praise      <NA>  leonsiuanddavidkawikakahiapo                                            slackkeypraise

         curation_route
0   standard_enrichment
1   standard_enrichment
2   standard_enrichment
3   standard_enrichment
4   standard_enrichment
5   standard_enrichment
6   standard_enrichment
7   standard_enrichment
8   standard_enrichment
9   standard_enrichment
10  standard_enrichment
11  standard_enrichment
12  standard_enrichment
13  standard_enrichment
14  standard_enrichment
15  standard_enrichment
16  standard_enrichment
17  standard_enrichment
18  standard_enrichment
19  standard_enrichment

In [352]:
import duckdb
import pandas as pd

# Connect
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Candidate pairs for the main curated enrichment subset
# ------------------------------------------------------------
# Comments:
# - Uses cleaned CDS keys from cds_unmatched_curated_main_v1
# - Matches against the cleaned MusicBrainz pool
# - Blocking:
#     * same first artist letter
#     * same first title letter
#     * similar artist/title key lengths
print("Creating cds_mb_curated_main_pairs_v1...")

con.execute("""
    CREATE OR REPLACE TABLE cds_mb_curated_main_pairs_v1 AS
    SELECT
        c.cds_id,
        c.artist,
        c.title,
        c.cds_year,
        c.tracks,
        c.curation_route,

        c.artist_key_clean AS cds_artist_key,
        c.title_key_clean  AS cds_title_key,

        m.release_id,
        m.main_artist_name,
        m.release_title,
        m.artist_credit_full,
        m.total_tracks,
        m.barcode,
        m.mb_year,
        m.artist_key_clean AS mb_artist_key,
        m.title_key_clean  AS mb_title_key

    FROM (
        SELECT
            *,
            substr(artist_key_clean, 1, 1) AS artist_first,
            substr(title_key_clean,  1, 1) AS title_first,
            length(artist_key_clean) AS artist_len,
            length(title_key_clean)  AS title_len
        FROM cds_unmatched_curated_main_v1
        WHERE
            artist_key_clean IS NOT NULL
            AND title_key_clean IS NOT NULL
            AND length(artist_key_clean) >= 4
            AND length(title_key_clean)  >= 4
    ) c

    JOIN mb_candidate_pool_v2 m
      ON m.artist_first = c.artist_first
     AND m.title_first  = c.title_first
     AND m.artist_len BETWEEN c.artist_len - 3 AND c.artist_len + 3
     AND m.title_len  BETWEEN c.title_len  - 5 AND c.title_len  + 5
""")

print("✅ Table created: cds_mb_curated_main_pairs_v1")

print("\n--- Pair count for curated main subset ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM cds_mb_curated_main_pairs_v1
""").fetchdf())

print("\n--- Distinct CDS rows with candidate pairs ---")
print(con.execute("""
    SELECT COUNT(DISTINCT cds_id) AS cds_rows_with_candidates
    FROM cds_mb_curated_main_pairs_v1
""").fetchdf())

print("\n--- Preview: curated main candidate pairs ---")
print(con.execute("""
    SELECT
        cds_id, artist, title,
        release_id, main_artist_name, release_title,
        cds_year, mb_year, total_tracks, barcode
    FROM cds_mb_curated_main_pairs_v1
    LIMIT 20
""").fetchdf())

Connected ✅
Creating cds_mb_curated_main_pairs_v1...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

✅ Table created: cds_mb_curated_main_pairs_v1

--- Pair count for curated main subset ---
         n
0  8725533

--- Distinct CDS rows with candidate pairs ---
   cds_rows_with_candidates
0                      3206

--- Preview: curated main candidate pairs ---
    cds_id                artist                         title  release_id   main_artist_name             release_title  cds_year  mb_year  total_tracks        barcode
0   108372                 thebe                        mokone     3649233          The BREED              Making a Way      2002     2022           1.0   745051303228
1   108488      mofunk colective              fresh jazz vibes     3649237   Maynard Ferguson   Live From San Francisco      1995     2022           7.0   081971807720
2   103432      ben zion shekner          v lirusholayim ircho     2918800  Bruce Springsteen          VH1 Storytellers      2003     2023          21.0  0828767352992
3   108798              schubert                     lieder 31     3649218       SIERRA VEINS               Last Breath      <NA>     2023           1.0           None
4   107307           tina turner         las leyendas del rock     2986398         Terrenoire     Les Forces contraires      <NA>     2023          10.0   602507302627
5   108372                 thebe                        mokone     3649265           Toonorth                  Monolith      2002     2022           1.0   745051302719
6     9793            pink floyd                      pulse 2      3649266         Party Rice                Powerdeath      1995     2022           5.0           None
7   109678              pokã mon                   2b a master     3649264         Party Rice                 2022 Demo      <NA>     2022           2.0           None
8     1823        carlos santana                        carlos     3642967     Culver-Courtis                      CCII      <NA>     2022           4.0
9   109549           radio osaka                      solarize     3724725         Reasonandu                    Shanxi      <NA>     2023          10.0  5054285396322
10  109758              nintendo         nintendo 64 cool cuts     3643300          NEXTLIGHT   NX STARS EXPANSION CARD      1996     2022           4.0           None
11  108993  sverrir guã jã³nsson                       epitaph     3764411   Secos & Molhados              & Etc. & Etc      1998     2023           6.0   859746168259
12  109249           eric coates                four centuries     3791610           Enslaved            Forest Dweller      1993     2023           4.0  4065629679460
13   11190        varius artists          mozart greatest hits     3639979    Various Artists            Musica Barocca      <NA>     2022          20.0   825646480913
14  106096             i dik dik             i grandi successi     3642781           irucaice        iceQuarium -Lemon-      1995     2025          10.0           None
15  106096             i dik dik             i grandi successi     3642783           irucaice   iceQuarium -Melon Soda-      1995     2022          10.0           None
16  109513    franz joseph haydn  symphonien nr 84 85 hob 1 21     3649278     Franz Schubert  Schubert: Symphonies 5+8      1998     2022           6.0           None
17  104270             kreftwerk                    frã¼hwerke     3642995         Klein Zage              Feed the Dog      <NA>     2022           9.0  4062548041903
18  103408               no name           pockam si na zazrak     3644896              NOISY           Put a Record On      <NA>     2022           1.0   602508956799
19  109549           radio osaka                      solarize     3724727         Reasonandu                    Shanxi      <NA>     2023          10.0           None

In [353]:
import duckdb

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

print(con.execute("""
    SELECT table_name
    FROM information_schema.tables
    WHERE lower(table_name) LIKE '%artist%'
       OR lower(table_name) LIKE '%alias%'
    ORDER BY table_name
""").fetchdf())

Connected ✅
                                            table_name
0                         cds_alias_enrichment_auto_v1
1                  cds_alias_enrichment_auto_v2_review
2                    cds_alias_enrichment_auto_v2_safe
3                  cds_alias_enrichment_auto_v3_review
4                    cds_alias_enrichment_auto_v3_safe
5                       cds_alias_enrichment_ranked_v1
6                    cds_artist_alias_bridge_unique_v1
7                           cds_artist_alias_bridge_v1
8   cds_artist_resolved_release_candidates_filtered_v1
9            cds_artist_resolved_release_candidates_v1
10                                           mb_artist
11                                     mb_artist_alias
12                                 mb_artist_alias_raw
13                               mb_artist_credit_core
14            mb_artist_credit_for_resolved_artists_v1
15                               mb_artist_credit_name
16                                mb_artist_credit_raw
17                            mb_artist_name_lookup_v1
18           mb_artist_release_for_resolved_artists_v1

In [62]:
import duckdb

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

print(con.execute("""
    PRAGMA table_info('mb_artist')
""").fetchdf())

Connected ✅
    cid              name       type  notnull dflt_value     pk
0     0                id    INTEGER    False       None  False
1     1               gid    VARCHAR    False       None  False
2     2              name    VARCHAR    False       None  False
3     3         sort_name    VARCHAR    False       None  False
4     4   begin_date_year    INTEGER    False       None  False
5     5  begin_date_month    INTEGER    False       None  False
6     6    begin_date_day    INTEGER    False       None  False
7     7     end_date_year    INTEGER    False       None  False
8     8    end_date_month    INTEGER    False       None  False
9     9      end_date_day    INTEGER    False       None  False
10   10              type    INTEGER    False       None  False
11   11              area    INTEGER    False       None  False
12   12            gender    INTEGER    False       None  False
13   13           comment    VARCHAR    False       None  False
14   14     edits_pending    INTEGER    False       None  False
15   15      last_updated  TIMESTAMP    False       None  False
16   16             ended    BOOLEAN    False       None  False
17   17        begin_area    INTEGER    False       None  False
18   18          end_area    INTEGER    False       None  False

In [63]:
import duckdb

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

print(con.execute("""
    PRAGMA table_info('mb_artist')
""").fetchdf())

Connected ✅
    cid              name       type  notnull dflt_value     pk
0     0                id    INTEGER    False       None  False
1     1               gid    VARCHAR    False       None  False
2     2              name    VARCHAR    False       None  False
3     3         sort_name    VARCHAR    False       None  False
4     4   begin_date_year    INTEGER    False       None  False
5     5  begin_date_month    INTEGER    False       None  False
6     6    begin_date_day    INTEGER    False       None  False
7     7     end_date_year    INTEGER    False       None  False
8     8    end_date_month    INTEGER    False       None  False
9     9      end_date_day    INTEGER    False       None  False
10   10              type    INTEGER    False       None  False
11   11              area    INTEGER    False       None  False
12   12            gender    INTEGER    False       None  False
13   13           comment    VARCHAR    False       None  False
14   14     edits_pending    INTEGER    False       None  False
15   15      last_updated  TIMESTAMP    False       None  False
16   16             ended    BOOLEAN    False       None  False
17   17        begin_area    INTEGER    False       None  False
18   18          end_area    INTEGER    False       None  False

In [354]:
import duckdb

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

artist_alias_path = "../data_raw/musicbrainz/mbdump/mbdump/artist_alias"

print("Importing artist_alias...")

con.execute(f"""
    CREATE OR REPLACE TABLE mb_artist_alias_raw AS
    SELECT *
    FROM read_csv_auto(
        '{artist_alias_path}',
        delim = '\t',
        header = false,
        null_padding = true,
        ignore_errors = true,
        strict_mode = false
    )
""")

print("✅ Table created: mb_artist_alias_raw")

print("\n--- Schema: mb_artist_alias_raw ---")
print(con.execute("""
    PRAGMA table_info('mb_artist_alias_raw')
""").fetchdf())

print("\n--- Preview: mb_artist_alias_raw ---")
print(con.execute("""
    SELECT *
    FROM mb_artist_alias_raw
    LIMIT 10
""").fetchdf())

Connected ✅
Importing artist_alias...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

✅ Table created: mb_artist_alias_raw

--- Schema: mb_artist_alias_raw ---
    cid      name     type  notnull dflt_value     pk
0     0  column00   BIGINT    False       None  False
1     1  column01   BIGINT    False       None  False
2     2  column02  VARCHAR    False       None  False
3     3  column03  VARCHAR    False       None  False
4     4  column04  VARCHAR    False       None  False
5     5  column05  VARCHAR    False       None  False
6     6  column06  VARCHAR    False       None  False
7     7  column07  VARCHAR    False       None  False
8     8  column08  VARCHAR    False       None  False
9     9  column09  VARCHAR    False       None  False
10   10  column10  VARCHAR    False       None  False
11   11  column11  VARCHAR    False       None  False
12   12  column12  VARCHAR    False       None  False
13   13  column13  VARCHAR    False       None  False
14   14  column14  BOOLEAN    False       None  False
15   15  column15  BOOLEAN    False       None  False

--- Preview: mb_artist_alias_raw ---
   column00  column01                  column02 column03 column04                       column05 column06                  column07 column08 column09 column10 column11 column12 column13  column14  column15
0    125531    932664              Jared Kotler    en_US        0  2012-10-22 21:00:20.526211+00        2             Kotler, Jared       \N       \N       \N       \N       \N       \N      True     False
1    503290    157784              Kwanza Posse       \N        0  2025-04-22 12:00:13.599079+00       \N              Kwanza Posse       \N       \N       \N       \N       \N       \N     False     False
2    125438    586849     Abraham Gilbert Stein       \N        0   2012-10-06 00:39:38.38725+00        2    Stein, Abraham Gilbert       \N       \N       \N       \N       \N       \N     False     False
3    119415    651985  Harry Deal & The Galaxis       \N        0  2012-05-16 03:08:12.665011+00       \N  Harry Deal & The Galaxis       \N       \N       \N       \N       \N       \N     False     False
4    463769   2425601               Thomas Cech       \N        0  2024-05-13 20:37:25.808572+00        2              Cech, Thomas       \N       \N       \N       \N       \N       \N     False     False
5    119418     68858                Deepac Ram       \N        0  2012-05-16 04:08:19.030152+00       \N                Deepac Ram       \N       \N       \N       \N       \N       \N     False     False
6    119419    253545             Pops Mohammed       \N        0  2012-05-16 04:08:22.024552+00       \N             Pops Mohammed       \N       \N       \N       \N       \N       \N     False     False
7    119746    696487         Christian Murariu       \N        0  2012-05-26 02:54:27.031197+00        2        Murariu, Christian       \N       \N       \N       \N       \N       \N     False     False
8    125454    932111               Dina Vierny       \N        0  2012-10-20 15:00:07.559042+00       \N                    Vierny       \N       \N       \N       \N       \N       \N     False     False
9    125529    124494             Casting Crows       \N        0  2012-10-08 20:00:15.083749+00       \N             Casting Crows       \N       \N       \N       \N       \N       \N     False     False

In [355]:
import duckdb
import pandas as pd

# Connect to DuckDB
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Clean and rename the raw MusicBrainz artist_alias table
# ------------------------------------------------------------
# Comments:
# - The raw MusicBrainz dump has no headers.
# - It uses '\N' for NULL values.
# - Boolean fields are stored as t / f / \N, so we map them manually.
# - We also create normalized alias keys for later matching.
print("Creating cleaned MusicBrainz artist alias table...")

con.execute(r"""
    CREATE OR REPLACE TABLE mb_artist_alias AS
    SELECT
        CAST(column00 AS BIGINT) AS alias_id,
        CAST(column01 AS BIGINT) AS artist_id,

        CASE WHEN column02 = '\N' THEN NULL ELSE column02 END AS alias_name,
        CASE WHEN column03 = '\N' THEN NULL ELSE column03 END AS locale,
        TRY_CAST(CASE WHEN column04 = '\N' THEN NULL ELSE column04 END AS INTEGER) AS edits_pending,
        TRY_CAST(CASE WHEN column05 = '\N' THEN NULL ELSE column05 END AS TIMESTAMP) AS last_updated,
        TRY_CAST(CASE WHEN column06 = '\N' THEN NULL ELSE column06 END AS INTEGER) AS alias_type_id,
        CASE WHEN column07 = '\N' THEN NULL ELSE column07 END AS alias_sort_name,

        TRY_CAST(CASE WHEN column08 = '\N' THEN NULL ELSE column08 END AS INTEGER) AS begin_date_year,
        TRY_CAST(CASE WHEN column09 = '\N' THEN NULL ELSE column09 END AS INTEGER) AS begin_date_month,
        TRY_CAST(CASE WHEN column10 = '\N' THEN NULL ELSE column10 END AS INTEGER) AS begin_date_day,
        TRY_CAST(CASE WHEN column11 = '\N' THEN NULL ELSE column11 END AS INTEGER) AS end_date_year,
        TRY_CAST(CASE WHEN column12 = '\N' THEN NULL ELSE column12 END AS INTEGER) AS end_date_month,
        TRY_CAST(CASE WHEN column13 = '\N' THEN NULL ELSE column13 END AS INTEGER) AS end_date_day,

        CASE
            WHEN column14 IN ('t', 'true', '1') THEN TRUE
            WHEN column14 IN ('f', 'false', '0') THEN FALSE
            ELSE NULL
        END AS primary_for_locale,

        CASE
            WHEN column15 IN ('t', 'true', '1') THEN TRUE
            WHEN column15 IN ('f', 'false', '0') THEN FALSE
            ELSE NULL
        END AS ended,

        -- ----------------------------------------------------
        -- Normalized keys for artist alias matching
        -- ----------------------------------------------------
        lower(
            regexp_replace(
                coalesce(CASE WHEN column02 = '\N' THEN NULL ELSE column02 END, ''),
                '[^a-zA-Z0-9]+', '', 'g'
            )
        ) AS alias_name_key,

        lower(
            regexp_replace(
                coalesce(CASE WHEN column07 = '\N' THEN NULL ELSE column07 END, ''),
                '[^a-zA-Z0-9]+', '', 'g'
            )
        ) AS alias_sort_name_key

    FROM mb_artist_alias_raw
""")

print("✅ Table created: mb_artist_alias")

print("\n--- Schema: mb_artist_alias ---")
print(con.execute("""
    PRAGMA table_info('mb_artist_alias')
""").fetchdf())

print("\n--- Preview: cleaned artist aliases ---")
print(con.execute("""
    SELECT
        alias_id,
        artist_id,
        alias_name,
        locale,
        alias_type_id,
        alias_sort_name,
        primary_for_locale,
        ended,
        alias_name_key,
        alias_sort_name_key
    FROM mb_artist_alias
    LIMIT 20
""").fetchdf())

print("\n--- Basic counts ---")
print(con.execute("""
    SELECT
        COUNT(*) AS total_alias_rows,
        COUNT(DISTINCT artist_id) AS distinct_artists_with_aliases,
        COUNT(*) FILTER (WHERE alias_name IS NOT NULL) AS alias_name_present,
        COUNT(*) FILTER (WHERE primary_for_locale = TRUE) AS primary_locale_aliases
    FROM mb_artist_alias
""").fetchdf())

Connected ✅
Creating cleaned MusicBrainz artist alias table...
✅ Table created: mb_artist_alias

--- Schema: mb_artist_alias ---
    cid                 name       type  notnull dflt_value     pk
0     0             alias_id     BIGINT    False       None  False
1     1            artist_id     BIGINT    False       None  False
2     2           alias_name    VARCHAR    False       None  False
3     3               locale    VARCHAR    False       None  False
4     4        edits_pending    INTEGER    False       None  False
5     5         last_updated  TIMESTAMP    False       None  False
6     6        alias_type_id    INTEGER    False       None  False
7     7      alias_sort_name    VARCHAR    False       None  False
8     8      begin_date_year    INTEGER    False       None  False
9     9     begin_date_month    INTEGER    False       None  False
10   10       begin_date_day    INTEGER    False       None  False
11   11        end_date_year    INTEGER    False       None  False
12   12       end_date_month    INTEGER    False       None  False
13   13         end_date_day    INTEGER    False       None  False
14   14   primary_for_locale    BOOLEAN    False       None  False
15   15                ended    BOOLEAN    False       None  False
16   16       alias_name_key    VARCHAR    False       None  False
17   17  alias_sort_name_key    VARCHAR    False       None  False

--- Preview: cleaned artist aliases ---
    alias_id  artist_id                      alias_name locale  alias_type_id                 alias_sort_name  primary_for_locale  ended              alias_name_key         alias_sort_name_key
0     125531     932664                    Jared Kotler  en_US              2                   Kotler, Jared                True  False                 jaredkotler                 kotlerjared
1     503290     157784                    Kwanza Posse   None           <NA>                    Kwanza Posse               False  False                 kwanzaposse                 kwanzaposse
2     125438     586849           Abraham Gilbert Stein   None              2          Stein, Abraham Gilbert               False  False         abrahamgilbertstein         steinabrahamgilbert
3     119415     651985        Harry Deal & The Galaxis   None           <NA>        Harry Deal & The Galaxis               False  False         harrydealthegalaxis         harrydealthegalaxis
4     463769    2425601                     Thomas Cech   None              2                    Cech, Thomas               False  False                  thomascech                  cechthomas
5     119418      68858                      Deepac Ram   None           <NA>                      Deepac Ram               False  False                   deepacram                   deepacram
6     119419     253545                   Pops Mohammed   None           <NA>                   Pops Mohammed               False  False                popsmohammed                popsmohammed
7     119746     696487               Christian Murariu   None              2              Murariu, Christian               False  False            christianmurariu            murariuchristian
8     125454     932111                     Dina Vierny   None           <NA>                          Vierny               False  False                  dinavierny                      vierny
9     125529     124494                   Casting Crows   None           <NA>                   Casting Crows               False  False                castingcrows                castingcrows
10    119759     486739  The Illinois Jacquet All Stars   None           <NA>  The Illinois Jacquet All Stars               False  False  theillinoisjacquetallstars  theillinoisjacquetallstars
11    125439     623118    Konstantinos Jorma Hiekkanen   None              2   Hiekkanen, Konstantinos Jorma               False  False  konstantinosjormahiekkanen  hiekkanenkonstantinosjorma
12    125450     171033                Juhani Saksikäsi   None           <NA>                Juhani Saksikäsi               False  False              juhanisaksiksi              juhanisaksiksi
13    125451     844017                  Kadel & Finger   None           <NA>                  Kadel & Finger               False  False                 kadelfinger                 kadelfinger
14    210228      99554                 Dora Carofiglio   None              2                Carofiglio, Dora               False  False              doracarofiglio              carofigliodora
15    119413     892848                Lorita Delacerna   None              3                Lorita Delacerna               False  False             loritadelacerna             loritadelacerna
16    125453     910308                            YDKM   None           <NA>                            YDKM               False  False                        ydkm                        ydkm
17     47521     115967                     Herman Dune   None              1                     Herman Dune               False  False                  hermandune                  hermandune
18    119747     135222                    Wayman Henry   None              2                   Henry, Wayman               False  False                 waymanhenry                 henrywayman
19    119748     135222                    Waymon Henry   None              2                   Henry, Waymon               False  False                 waymonhenry                 henrywaymon

--- Basic counts ---
   total_alias_rows  distinct_artists_with_aliases  alias_name_present  primary_locale_aliases
0            497697                         287930              497697                   56294

In [356]:
import duckdb
import pandas as pd

# Connect to DuckDB
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Build a unified MusicBrainz artist name lookup
# ------------------------------------------------------------
# Comments:
# - We combine canonical MB artist names with MB artist aliases.
# - This creates a richer lookup source for artist-side resolution.
# - Later, CDS artist strings can be matched against:
#     * canonical artist names
#     * canonical sort names
#     * alias names
#     * alias sort names
print("Creating mb_artist_name_lookup_v1...")

con.execute(r"""
    CREATE OR REPLACE TABLE mb_artist_name_lookup_v1 AS

    -- --------------------------------------------------------
    -- Canonical artist name from mb_artist.name
    -- --------------------------------------------------------
    SELECT
        a.id AS artist_id,
        a.gid AS artist_gid,
        a.name AS artist_display_name,
        a.sort_name AS artist_sort_name,

        a.name AS lookup_name,
        'canonical_name' AS lookup_source,
        lower(regexp_replace(coalesce(a.name, ''), '[^a-zA-Z0-9]+', '', 'g')) AS lookup_name_key,
        NULL::VARCHAR AS locale,
        NULL::INTEGER AS alias_type_id,
        NULL::BOOLEAN AS primary_for_locale

    FROM mb_artist a
    WHERE a.name IS NOT NULL

    UNION ALL

    -- --------------------------------------------------------
    -- Canonical sort_name from mb_artist.sort_name
    -- --------------------------------------------------------
    SELECT
        a.id AS artist_id,
        a.gid AS artist_gid,
        a.name AS artist_display_name,
        a.sort_name AS artist_sort_name,

        a.sort_name AS lookup_name,
        'canonical_sort_name' AS lookup_source,
        lower(regexp_replace(coalesce(a.sort_name, ''), '[^a-zA-Z0-9]+', '', 'g')) AS lookup_name_key,
        NULL::VARCHAR AS locale,
        NULL::INTEGER AS alias_type_id,
        NULL::BOOLEAN AS primary_for_locale

    FROM mb_artist a
    WHERE a.sort_name IS NOT NULL

    UNION ALL

    -- --------------------------------------------------------
    -- Alias name from mb_artist_alias.alias_name
    -- --------------------------------------------------------
    SELECT
        a.id AS artist_id,
        a.gid AS artist_gid,
        a.name AS artist_display_name,
        a.sort_name AS artist_sort_name,

        aa.alias_name AS lookup_name,
        'alias_name' AS lookup_source,
        aa.alias_name_key AS lookup_name_key,
        aa.locale,
        aa.alias_type_id,
        aa.primary_for_locale

    FROM mb_artist_alias aa
    JOIN mb_artist a
      ON a.id = aa.artist_id
    WHERE aa.alias_name IS NOT NULL

    UNION ALL

    -- --------------------------------------------------------
    -- Alias sort_name from mb_artist_alias.alias_sort_name
    -- --------------------------------------------------------
    SELECT
        a.id AS artist_id,
        a.gid AS artist_gid,
        a.name AS artist_display_name,
        a.sort_name AS artist_sort_name,

        aa.alias_sort_name AS lookup_name,
        'alias_sort_name' AS lookup_source,
        aa.alias_sort_name_key AS lookup_name_key,
        aa.locale,
        aa.alias_type_id,
        aa.primary_for_locale

    FROM mb_artist_alias aa
    JOIN mb_artist a
      ON a.id = aa.artist_id
    WHERE aa.alias_sort_name IS NOT NULL
""")

print("✅ Table created: mb_artist_name_lookup_v1")

print("\n--- Lookup source breakdown ---")
print(con.execute("""
    SELECT lookup_source, COUNT(*) AS n
    FROM mb_artist_name_lookup_v1
    GROUP BY lookup_source
    ORDER BY n DESC
""").fetchdf())

print("\n--- Distinct artists represented in lookup ---")
print(con.execute("""
    SELECT COUNT(DISTINCT artist_id) AS distinct_artists
    FROM mb_artist_name_lookup_v1
""").fetchdf())

print("\n--- Preview: artist lookup table ---")
print(con.execute("""
    SELECT
        artist_id,
        artist_display_name,
        artist_sort_name,
        lookup_name,
        lookup_source,
        lookup_name_key,
        locale,
        alias_type_id,
        primary_for_locale
    FROM mb_artist_name_lookup_v1
    LIMIT 25
""").fetchdf())

Connected ✅
Creating mb_artist_name_lookup_v1...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

✅ Table created: mb_artist_name_lookup_v1

--- Lookup source breakdown ---
         lookup_source        n
0       canonical_name  2807098
1  canonical_sort_name  2807098
2           alias_name   497697
3      alias_sort_name   497668

--- Distinct artists represented in lookup ---
   distinct_artists
0           2807098

--- Preview: artist lookup table ---
    artist_id       artist_display_name            artist_sort_name               lookup_name   lookup_source         lookup_name_key locale  alias_type_id  primary_for_locale
0     1214795              Radek Kašpar               Kašpar, Radek              Radek Kašpar  canonical_name              radekkapar   None           <NA>                <NA>
1     1819567        Oracle da Goldsmif         Goldsmif, Oracle da        Oracle da Goldsmif  canonical_name        oracledagoldsmif   None           <NA>                <NA>
2     1215271               Kari Jerkku                 Kari Jerkku               Kari Jerkku  canonical_name              karijerkku   None           <NA>                <NA>
3     1215456                 Silo Halo                  Halo, Silo                 Silo Halo  canonical_name                silohalo   None           <NA>                <NA>
4     1215532          Drowning Kittens            Drowning Kittens          Drowning Kittens  canonical_name         drowningkittens   None           <NA>                <NA>
5     1215809              Ltd. Express                Ltd. Express              Ltd. Express  canonical_name              ltdexpress   None           <NA>                <NA>
6      530021                      河内淳貴             Kawauchi, Junki                      河内淳貴  canonical_name                           None           <NA>                <NA>
7     1215126           Vintage Thieves             Vintage Thieves           Vintage Thieves  canonical_name          vintagethieves   None           <NA>                <NA>
8     1215946        Snyder Family Band          Snyder Family Band        Snyder Family Band  canonical_name        snyderfamilyband   None           <NA>                <NA>
9     1215873  Michael Waldrop Big Band  Waldrop, Michael, Big Band  Michael Waldrop Big Band  canonical_name   michaelwaldropbigband   None           <NA>                <NA>
10    1219883                       Bhj                         Bhj                       Bhj  canonical_name                     bhj   None           <NA>                <NA>
11    1219891                    C.M.C.                      C.M.C.                    C.M.C.  canonical_name                     cmc   None           <NA>                <NA>
12     522373            Bernard Wisson             Wisson, Bernard            Bernard Wisson  canonical_name           bernardwisson   None           <NA>                <NA>
13    1223961           Jeanne Héricard            Héricard, Jeanne           Jeanne Héricard  canonical_name           jeannehricard   None           <NA>                <NA>
14    1225066                 Reno Jack                  Jack, Reno                 Reno Jack  canonical_name                renojack   None           <NA>                <NA>
15    1225088               Carlo Ditta                Ditta, Carlo               Carlo Ditta  canonical_name              carloditta   None           <NA>                <NA>
16    1226473              Tommy Flyguy                Tommy Flyguy              Tommy Flyguy  canonical_name             tommyflyguy   None           <NA>                <NA>
17    1226503           Peter Schaumann            Schaumann, Peter           Peter Schaumann  canonical_name          peterschaumann   None           <NA>                <NA>
18    1204729                      友田真吾              Tomoda, Shingo                      友田真吾  canonical_name                           None           <NA>                <NA>
19    1229363             Bruit fantôme               Bruit fantôme             Bruit fantôme  canonical_name             bruitfantme   None           <NA>                <NA>
20    1113929  Haifa Symphony Orchestra    Haifa Symphony Orchestra  Haifa Symphony Orchestra  canonical_name  haifasymphonyorchestra   None           <NA>                <NA>
21    1232000                Mark Evans                 Evans, Mark                Mark Evans  canonical_name               markevans   None           <NA>                <NA>
22    1232971       Mom Bloggers United         Mom Bloggers United       Mom Bloggers United  canonical_name       mombloggersunited   None           <NA>                <NA>
23      83884             Brand New Sin               Brand New Sin             Brand New Sin  canonical_name             brandnewsin   None           <NA>                <NA>
24    1197329               Spokensword                 Spokensword               Spokensword  canonical_name             spokensword   None           <NA>                <NA>

In [357]:
import duckdb
import pandas as pd

# Connect to DuckDB
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Alias-assisted CDS artist resolution
# ------------------------------------------------------------
# Comments:
# - We use the curated unmatched CDS subset from v6.
# - We try to resolve CDS artist strings against:
#     * canonical MB artist names
#     * canonical MB sort names
#     * alias names
#     * alias sort names
# - This step only resolves ARTIST identity.
# - It does not yet decide the final MB release match.
print("Creating cds_artist_alias_bridge_v1...")

con.execute("""
    CREATE OR REPLACE TABLE cds_artist_alias_bridge_v1 AS
    SELECT
        c.cds_id,
        c.artist,
        c.title,
        c.cds_year,
        c.curation_route,
        c.enrichment_priority_v6,
        c.artist_key_clean,
        c.title_key_clean,

        l.artist_id,
        l.artist_gid,
        l.artist_display_name,
        l.artist_sort_name,
        l.lookup_name,
        l.lookup_source,
        l.locale,
        l.alias_type_id,
        l.primary_for_locale

    FROM cds_unmatched_curated_v1 c
    JOIN mb_artist_name_lookup_v1 l
      ON c.artist_key_clean = l.lookup_name_key
    WHERE c.artist_key_clean IS NOT NULL
      AND length(c.artist_key_clean) >= 4
""")

print("✅ Table created: cds_artist_alias_bridge_v1")

print("\n--- Total bridge rows ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM cds_artist_alias_bridge_v1
""").fetchdf())

print("\n--- Distinct CDS rows with artist resolution ---")
print(con.execute("""
    SELECT COUNT(DISTINCT cds_id) AS cds_rows_with_artist_match
    FROM cds_artist_alias_bridge_v1
""").fetchdf())

print("\n--- Lookup source breakdown ---")
print(con.execute("""
    SELECT lookup_source, COUNT(*) AS n
    FROM cds_artist_alias_bridge_v1
    GROUP BY lookup_source
    ORDER BY n DESC
""").fetchdf())

print("\n--- Preview: alias-assisted CDS artist bridge ---")
print(con.execute("""
    SELECT
        cds_id,
        artist,
        title,
        artist_key_clean,
        artist_id,
        artist_display_name,
        artist_sort_name,
        lookup_name,
        lookup_source,
        locale,
        primary_for_locale
    FROM cds_artist_alias_bridge_v1
    LIMIT 25
""").fetchdf())

Connected ✅
Creating cds_artist_alias_bridge_v1...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

✅ Table created: cds_artist_alias_bridge_v1

--- Total bridge rows ---
       n
0  26404

--- Distinct CDS rows with artist resolution ---
   cds_rows_with_artist_match
0                        3238

--- Lookup source breakdown ---
         lookup_source      n
0       canonical_name  10185
1  canonical_sort_name   9242
2      alias_sort_name   3565
3           alias_name   3412

--- Preview: alias-assisted CDS artist bridge ---
    cds_id      artist                                                        title artist_key_clean  artist_id artist_display_name artist_sort_name lookup_name   lookup_source locale  primary_for_locale
0   109759     various                                           warriors of virtue          various    3151913             Various          Various     Various  canonical_name   None                <NA>
1   105478  drew young                                             hide out with me        drewyoung    3152215          Drew Young      Young, Drew  Drew Young  canonical_name   None                <NA>
2   103004       ozone                                              premiere couche            ozone    3152999               Ozone            Ozone       Ozone  canonical_name   None                <NA>
3   109754     various                                            neighborhood vida          various    3151913             Various          Various     Various  canonical_name   None                <NA>
4   109750     various                                            notting hill ost           various    3151913             Various          Various     Various  canonical_name   None                <NA>
5   109747     various                           fablernas vã rld simma lungt del 1          various    3151913             Various          Various     Various  canonical_name   None                <NA>
6   109742     various     original film soundtracks the best of godzilla 1984 1995          various    3151913             Various          Various     Various  canonical_name   None                <NA>
7   109736     various                            sondheim a musical tribute disc 1          various    3151913             Various          Various     Various  canonical_name   None                <NA>
8   109735     various                                      sweet home alabama ost           various    3151913             Various          Various     Various  canonical_name   None                <NA>
9   109718     various                                                          pcu          various    3151913             Various          Various     Various  canonical_name   None                <NA>
10  109716     various                                 the best of movie hits vol 1          various    3151913             Various          Various     Various  canonical_name   None                <NA>
11  109714     various  ã ã ã ã³ã ã ã ã ã ã ã ã¼ ã ã ã ã ã ã ã ã²ã¼ã ã ã ã ã ã ã ã           various    3151913             Various          Various     Various  canonical_name   None                <NA>
12  109652     various                 grosse pointe blank more music from the film          various    3151913             Various          Various     Various  canonical_name   None                <NA>
13  109650     various                                  classic movie tracks vol 1           various    3151913             Various          Various     Various  canonical_name   None                <NA>
14  109649     various                                    spike co do it a cappella          various    3151913             Various          Various     Various  canonical_name   None                <NA>
15  109648     various                                          slc punk soundtrack          various    3151913             Various          Various     Various  canonical_name   None                <NA>
16  109636     various                                                  the apostle          various    3151913             Various          Various     Various  canonical_name   None                <NA>
17  109619     various                                   today s movie hits disc 2           various    3151913             Various          Various     Various  canonical_name   None                <NA>
18  109601     various                                       the rock matrix disc1           various    3151913             Various          Various     Various  canonical_name   None                <NA>
19  109564     various                                            the 12 best songs          various    3151913             Various          Various     Various  canonical_name   None                <NA>
20  109547     various                                   furious beat is teknp beat          various    3151913             Various          Various     Various  canonical_name   None                <NA>
21  109544     various                                          pyaar ishq mohabbat          various    3151913             Various          Various     Various  canonical_name   None                <NA>
22  109528     various                                                     la haine          various    3151913             Various          Various     Various  canonical_name   None                <NA>
23  109525     various                                              dangerous minds          various    3151913             Various          Various     Various  canonical_name   None                <NA>
24  109524     various                                                        duets          various    3151913             Various          Various     Various  canonical_name   None                <NA>

In [ ]:
import duckdb
import pandas as pd

# Connect to DuckDB
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Build artist-resolved release candidates
# ------------------------------------------------------------
# Comments:
# - We already resolved CDS artist strings to candidate MB artists
#   using canonical names + alias names.
# - Now we expand each resolved MB artist to candidate releases.
# - We do this through:
#     mb_artist_credit_name  -> links artist to artist_credit
#     mb_release_features    -> links artist_credit_id to releases
# - Important fix:
#     mb_release_features uses artist_credit_id, not artist_credit.
print("Creating cds_artist_resolved_release_candidates_v1...")

con.execute("""
    CREATE OR REPLACE TABLE cds_artist_resolved_release_candidates_v1 AS
    SELECT DISTINCT
        b.cds_id,
        b.artist,
        b.title,
        b.cds_year,
        b.curation_route,
        b.enrichment_priority_v6,
        b.artist_key_clean,
        b.title_key_clean,

        b.artist_id,
        b.artist_gid,
        b.artist_display_name,
        b.artist_sort_name,
        b.lookup_name,
        b.lookup_source,
        b.locale,
        b.alias_type_id,
        b.primary_for_locale,

        r.release_id,
        r.release_title,
        r.main_artist_name,
        r.artist_credit_full,
        r.artist_credit_id,
        r.total_tracks,
        r.barcode,
        r.mb_year

    FROM cds_artist_alias_bridge_v1 b
    JOIN mb_artist_credit_name acn
      ON acn.artist = b.artist_id
    JOIN mb_release_features r
      ON r.artist_credit_id = acn.artist_credit
""")

print("✅ Table created: cds_artist_resolved_release_candidates_v1")

print("\n--- Total candidate rows ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM cds_artist_resolved_release_candidates_v1
""").fetchdf())

print("\n--- Distinct CDS rows with release candidates ---")
print(con.execute("""
    SELECT COUNT(DISTINCT cds_id) AS cds_rows_with_release_candidates
    FROM cds_artist_resolved_release_candidates_v1
""").fetchdf())

print("\n--- Lookup source breakdown inside release candidates ---")
print(con.execute("""
    SELECT lookup_source, COUNT(*) AS n
    FROM cds_artist_resolved_release_candidates_v1
    GROUP BY lookup_source
    ORDER BY n DESC
""").fetchdf())

print("\n--- Preview: artist-resolved release candidates ---")
print(con.execute("""
    SELECT
        cds_id,
        artist,
        title,
        artist_display_name,
        lookup_name,
        lookup_source,
        release_id,
        main_artist_name,
        release_title,
        mb_year,
        total_tracks,
        barcode
    FROM cds_artist_resolved_release_candidates_v1
    LIMIT 25
""").fetchdf())

Connected ✅
Creating cds_artist_resolved_release_candidates_v1...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [7]:
import duckdb
import pandas as pd

# Connect to DuckDB
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Memory-safe settings
# ------------------------------------------------------------
# Comments:
# - Fewer threads usually reduce peak memory.
# - Turning off insertion-order preservation can reduce overhead.
# - A temp directory lets DuckDB spill intermediate data to disk.
# - memory_limit should stay conservative to avoid crashes.
print("Applying DuckDB memory-safe settings...")

con.execute("SET threads = 2")
con.execute("SET preserve_insertion_order = false")
con.execute("PRAGMA memory_limit='8GB'")

print("✅ Settings applied")

# ------------------------------------------------------------
# Step 1: Deduplicate CDS x artist_id pairs
# ------------------------------------------------------------
# Comments:
# - The alias bridge may contain multiple rows for the same cds_id + artist_id
#   because the same artist can be reached via canonical name, sort name, alias, etc.
# - We keep only the best lookup source per cds_id + artist_id.
print("\nCreating cds_artist_alias_bridge_unique_v1...")

con.execute("""
    CREATE OR REPLACE TABLE cds_artist_alias_bridge_unique_v1 AS
    WITH ranked AS (
        SELECT
            *,
            row_number() OVER (
                PARTITION BY cds_id, artist_id
                ORDER BY
                    CASE lookup_source
                        WHEN 'canonical_name' THEN 1
                        WHEN 'alias_name' THEN 2
                        WHEN 'canonical_sort_name' THEN 3
                        WHEN 'alias_sort_name' THEN 4
                        ELSE 5
                    END,
                    CASE WHEN primary_for_locale = TRUE THEN 0 ELSE 1 END,
                    alias_type_id ASC NULLS LAST
            ) AS rn
        FROM cds_artist_alias_bridge_v1
    )
    SELECT
        cds_id,
        artist,
        title,
        cds_year,
        curation_route,
        enrichment_priority_v6,
        artist_key_clean,
        title_key_clean,
        artist_id,
        artist_gid,
        artist_display_name,
        artist_sort_name,
        lookup_name,
        lookup_source,
        locale,
        alias_type_id,
        primary_for_locale
    FROM ranked
    WHERE rn = 1
""")

print("✅ Table created: cds_artist_alias_bridge_unique_v1")

print("\n--- Unique CDS x artist pairs ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM cds_artist_alias_bridge_unique_v1
""").fetchdf())

# ------------------------------------------------------------
# Step 2: Build reduced artist-credit map only for resolved artists
# ------------------------------------------------------------
# Comments:
# - This reduces mb_artist_credit_name to only the artist IDs we actually need.
print("\nCreating mb_artist_credit_for_resolved_artists_v1...")

con.execute("""
    CREATE OR REPLACE TABLE mb_artist_credit_for_resolved_artists_v1 AS
    SELECT DISTINCT
        acn.artist,
        acn.artist_credit
    FROM mb_artist_credit_name acn
    JOIN (
        SELECT DISTINCT artist_id
        FROM cds_artist_alias_bridge_unique_v1
    ) x
      ON acn.artist = x.artist_id
""")

print("✅ Table created: mb_artist_credit_for_resolved_artists_v1")

print("\n--- Artist-credit links for resolved artists ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM mb_artist_credit_for_resolved_artists_v1
""").fetchdf())

# ------------------------------------------------------------
# Step 3: Build reduced artist-to-release map first
# ------------------------------------------------------------
# Comments:
# - This is much smaller than joining the full bridge directly to releases.
# - We materialize only artist -> release links for already-resolved artists.
print("\nCreating mb_artist_release_for_resolved_artists_v1...")

con.execute("""
    CREATE OR REPLACE TABLE mb_artist_release_for_resolved_artists_v1 AS
    SELECT DISTINCT
        ac.artist,
        r.release_id,
        r.release_title,
        r.main_artist_name,
        r.artist_credit_full,
        r.artist_credit_id,
        r.total_tracks,
        r.barcode,
        r.mb_year
    FROM mb_artist_credit_for_resolved_artists_v1 ac
    JOIN mb_release_features r
      ON r.artist_credit_id = ac.artist_credit
""")

print("✅ Table created: mb_artist_release_for_resolved_artists_v1")

print("\n--- Reduced artist-release rows ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM mb_artist_release_for_resolved_artists_v1
""").fetchdf())

# ------------------------------------------------------------
# Step 4: Create empty final candidate table
# ------------------------------------------------------------
# Comments:
# - We will insert into this table in chunks of artist_id values.
# - Chunking avoids one giant join result in memory.
print("\nPreparing cds_artist_resolved_release_candidates_v1...")

con.execute("""
    DROP TABLE IF EXISTS cds_artist_resolved_release_candidates_v1
""")

con.execute("""
    CREATE TABLE cds_artist_resolved_release_candidates_v1 AS
    SELECT
        b.cds_id,
        b.artist,
        b.title,
        b.cds_year,
        b.curation_route,
        b.enrichment_priority_v6,
        b.artist_key_clean,
        b.title_key_clean,
        b.artist_id,
        b.artist_gid,
        b.artist_display_name,
        b.artist_sort_name,
        b.lookup_name,
        b.lookup_source,
        b.locale,
        b.alias_type_id,
        b.primary_for_locale,
        r.release_id,
        r.release_title,
        r.main_artist_name,
        r.artist_credit_full,
        r.artist_credit_id,
        r.total_tracks,
        r.barcode,
        r.mb_year
    FROM cds_artist_alias_bridge_unique_v1 b
    JOIN mb_artist_release_for_resolved_artists_v1 r
      ON r.artist = b.artist_id
    WHERE 1 = 0
""")

print("✅ Empty table created: cds_artist_resolved_release_candidates_v1")

# ------------------------------------------------------------
# Step 5: Insert candidates in artist_id chunks
# ------------------------------------------------------------
# Comments:
# - We chunk on artist_id, not cds_id, because the explosion happens on artist->release expansion.
# - Adjust CHUNK_SIZE if needed.
artist_ids = con.execute("""
    SELECT DISTINCT artist_id
    FROM cds_artist_alias_bridge_unique_v1
    ORDER BY artist_id
""").fetchdf()["artist_id"].tolist()

CHUNK_SIZE = 5000
print(f"\nInserting candidate rows in chunks of {CHUNK_SIZE} artist IDs...")

for start in range(0, len(artist_ids), CHUNK_SIZE):
    chunk = artist_ids[start:start + CHUNK_SIZE]
    lo = chunk[0]
    hi = chunk[-1]
    print(f"  Processing artist_id chunk {start:,}..{min(start + CHUNK_SIZE, len(artist_ids)):,}  "
          f"(artist_id {lo}..{hi})")

    values_sql = ",".join(str(int(x)) for x in chunk)

    con.execute(f"""
        INSERT INTO cds_artist_resolved_release_candidates_v1
        SELECT
            b.cds_id,
            b.artist,
            b.title,
            b.cds_year,
            b.curation_route,
            b.enrichment_priority_v6,
            b.artist_key_clean,
            b.title_key_clean,
            b.artist_id,
            b.artist_gid,
            b.artist_display_name,
            b.artist_sort_name,
            b.lookup_name,
            b.lookup_source,
            b.locale,
            b.alias_type_id,
            b.primary_for_locale,
            r.release_id,
            r.release_title,
            r.main_artist_name,
            r.artist_credit_full,
            r.artist_credit_id,
            r.total_tracks,
            r.barcode,
            r.mb_year
        FROM cds_artist_alias_bridge_unique_v1 b
        JOIN mb_artist_release_for_resolved_artists_v1 r
          ON r.artist = b.artist_id
        WHERE b.artist_id IN ({values_sql})
    """)

print("✅ Table created: cds_artist_resolved_release_candidates_v1")

print("\n--- Total candidate rows ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM cds_artist_resolved_release_candidates_v1
""").fetchdf())

print("\n--- Distinct CDS rows with release candidates ---")
print(con.execute("""
    SELECT COUNT(DISTINCT cds_id) AS cds_rows_with_release_candidates
    FROM cds_artist_resolved_release_candidates_v1
""").fetchdf())

print("\n--- Average candidates per CDS row ---")
print(con.execute("""
    SELECT ROUND(AVG(k), 2) AS avg_candidates_per_cds
    FROM (
        SELECT cds_id, COUNT(*) AS k
        FROM cds_artist_resolved_release_candidates_v1
        GROUP BY cds_id
    )
""").fetchdf())

print("\n--- Preview: artist-resolved release candidates ---")
print(con.execute("""
    SELECT
        cds_id,
        artist,
        title,
        artist_display_name,
        lookup_name,
        lookup_source,
        release_id,
        main_artist_name,
        release_title,
        mb_year,
        total_tracks,
        barcode
    FROM cds_artist_resolved_release_candidates_v1
    LIMIT 25
""").fetchdf())

Connected ✅
Applying DuckDB memory-safe settings...
✅ Settings applied

Creating cds_artist_alias_bridge_unique_v1...
✅ Table created: cds_artist_alias_bridge_unique_v1

--- Unique CDS x artist pairs ---
       n
0  11585

Creating mb_artist_credit_for_resolved_artists_v1...
✅ Table created: mb_artist_credit_for_resolved_artists_v1

--- Artist-credit links for resolved artists ---
        n
0  177386

Creating mb_artist_release_for_resolved_artists_v1...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

✅ Table created: mb_artist_release_for_resolved_artists_v1

--- Reduced artist-release rows ---
        n
0  631241

Preparing cds_artist_resolved_release_candidates_v1...
✅ Empty table created: cds_artist_resolved_release_candidates_v1

Inserting candidate rows in chunks of 5000 artist IDs...
  Processing artist_id chunk 0..5,000  (artist_id 1..2674420)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  Processing artist_id chunk 5,000..5,796  (artist_id 2674601..3208878)
✅ Table created: cds_artist_resolved_release_candidates_v1

--- Total candidate rows ---
           n
0  241255822

--- Distinct CDS rows with release candidates ---
   cds_rows_with_release_candidates
0                              2820

--- Average candidates per CDS row ---

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   avg_candidates_per_cds
0                85551.71

--- Preview: artist-resolved release candidates ---
    cds_id   artist                  title artist_display_name lookup_name  \
0   103671  various  the ultimate hardcore     Various Artists     Various
1   103671  various  the ultimate hardcore     Various Artists     Various
2   103671  various  the ultimate hardcore     Various Artists     Various
3   103671  various  the ultimate hardcore     Various Artists     Various
4   103671  various  the ultimate hardcore     Various Artists     Various
5   103671  various  the ultimate hardcore     Various Artists     Various
6   103671  various  the ultimate hardcore     Various Artists     Various
7   103671  various  the ultimate hardcore     Various Artists     Various
8   103671  various  the ultimate hardcore     Various Artists     Various
9   103671  various  the ultimate hardcore     Various Artists     Various
10  103671  various  the ultimate hardcore     Various Artists     Various
11  103671  various  the ultimate hardcore     Various Artists     Various
12  103671  various  the ultimate hardcore     Various Artists     Various
13  103671  various  the ultimate hardcore     Various Artists     Various
14  103671  various  the ultimate hardcore     Various Artists     Various
15  103671  various  the ultimate hardcore     Various Artists     Various
16  103671  various  the ultimate hardcore     Various Artists     Various
17  103671  various  the ultimate hardcore     Various Artists     Various
18  103671  various  the ultimate hardcore     Various Artists     Various
19  103671  various  the ultimate hardcore     Various Artists     Various
20  103671  various  the ultimate hardcore     Various Artists     Various
21  103671  various  the ultimate hardcore     Various Artists     Various
22  103671  various  the ultimate hardcore     Various Artists     Various
23  103671  various  the ultimate hardcore     Various Artists     Various
24  103671  various  the ultimate hardcore     Various Artists     Various

   lookup_source  release_id main_artist_name  \
0     alias_name      190194  Various Artists
1     alias_name      190336  Various Artists
2     alias_name      876171  Various Artists
3     alias_name      190278  Various Artists
4     alias_name      190305  Various Artists
5     alias_name      190395  Various Artists
6     alias_name      190448  Various Artists
7     alias_name      190496  Various Artists
8     alias_name      190422  Various Artists
9     alias_name      190385  Various Artists
10    alias_name      190619  Various Artists
11    alias_name      190465  Various Artists
12    alias_name      190537  Various Artists
13    alias_name     1089954  Various Artists
14    alias_name      190625  Various Artists
15    alias_name      190609  Various Artists
16    alias_name       45589  Various Artists
17    alias_name      190611  Various Artists
18    alias_name     5156326  Various Artists
19    alias_name     2081067  Various Artists
20    alias_name     1544558  Various Artists
21    alias_name      190610  Various Artists
22    alias_name      190677  Various Artists
23    alias_name      190744  Various Artists
24    alias_name      190832  Various Artists

                                        release_title  mb_year  total_tracks  \
0   Tribes of Da Underground, Volume 4: Strings'n'...     2015          11.0
1                                      Mi vida sin mí     2009          21.0
2                                     Arriva la bomba     2021          18.0
3                                        Yes New York     2020          16.0
4                                Hy! From Hypnotic...     2012          17.0
5                             Infinite Beat, Volume 1     2017          11.0
6                                            Big Beat     <NA>          13.0
7                                      Axé Bahia 2004     2008          14.0
8                                         Sounds Easy     2024          26.0
9                       Czarne Zastępy: W Hołdzie KAT     2025          15.0
10       Entertainment Weekly: The Greatest Hits 1982     2023          12.0
11                                   Arctic Circles 2     2013          14.0
12                              Jah Warrior & Friends     2014          19.0
13  Fall Music Sampler Burning Building Recordings...     2026           8.0
14                                    Halloween Rocks     <NA>          10.0
15                                   British Invasion     2015          12.0
16                                              House     2011          16.0
17                            Classic Rock: 1982–1983     2023          30.0
18               الموسيقى التصويرية لفيلم شمس المعارف     2025           8.0
19                   San Francisco With Fond Memories     2017          12.0
20                                 Let's Have a Party     2020          16.0
21                             British Rock, Volume 2     2025          10.0
22                         The Number One’s: The ’70s     2026          16.0
23                                Main Floor (disc 1)     <NA>          20.0
24                                            Total 7     2019          24.0

          barcode
0    667548005012
1            None
2   5099748968623
3    075679318220
4   4014391005021
5    720642514429
6            None
7            None
8            None
9            None
10   744659971228
11           None
12           None
13           None
14   090121200045
15   018111931427
16           None
17
18   195448339000
19   000834570243
20  4007182910628
21           None
22   082551543427
23           None
24   880319026225

In [19]:
import duckdb
import pandas as pd

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Filter alias-assisted release candidates before scoring
# ------------------------------------------------------------
# Comments:
# - The error came from subtracting r.total_tracks - c.tracks
# - c.tracks is text (VARCHAR), so we must convert it to numeric first.
# - We use TRY_CAST so bad/non-numeric values become NULL instead of failing.
print("Creating cds_artist_resolved_release_candidates_filtered_v1...")

con.execute("""
    CREATE OR REPLACE TABLE cds_artist_resolved_release_candidates_filtered_v1 AS
    WITH cds_curated_numeric AS (
        SELECT
            cds_id,
            TRY_CAST(tracks AS BIGINT) AS cds_trackcount_num
        FROM cds_unmatched_curated_main_v1
    )
    SELECT
        r.*,
        c.cds_trackcount_num
    FROM cds_artist_resolved_release_candidates_v1 r
    LEFT JOIN cds_curated_numeric c
      ON r.cds_id = c.cds_id
    WHERE
        -- Exclude non-discriminative artist identities
        lower(coalesce(r.artist_display_name, '')) NOT IN ('various artists', 'various')
        AND lower(coalesce(r.main_artist_name, '')) NOT IN ('various artists', 'various')

        -- Release title must exist
        AND r.release_title IS NOT NULL
        AND trim(r.release_title) <> ''

        -- Year compatibility
        AND (
            r.cds_year IS NULL
            OR r.mb_year IS NULL
            OR abs(r.cds_year - r.mb_year) <= 5
        )

        -- Rough track compatibility
        AND (
            c.cds_trackcount_num IS NULL
            OR r.total_tracks IS NULL
            OR abs(r.total_tracks - c.cds_trackcount_num) <= 8
        )
""")

print("✅ Table created: cds_artist_resolved_release_candidates_filtered_v1")

print("\n--- Candidate count before filtering ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM cds_artist_resolved_release_candidates_v1
""").fetchdf())

print("\n--- Candidate count after filtering ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM cds_artist_resolved_release_candidates_filtered_v1
""").fetchdf())

print("\n--- Distinct CDS rows after filtering ---")
print(con.execute("""
    SELECT COUNT(DISTINCT cds_id) AS cds_rows_with_candidates
    FROM cds_artist_resolved_release_candidates_filtered_v1
""").fetchdf())

print("\n--- Average candidates per CDS row after filtering ---")
print(con.execute("""
    SELECT ROUND(AVG(k), 2) AS avg_candidates_per_cds
    FROM (
        SELECT cds_id, COUNT(*) AS k
        FROM cds_artist_resolved_release_candidates_filtered_v1
        GROUP BY cds_id
    )
""").fetchdf())

print("\n--- Preview: filtered alias-assisted candidates ---")
print(con.execute("""
    SELECT
        cds_id,
        artist,
        title,
        artist_display_name,
        lookup_name,
        lookup_source,
        release_id,
        main_artist_name,
        release_title,
        cds_year,
        mb_year,
        cds_trackcount_num,
        total_tracks,
        barcode
    FROM cds_artist_resolved_release_candidates_filtered_v1
    LIMIT 25
""").fetchdf())

Connected ✅
Creating cds_artist_resolved_release_candidates_filtered_v1...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

✅ Table created: cds_artist_resolved_release_candidates_filtered_v1

--- Candidate count before filtering ---
           n
0  241255822

--- Candidate count after filtering ---
        n
0  544138

--- Distinct CDS rows after filtering ---
   cds_rows_with_candidates
0                      1839

--- Average candidates per CDS row after filtering ---
   avg_candidates_per_cds
0                  295.89

--- Preview: filtered alias-assisted candidates ---
    cds_id                            artist  \
0   102060                      scott joplin
1   107053                      king crimson
2   109175                   igor stravinsky
3   107117                      joe satriani
4     9068                      depeche mode
5   107388                     reel big fish
6   101188               cannonball adderley
7   105763                         john cale
8   101939  the royal philharmonic orchestra
9   108994         london symphony orchestra
10  100981                  brecker brothers
11  105993                           traffic
12  104844                     cliff richard
13  100837                    billie holiday
14  100838                       count basie
15  101628            alexander mccall smith
16  109432              jean sã bastien bach
17  108931                      shostakovich
18  105634                         metallica
19  107977                   clifton chenier
20  106019                      eric clapton
21  109175                   igor stravinsky
22  109359                             verdi
23  109432              jean sã bastien bach
24  100757                  ibrahim tatlises

                                               title  \
0                                 the age of ragtime
1                         studio rehearsals disc one
2         sacre du printemps firebird pierre boulez
3                                 g3 live in concert
4                                 opening old wounds
5                                  cheer up advance
6                          compact jazz compilation
7                   rytmeposten odense 04 12 2003 2
8                               hits of phil collins
9                               norske popklassikere
10                    return of the brecker brothers
11                         anderson theatre 11 23 70
12                        i m nearly famous 21 today
13                       1949 52 radio tv broadcasts
14                                basie s beatle bag
15               kalahari typing school for men 4of6
16      le clavier bien tempã rã 1 gustav leonhardt
17  quartets nos 3 5 7 st petersburg string quartet
18                        the unforgiven hits part 1
19                                    king of zydeco
20                                  live in usa 1984
21        sacre du printemps firebird pierre boulez
22                                              aida
23      le clavier bien tempã rã 1 gustav leonhardt
24                                       selam olsun

              artist_display_name                       lookup_name  \
0                    Scott Joplin                      Scott Joplin
1                    King Crimson                      King Crimson
2     Игорь Фёдорович Стравинский                   Igor Stravinsky
3                    Joe Satriani                      Joe Satriani
4                    Depeche Mode                      Depeche Mode
5                   Reel Big Fish                     Reel Big Fish
6             Cannonball Adderley               Cannonball Adderley
7                       John Cale                         John Cale
8    Royal Philharmonic Orchestra  The Royal Philharmonic Orchestra
9       London Symphony Orchestra         London Symphony Orchestra
10           The Brecker Brothers                  Brecker Brothers
11                        Traffic                           Traffic
12                  Cliff Richard                     Cliff Richard
13                 Billie Holiday                    Billie Holiday
14                    Count Basie                       Count Basie
15         Alexander McCall Smith            Alexander McCall Smith
16          Johann Sebastian Bach               Jean-Sébastien Bach
17  Дмитрий Дмитриевич Шостакович                      Shostakovich
18                      Metallica                         Metallica
19                Clifton Chenier                   Clifton Chenier
20                   Eric Clapton                      Eric Clapton
21    Игорь Фёдорович Стравинский                   Igor Stravinsky
22                 Giuseppe Verdi                             Verdi
23          Johann Sebastian Bach               Jean-Sébastien Bach
24               İbrahim Tatlıses                  Ibrahim Tatlises

     lookup_source  release_id               main_artist_name  \
0   canonical_name     1187344                   Scott Joplin
1   canonical_name      178462                   King Crimson
2       alias_name     3059211    Игорь Фёдорович Стравинский
3   canonical_name     1730076                   Joe Satriani
4   canonical_name      178954                   Depeche Mode
5   canonical_name      178974                  Reel Big Fish
6   canonical_name     1551593            Cannonball Adderley
7   canonical_name      179289                      John Cale
8       alias_name     3059214   Royal Philharmonic Orchestra
9   canonical_name      179632      London Symphony Orchestra
10      alias_name      179682           The Brecker Brothers
11  canonical_name      179927                        Traffic
12  canonical_name      180014                  Cliff Richard
13  canonical_name      180104                 Billie Holiday
14  canonical_name      180534                    Count Basie
15  canonical_name     2415617         Alexander McCall Smith
16      alias_name      465089          Johann Sebastian Bach
17      alias_name     1428742  Дмитрий Дмитриевич Шостакович
18  canonical_name      180571                      Metallica
19  canonical_name      180693                Clifton Chenier
20  canonical_name      178501                      B.B. King
21      alias_name      178975    Игорь Фёдорович Стравинский
22      alias_name      289443                 Giuseppe Verdi
23      alias_name     2089364          Johann Sebastian Bach
24      alias_name      181114               İbrahim Tatlıses

                                        release_title  cds_year  mb_year  \
0                                         Treemonisha      <NA>     2014
1                                            Doctor D      <NA>     2025
2   The Firebird Suite, Pulcinella Suite, Scherzo ...      <NA>     2021
3   Professor Satchafunkilus and the Musterion of ...      <NA>     2024
4                                            Precious      <NA>     2009
5                                  Turn the Radio Off      <NA>     2013
6                                      Somethin’ Else      <NA>     2022
7                                     Paris s’éveille      <NA>     2023
8                      Classic Rock, Vol. 8: Pop Rock      <NA>     2022
9                     The Best Loved Christmas Carols      <NA>     <NA>
10                                    Out of the Loop      <NA>     2011
11                                      Far From Home      <NA>     2015
12               I Could Easily Fall in Love With You      1976     <NA>
13                         The Best of Billie Holiday      <NA>     <NA>
14                    The Count Basie Gold Collection      <NA>     <NA>
15                 The No. 1 Ladies’ Detective Agency      <NA>     2023
16                                Cantatas, Volume 26      <NA>     2014
17                         Strijkkwartetten 1, 2 en 3      <NA>     2023
18                                  The Unforgiven II      <NA>     2017
19                         Louisiana Blues and Zydeco      <NA>     2014
20                               Riding With the King      <NA>     2009
21                                    Modern Pictures      <NA>     2025
22         Great Recordings of the Century: Don Carlo      <NA>     2017
23             Ouvertüren - Quatre Suites BWV 1066-69      <NA>     2018
24                                   Ayağında Kundura      1999     <NA>

    cds_trackcount_num  total_tracks        barcode
0                 <NA>          29.0   093228072027
1                 <NA>          10.0           None
2                 <NA>          27.0
3                 <NA>          10.0   886972126227
4                 <NA>           6.0   093624283126
5                 <NA>          15.0           None
6                 <NA>           6.0   724349532922
7                 <NA>           7.0  5413303209523
8                 <NA>          14.0  7619929569173
9                 <NA>          12.0           None
10                <NA>           9.0   011105978422
11                <NA>          10.0   724383949021
12                <NA>           2.0           None
13                <NA>          18.0           None
14                <NA>          14.0           None
15                <NA>          72.0  9781405500012
16                <NA>          19.0  7318590014011
17                <NA>          13.0           None
18                <NA>           2.0           None
19                <NA>          11.0           None
20                <NA>          16.0           None
21                <NA>           4.0  0035626082727
22                <NA>          74.0   724356740129
23                <NA>          24.0   794881350629
24                <NA>          11.0           None

In [20]:
import duckdb
import pandas as pd
from rapidfuzz import fuzz

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)

# Connect
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Score and rank filtered alias-assisted release candidates
# ------------------------------------------------------------
# Comments:
# - We already resolved artist identity through MB aliases.
# - So now the main discriminative signal is the CDS title vs MB release title.
# - We also use year compatibility and lookup-source quality.
# - Then we rank candidates per cds_id and assign confidence classes.
print("Loading filtered alias-assisted candidates...")

df = con.execute("""
    SELECT
        cds_id,
        artist,
        title,
        cds_year,
        curation_route,
        enrichment_priority_v6,
        artist_key_clean,
        title_key_clean,
        artist_id,
        artist_display_name,
        artist_sort_name,
        lookup_name,
        lookup_source,
        locale,
        alias_type_id,
        primary_for_locale,
        release_id,
        release_title,
        main_artist_name,
        artist_credit_full,
        total_tracks,
        barcode,
        mb_year
    FROM cds_artist_resolved_release_candidates_filtered_v1
""").fetchdf()

print(f"✅ Loaded rows: {len(df):,}")

# ------------------------------------------------------------
# Compute title similarity + small metadata bonuses
# ------------------------------------------------------------
# Comments:
# - Artist is already "resolved" by the alias bridge, so title gets higher weight.
# - We add:
#     * year bonus if close
#     * barcode bonus
#     * lookup-source preference
print("Scoring alias-assisted candidates...")

title_sims = []
year_bonus = []
barcode_bonus = []
lookup_bonus = []
final_scores = []

for _, row in df.iterrows():
    cds_title = row["title"] if row["title"] is not None else ""
    mb_title = row["release_title"] if row["release_title"] is not None else ""

    t_sim = fuzz.token_set_ratio(str(cds_title), str(mb_title))
    title_sims.append(t_sim)

    # Year bonus
    if pd.isna(row["cds_year"]) or pd.isna(row["mb_year"]):
        y_bonus = 0.0
    else:
        diff = abs(int(row["cds_year"]) - int(row["mb_year"]))
        if diff == 0:
            y_bonus = 8.0
        elif diff <= 1:
            y_bonus = 5.0
        elif diff <= 3:
            y_bonus = 2.0
        else:
            y_bonus = -3.0
    year_bonus.append(y_bonus)

    # Barcode bonus
    b_bonus = 3.0 if pd.notna(row["barcode"]) and str(row["barcode"]).strip() != "" else 0.0
    barcode_bonus.append(b_bonus)

    # Lookup source bonus
    source = row["lookup_source"]
    if source == "canonical_name":
        l_bonus = 4.0
    elif source == "alias_name":
        l_bonus = 2.5
    elif source == "canonical_sort_name":
        l_bonus = 1.5
    elif source == "alias_sort_name":
        l_bonus = 1.0
    else:
        l_bonus = 0.0
    lookup_bonus.append(l_bonus)

    # Final weighted score
    score = 0.85 * t_sim + y_bonus + b_bonus + l_bonus
    final_scores.append(score)

df["title_sim"] = title_sims
df["year_bonus"] = year_bonus
df["barcode_bonus"] = barcode_bonus
df["lookup_bonus"] = lookup_bonus
df["alias_final_score"] = final_scores

# ------------------------------------------------------------
# Keep top candidates per CDS row
# ------------------------------------------------------------
df = df.sort_values(
    ["cds_id", "alias_final_score", "title_sim", "release_id"],
    ascending=[True, False, False, True]
)

# Keep top 5 per cds_id
df_top = df.groupby("cds_id").head(5).copy()

print("Top candidates retained:", len(df_top))

# Register and rank in DuckDB
con.register("alias_rank_df", df_top)

con.execute("""
    CREATE OR REPLACE TABLE cds_alias_enrichment_ranked_v1 AS
    WITH ranked AS (
        SELECT
            *,
            row_number() OVER (
                PARTITION BY cds_id
                ORDER BY
                    alias_final_score DESC,
                    title_sim DESC,
                    release_id ASC
            ) AS candidate_rank,

            first_value(alias_final_score) OVER (
                PARTITION BY cds_id
                ORDER BY
                    alias_final_score DESC,
                    title_sim DESC,
                    release_id ASC
            ) AS best_score,

            lead(alias_final_score) OVER (
                PARTITION BY cds_id
                ORDER BY
                    alias_final_score DESC,
                    title_sim DESC,
                    release_id ASC
            ) AS second_best_score
        FROM alias_rank_df
    )
    SELECT
        *,
        (best_score - second_best_score) AS score_gap,
        CASE
            WHEN candidate_rank = 1
                 AND title_sim >= 92
                 AND alias_final_score >= 86
                 AND (best_score - second_best_score >= 6 OR second_best_score IS NULL)
            THEN 'auto_accept'

            WHEN candidate_rank = 1
                 AND title_sim >= 86
                 AND alias_final_score >= 80
            THEN 'review'

            ELSE 'reject'
        END AS confidence_class
    FROM ranked
""")

print("✅ Table created: cds_alias_enrichment_ranked_v1")

print("\n--- Confidence class summary (top-ranked only) ---")
print(con.execute("""
    SELECT
        confidence_class,
        COUNT(*) AS n
    FROM cds_alias_enrichment_ranked_v1
    WHERE candidate_rank = 1
    GROUP BY confidence_class
    ORDER BY n DESC
""").fetchdf())

print("\n--- Preview: top-ranked alias-assisted candidates ---")
print(con.execute("""
    SELECT
        cds_id,
        artist,
        title,
        artist_display_name,
        lookup_name,
        lookup_source,
        release_id,
        main_artist_name,
        release_title,
        title_sim,
        alias_final_score,
        best_score,
        second_best_score,
        score_gap,
        confidence_class
    FROM cds_alias_enrichment_ranked_v1
    WHERE candidate_rank = 1
    ORDER BY alias_final_score DESC, score_gap DESC NULLS LAST
    LIMIT 30
""").fetchdf())

Connected ✅
Loading filtered alias-assisted candidates...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

✅ Loaded rows: 544,138
Scoring alias-assisted candidates...
Top candidates retained: 6737
✅ Table created: cds_alias_enrichment_ranked_v1

--- Confidence class summary (top-ranked only) ---
  confidence_class     n
0           reject  1807
1           review    23
2      auto_accept     9

--- Preview: top-ranked alias-assisted candidates ---
    cds_id                      artist                                          title           artist_display_name                 lookup_name   lookup_source  release_id  \
0   100136                   joan baez                                              5                     Joan Baez                   Joan Baez  canonical_name     5080207
1   108936            paul baumgartner                                          piano              Paul Baumgartner            Paul Baumgartner  canonical_name     1458913
2   103932                  zã ramalho                               grandes sucessos                    Zé Ramalho                  Zé Ramalho  canonical_name     1781355
3   105312         frank boeijen groep                                              1           Frank Boeijen Groep         Frank Boeijen Groep  canonical_name     2458233
4   105165                        gang                             le radici e le ali                      The Gang                        Gang      alias_name      284112
5   108945                     vivaldi                               the four seasons               Antonio Vivaldi                     Vivaldi      alias_name     2951286
6   104297                 luis kalaff                                       merengue                   Luis Kalaff                 Luis Kalaff  canonical_name     1140251
7   105628             yolandita monge                                        en vivo               Yolandita Monge             Yolandita Monge  canonical_name     1602500
8   101155                woody herman                               1963 summer tour                  Woody Herman                Woody Herman  canonical_name     3014850
9   105465                   the clash                      cardiff live 22 july 1977                     The Clash                   The Clash  canonical_name     2151661
10  108898                eugen jochum  kr nungsmesse vesperae solennes de confessore                  Eugen Jochum                Eugen Jochum  canonical_name     1198081
11  100160                      nylons                                 4 on the floor                    The Nylons                      Nylons      alias_name     1470046
12  109175             igor stravinsky     sacre du printemps firebird pierre boulez    Игорь Фёдорович Стравинский             Igor Stravinsky      alias_name      701122
13  108878                rachmaninoff                       rachmaninoff for romance  Сергей Васильевич Рахманинов                Rachmaninoff      alias_name      877518
14  108013                  tomita lab                                   shipbuilding                          冨田恵一                  Tomita Lab      alias_name      535572
15   11174                  mussorgsky                       bilder einer ausstellung    Модест Петрович Мусоргский                  Mussorgsky      alias_name      421192
16   10983                  mussorgsky                       bilder einer ausstellung    Модест Петрович Мусоргский                  Mussorgsky      alias_name      421192
17  107139  the overwhelming colorfast                        moonlight and castanets        Overwhelming Colorfast  The Overwhelming Colorfast      alias_name       19212
18  108747                        bach                          brandenburg concertos         Johann Sebastian Bach                        Bach      alias_name       92387
19  100149                     al bano                   i grandi successi di al bano               Al Bano Carrisi                     Al Bano      alias_name     1136165
20  101378                   yuji ohno            lupin the 3rd original soundtrack 3                          大野雄二                   Yuji Ohno      alias_name     1266353
21  105399            sinã ad o connor                          the year of the horse               Sinéad O’Connor             Sinéad O’Connor  canonical_name      127847
22  107058                  videodrone                                     videodrone              Cradle of Thorns                  Videodrone      alias_name       19192
23  100981            brecker brothers                 return of the brecker brothers          The Brecker Brothers            Brecker Brothers      alias_name      275553
24  102685                claude semal                                   a nos amours                  Claude Semal                Claude Semal  canonical_name      257789
25  102182              eddie santiago                            la vida musical de                 Eddie Santiago              Eddie Santiago  canonical_name     1008061
26  108930                   hindemith                   hindemith conducts hindemith                Paul Hindemith                   Hindemith      alias_name     2743033
27  105257                  beach boys                                      sunflower                The Beach Boys                  Beach Boys      alias_name      819921
28  109622                        witt                                      eisenherz                  Joachim Witt                        witt      alias_name      173455
29  108727                      mozart                            piano sonatas vol 2       Wolfgang Amadeus Mozart                      Mozart      alias_name      494702

                main_artist_name                                      release_title   title_sim  alias_final_score  best_score  second_best_score  score_gap confidence_class
0                      Joan Baez                                                  5  100.000000          92.000000   92.000000          21.166667  70.833333      auto_accept
1          Johann Sebastian Bach  Pablo Casals interpreta Bach II: 2 sonatas par...  100.000000          92.000000   92.000000          31.285714  60.714286      auto_accept
2                     Zé Ramalho                                21 grandes sucessos  100.000000          92.000000   92.000000          63.666667  28.333333      auto_accept
3            Frank Boeijen Groep                                                  1  100.000000          92.000000   92.000000          89.000000   3.000000           review
4                       The Gang                                 Le radici e le ali  100.000000          90.500000   90.500000          48.000000  42.500000      auto_accept
5                Antonio Vivaldi                           Vivaldi the four seasons  100.000000          90.500000   90.500000          74.562500  15.937500      auto_accept
6                    Luis Kalaff                                El rey del merengue  100.000000          89.000000   89.000000          25.378378  63.621622      auto_accept
7                Yolandita Monge                                  Yolandita en vivo  100.000000          89.000000   89.000000          43.230769  45.769231      auto_accept
8                   Woody Herman                                               1963  100.000000          89.000000   89.000000          44.000000  45.000000      auto_accept
9                      The Clash                                               1977  100.000000          89.000000   89.000000          75.923077  13.076923      auto_accept
10       Wolfgang Amadeus Mozart    Krönungsmesse & Vesperae solennes de confessore   91.304348          84.608696   84.608696          49.967033  34.641663           review
11                    The Nylons                                     4 on the Floor   92.857143          84.428571   84.428571          65.822581  18.605991           review
12   Игорь Фёдорович Стравинский                              Le sacre du printemps   92.307692          83.961538   83.961538          73.034247  10.927292           review
13  Сергей Васильевич Рахманинов                           Rachmaninoff for Romance   91.666667          83.416667   83.416667          71.181818  12.234848           review
14                          冨田恵一                                       Shipbuilding   91.666667          83.416667   83.416667          83.416667   0.000000           review
15    Модест Петрович Мусоргский                           Bilder einer Ausstellung   91.666667          83.416667   83.416667          83.416667   0.000000           review
16    Модест Петрович Мусоргский                           Bilder einer Ausstellung   91.666667          83.416667   83.416667          83.416667   0.000000           review
17        Overwhelming Colorfast                            Moonlight and Castanets   91.304348          83.108696   83.108696          31.944444  51.164251           review
18         Johann Sebastian Bach                              Brandenburg Concertos   90.476190          82.404762   82.404762          82.404762   0.000000           review
19               Al Bano Carrisi                                  I grandi successi   93.750000          82.187500   82.187500          48.904255  33.283245           review
20                          大野雄二               Lupin the 3rd: Original Soundtrack 3   90.140845          82.119718   82.119718          79.725352   2.394366           review
21               Sinéad O’Connor                                  Year of the Horse   88.235294          82.000000   82.000000          58.944444  23.055556           review
22              Cradle of Thorns                                         Videodrone   90.000000          82.000000   82.000000          82.000000   0.000000           review
23          The Brecker Brothers                     Return of the Brecker Brothers   90.000000          82.000000   82.000000          82.000000   0.000000           review
24                  Claude Semal                                       À nos amours   91.666667          81.916667   81.916667          34.222222  47.694444           review
25                Eddie Santiago                  La vida musical de Eddie Santiago   90.909091          81.272727   81.272727          55.395349  25.877378           review
26                Paul Hindemith                       Hindemith Conducts Hindemith   88.888889          81.055556   81.055556          57.107143  23.948413           review
27                The Beach Boys                                          Sunflower   88.888889          81.055556   81.055556          81.055556   0.000000           review
28                  Joachim Witt                                          Eisenherz   88.888889          81.055556   81.055556          81.055556   0.000000           review
29       Wolfgang Amadeus Mozart                               Piano sonatas vol. 2   92.307692          80.961538   80.961538          74.562500   6.399038           review

In [359]:
import duckdb
import pandas as pd

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Stricter alias-assisted automatic acceptance
# ------------------------------------------------------------
# Comments:
# - Keep only top-ranked alias candidates
# - Keep only auto_accept rows
# - Add an extra safeguard:
#     * reject titles that are too short
#     * reject titles that are numeric-only
print("Creating cds_alias_enrichment_auto_v1...")

con.execute("""
    CREATE OR REPLACE TABLE cds_alias_enrichment_auto_v1 AS
    SELECT *
    FROM cds_alias_enrichment_ranked_v1
    WHERE candidate_rank = 1
      AND confidence_class = 'auto_accept'
      AND length(trim(coalesce(title, ''))) >= 4
      AND NOT regexp_matches(trim(coalesce(title, '')), '^[0-9]+$')
""")

print("✅ Table created: cds_alias_enrichment_auto_v1")

print("\n--- Count of stricter alias auto-accept rows ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM cds_alias_enrichment_auto_v1
""").fetchdf())

print("\n--- Preview: stricter alias auto-accept rows ---")
print(con.execute("""
    SELECT
        cds_id,
        artist,
        title,
        artist_display_name,
        lookup_name,
        lookup_source,
        release_id,
        main_artist_name,
        release_title,
        title_sim,
        alias_final_score,
        score_gap
    FROM cds_alias_enrichment_auto_v1
    ORDER BY alias_final_score DESC, score_gap DESC NULLS LAST
""").fetchdf())

Connected ✅
Creating cds_alias_enrichment_auto_v1...
✅ Table created: cds_alias_enrichment_auto_v1

--- Count of stricter alias auto-accept rows ---
   n
0  8

--- Preview: stricter alias auto-accept rows ---
   cds_id            artist                      title artist_display_name       lookup_name   lookup_source  release_id       main_artist_name                                                  release_title  title_sim  \
0  108936  paul baumgartner                      piano    Paul Baumgartner  Paul Baumgartner  canonical_name     1458913  Johann Sebastian Bach  Pablo Casals interpreta Bach II: 2 sonatas para cello y piano      100.0
1  103932        zã ramalho           grandes sucessos          Zé Ramalho        Zé Ramalho  canonical_name     1781355             Zé Ramalho                                            21 grandes sucessos      100.0
2  105165              gang         le radici e le ali            The Gang              Gang      alias_name      284112               The Gang                                             Le radici e le ali      100.0
3  108945           vivaldi           the four seasons     Antonio Vivaldi           Vivaldi      alias_name     2951286        Antonio Vivaldi                                       Vivaldi the four seasons      100.0
4  104297       luis kalaff                   merengue         Luis Kalaff       Luis Kalaff  canonical_name     1140251            Luis Kalaff                                            El rey del merengue      100.0
5  105628   yolandita monge                    en vivo     Yolandita Monge   Yolandita Monge  canonical_name     1602500        Yolandita Monge                                              Yolandita en vivo      100.0
6  101155      woody herman           1963 summer tour        Woody Herman      Woody Herman  canonical_name     3014850           Woody Herman                                                           1963      100.0
7  105465         the clash  cardiff live 22 july 1977           The Clash         The Clash  canonical_name     2151661              The Clash                                                           1977      100.0

   alias_final_score  score_gap
0               92.0  60.714286
1               92.0  28.333333
2               90.5  42.500000
3               90.5  15.937500
4               89.0  63.621622
5               89.0  45.769231
6               89.0  45.000000
7               89.0  13.076923

In [360]:
import duckdb
import pandas as pd

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Build a better alias-assisted automatic subset
# ------------------------------------------------------------
# Comments:
# - Do NOT exclude titles just because they contain words like
#   "live", "en vivo", or "greatest hits".
# - Some such titles are actually highly specific.
# - Instead, exclude only titles that are too short or purely numeric.
print("Creating cds_alias_enrichment_auto_v2_safe...")

con.execute("""
    CREATE OR REPLACE TABLE cds_alias_enrichment_auto_v2_safe AS
    SELECT *
    FROM cds_alias_enrichment_auto_v1
    WHERE
        -- title must not be too short
        length(trim(coalesce(title, ''))) >= 4

        -- title must not be purely numeric
        AND NOT regexp_matches(trim(coalesce(title, '')), '^[0-9]+$')

        -- title must not be just one very short token
        AND NOT (
            regexp_matches(trim(coalesce(title, '')), '^[A-Za-z0-9]+$')
            AND length(trim(coalesce(title, ''))) <= 5
        )
""")

con.execute("""
    CREATE OR REPLACE TABLE cds_alias_enrichment_auto_v2_review AS
    SELECT *
    FROM cds_alias_enrichment_auto_v1
    WHERE cds_id NOT IN (
        SELECT cds_id
        FROM cds_alias_enrichment_auto_v2_safe
    )
""")

print("✅ Tables created: cds_alias_enrichment_auto_v2_safe, cds_alias_enrichment_auto_v2_review")

print("\n--- Safe alias auto rows ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM cds_alias_enrichment_auto_v2_safe
""").fetchdf())

print("\n--- Moved from auto to review ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM cds_alias_enrichment_auto_v2_review
""").fetchdf())

print("\n--- Preview: safe alias auto rows ---")
print(con.execute("""
    SELECT
        cds_id,
        artist,
        title,
        artist_display_name,
        release_id,
        main_artist_name,
        release_title,
        title_sim,
        alias_final_score,
        score_gap
    FROM cds_alias_enrichment_auto_v2_safe
    ORDER BY alias_final_score DESC, score_gap DESC NULLS LAST
""").fetchdf())

Connected ✅
Creating cds_alias_enrichment_auto_v2_safe...
✅ Tables created: cds_alias_enrichment_auto_v2_safe, cds_alias_enrichment_auto_v2_review

--- Safe alias auto rows ---
   n
0  7

--- Moved from auto to review ---
   n
0  1

--- Preview: safe alias auto rows ---
   cds_id           artist                      title artist_display_name  release_id main_artist_name             release_title  title_sim  alias_final_score  score_gap
0  103932       zã ramalho           grandes sucessos          Zé Ramalho     1781355       Zé Ramalho       21 grandes sucessos      100.0               92.0  28.333333
1  105165             gang         le radici e le ali            The Gang      284112         The Gang        Le radici e le ali      100.0               90.5  42.500000
2  108945          vivaldi           the four seasons     Antonio Vivaldi     2951286  Antonio Vivaldi  Vivaldi the four seasons      100.0               90.5  15.937500
3  104297      luis kalaff                   merengue         Luis Kalaff     1140251      Luis Kalaff       El rey del merengue      100.0               89.0  63.621622
4  105628  yolandita monge                    en vivo     Yolandita Monge     1602500  Yolandita Monge         Yolandita en vivo      100.0               89.0  45.769231
5  101155     woody herman           1963 summer tour        Woody Herman     3014850     Woody Herman                      1963      100.0               89.0  45.000000
6  105465        the clash  cardiff live 22 july 1977           The Clash     2151661        The Clash                      1977      100.0               89.0  13.076923

In [361]:
import duckdb
import pandas as pd

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Final expert split for alias-assisted high-confidence rows
# ------------------------------------------------------------
# Comments:
# - Even after strong filtering, some high-scoring rows still have
#   generic titles ("en vivo", "merengue", year-only style cases).
# - For the thesis, we keep only the most defensible rows as fully
#   automatic alias enrichments.
# - The rest remain as review candidates.
print("Creating cds_alias_enrichment_auto_v3_safe...")

con.execute("""
    CREATE OR REPLACE TABLE cds_alias_enrichment_auto_v3_safe AS
    SELECT *
    FROM cds_alias_enrichment_auto_v2_safe
    WHERE cds_id IN (103932, 105165, 108945, 105465)
""")

con.execute("""
    CREATE OR REPLACE TABLE cds_alias_enrichment_auto_v3_review AS
    SELECT *
    FROM cds_alias_enrichment_auto_v2_safe
    WHERE cds_id NOT IN (103932, 105165, 108945, 105465)
""")

print("✅ Tables created: cds_alias_enrichment_auto_v3_safe, cds_alias_enrichment_auto_v3_review")

print("\n--- Safe alias auto rows ---")
print(con.execute("""
    SELECT
        cds_id,
        artist,
        title,
        artist_display_name,
        release_id,
        main_artist_name,
        release_title,
        title_sim,
        alias_final_score,
        score_gap
    FROM cds_alias_enrichment_auto_v3_safe
    ORDER BY alias_final_score DESC, score_gap DESC NULLS LAST
""").fetchdf())

print("\n--- Alias rows moved to review ---")
print(con.execute("""
    SELECT
        cds_id,
        artist,
        title,
        artist_display_name,
        release_id,
        main_artist_name,
        release_title,
        title_sim,
        alias_final_score,
        score_gap
    FROM cds_alias_enrichment_auto_v3_review
    ORDER BY alias_final_score DESC, score_gap DESC NULLS LAST
""").fetchdf())

Connected ✅
Creating cds_alias_enrichment_auto_v3_safe...
✅ Tables created: cds_alias_enrichment_auto_v3_safe, cds_alias_enrichment_auto_v3_review

--- Safe alias auto rows ---
   cds_id      artist                      title artist_display_name  release_id main_artist_name             release_title  title_sim  alias_final_score  score_gap
0  103932  zã ramalho           grandes sucessos          Zé Ramalho     1781355       Zé Ramalho       21 grandes sucessos      100.0               92.0  28.333333
1  105165        gang         le radici e le ali            The Gang      284112         The Gang        Le radici e le ali      100.0               90.5  42.500000
2  108945     vivaldi           the four seasons     Antonio Vivaldi     2951286  Antonio Vivaldi  Vivaldi the four seasons      100.0               90.5  15.937500
3  105465   the clash  cardiff live 22 july 1977           The Clash     2151661        The Clash                      1977      100.0               89.0  13.076923

--- Alias rows moved to review ---
   cds_id           artist             title artist_display_name  release_id main_artist_name        release_title  title_sim  alias_final_score  score_gap
0  104297      luis kalaff          merengue         Luis Kalaff     1140251      Luis Kalaff  El rey del merengue      100.0               89.0  63.621622
1  105628  yolandita monge           en vivo     Yolandita Monge     1602500  Yolandita Monge    Yolandita en vivo      100.0               89.0  45.769231
2  101155     woody herman  1963 summer tour        Woody Herman     3014850     Woody Herman                 1963      100.0               89.0  45.000000

In [393]:
import duckdb
import pandas as pd

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Safe merge into final mapping v9
# ------------------------------------------------------------
# Comments:
# - The previous UNION ALL failed because v8 and the alias table
#   did not have the same number of columns.
# - Here we:
#     1) read the exact schema of v8
#     2) map alias-safe columns into that schema
#     3) fill any missing v8 columns with NULL
# - This guarantees column-count compatibility.
print("Reading schemas...")

v8_schema = con.execute("PRAGMA table_info('cds_to_mb_final_mapping_v8')").fetchdf()
alias_schema = con.execute("PRAGMA table_info('cds_alias_enrichment_auto_v3_safe')").fetchdf()

v8_cols = v8_schema["name"].tolist()
alias_cols = set(alias_schema["name"].tolist())

print("\n--- v8 columns ---")
print(v8_cols)

print("\n--- alias-safe columns ---")
print(sorted(alias_cols))

# ------------------------------------------------------------
# Mapping from v8 columns -> alias-safe source expressions
# ------------------------------------------------------------
# Adjusted to your pipeline tables
column_mapping = {
    "cds_id": "a.cds_id",
    "artist": "a.artist",
    "title": "a.title",
    "cds_year": "a.cds_year",
    "release_id": "a.release_id",
    "release_title": "a.release_title",
    "main_artist_name": "a.main_artist_name",
    "artist_credit_full": "a.artist_credit_full",
    "total_tracks": "a.total_tracks",
    "barcode": "a.barcode",
    "mb_year": "a.mb_year",
    "match_type": "'alias_enrichment_safe'",
    "score": "a.alias_final_score",
}

# ------------------------------------------------------------
# Build the alias SELECT so it matches v8 exactly
# ------------------------------------------------------------
alias_select_parts = []

for col in v8_cols:
    if col in column_mapping:
        alias_select_parts.append(f"{column_mapping[col]} AS {col}")
    else:
        alias_select_parts.append(f"NULL AS {col}")

alias_select_sql = ",\n        ".join(alias_select_parts)

print("\nCreating cds_to_mb_final_mapping_v9...")

sql = f"""
    CREATE OR REPLACE TABLE cds_to_mb_final_mapping_v9 AS

    SELECT
        {", ".join(v8_cols)}
    FROM cds_to_mb_final_mapping_v8

    UNION ALL

    SELECT
        {alias_select_sql}
    FROM cds_alias_enrichment_auto_v3_safe a
    LEFT JOIN cds_to_mb_final_mapping_v8 x
      ON a.cds_id = x.cds_id
    WHERE x.cds_id IS NULL
"""

con.execute(sql)

print("✅ Table created: cds_to_mb_final_mapping_v9")

print("\n--- Coverage after alias-safe merge ---")
print(con.execute("""
    SELECT
        (SELECT COUNT(*) FROM cds) AS cds_total,
        (SELECT COUNT(*) FROM cds_to_mb_final_mapping_v8) AS matched_before,
        (SELECT COUNT(*) FROM cds_alias_enrichment_auto_v3_safe) AS alias_added_raw,
        (SELECT COUNT(*) FROM cds_to_mb_final_mapping_v9) AS matched_after,
        (SELECT COUNT(*) FROM cds) - (SELECT COUNT(*) FROM cds_to_mb_final_mapping_v9) AS still_unmatched
""").fetchdf())

print("\n--- Match type breakdown in v9 ---")
print(con.execute("""
    SELECT match_type, COUNT(*) AS n
    FROM cds_to_mb_final_mapping_v9
    GROUP BY match_type
    ORDER BY n DESC
""").fetchdf())

print("\n--- Preview of newly added alias-safe rows ---")
print(con.execute("""
    SELECT *
    FROM cds_to_mb_final_mapping_v9
    WHERE match_type = 'alias_enrichment_safe'
    LIMIT 20
""").fetchdf())

Connected ✅
Reading schemas...

--- v8 columns ---
['cds_id', 'artist', 'title', 'cds_year', 'release_id', 'release_title', 'main_artist_name', 'artist_credit_full', 'total_tracks', 'barcode', 'mb_year', 'match_type', 'confidence_label', 'score', 'title_sim', 'artist_sim']

--- alias-safe columns ---
['alias_final_score', 'alias_type_id', 'artist', 'artist_credit_full', 'artist_display_name', 'artist_id', 'artist_key_clean', 'artist_sort_name', 'barcode', 'barcode_bonus', 'best_score', 'candidate_rank', 'cds_id', 'cds_year', 'confidence_class', 'curation_route', 'enrichment_priority_v6', 'locale', 'lookup_bonus', 'lookup_name', 'lookup_source', 'main_artist_name', 'mb_year', 'primary_for_locale', 'release_id', 'release_title', 'score_gap', 'second_best_score', 'title', 'title_key_clean', 'title_sim', 'total_tracks', 'year_bonus']

Creating cds_to_mb_final_mapping_v9...
✅ Table created: cds_to_mb_final_mapping_v9

--- Coverage after alias-safe merge ---
   cds_total  matched_before  alias_added_raw  matched_after  still_unmatched
0       9763            4211                4           4214             5549

--- Match type breakdown in v9 ---
               match_type     n
0                   exact  3482
1       fuzzy_second_pass   543
2      various_title_only   183
3   alias_enrichment_safe     3
4  enrichment_round2_auto     3

--- Preview of newly added alias-safe rows ---
   cds_id      artist               title  cds_year  release_id             release_title main_artist_name                                                         artist_credit_full  total_tracks        barcode  \
0  105165        gang  le radici e le ali      <NA>      284112        Le radici e le ali         The Gang                                                                       Gang          12.0   090317348827
1  103932  zã ramalho    grandes sucessos      <NA>     1781355       21 grandes sucessos       Zé Ramalho                                                                 Zé Ramalho          21.0  5099749575325
2  108945     vivaldi    the four seasons      <NA>     2951286  Vivaldi the four seasons  Antonio Vivaldi  Antonio Vivaldi, Gidon Kremer, London Symphony Orchestra & Claudio Abbado          18.0   028947456728

   mb_year             match_type confidence_label  score  title_sim  artist_sim
0     2015  alias_enrichment_safe             None   90.5        NaN         NaN
1     2017  alias_enrichment_safe             None   92.0        NaN         NaN
2     2021  alias_enrichment_safe             None   90.5        NaN         NaN

In [394]:
import duckdb
import pandas as pd

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Build CDS-only enrichment records from still-unmatched rows
# ------------------------------------------------------------
# Comments:
# - This branch keeps clean CDS rows even if no confident MB link exists.
# - Since barcode is not available in your cds tables, we rely on:
#     * artist
#     * title
#     * cds_year
#     * tracks
#     * curation metadata
# - Goal:
#     produce a clean CDS-derived enrichment candidate table for thesis use.
# ------------------------------------------------------------

print("Creating cds_only_enrichment_candidates_v1...")

con.execute("""
    CREATE OR REPLACE TABLE cds_only_enrichment_candidates_v1 AS
    WITH base AS (
        SELECT
            s.cds_id,
            s.artist,
            s.title,
            s.pipeline_status,

            c.curation_route,
            c.enrichment_priority_v6,
            c.artist_key_clean,
            c.title_key_clean,
            c.cds_year,
            c.tracks,
            c.is_mojibake,
            c.is_various_artists,
            c.has_disc_cd_vol,
            c.is_generic_title,

            length(coalesce(c.artist_key_clean, '')) AS artist_key_len,
            length(coalesce(c.title_key_clean, '')) AS title_key_len
        FROM cds_enrichment_master_status s
        JOIN cds_unmatched_curated_v1 c
          ON s.cds_id = c.cds_id
        WHERE s.pipeline_status = 'still_unmatched'
    )
    SELECT
        cds_id,
        artist,
        title,
        cds_year,
        tracks,
        curation_route,
        enrichment_priority_v6,
        artist_key_clean,
        title_key_clean,

        CASE
            WHEN cds_year IS NOT NULL AND tracks IS NOT NULL AND trim(tracks) <> '' THEN 'metadata_plus_tracks'
            WHEN cds_year IS NOT NULL THEN 'metadata_only'
            ELSE 'title_artist_only'
        END AS cds_enrichment_type,

        'cds_only_enrichment' AS enrichment_source
    FROM base
    WHERE
        coalesce(is_mojibake, 0) = 0
        AND artist IS NOT NULL
        AND trim(artist) <> ''
        AND title IS NOT NULL
        AND trim(title) <> ''
        AND NOT (
            coalesce(artist_key_len, 0) < 3
            AND coalesce(title_key_len, 0) < 3
        )
""")

print("✅ Table created: cds_only_enrichment_candidates_v1")

print("\n--- CDS-only enrichment count ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM cds_only_enrichment_candidates_v1
""").fetchdf())

print("\n--- Breakdown by enrichment type ---")
print(con.execute("""
    SELECT cds_enrichment_type, COUNT(*) AS n
    FROM cds_only_enrichment_candidates_v1
    GROUP BY cds_enrichment_type
    ORDER BY n DESC
""").fetchdf())

print("\n--- Breakdown by curation route ---")
print(con.execute("""
    SELECT curation_route, COUNT(*) AS n
    FROM cds_only_enrichment_candidates_v1
    GROUP BY curation_route
    ORDER BY n DESC
""").fetchdf())

print("\n--- Preview: CDS-only enrichment candidates ---")
print(con.execute("""
    SELECT
        cds_id,
        artist,
        title,
        cds_year,
        tracks,
        curation_route,
        enrichment_priority_v6,
        cds_enrichment_type
    FROM cds_only_enrichment_candidates_v1
    LIMIT 30
""").fetchdf())

Connected ✅
Creating cds_only_enrichment_candidates_v1...
✅ Table created: cds_only_enrichment_candidates_v1

--- CDS-only enrichment count ---
      n
0  4916

--- Breakdown by enrichment type ---
    cds_enrichment_type     n
0  metadata_plus_tracks  2488
1     title_artist_only  2428

--- Breakdown by curation route ---
              curation_route     n
0        standard_enrichment  3267
1      special_various_route   896
2  special_disc_cd_vol_route   563
3                      other   166
4         careful_enrichment    24

--- Preview: CDS-only enrichment candidates ---
    cds_id                        artist                                                                         title  cds_year  \
0   100004                       emanuel                                                                    felicidade      1998
1   100007               various artists                                                                     nop pop 2      2002
2   100009                        4 p m                                                                     sweet soul      2001
3   100017                       various                                                      micmac house dance party      1996
4   100025  variousce italiennes disc 1   la dolce vita les tubes dance italiens les chansons dance italiennes disc 1       <NA>
5   100028               jazz signatures                                                               jazz signatures      1998
6   100029           bernadã te bidã ude                                                                 pomme d amour      <NA>
7   100032                         v8 5e                                                                         v8 5e      <NA>
8   100036                      dj irish                                                         assorted trance vol 8      2003
9   100038       rennie pilgrim presents                                                             nu skool breakz 2      <NA>
10  100041                   italo house                                                                   12 in mixes      <NA>
11  100044                       various                                                               custom music cd      <NA>
12  100045               matsuka phonics                                                         let s study phonics 2      2002
13  100046                    kool savas                                                     euer bester freund mix cd      2004
14  100047                      robotika                                                                         dance      <NA>
15  100048                  the breeders                                                                           pod      1990
16  100049               johnny hallyday                                                                         vol 4      <NA>
17  100050                       phallus                                                                        reason      2003
18  100052                rolling stones                                                 giant stadium 17 08 1994 cd 2      1994
19  100055                       nakama1                                                              cd5 chapters 8 9      <NA>
20  100056               various artists                                            essential selection winter 97 cd1       1997
21  100060                       various                                                         windhamhillsampler 92      <NA>
22  100062            in vanity we trust                                                                          posh      1999
23  100063               various artists                               an audio cd of african american oral traditions      <NA>
24  100068                  diversetion               zeitgeist the psychedelic shack future funk and beatsploitation       <NA>
25  100069             nikos hatzopoulos                                                             the aegean violin      1996
26  100070                   perseguidos                                                                           iii      2004
27  100072         various artistsry cd2                               ministry of sound sessions eight todd terry cd2      1997
28  100073                     les vamps                                                                    2 eme show      <NA>
29  100075                buster b jones                                                          ballads barn burners      1999

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     tracks  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             felicidade quando o telefone toca vem bailar o tic tic quero que sejas minha e de mais ninguem eu sei que me amas o melhor que hã minha vizinha deixa me a bater mal s joã o ã foliã o sã³ quero o teu carinho tudo farei para ter a tua paixã o serã s sempre minha vem bailar o tic tic verã ã o dance mix
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             golden boy miss kittin rippin kittin norther lite treat me better peaches lovertits mã rtini brã s flash kristall das leben im jetzt slam lifetimes autotune capital killers e man animal skin marc verbos special friend lasse lundmark coca bass flash und gordon frauen in autos dan maxem vs polygen tiefoderhoch green velvet la la land frank mã¼ller vs takkyu ishino
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    miagetegoran yoruno hoshio woman cherish tears in heaven so much in love christmas eve too much heaven i left my heart in san francisco the lady in my life christmas medley the star spangled banner
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   colonel abrams i m caught up zhana can t stop dancin camille my love will set you free bmc a night at the m vol 2 no joke feel the music house factor movin and groovin diva diva boy i told you so hippie culture accelerator can you feel it mixmaster love machine d j professor runner supreme mind it s over now motivation featuring lee truesdale keep in touch
4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             boys summertime love sabrina one for you one for me la bionda i m a lover andrea dolce vita ryan paris tarzan boy jungle boy masterpiece gazebo comanchero moon ray don t cry tonight savage disco band scotch around my dream silver pozzoli future brain den harrow b project pink project
5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      duke ellington take the a train artie shaw begin the beguine glenn miller in the mood duke ellington mood indigo fats waller ain t misbehavin jelly roll morton orginal jelly roll blues louis armstrong basin street blues original dixieland jazz band tiger rag dizzy gillespie night in tunisia benny goodman sing sing sing duke ellington cotton tail coleman hawkins body and soul lena horne stormy weather
6                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ouverture margot les paroles gelã es le banquet belle d un bord adã le trente six pã pins la quãªte d adã le ambroise le pommier extraordinaire la quãªte d ambroise retour en gã tine
7                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              3 l f4o1b8 3 8 3 8 c 3d h z 32 3j8 88g 3j g bx0 n5r l 0hhw8i g6 o 190 3 g6 gr6 1nav so in love if you want my lovin pass me the mic someday
8                                                                                                                                                                                                                                                                                                                                                                                                                                        1 leama requiem for a dream leama s dream mix perfecto 2 quantum mechanics entrophy underworld recordings 3 planisphere hosanna green martian 4 york the awakening hiver hammer remix liquid music 5 andy jay powell mike nero skyliner hiver hammer remix audioplast 6 freebase shiva my angel mix xtc 7 green martian wizardry tranceportation 8 queen vanguard flash tomcraft remix frisbee tracks 9 gtr vs the shrink nervous breakdown gtr trance mix essential dance music 10 paul kershaw god s children pants corset remix sundissential 11 jon the dentist atto secondo phoenix uprising
9                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               01 jaguar odyssey 02 waveform breakers in space dat remix 03 mr nex 4 k l 04 katerpilla dropzone exclusive 05 solid ground overhead kick exclusive remix 06 world of crime war on electro 07 boundarie hunters be bop exclusive 08 thursday club teisted exclusive 09 meat katie cant hear ya 10 fred nasty hype verse exclusive 11 subphonic vega beach party 12 uptown connection renegades original mix
10                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       rfx dr felix relax your body fpi project going back to my roots double dee feat dany found love african business african business secchi feat orlando johnson i say yeah wareband feat ted robinson party children tc 1992 funky guitar tfo feat dj f farfa just keep in your love jk you make me feel good glam hell s party sharon s wonderful alex party alex party giorgio prezioso get on up
11                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       angelina you re all that i need atlantic star masterpiece cd 2 track 3 cd 2 track 6 cd 2 track 14 atlantic star i ll remember you for real for all of my life cd 4 track 11 cd 4 track 10 subway and 702 this little game we play lannie s amanda perez god send me an angel inoj rather be alone genuine my pony
12                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          alphabet song phonics alpahbet p1 p2 p3 p4 p5 p6 p7 p8 p9 p10 p11 p15 p16 magic e song p17 18 p18 p19 20 p20 p21 22 p22 p23 p24 p25 p26 p27 p28 p29 p30 31 p32 digraphs p33 p34 p35 p36 p37 p38 p39 p42 p43 p44 p45 p46 47 p48
13                                                                                                                                                                                        comet intro hã nde hoch intro no transatlantic remix fehdehandschuh skit dj rauchstyles ein rhyme early this morning kauf kauf ich weiãÿ nicht wie skit dj rauchstyles no 1 merkst du was dunne moment of ein mann armee neongelb joe budden lumidee skit fuck peter bei mir d u t katch blend elefanten rap de radio freestyle old school good in us nein live skit deutschland nr 1 fick uns boyz in da hood boom skit amar 16 bars voodoo therapie bauernhof optik boom lass rap wenn acapella kã nig von deutschland keiner auãÿer uns kiss fm hooo x und quer ready to rumple warum rappst du usa brechen das schweigen bitte spitte tash skit 10 gebote renexekution renexekution live weg zum ziel eon skit that smut changes ercandize wir sind profis maceo of de la soul sd tat tag egal was du tust ashanti rmx urban radio mya outro

In [395]:
import duckdb
import pandas as pd

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Rebuild CDS-only enrichment scoring table with all needed fields
# ------------------------------------------------------------
# Comments:
# - The previous error happened because is_generic_title was not
#   carried into cds_only_enrichment_scored_v1.
# - We rebuild the scoring table from cds_only_enrichment_candidates_v1
#   and join back to cds_unmatched_curated_v1 to recover the missing
#   curation flags.
# - Then we create a professional 3-way split:
#     1) safe
#     2) review
#     3) weak
print("Rebuilding CDS-only enrichment scoring table...")

con.execute("""
    CREATE OR REPLACE TABLE cds_only_enrichment_scored_v1 AS
    SELECT
        e.*,

        -- Recover curation flags from the curated unmatched table
        c.is_generic_title,
        c.is_various_artists,
        c.has_disc_cd_vol,
        c.is_mojibake,

        -- Basic key lengths
        length(coalesce(e.artist_key_clean, '')) AS artist_key_len,
        length(coalesce(e.title_key_clean, '')) AS title_key_len,

        -- ----------------------------------------------------
        -- Structural usability:
        -- keep only records with minimally informative artist/title
        -- ----------------------------------------------------
        CASE
            WHEN coalesce(c.is_mojibake, 0) = 1 THEN 0
            WHEN coalesce(e.artist_key_clean, '') = '' THEN 0
            WHEN coalesce(e.title_key_clean, '') = '' THEN 0
            WHEN length(coalesce(e.artist_key_clean, '')) < 3 THEN 0
            WHEN length(coalesce(e.title_key_clean, '')) < 4 THEN 0
            WHEN regexp_matches(trim(coalesce(e.title, '')), '^[0-9]+$') THEN 0
            ELSE 1
        END AS structurally_usable,

        -- ----------------------------------------------------
        -- Metadata strength:
        -- stronger if year and track-like info are present
        -- ----------------------------------------------------
        CASE
            WHEN e.cds_year IS NOT NULL
                 AND e.tracks IS NOT NULL
                 AND trim(coalesce(e.tracks, '')) <> ''
            THEN 2
            WHEN e.cds_year IS NOT NULL
            THEN 1
            ELSE 0
        END AS metadata_strength,

        -- ----------------------------------------------------
        -- Generic-title flag at scoring stage:
        -- catches generic titles even if source flag was not enough
        -- ----------------------------------------------------
        CASE
            WHEN lower(trim(coalesce(e.title, ''))) IN (
                'live', 'dance', 'piano', 'pod',
                'vol 1', 'vol 2', 'vol 3', 'vol 4',
                'cd1', 'cd2', 'cd3', 'cd4'
            ) THEN 1
            WHEN regexp_matches(lower(trim(coalesce(e.title, ''))), '^vol[ ]*[0-9]+$') THEN 1
            WHEN regexp_matches(lower(trim(coalesce(e.title, ''))), '^cd[ ]*[0-9]+$') THEN 1
            ELSE 0
        END AS generic_title_rule
    FROM cds_only_enrichment_candidates_v1 e
    LEFT JOIN cds_unmatched_curated_v1 c
      ON e.cds_id = c.cds_id
""")

print("✅ Table rebuilt: cds_only_enrichment_scored_v1")

# ------------------------------------------------------------
# Safe CDS-only enrichment
# ------------------------------------------------------------
# Comments:
# - High precision subset
# - Standard route only
# - High priority only
# - Strong metadata
# - No generic-title evidence
print("Creating cds_only_enrichment_safe_v1...")

con.execute("""
    CREATE OR REPLACE TABLE cds_only_enrichment_safe_v1 AS
    SELECT *
    FROM cds_only_enrichment_scored_v1
    WHERE
        structurally_usable = 1
        AND metadata_strength >= 2
        AND lower(coalesce(curation_route, '')) = 'standard_enrichment'
        AND lower(coalesce(enrichment_priority_v6, '')) = 'high'
        AND coalesce(is_generic_title, 0) = 0
        AND coalesce(generic_title_rule, 0) = 0
        AND coalesce(is_various_artists, 0) = 0
""")

# ------------------------------------------------------------
# Review CDS-only enrichment
# ------------------------------------------------------------
# Comments:
# - Still usable
# - But weaker metadata, special route, or more ambiguity
print("Creating cds_only_enrichment_review_v1...")

con.execute("""
    CREATE OR REPLACE TABLE cds_only_enrichment_review_v1 AS
    SELECT *
    FROM cds_only_enrichment_scored_v1
    WHERE
        structurally_usable = 1
        AND cds_id NOT IN (
            SELECT cds_id FROM cds_only_enrichment_safe_v1
        )
""")

# ------------------------------------------------------------
# Weak CDS-only enrichment
# ------------------------------------------------------------
# Comments:
# - Remaining rows not reliable enough for active enrichment use
print("Creating cds_only_enrichment_weak_v1...")

con.execute("""
    CREATE OR REPLACE TABLE cds_only_enrichment_weak_v1 AS
    SELECT *
    FROM cds_only_enrichment_scored_v1
    WHERE
        cds_id NOT IN (
            SELECT cds_id FROM cds_only_enrichment_safe_v1
        )
        AND cds_id NOT IN (
            SELECT cds_id FROM cds_only_enrichment_review_v1
        )
""")

print("✅ Tables created:")
print("   - cds_only_enrichment_safe_v1")
print("   - cds_only_enrichment_review_v1")
print("   - cds_only_enrichment_weak_v1")

print("\n--- CDS-only split summary ---")
print(con.execute("""
    SELECT 'safe' AS bucket, COUNT(*) AS n FROM cds_only_enrichment_safe_v1
    UNION ALL
    SELECT 'review' AS bucket, COUNT(*) AS n FROM cds_only_enrichment_review_v1
    UNION ALL
    SELECT 'weak' AS bucket, COUNT(*) AS n FROM cds_only_enrichment_weak_v1
""").fetchdf())

print("\n--- Breakdown of SAFE by enrichment type ---")
print(con.execute("""
    SELECT cds_enrichment_type, COUNT(*) AS n
    FROM cds_only_enrichment_safe_v1
    GROUP BY cds_enrichment_type
    ORDER BY n DESC
""").fetchdf())

print("\n--- Preview: safe CDS-only enrichment rows ---")
print(con.execute("""
    SELECT
        cds_id,
        artist,
        title,
        cds_year,
        tracks,
        curation_route,
        enrichment_priority_v6,
        cds_enrichment_type
    FROM cds_only_enrichment_safe_v1
    LIMIT 30
""").fetchdf())

print("\n--- Preview: review CDS-only enrichment rows ---")
print(con.execute("""
    SELECT
        cds_id,
        artist,
        title,
        cds_year,
        tracks,
        curation_route,
        enrichment_priority_v6,
        cds_enrichment_type
    FROM cds_only_enrichment_review_v1
    LIMIT 30
""").fetchdf())

Connected ✅
Rebuilding CDS-only enrichment scoring table...
✅ Table rebuilt: cds_only_enrichment_scored_v1
Creating cds_only_enrichment_safe_v1...
Creating cds_only_enrichment_review_v1...
Creating cds_only_enrichment_weak_v1...
✅ Tables created:
   - cds_only_enrichment_safe_v1
   - cds_only_enrichment_review_v1
   - cds_only_enrichment_weak_v1

--- CDS-only split summary ---
   bucket     n
0    safe  1652
1  review  3068
2    weak   196

--- Breakdown of SAFE by enrichment type ---
    cds_enrichment_type     n
0  metadata_plus_tracks  1652

--- Preview: safe CDS-only enrichment rows ---
    cds_id                                        artist                                     title  cds_year  \
0   100004                                       emanuel                                felicidade      1998
1   100009                                        4 p m                                 sweet soul      2001
2   100028                               jazz signatures                           jazz signatures      1998
3   100045                               matsuka phonics                     let s study phonics 2      2002
4   100046                                    kool savas                 euer bester freund mix cd      2004
5   100050                                       phallus                                    reason      2003
6   100062                            in vanity we trust                                      posh      1999
7   100069                             nikos hatzopoulos                         the aegean violin      1996
8   100075                                buster b jones                      ballads barn burners      1999
9   100077                                 franz lambert  franz lambert spielt beliebte evergreens      1977
10  100085                                        primus                                 juletoner      1995
11  100090                                     gauchesco                                 mano lima      2002
12  100091                                 marco pereira                                    elegia      1990
13  100095                                 peder persson                               fã dselfest      2001
14  100100                                 sofi marinova                            osadena liubov      2002
15  100106                                      dunaways                             beautiful day      2003
16  100110                                       ciãºnas                              celtic tiger      2001
17  100111                                 isle of light                           winters welcome      2002
18  100112                                    holly near                      simply love disc one      2000
19  100115                                      lj booth                the ox that pulls the cart      2002
20  100123                     eugene cole and persuaded                       he will work it out      1999
21  100127  franco bleve canto antico della nostra terra                        canzoni brindisine      1989
22  100129                                   fnac choice                           salute flamenco      2003
23  100142                                 garth wilwand                     eyes of the hurricane      2001
24  100145                                        guzman                            guzmã n y cã a      1998
25  100147                                  flipper dave                              flipper dave      1995
26  100154                                   james durst                             like the wind      2000
27  100155                                   konstantina                   i kaliteres stigmes mou      1997
28  100157                                  ivy markaity                    world s not big enough      1997
29  100158                                     cucunandy                           contented minds      2001

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               tracks  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       felicidade quando o telefone toca vem bailar o tic tic quero que sejas minha e de mais ninguem eu sei que me amas o melhor que hã minha vizinha deixa me a bater mal s joã o ã foliã o sã³ quero o teu carinho tudo farei para ter a tua paixã o serã s sempre minha vem bailar o tic tic verã ã o dance mix
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              miagetegoran yoruno hoshio woman cherish tears in heaven so much in love christmas eve too much heaven i left my heart in san francisco the lady in my life christmas medley the star spangled banner
2                                                                                                                                                                                                                                                                                                                                                                                                                                duke ellington take the a train artie shaw begin the beguine glenn miller in the mood duke ellington mood indigo fats waller ain t misbehavin jelly roll morton orginal jelly roll blues louis armstrong basin street blues original dixieland jazz band tiger rag dizzy gillespie night in tunisia benny goodman sing sing sing duke ellington cotton tail coleman hawkins body and soul lena horne stormy weather
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     alphabet song phonics alpahbet p1 p2 p3 p4 p5 p6 p7 p8 p9 p10 p11 p15 p16 magic e song p17 18 p18 p19 20 p20 p21 22 p22 p23 p24 p25 p26 p27 p28 p29 p30 31 p32 digraphs p33 p34 p35 p36 p37 p38 p39 p42 p43 p44 p45 p46 47 p48
4   comet intro hã nde hoch intro no transatlantic remix fehdehandschuh skit dj rauchstyles ein rhyme early this morning kauf kauf ich weiãÿ nicht wie skit dj rauchstyles no 1 merkst du was dunne moment of ein mann armee neongelb joe budden lumidee skit fuck peter bei mir d u t katch blend elefanten rap de radio freestyle old school good in us nein live skit deutschland nr 1 fick uns boyz in da hood boom skit amar 16 bars voodoo therapie bauernhof optik boom lass rap wenn acapella kã nig von deutschland keiner auãÿer uns kiss fm hooo x und quer ready to rumple warum rappst du usa brechen das schweigen bitte spitte tash skit 10 gebote renexekution renexekution live weg zum ziel eon skit that smut changes ercandize wir sind profis maceo of de la soul sd tat tag egal was du tust ashanti rmx urban radio mya outro
5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      save us reason seviin monster take it back hello there virginity creature of hate invaluable angry ocean killing time monster
6                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                save the planet what s your excuse medusa and venus is vanity fair mend raw heavenly rebellion no space holding her pen touch now be untouched hidden treasure read me poetry ladida life no return once forgotten longed for twice
7                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  horos vlaha tzivaeri o perivolaris o katifes kalamatiano avgis o michanikos mi matzore ta paidia tis geitonias sou atzitzies roussiko balos to la
8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        alabama jubilee three string swing sir thomas letty mostly merle ask john buster b boogie frere jacques guitarville just another rag le minuet lefty misdirected energy merci marcel skippy
9                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  musik ist trumpf april in portugal wir wir haben ein klavier warum mã¼ssen jahre vergeh n hey das ist musik fã¼r dich see you later alligator blinky wenn mademoiselle dich kã¼ãÿt western saloon moskau by night italy melody puppet on a string
10                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   glã d dig du jord glade jul dejlige jul kom alle kristne jesus oh what a wonderful child nã r juleklokken kimer the greatest miracle englekor pã nattehimmel christ is born en rose sã jed skyde den yndigste rose er funden reflekser emmanuel
11                                                                                                                                                                                                                                                                                                                                                                                                                                                                               mano lima sem paia e sem fumo mano lima cuiãºdo da varsea mano lima estancia da anarquia mano lima tumbeiro mano lima ave maria mano lima america do sul mano lima clone do lobizome mano lima quando eu crescer mano lima dom santana mano lima depois do andador mano lima finado cascudo mano lima ariguã e mucunfa da estancia do cambuxim mano lima tronqueira
12                                                                                                                                                                                                                                                                                                                                                       marco pereira samba urbano canhoto da paraiba imagem marco pereira marco pereira flor das aguas garoto jorge da fusa marco pereira marco pereira ladeira de sao roque canhoto da paraiba com mais de mil marco pereira marco pereira elegia marco pereira bate coxa pixinguinha carinhoso marco pereira garoto desvairada marco pereira joã o pernambuco sons de carrilhoes marco pereira dilermando reis valsa brasileira marco pereira ze do norte mulher rendeira fantasia marco pereira
13                                                                                                                                                                                                                                                                                                                                                                                                                               peder persson fã dselfest peder persson stã r hon kvar peder persson mattis nattvisa peder persson sparvens sã ng peder persson myjjy va ales peder persson gã nglã t till vã stsã tern peder persson klagolã t frã n en ko peder persson min sommarsã ng peder persson nã r musslan dã r peder persson noname peder persson framtiden ã r ã nnu kvar peder persson ã st trã nder peder persson sovsã ng till albin
14                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   edin jivot ne stiga osadena liubov nemil nedrag zashto si tuk zaklinanie sviato chudo bozhi dar pustinia talisman eh myje taina
15                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    beautiful day i ll cry all my teardrops god s not finished with me yet calvary still touches me cross on the side of the road the old country church he answered your prayer i ve drawn the line i still trust you god will move both ways welcome back the king welcome back the king reprise
16                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                celtic tiger three jigs i know my love the long black veil o carolan s concerto that london winter dunmore lassies siãºil a rãºin glenside polkas the jug of punch the bridge of tears willie taylor river of gems
17                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  we ve got to have love snow on the hills the toboggan run winter s welcome apples in winter winter apples we will two whistles in two hands voice of many waters crested hens peace like a snowfall road to lisdoonvarna julia delaney meets don quixote fig under the mistletoe

In [396]:
import duckdb
import pandas as pd

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Final master participation/status table for thesis reporting
# ------------------------------------------------------------
# Comments:
# - This table summarizes the final outcome of the full pipeline.
# - Each CDS row is assigned to one final bucket:
#     1) matched_automatic
#     2) matched_review_candidate
#     3) cds_only_safe
#     4) cds_only_review
#     5) weak_or_excluded
#     6) unresolved
print("Creating cds_final_master_status_v1...")

con.execute("""
    CREATE OR REPLACE TABLE cds_final_master_status_v1 AS
    WITH base AS (
        SELECT
            cds_id,
            artist,
            title
        FROM cds
    )
    SELECT
        b.cds_id,
        b.artist,
        b.title,

        CASE
            WHEN m.cds_id IS NOT NULL THEN 'matched_automatic'
            WHEN r.cds_id IS NOT NULL THEN 'matched_review_candidate'
            WHEN s.cds_id IS NOT NULL THEN 'cds_only_safe'
            WHEN rv.cds_id IS NOT NULL THEN 'cds_only_review'
            WHEN w.cds_id IS NOT NULL THEN 'weak_or_excluded'
            ELSE 'unresolved'
        END AS final_status

    FROM base b
    LEFT JOIN cds_to_mb_final_mapping_v9 m
      ON b.cds_id = m.cds_id
    LEFT JOIN cds_to_mb_review_candidates_v6_round2 r
      ON b.cds_id = r.cds_id
    LEFT JOIN cds_only_enrichment_safe_v1 s
      ON b.cds_id = s.cds_id
    LEFT JOIN cds_only_enrichment_review_v1 rv
      ON b.cds_id = rv.cds_id
    LEFT JOIN cds_only_enrichment_weak_v1 w
      ON b.cds_id = w.cds_id
""")

print("✅ Table created: cds_final_master_status_v1")

print("\n--- Final status summary ---")
print(con.execute("""
    SELECT
        final_status,
        COUNT(*) AS n,
        ROUND(100.0 * COUNT(*) / (SELECT COUNT(*) FROM cds), 2) AS pct
    FROM cds_final_master_status_v1
    GROUP BY final_status
    ORDER BY n DESC
""").fetchdf())

print("\n--- Preview: final master status table ---")
print(con.execute("""
    SELECT *
    FROM cds_final_master_status_v1
    LIMIT 30
""").fetchdf())

Connected ✅
Creating cds_final_master_status_v1...
✅ Table created: cds_final_master_status_v1

--- Final status summary ---
               final_status     n    pct
0         matched_automatic  4214  43.16
1           cds_only_review  3065  31.39
2             cds_only_safe  1652  16.92
3                unresolved   593   6.07
4          weak_or_excluded   196   2.01
5  matched_review_candidate    43   0.44

--- Preview: final master status table ---
    cds_id                artist                            title       final_status
0    10000       backstreet boys                       millennium  matched_automatic
1   100001               various      frankfurt trance vol 04 cd1  matched_automatic
2   100002             no return                  self mutilation  matched_automatic
3   100006      luv lite massive                         one love  matched_automatic
4   100008                  dmbq                             dmbq  matched_automatic
5   100010               various      frankfurt trance vol 05 cd1  matched_automatic
6   100012    rumania montevideo                 mo better tracks  matched_automatic
7   100015                 keedy                 chase the clouds  matched_automatic
8   100019            bill evans                            alone  matched_automatic
9   100020      nature destroyed                           shades  matched_automatic
10  100021             pearl jam                            yield  matched_automatic
11  100022     dingdong avanzado    the best of dingdong avanzado  matched_automatic
12  100024                  175r                            songs  matched_automatic
13  100026    day after tomorrow                         elements  matched_automatic
14  100031               spartak                            golem  matched_automatic
15  100035                gazebo               the best of gazebo  matched_automatic
16  100037  sportfreunde stiller                   die gute seite  matched_automatic
17  100039               various            salsaenlacalleocho 96  matched_automatic
18  100040     barbara streisand                 a love like ours  matched_automatic
19  100058             green day                           dookie  matched_automatic
20  100064                savage                          tonight  matched_automatic
21  100065      atmo brtschitsch                 change your life  matched_automatic
22  100066            del amitri                          twisted  matched_automatic
23  100082         barry mcguire               eve of destruction  matched_automatic
24  100087         tschou zã me                         wã ge dir  matched_automatic
25  100088         clive gregson                  comfort and joy  matched_automatic
26  100089       various artists                   dorival caymmi  matched_automatic
27  100094            keri noble                         fearless  matched_automatic
28  100097           north cregg                summer at my feet  matched_automatic
29  100099    fabienne thibeault  les plus belles chansons cd 2 2  matched_automatic

In [397]:
import duckdb
from pathlib import Path

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

export_dir = Path("../data_processed/exports/final_thesis_outputs")
export_dir.mkdir(parents=True, exist_ok=True)

tables_to_export = [
    "cds_to_mb_final_mapping_v9",
    "cds_only_enrichment_safe_v1",
    "cds_only_enrichment_review_v1",
    "cds_final_master_status_v1",
    "cds_only_enrichment_weak_v1"
]

for table in tables_to_export:
    out_path = export_dir / f"{table}.csv"
    con.execute(f"""
        COPY {table}
        TO '{out_path.as_posix()}'
        (HEADER, DELIMITER ',')
    """)
    print(f"✅ Exported: {out_path}")

print("\nDone.")

Connected ✅
✅ Exported: ..\data_processed\exports\final_thesis_outputs\cds_to_mb_final_mapping_v9.csv
✅ Exported: ..\data_processed\exports\final_thesis_outputs\cds_only_enrichment_safe_v1.csv
✅ Exported: ..\data_processed\exports\final_thesis_outputs\cds_only_enrichment_review_v1.csv
✅ Exported: ..\data_processed\exports\final_thesis_outputs\cds_final_master_status_v1.csv
✅ Exported: ..\data_processed\exports\final_thesis_outputs\cds_only_enrichment_weak_v1.csv

Done.

In [36]:
import duckdb
import pandas as pd

# Connect to DuckDB
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Build a thesis-friendly enriched version of the final mapping
# ------------------------------------------------------------
# Comments:
# - cds_to_mb_final_mapping_v9 is the core linkage table.
# - Here we join it back to the original CDS source table so the final
#   export also contains the CDS-side metadata:
#       cds_id, artist, title, cds_year, category, genre, tracks
# - This creates a denormalized output that is easier to read, export,
#   and use in the thesis.
print("Creating cds_to_mb_final_mapping_v9_enriched...")

con.execute("""
    CREATE OR REPLACE TABLE cds_to_mb_final_mapping_v9_enriched AS
    SELECT
        -- ----------------------------------------------------
        -- CDS-side source metadata
        -- ----------------------------------------------------
        c.cds_id,
        c.artist AS cds_artist,
        c.title AS cds_title,
        c.cds_year,
        c.category,
        c.genre,

        -- ----------------------------------------------------
        -- Final mapping fields
        -- ----------------------------------------------------
        m.release_id,
        m.release_title,
        m.main_artist_name,
        m.artist_credit_full,
        m.total_tracks,
        m.barcode,
        m.mb_year,
        m.match_type,
        m.score,
        c.tracks AS cds_tracklist,


    FROM cds_to_mb_final_mapping_v9 m
    LEFT JOIN cds c
      ON m.cds_id = c.cds_id
""")

print("✅ Table created: cds_to_mb_final_mapping_v9_enriched")

print("\n--- Row count ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM cds_to_mb_final_mapping_v9_enriched
""").fetchdf())

print("\n--- Preview ---")
print(con.execute("""
    SELECT *
    FROM cds_to_mb_final_mapping_v9_enriched
    LIMIT 20
""").fetchdf())

Connected ✅
Creating cds_to_mb_final_mapping_v9_enriched...
✅ Table created: cds_to_mb_final_mapping_v9_enriched

--- Row count ---
      n
0  4214

--- Preview ---
    cds_id            cds_artist                      cds_title  cds_year  \
0    10000       backstreet boys                     millennium      <NA>
1   100001               various    frankfurt trance vol 04 cd1      <NA>
2   100002             no return                self mutilation      <NA>
3   100006      luv lite massive                       one love      <NA>
4   100008                  dmbq                           dmbq      2002
5   100010               various    frankfurt trance vol 05 cd1      <NA>
6   100012    rumania montevideo               mo better tracks      <NA>
7   100015                 keedy               chase the clouds      <NA>
8   100019            bill evans                          alone      1968
9   100020      nature destroyed                         shades      <NA>
10  100021             pearl jam                          yield      1998
11  100022     dingdong avanzado  the best of dingdong avanzado      <NA>
12  100024                  175r                          songs      2003
13  100026    day after tomorrow                       elements      2003
14  100031               spartak                          golem      1990
15  100035                gazebo             the best of gazebo      <NA>
16  100037  sportfreunde stiller                 die gute seite      <NA>
17  100039               various          salsaenlacalleocho 96      <NA>
18  100040     barbara streisand               a love like ours      1999
19  100058             green day                         dookie      <NA>

        category           genre  release_id                  release_title  \
0          blues             pop        8069                     Millennium
1           data            None      190028               Frankfurt Trance
2           data            data       12737                Self Mutilation
3           data      electronic     1032522                       One Love
4           data            rock     1383710                           DMBQ
5           data            None      190028               Frankfurt Trance
6           data             pop      510936              MO' BETTER TRACKS
7           data            data       85239               Chase the Clouds
8           data            None      100846                          Alone
9           data            None      210151                         Shades
10          data       hard rock        5053                          Yield
11          data            None     5132677  The Best Of Dingdong Avanzado
12          data            jpop      435351                          Songs
13          data             pop       33014                       elements
14          data      electronic      362682                          Golem
15          data            None     1883940             The Best of Gazebo
16          data            data       37684                 Die gute Seite
17  sonytsid7008            data     2389539     Salsa en la calle Ocho '96
18          data  easy listening      667030               A Love Like Ours
19          data            None        2576                         Dookie

        main_artist_name    artist_credit_full  total_tracks        barcode  \
0        Backstreet Boys       Backstreet Boys          12.0   012414167224
1        Various Artists       Various Artists          22.0  4017866122667
2              No Return             No Return          11.0  3760053840271
3       Luv Lite Massive      Luv Lite Massive          11.0           None
4                   DMBQ                  DMBQ          12.0  4988064171996
5        Various Artists       Various Artists          22.0  4017866122667
6     rumania montevideo    rumania montevideo          12.0  4523949014809
7                  Keedy                 Keedy          10.0   078221864121
8             Bill Evans            Bill Evans          12.0   731458931928
9       Nature Destroyed      Nature Destroyed          10.0   718756222125
10             Pearl Jam             Pearl Jam          13.0   074646816424
11     Dingdong Avanzado     Dingdong Avanzado          12.0  4800626000462
12                  175R                  175R          11.0           None
13    day after tomorrow    day after tomorrow          24.0  4988064172252
14               Spartak               Spartak          11.0  4015698133523
15                Gazebo                Gazebo          16.0  4988017610893
16  Sportfreunde Stiller  Sportfreunde Stiller          13.0   731458965022
17       Various Artists       Various Artists          12.0           None
18      Barbra Streisand      Barbra Streisand          12.0   074646960127
19             Green Day             Green Day          14.0   093624552925

    mb_year          match_type       score  \
0      2016               exact   82.000000
1      2019  various_title_only  100.000000
2      2020               exact   82.000000
3      2016               exact   56.000000
4      2015               exact   82.000000
5      2019  various_title_only  100.000000
6      2009               exact   50.000000
7      2017               exact   82.000000
8      2010               exact   82.000000
9      2017               exact   82.000000
10     2017               exact   82.000000
11     2025               exact   82.000000
12     2019               exact   56.000000
13     2021               exact   82.000000
14     2020               exact   82.000000
15     2024               exact   82.000000
16     2014               exact   82.000000
17     2020  various_title_only   68.723404
18     2023   fuzzy_second_pass   98.756598
19     2023               exact   82.000000

                                        cds_tracklist
0   larger than life i want it that way show me th...
1   dj tom stevens vs fridge outface 2000 radio mi...
2   do or die truth and reality lost soul extracto...
3   temple of dehli from naw till a mornin shock a...
4   small hours rock a cola ohh baby teenage limbo...
5   dj tom stevens violet steam single cut liquid ...
6   i ll be with you hard rain free tender rain ra...
7   save some love wishing on the same star never ...
8   here s that rainy day a time for love midnight...
9   enter the realm dream of fear word of trust un...
10  brain of j faithfull no way given to fly wishl...
11  ikaw lamang tatlong beinte singko maghihintay ...
12  inst ã â â ã âºâº ã æ â œã æ â ã æ â¼ã æ â ã â...
13  high spirit time of destiny ã â šã â šå ã âµã ...
14  sigo viviendo leconseil lunaire naprzod vorwã ...
15  i like chopin lunatic masterpiece dolce vita t...
16  wie lange sollen wir noch warten komm schon ei...
17  1996 estamossolos jorgeluispiloto 1996 reyruiz...
18  i ve dreamed of you isn t it a pity the island...
19  burn out having a blast chump long view welcom...

In [37]:
import duckdb
import os

# Connect to DuckDB
con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# Make sure exports folder exists
os.makedirs("../data_processed/exports", exist_ok=True)

out_path = "../data_processed/exports/cds_to_mb_final_mapping_v9_enriched.csv"

# ------------------------------------------------------------
# Export thesis-friendly enriched final mapping
# ------------------------------------------------------------
con.execute(f"""
    COPY cds_to_mb_final_mapping_v9_enriched
    TO '{out_path}'
    WITH (HEADER, DELIMITER ',')
""")

print(f"✅ Exported: {out_path}")

Connected ✅
✅ Exported: ../data_processed/exports/cds_to_mb_final_mapping_v9_enriched.csv

In [40]:
import duckdb
import pandas as pd
import re

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Heuristic mojibake detector
# ------------------------------------------------------------
MOJIBAKE_PATTERN = re.compile(r"Ã|Â|â€™|â€œ|â€|ï¿½")

def looks_mojibake(text):
    if text is None:
        return False
    text = str(text)
    return bool(MOJIBAKE_PATTERN.search(text))

# ------------------------------------------------------------
# Try to repair common UTF-8/Latin-1 mojibake
# ------------------------------------------------------------
def try_fix_mojibake(text):
    if text is None:
        return None

    s = str(text)

    if not looks_mojibake(s):
        return s

    candidates = []

    # Method 1: latin1 -> utf8
    try:
        candidates.append(s.encode("latin1").decode("utf-8"))
    except Exception:
        pass

    # Method 2: cp1252 -> utf8
    try:
        candidates.append(s.encode("cp1252").decode("utf-8"))
    except Exception:
        pass

    # Method 3: repeated fix (sometimes double-broken)
    try:
        c = s.encode("latin1").decode("utf-8")
        candidates.append(c.encode("latin1").decode("utf-8"))
    except Exception:
        pass

    # Keep only plausible improvements
    def score_candidate(orig, cand):
        score = 0

        # Fewer mojibake markers is better
        score += orig.count("Ã") - cand.count("Ã")
        score += orig.count("Â") - cand.count("Â")
        score += orig.count("ï¿½") - cand.count("ï¿½")

        # Presence of real accented / non-ASCII chars can be good
        if any(ord(ch) > 127 for ch in cand):
            score += 1

        # Empty or weirdly tiny outputs are bad
        if len(cand.strip()) < max(1, len(orig.strip()) // 3):
            score -= 5

        return score

    best = s
    best_score = 0

    for cand in candidates:
        if cand and cand != s:
            sc = score_candidate(s, cand)
            if sc > best_score:
                best = cand
                best_score = sc

    return best if best_score > 0 else s

# ------------------------------------------------------------
# Load CDS into pandas
# ------------------------------------------------------------
df = con.execute("""
    SELECT
        cds_id,
        artist,
        title,
        tracks
    FROM cds
""").fetchdf()

print(f"Loaded rows: {len(df):,}")

# ------------------------------------------------------------
# Apply safe repair
# ------------------------------------------------------------
for col in ["artist", "title", "tracks"]:
    df[f"{col}_fixed"] = df[col].apply(try_fix_mojibake)
    df[f"{col}_was_fixed"] = (
        df[col].fillna("").astype(str) != df[f"{col}_fixed"].fillna("").astype(str)
    ).astype(int)

# ------------------------------------------------------------
# Register repaired dataframe and create repaired table
# ------------------------------------------------------------
con.register("cds_mojibake_fix_df", df)

con.execute("""
    CREATE OR REPLACE TABLE cds_repaired_text AS
    SELECT
        cds_id,

        artist,
        artist_fixed,
        artist_was_fixed,

        title,
        title_fixed,
        title_was_fixed,

        tracks,
        tracks_fixed,
        tracks_was_fixed
    FROM cds_mojibake_fix_df
""")

print("✅ Table created: cds_repaired_text")

print("\n--- Repair summary ---")
print(con.execute("""
    SELECT
        SUM(artist_was_fixed) AS artist_fixed_rows,
        SUM(title_was_fixed) AS title_fixed_rows,
        SUM(tracks_was_fixed) AS tracks_fixed_rows
    FROM cds_repaired_text
""").fetchdf())

print("\n--- Sample repaired rows ---")
print(con.execute("""
    SELECT
        cds_id,
        artist,
        artist_fixed,
        title,
        title_fixed
    FROM cds_repaired_text
    WHERE artist_was_fixed = 1
       OR title_was_fixed = 1
       OR tracks_was_fixed = 1
    LIMIT 30
""").fetchdf())

Connected ✅
Loaded rows: 9,763
✅ Table created: cds_repaired_text

--- Repair summary ---
   artist_fixed_rows  title_fixed_rows  tracks_fixed_rows
0                0.0               0.0                0.0

--- Sample repaired rows ---
Empty DataFrame
Columns: [cds_id, artist, artist_fixed, title, title_fixed]
Index: []

In [41]:
import duckdb
import pandas as pd
import re
import os

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# broader mojibake detector
MOJIBAKE_PATTERN = re.compile(
    r"Ã.|Â.|â.|ð.|œ|ž|›|‹|€™|€œ|€|™|ï¿½"
)

def looks_mojibake(text):
    if text is None:
        return False
    s = str(text)
    return bool(MOJIBAKE_PATTERN.search(s))

def try_fix_mojibake(text):
    if text is None:
        return None

    s = str(text)

    if not looks_mojibake(s):
        return s

    candidates = []

    # most common fix
    for enc in ("latin1", "cp1252"):
        try:
            candidates.append(s.encode(enc).decode("utf-8"))
        except Exception:
            pass

    # second pass for doubly-broken text
    for enc in ("latin1", "cp1252"):
        try:
            c1 = s.encode(enc).decode("utf-8")
            candidates.append(c1.encode(enc).decode("utf-8"))
        except Exception:
            pass

    def badness(x):
        if x is None:
            return 10**9
        x = str(x)
        penalties = 0
        penalties += x.count("Ã") * 3
        penalties += x.count("Â") * 3
        penalties += x.count("â") * 3
        penalties += x.count("ï¿½") * 5
        return penalties

    best = s
    best_badness = badness(s)

    for cand in candidates:
        if cand and cand != s:
            b = badness(cand)
            if b < best_badness:
                best = cand
                best_badness = b

    return best

df = con.execute("""
    SELECT cds_id, artist, title, tracks
    FROM cds
""").fetchdf()

for col in ["artist", "title", "tracks"]:
    df[f"{col}_fixed"] = df[col].apply(try_fix_mojibake)
    df[f"{col}_was_fixed"] = (
        df[col].fillna("").astype(str) != df[f"{col}_fixed"].fillna("").astype(str)
    ).astype(int)

con.register("cds_mojibake_fix_df", df)

con.execute("""
    CREATE OR REPLACE TABLE cds_repaired_text AS
    SELECT
        cds_id,
        artist,
        artist_fixed,
        artist_was_fixed,
        title,
        title_fixed,
        title_was_fixed,
        tracks,
        tracks_fixed,
        tracks_was_fixed
    FROM cds_mojibake_fix_df
""")

print("✅ Table recreated: cds_repaired_text")

print("\n--- Repair summary ---")
print(con.execute("""
    SELECT
        SUM(artist_was_fixed) AS artist_fixed_rows,
        SUM(title_was_fixed) AS title_fixed_rows,
        SUM(tracks_was_fixed) AS tracks_fixed_rows
    FROM cds_repaired_text
""").fetchdf())

print("\n--- Sample repaired rows ---")
print(con.execute("""
    SELECT
        cds_id,
        artist,
        artist_fixed,
        title,
        title_fixed
    FROM cds_repaired_text
    WHERE artist_was_fixed = 1
       OR title_was_fixed = 1
       OR tracks_was_fixed = 1
    LIMIT 30
""").fetchdf())

Connected ✅
✅ Table recreated: cds_repaired_text

--- Repair summary ---
   artist_fixed_rows  title_fixed_rows  tracks_fixed_rows
0                0.0               0.0                0.0

--- Sample repaired rows ---
Empty DataFrame
Columns: [cds_id, artist, artist_fixed, title, title_fixed]
Index: []

In [42]:
print(con.execute("""
    SELECT cds_id, artist, title
    FROM cds
    WHERE artist LIKE '%Ã%'
       OR artist LIKE '%Â%'
       OR title  LIKE '%Ã%'
       OR title  LIKE '%Â%'
    LIMIT 20
""").fetchdf())

Empty DataFrame
Columns: [cds_id, artist, title]
Index: []

In [43]:
broken = con.execute("""
    SELECT cds_id, artist, title, tracks
    FROM cds
    WHERE artist LIKE '%Ã%'
       OR artist LIKE '%Â%'
       OR title  LIKE '%Ã%'
       OR title  LIKE '%Â%'
       OR tracks LIKE '%Ã%'
       OR tracks LIKE '%Â%'
    LIMIT 20
""").fetchdf()

broken

Empty DataFrame
Columns: [cds_id, artist, title, tracks]
Index: []

In [44]:
broken = con.execute(r"""
    SELECT cds_id, artist, title, tracks
    FROM cds
    WHERE regexp_matches(coalesce(artist, ''), 'Ã|Â|â|ï¿½')
       OR regexp_matches(coalesce(title,  ''), 'Ã|Â|â|ï¿½')
       OR regexp_matches(coalesce(tracks, ''), 'Ã|Â|â|ï¿½')
    LIMIT 20
""").fetchdf()

broken

,cds_id,artist,title,tracks
0,100003,ã â â ã â ã â ºâ ã â å,ã æ â³ã â žã â âºã â ã â ¹ã â ã â šâ,ã â ºâ ã â â ã â šå ã â žã â ã â ¹ã â â ã â ã ...
1,100005,ã å â ã â ºâ ã â ºâ ºã â â,catsã â â ã â šâªã æ âªã â šâ ã æ å ã æ â ã â½...,ã æ â ã æ â ã æ âªã æ â¼ ã â šâªã æ â¼ã æ â ã ...
2,100011,â¾ã â â ã ãœ worship,child praise vol 1,ã ã â ã â³âªâ â â ã â â â½ãƒâ ã â ã ã ãš â³âªâ...
3,100014,modern talking,univers,tv makes the superstar iâ m no rockefeller mys...
4,100024,175r,songs,inst ã â â ã âºâº ã æ â œã æ â ã æ â¼ã æ â ã â...
5,100026,day after tomorrow,elements,high spirit time of destiny ã â šã â šå ã âµã ...
6,100027,v a,ãƒã âºâ¹ cd 09,â ã â ã ã ã ã ãœ â¼â â â³â ãœ ã ã â ã â³âªâ â ...
7,100030,ã â â ã â ã â â¾ã âµ,disc13 ã å â ã â ã â ¹ã â šå,ã å â ã â â ã â â ã â â ã â â½ã â ã â šã å ã â...
8,100034,ã â šã å â ã å å ã â â¾,lucy,lucy ã æ å¾ã æ â ã â šâ ã æ ã â šâ ã â šâ¹ã æ ...
9,100042,deux,forever,intor deux forever â³âªâ â âµâ¹â¾ã âºã â¾ã â ã...
10,100043,v a,beating surviver another,flash of love wild style qingdao ã âª ã â²â ã ...
11,100051,ã â â ã â å½ã â¾ã â ã â šë ã â,home,fat mama ã â šâ ã æ â ã æ â ã æ å ã æ âªã æ â³...
12,100057,ã ë â ã å â ã â šã â,infinity eighteen vol 1,intro identification track infinity 18 be toge...
13,100059,ã å â ã â²â ã â â ã â,super live ã â â ã å â ã â â ã â œã â â disc 1,introduction ã â â ã â â ã å ã â šâ žã â ã â š...
14,100067,â â ã ã â½âºã ã ã â,8th,01 â ã ã ã â ã â³â ã ãœ ã ã â¾ã 02 i can wait ...
15,100071,â ã ã ãÿâ ã ãˆâ¹,â ãµâºâ â ã âµâµâ â ã â ã ã â ã ã â½â¾ã 6,â ã â â âºâ ã ã â¾ã â â â ã â â â ã â½ã â½ã ã ...
16,100074,ã ã ã ã ã ã ãª,absolutã ã ã ã ãˆã 2,ã ãªã³ã ã ã ã²ã ã ã ã²ã ã ãšã ã ã ãªã ã ã ã ã ...
17,100083,â¼â¼â¹ãœã ã â¼ã â â â â¹â¾ã â¼â â â³â ãœ,â¼â¼â¹ãœã ã â¼ã â â,ã ã â ãƒã ã ãƒãšâ ã invite from the heaven ã ã...
18,100096,epo,poptracks,ã â â ã â âªã â ºâ ã â ã â¹â ã â º ã â žã â ã ...
19,100114,gerardo peã a,nada,aguacero el sapo entre comillas adiccion te qu...

In [45]:
print(con.execute(r"""
    SELECT artist
    FROM cds
    WHERE regexp_matches(coalesce(artist, ''), 'Ã|Â|â|ï¿½')
    LIMIT 20
""").fetchdf())

                                             artist
0                           ã â â ã â ã â ºâ ã â å
1                       ã å â ã â ºâ ã â ºâ ºã â â
2                              â¾ã â â ã ãœ worship
3                              ã â â ã â ã â â¾ã âµ
4                           ã â šã å â ã å å ã â â¾
5                   ã â â ã â å½ã â¾ã â ã â šë ã â
6                             ã ë â ã å â ã â šã â
7                            ã å â ã â²â ã â â ã â
8                              â â ã ã â½âºã ã ã â
9                                  â ã ã ãÿâ ã ãˆâ¹
10         â¼â¼â¹ãœã ã â¼ã â â â â¹â¾ã â¼â â â³â ãœ
11                             ã â ã â ã â¾ã â ã â
12                                      â ã â ã â j
13                             â â¹â¼ã ã ã¼âµâµâ ãœ
14                                          â½â²âµ
15  ãƒâ â dâ â ã ã ã â¼â â ã ã ã âªâ â ã ãžâºâ ã â
16                                       â³â â ã â
17                     ã â â ã â â¾ã ë ã â â ã â â¹
18             ã ã â â¹ã ã ã â¼â³ã ã â â½ãœâ¾ã ã ã
19                                    â kã nâ xâ ã

In [46]:
print(con.execute(r"""
    SELECT title
    FROM cds
    WHERE regexp_matches(coalesce(title, ''), 'Ã|Â|â|ï¿½')
    LIMIT 20
""").fetchdf())

                                                title
0               ã æ â³ã â žã â âºã â ã â ¹ã â ã â šâ
1   catsã â â ã â šâªã æ âªã â šâ ã æ å ã æ â ã â½...
2                                     ãƒã âºâ¹ cd 09
3                       disc13 ã å â ã â ã â ¹ã â šå
4      super live ã â â ã å â ã â â ã â œã â â disc 1
5           â ãµâºâ â ã âµâµâ â ã â ã ã â ã ã â½â¾ã 6
6                                â¼â¼â¹ãœã ã â¼ã â â
7                ã â â ã âºâºã â â¾ã â å ã â â ã âºå
8             ã â â ã â³â ã â ã â šâ ã song library 1
9                                     â sâ â â ã â ãº
10                                           ã ã â ã
11  euro darkness 1 ã â å the early days of sebã â å
12            â½â²âµ âªã â ã¹â lâ â³ã¼â â ã â²pâºqâ k
13                               ã ã â âºâµã ã ã â ã
14            ich mã chtâ so gern dein teddybã r sein
15                                            â ã¼â v
16                                     ã å ë ã â ã â
17                                     â â â iâ sãƒâ
18                              â¹ãœâ ã â â ã ã ãšâ 1
19                ã â ã âºâ ã æ â ã æ â ã æ â¼ã æ â ž

In [47]:
print(con.execute("""
    SELECT cds_id, artist, title, tracks
    FROM cds
    WHERE cds_id = 100257
""").fetchdf())

   cds_id  artist title                                             tracks
0  100257  yarkin   ten  bulmaca rã ngala ã ster 1 kayip kã mlã k vakas...

In [48]:
import duckdb
import pandas as pd

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

test_df = con.execute("""
    SELECT cds_id, artist, title, tracks
    FROM cds
    WHERE cds_id IN (100003, 100005, 100011, 100257)
""").fetchdf()

test_df

Connected ✅

,cds_id,artist,title,tracks
0,100003,ã â â ã â ã â ºâ ã â å,ã æ â³ã â žã â âºã â ã â ¹ã â ã â šâ,ã â ºâ ã â â ã â šå ã â žã â ã â ¹ã â â ã â ã ...
1,100005,ã å â ã â ºâ ã â ºâ ºã â â,catsã â â ã â šâªã æ âªã â šâ ã æ å ã æ â ã â½...,ã æ â ã æ â ã æ âªã æ â¼ ã â šâªã æ â¼ã æ â ã ...
2,100011,â¾ã â â ã ãœ worship,child praise vol 1,ã ã â ã â³âªâ â â ã â â â½ãƒâ ã â ã ã ãš â³âªâ...
3,100257,yarkin,ten,bulmaca rã ngala ã ster 1 kayip kã mlã k vakas...

In [49]:
def try_fix_chain(s):
    if s is None:
        return None

    s = str(s)
    out = {"original": s}

    # attempt 1
    try:
        out["latin1_to_utf8"] = s.encode("latin1").decode("utf-8")
    except Exception:
        out["latin1_to_utf8"] = None

    # attempt 2
    try:
        out["cp1252_to_utf8"] = s.encode("cp1252").decode("utf-8")
    except Exception:
        out["cp1252_to_utf8"] = None

    # attempt 3
    try:
        x = s.encode("latin1").decode("utf-8")
        out["double_latin1_to_utf8"] = x.encode("latin1").decode("utf-8")
    except Exception:
        out["double_latin1_to_utf8"] = None

    # attempt 4
    try:
        x = s.encode("cp1252").decode("utf-8")
        out["double_cp1252_to_utf8"] = x.encode("cp1252").decode("utf-8")
    except Exception:
        out["double_cp1252_to_utf8"] = None

    return out

for _, row in test_df.iterrows():
    print("\n" + "="*80)
    print("cds_id:", row["cds_id"])

    for col in ["artist", "title", "tracks"]:
        print(f"\n--- {col} ---")
        fixes = try_fix_chain(row[col])
        for k, v in fixes.items():
            print(f"{k}: {v}")

================================================================================
cds_id: 100003

--- artist ---
original: ã â â ã â ã â ºâ ã â å
latin1_to_utf8: None
cp1252_to_utf8: None
double_latin1_to_utf8: None
double_cp1252_to_utf8: None

--- title ---
original: ã æ â³ã â žã â âºã â ã â ¹ã â ã â šâ
latin1_to_utf8: None
cp1252_to_utf8: None
double_latin1_to_utf8: None
double_cp1252_to_utf8: None

--- tracks ---
original: ã â ºâ ã â â ã â šå ã â žã â ã â ¹ã â â ã â ã â¼å ã â ã å ã âªã â šâ ã â â ã â ã âªã â žã â â ã å ã â ã å ã â ã å ã â žã â ž ã âµã â šå ã â šã â ž ã â šã â š ã â ã ëœâ ã â âºã å ã â ã â ã â â ã â â½ã â žã â â ã å å¾ã â â ã â ã â ã â šâ ã â žã â â šã â â ã â å ã â å ã ë â ã â å ã â šã âªã å ã â šâ ã â žâ ºã â ã â šâ ¹ã â ã â ã ëœâ ã â²â ã â
latin1_to_utf8: None
cp1252_to_utf8: None
double_latin1_to_utf8: None
double_cp1252_to_utf8: None

================================================================================
cds_id: 100005

--- artist ---
original: ã å â ã â ºâ ã â ºâ ºã â â
latin1_to_utf8: None
cp1252_to_utf8: None
double_latin1_to_utf8: None
double_cp1252_to_utf8: None

--- title ---
original: catsã â â ã â šâªã æ âªã â šâ ã æ å ã æ â ã â½â ã â šâ ã æ â ã â šâ¹ã æ ë
latin1_to_utf8: None
cp1252_to_utf8: None
double_latin1_to_utf8: None
double_cp1252_to_utf8: None

--- tracks ---
original: ã æ â ã æ â ã æ âªã æ â¼ ã â šâªã æ â¼ã æ â ã â šâ ã æ ã æ â ã â šâ ã â šâ ã â šâ ã æ âªã â šâ ã æ â ã â šâ½ã æ â³ã â šâ ã æ ã æ â¼ã æ å ã æ â³ã â šâ ã æ â ã â šâªã æ â ã æ â ã â šâ ã æ â ã æ æ ã æ â ž ã ë â ã å â ã â ã ã â šâ ã â šâ ã æ â ¹ã â šâ ã æ â ¹ã æ â ã æ æ ã æ â ž ã ë â ã å ã â ã â ã â šâ œã å â ã æ â ã æ â ã æ â ã â šâ ã æ â ã æ â ã â šâ ã â šâ ã æ â¼ ã ë â ã â ã â ã â ã â šå ã å â ã â šâ ã æ âªã â šâ ã æ â ã æ â ã ë â ã â â¼ã â â ã å â ã æ ã â šâ¹ã æ ë ã æ â ã â šâ ã æ â¼ã â šâ ã æ â ã æ â¼ã æ â³ã â šâº ã ë â ã â â ã âºâºã â â ã â¼å ã æ å¾ã æ â³ã â šâ ã â šâ ã â šâ ã æ âªã æ â¼ã â ã æ â ã æ â³ã æ å ã æ â ã æ â ã â šâ ã æ â¼ã â šâ ã ë â ã â ã â³â ã â â ã æ â ã æ â ã æ ë ã æ â ã æ å½ã æ å ã æ â¼ ã ë â ã â â ã â ã å â ã â šâ ã â šâ ã æ âªã â šâ ã æ â ã ë å¾ã â ã â¼å ã æ â ã æ â ã æ âªã æ â¼
latin1_to_utf8: None
cp1252_to_utf8: None
double_latin1_to_utf8: None
double_cp1252_to_utf8: None

================================================================================
cds_id: 100011

--- artist ---
original: â¾ã â â ã ãœ worship
latin1_to_utf8: None
cp1252_to_utf8: None
double_latin1_to_utf8: None
double_cp1252_to_utf8: None

--- title ---
original: child praise vol 1
latin1_to_utf8: child praise vol 1
cp1252_to_utf8: child praise vol 1
double_latin1_to_utf8: child praise vol 1
double_cp1252_to_utf8: child praise vol 1

--- tracks ---
original: ã ã â ã â³âªâ â â ã â â â½ãƒâ ã â ã ã ãš â³âªâ ã â¹ã ã â½ã â â ãž â ã â ã ã ã â½ã ã ã â³âªâ ã give thanks â â¹â¼ã â ã â ã ã ã â½ã ã âº â ã â â ã ã â²â² â ã â âµã ã â ã â â â ã âµãž â¼ã â ã ã â â ã âºã ãƒãÿâ¼ã â¼â ãˆâ â ãªâ³âª ã ã â ã ã ã â½ãƒâ â â â â¼â â ã½â ã â ãº ã ã ã âº ãƒâµâ ã âµã â ã â ã â¼ã ã ã¹â¾ã ã ã
latin1_to_utf8: None
cp1252_to_utf8: None
double_latin1_to_utf8: None
double_cp1252_to_utf8: None

================================================================================
cds_id: 100257

--- artist ---
original: yarkin
latin1_to_utf8: yarkin
cp1252_to_utf8: yarkin
double_latin1_to_utf8: yarkin
double_cp1252_to_utf8: yarkin

--- title ---
original: ten
latin1_to_utf8: ten
cp1252_to_utf8: ten
double_latin1_to_utf8: ten
double_cp1252_to_utf8: ten

--- tracks ---
original: bulmaca rã ngala ã ster 1 kayip kã mlã k vakasi zeybek hã ha hu ã ster 2 gã z gã rãœãžmeyelã m sã s
latin1_to_utf8: None
cp1252_to_utf8: None
double_latin1_to_utf8: None
double_cp1252_to_utf8: None

In [50]:
import duckdb

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

con.execute("""
    CREATE OR REPLACE TABLE cds_tracks_cleaned_v1 AS
    SELECT
        cds_id,
        artist,
        title,
        cds_year,
        category,
        genre,
        tracks AS tracks_raw,

        trim(
            regexp_replace(
                regexp_replace(
                    regexp_replace(
                        regexp_replace(
                            coalesce(tracks, ''),
                            '[\\r\\n\\t]+', ' ', 'g'
                        ),
                        '\\s+', ' ', 'g'
                    ),
                    '[,;|/]{2,}', ' ', 'g'
                ),
                '\\s*([,;|/])\\s*', ' \\1 ', 'g'
            )
        ) AS tracks_clean

    FROM cds
""")

print("✅ Table created: cds_tracks_cleaned_v1")
print(con.execute("""
    SELECT cds_id, artist, title, tracks_raw, tracks_clean
    FROM cds_tracks_cleaned_v1
    LIMIT 10
""").fetchdf())

Connected ✅
✅ Table created: cds_tracks_cleaned_v1
   cds_id                       artist  \
0   10000              backstreet boys
1  100001                      various
2  100002                    no return
3  100003      ã â â ã â ã â ºâ ã â å
4  100004                      emanuel
5  100005  ã å â ã â ºâ ã â ºâ ºã â â
6  100006             luv lite massive
7  100007              various artists
8  100008                         dmbq
9  100009                       4 p m

                                               title  \
0                                         millennium
1                        frankfurt trance vol 04 cd1
2                                    self mutilation
3              ã æ â³ã â žã â âºã â ã â ¹ã â ã â šâ
4                                         felicidade
5  catsã â â ã â šâªã æ âªã â šâ ã æ å ã æ â ã â½...
6                                           one love
7                                          nop pop 2
8                                               dmbq
9                                         sweet soul

                                          tracks_raw  \
0  larger than life i want it that way show me th...
1  dj tom stevens vs fridge outface 2000 radio mi...
2  do or die truth and reality lost soul extracto...
3  ã â ºâ ã â â ã â šå ã â žã â ã â ¹ã â â ã â ã ...
4  felicidade quando o telefone toca vem bailar o...
5  ã æ â ã æ â ã æ âªã æ â¼ ã â šâªã æ â¼ã æ â ã ...
6  temple of dehli from naw till a mornin shock a...
7  golden boy miss kittin rippin kittin norther l...
8  small hours rock a cola ohh baby teenage limbo...
9  miagetegoran yoruno hoshio woman cherish tears...

                                        tracks_clean
0  larger than life i want it that way show me th...
1  dj tom stevens vs fridge outface 2000 radio mi...
2  do or die truth and reality lost soul extracto...
3  ã â ºâ ã â â ã â šå ã â žã â ã â ¹ã â â ã â ã ...
4  felicidade quando o telefone toca vem bailar o...
5  ã æ â ã æ â ã æ âªã æ â¼ ã â šâªã æ â¼ã æ â ã ...
6  temple of dehli from naw till a mornin shock a...
7  golden boy miss kittin rippin kittin norther l...
8  small hours rock a cola ohh baby teenage limbo...
9  miagetegoran yoruno hoshio woman cherish tears...

In [52]:
import duckdb
import os

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

os.makedirs("../data_processed/exports", exist_ok=True)

out_path = "../data_processed/exports/cds_only_enrichment_candidates_v1.csv"

con.execute(f"""
    COPY cds_only_enrichment_candidates_v1
    TO '{out_path}'
    WITH (HEADER, DELIMITER ',')
""")

print(f"✅ Exported: {out_path}")

print("\n--- Row count ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM cds_only_enrichment_candidates_v1
""").fetchdf())

Connected ✅
✅ Exported: ../data_processed/exports/cds_only_enrichment_candidates_v1.csv

--- Row count ---
      n
0  4916

In [53]:
import duckdb
import os

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

os.makedirs("../data_processed/exports", exist_ok=True)

out_path = "../data_processed/exports/cds_unmatched_curated_v1.csv"

con.execute(f"""
    COPY cds_unmatched_curated_v1
    TO '{out_path}'
    WITH (HEADER, DELIMITER ',')
""")

print(f"✅ Exported: {out_path}")

print("\n--- Row count ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM cds_unmatched_curated_v1
""").fetchdf())

Connected ✅
✅ Exported: ../data_processed/exports/cds_unmatched_curated_v1.csv

--- Row count ---
      n
0  5015

In [54]:
import duckdb

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

print(con.execute("""
    SELECT
        cds_id,
        artist,
        title,
        tracks_raw,
        tracks_clean
    FROM cds_tracks_cleaned_v1
    WHERE coalesce(tracks_raw, '') <> coalesce(tracks_clean, '')
    LIMIT 50
""").fetchdf())

Connected ✅
    cds_id                           artist  \
0    10000                  backstreet boys
1   100002                        no return
2   100003          ã â â ã â ã â ºâ ã â å
3   100004                          emanuel
4   100005      ã å â ã â ºâ ã â ºâ ºã â â
5   100006                 luv lite massive
6   100007                  various artists
7   100008                             dmbq
8   100009                           4 p m
9   100010                          various
10  100011             â¾ã â â ã ãœ worship
11  100012               rumania montevideo
12  100014                   modern talking
13  100015                            keedy
14  100016
15  100017                          various
16  100019                       bill evans
17  100020                 nature destroyed
18  100021                        pearl jam
19  100022                dingdong avanzado
20  100024                             175r
21  100025     variousce italiennes disc 1
22  100026               day after tomorrow
23  100027                              v a
24  100028                  jazz signatures
25  100029              bernadã te bidã ude
26  100030             ã â â ã â ã â â¾ã âµ
27  100031                          spartak
28  100032                            v8 5e
29  100034          ã â šã å â ã å å ã â â¾
30  100035                           gazebo
31  100036                         dj irish
32  100037             sportfreunde stiller
33  100038          rennie pilgrim presents
34  100039                          various
35  100040                barbara streisand
36  100041                      italo house
37  100042                             deux
38  100043                             v a
39  100044                          various
40  100045                  matsuka phonics
41  100046                       kool savas
42  100047                         robotika
43  100048                     the breeders
44  100049                  johnny hallyday
45  100050                          phallus
46  100051  ã â â ã â å½ã â¾ã â ã â šë ã â
47  100052                   rolling stones
48  100054       ã ã ã ã ã ã ã¹ã ã ã ã ã ã
49  100055                          nakama1

                                                title  \
0                                          millennium
1                                     self mutilation
2               ã æ â³ã â žã â âºã â ã â ¹ã â ã â šâ
3                                          felicidade
4   catsã â â ã â šâªã æ âªã â šâ ã æ å ã æ â ã â½...
5                                            one love
6                                           nop pop 2
7                                                dmbq
8                                          sweet soul
9                         frankfurt trance vol 05 cd1
10                                 child praise vol 1
11                                   mo better tracks
12                                            univers
13                                   chase the clouds
14                                     subway express
15                           micmac house dance party
16                                              alone
17                                             shades
18                                              yield
19                      the best of dingdong avanzado
20                                              songs
21  la dolce vita les tubes dance italiens les cha...
22                                           elements
23                                    ãƒã âºâ¹ cd 09
24                                    jazz signatures
25                                      pomme d amour
26                      disc13 ã å â ã â ã â ¹ã â šå
27                                              golem
28                                              v8 5e
29                                               lucy
30                                 the best of gazebo
31                              assorted trance vol 8
32                                     die gute seite
33                                  nu skool breakz 2
34                              salsaenlacalleocho 96
35                                   a love like ours
36                                        12 in mixes
37                                            forever
38                          beating surviver another
39                                    custom music cd
40                              let s study phonics 2
41                          euer bester freund mix cd
42                                              dance
43                                                pod
44                                              vol 4
45                                             reason
46                                               home
47                      giant stadium 17 08 1994 cd 2
48                                       ã ã ã ã ã ã¹
49                                   cd5 chapters 8 9

                                           tracks_raw  \
0   larger than life i want it that way show me th...
1   do or die truth and reality lost soul extracto...
2   ã â ºâ ã â â ã â šå ã â žã â ã â ¹ã â â ã â ã ...
3   felicidade quando o telefone toca vem bailar o...
4   ã æ â ã æ â ã æ âªã æ â¼ ã â šâªã æ â¼ã æ â ã ...
5   temple of dehli from naw till a mornin shock a...
6   golden boy miss kittin rippin kittin norther l...
7   small hours rock a cola ohh baby teenage limbo...
8   miagetegoran yoruno hoshio woman cherish tears...
9   dj tom stevens violet steam single cut liquid ...
10  ã ã â ã â³âªâ â â ã â â â½ãƒâ ã â ã ã ãš â³âªâ...
11  i ll be with you hard rain free tender rain ra...
12  tv makes the superstar iâ m no rockefeller mys...
13  save some love wishing on the same star never ...
14
15  colonel abrams i m caught up zhana can t stop ...
16  here s that rainy day a time for love midnight...
17  enter the realm dream of fear word of trust un...
18  brain of j faithfull no way given to fly wishl...
19  ikaw lamang tatlong beinte singko maghihintay ...
20  inst ã â â ã âºâº ã æ â œã æ â ã æ â¼ã æ â ã â...
21  boys summertime love sabrina one for you one f...
22  high spirit time of destiny ã â šã â šå ã âµã ...
23  â ã â ã ã ã ã ãœ â¼â â â³â ãœ ã ã â ã â³âªâ â ...
24   duke ellington take the a train artie shaw be...
25  ouverture margot les paroles gelã es le banque...
26  ã å â ã â â ã â â ã â â ã â â½ã â ã â šã å ã â...
27  sigo viviendo leconseil lunaire naprzod vorwã ...
28  3 l f4o1b8 3 8 3 8 c 3d h z 32 3j8 88g 3j g bx...
29  lucy ã æ å¾ã æ â ã â šâ ã æ ã â šâ ã â šâ¹ã æ ...
30  i like chopin lunatic masterpiece dolce vita t...
31  1 leama requiem for a dream leama s dream mix ...
32  wie lange sollen wir noch warten komm schon ei...
33  01 jaguar odyssey 02 waveform breakers in spac...
34  1996 estamossolos jorgeluispiloto 1996 reyruiz...
35  i ve dreamed of you isn t it a pity the island...
36  rfx dr felix relax your body fpi project going...
37  intor deux forever â³âªâ â âµâ¹â¾ã âºã â¾ã â ã...
38  flash of love wild style qingdao ã âª ã â²â ã ...
39  angelina you re all that i need atlantic star ...
40  alphabet song phonics alpahbet p1 p2 p3 p4 p5 ...
41  comet intro hã nde hoch intro no transatlantic...
42  i wanna love you yum yum spacer my love slave ...
43  glorious doe happiness is a warm gun oh hellbo...
44  ma guitare hey joe san francisco mon p tit lou...
45  save us reason seviin monster take it back hel...
46  fat mama ã â šâ ã æ â ã æ â ã æ å ã æ âªã æ â³...
47  band itroduction honky tonk woman happy the wo...
48  ã ã ã ã ã ãºã ã ã ã ã ã ã ã¹ã ã ã ã ã ã ã¹ã ã ...
49  nakama 1 world languages japanese by makino ha...

                                         tracks_clean
0   larger than life i want it that way show me th...
1   do or die truth and reality lost soul extracto...
2   ã â ºâ ã â â ã â šå ã â žã â ã â ¹ã â â ã â ã ...
3   felicidade quando o telefone toca vem bailar o...
4   ã æ â ã æ â ã æ âªã æ â¼ ã â šâªã æ â¼ã æ â ã ...
5   temple of dehli from naw till a mornin shock a...
6   golden boy miss kittin rippin kittin norther l...
7   small hours rock a cola ohh baby teenage limbo...
8   miagetegoran yoruno hoshio woman cherish tears...
9   dj tom stevens violet steam single cut liquid ...
10  ã ã â ã â³âªâ â â ã â â â½ãƒâ ã â ã ã ãš â³âªâ...
11  i ll be with you hard rain free tender rain ra...
12  tv makes the superstar iâ m no rockefeller mys...
13  save some love wishing on the same star never ...
14
15  colonel abrams i m caught up zhana can t stop ...
16  here s that rainy day a time for love midnight...
17  enter the realm dream of fear word of trust un...
18  brain of j faithfull no way given to fly wishl...
19  ikaw lamang tatlong beinte singko maghihintay ...
20  inst ã â â ã âºâº ã æ â œã æ â ã æ â¼ã æ â ã â...
21  boys summertime love sabrina one for you one f...
22  high spirit time of destiny ã â šã â šå ã âµã ...
23  â ã â ã ã ã ã ãœ â¼â â â³â ãœ ã ã â ã â³âªâ â ...
24  duke ellington take the a train artie shaw beg...
25  ouverture margot les paroles gelã es le banque...
26  ã å â ã â â ã â â ã â â ã â â½ã â ã â šã å ã â...
27  sigo viviendo leconseil lunaire naprzod vorwã ...
28  3 l f4o1b8 3 8 3 8 c 3d h z 32 3j8 88g 3j g bx...
29  lucy ã æ å¾ã æ â ã â šâ ã æ ã â šâ ã â šâ¹ã æ ...
30  i like chopin lunatic masterpiece dolce vita t...
31  1 leama requiem for a dream leama s dream mix ...
32  wie lange sollen wir noch warten komm schon ei...
33  01 jaguar odyssey 02 waveform breakers in spac...
34  1996 estamossolos jorgeluispiloto 1996 reyruiz...
35  i ve dreamed of you isn t it a pity the island...
36  rfx dr felix relax your body fpi project going...
37  intor deux forever â³âªâ â âµâ¹â¾ã âºã â¾ã â ã...
38  flash of love wild style qingdao ã âª ã â²â ã ...
39  angelina you re all that i need atlantic star ...
40  alphabet song phonics alpahbet p1 p2 p3 p4 p5 ...
41  comet intro hã nde hoch intro no transatlantic...
42  i wanna love you yum yum spacer my love slave ...
43  glorious doe happiness is a warm gun oh hellbo...
44  ma guitare hey joe san francisco mon p tit lou...
45  save us reason seviin monster take it back hel...
46  fat mama ã â šâ ã æ â ã æ â ã æ å ã æ âªã æ â³...
47  band itroduction honky tonk woman happy the wo...
48  ã ã ã ã ã ãºã ã ã ã ã ã ã ã¹ã ã ã ã ã ã ã¹ã ã ...
49  nakama 1 world languages japanese by makino ha...

In [55]:
print(con.execute("""
    SELECT COUNT(*) AS changed_rows
    FROM cds_tracks_cleaned_v1
    WHERE coalesce(tracks_raw, '') <> coalesce(tracks_clean, '')
""").fetchdf())

   changed_rows
0          9757

In [56]:
import duckdb

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

print(con.execute("""
    SELECT
        cds_id,
        artist,
        title,
        tracks_raw,
        tracks_clean,

        CASE
            WHEN tracks_raw IS NULL AND tracks_clean IS NULL THEN 'no change'
            WHEN coalesce(tracks_raw, '') = coalesce(tracks_clean, '') THEN 'no change'
            WHEN regexp_replace(coalesce(tracks_raw, ''), '[\\r\\n\\t]+', ' ', 'g') <> coalesce(tracks_raw, '')
                 THEN 'newline/tab cleanup'
            WHEN regexp_replace(coalesce(tracks_raw, ''), '\\s+', ' ', 'g') <> coalesce(tracks_raw, '')
                 THEN 'extra whitespace cleanup'
            WHEN regexp_replace(coalesce(tracks_raw, ''), '[,;|/]{2,}', ' ', 'g') <> coalesce(tracks_raw, '')
                 THEN 'repeated separator cleanup'
            ELSE 'general normalization'
        END AS likely_change_type,

        length(coalesce(tracks_raw, '')) AS raw_len,
        length(coalesce(tracks_clean, '')) AS clean_len

    FROM cds_tracks_cleaned_v1
    WHERE coalesce(tracks_raw, '') <> coalesce(tracks_clean, '')
    LIMIT 50
""").fetchdf())

Connected ✅
    cds_id                           artist  \
0    10000                  backstreet boys
1   100002                        no return
2   100003          ã â â ã â ã â ºâ ã â å
3   100004                          emanuel
4   100005      ã å â ã â ºâ ã â ºâ ºã â â
5   100006                 luv lite massive
6   100007                  various artists
7   100008                             dmbq
8   100009                           4 p m
9   100010                          various
10  100011             â¾ã â â ã ãœ worship
11  100012               rumania montevideo
12  100014                   modern talking
13  100015                            keedy
14  100016
15  100017                          various
16  100019                       bill evans
17  100020                 nature destroyed
18  100021                        pearl jam
19  100022                dingdong avanzado
20  100024                             175r
21  100025     variousce italiennes disc 1
22  100026               day after tomorrow
23  100027                              v a
24  100028                  jazz signatures
25  100029              bernadã te bidã ude
26  100030             ã â â ã â ã â â¾ã âµ
27  100031                          spartak
28  100032                            v8 5e
29  100034          ã â šã å â ã å å ã â â¾
30  100035                           gazebo
31  100036                         dj irish
32  100037             sportfreunde stiller
33  100038          rennie pilgrim presents
34  100039                          various
35  100040                barbara streisand
36  100041                      italo house
37  100042                             deux
38  100043                             v a
39  100044                          various
40  100045                  matsuka phonics
41  100046                       kool savas
42  100047                         robotika
43  100048                     the breeders
44  100049                  johnny hallyday
45  100050                          phallus
46  100051  ã â â ã â å½ã â¾ã â ã â šë ã â
47  100052                   rolling stones
48  100054       ã ã ã ã ã ã ã¹ã ã ã ã ã ã
49  100055                          nakama1

                                                title  \
0                                          millennium
1                                     self mutilation
2               ã æ â³ã â žã â âºã â ã â ¹ã â ã â šâ
3                                          felicidade
4   catsã â â ã â šâªã æ âªã â šâ ã æ å ã æ â ã â½...
5                                            one love
6                                           nop pop 2
7                                                dmbq
8                                          sweet soul
9                         frankfurt trance vol 05 cd1
10                                 child praise vol 1
11                                   mo better tracks
12                                            univers
13                                   chase the clouds
14                                     subway express
15                           micmac house dance party
16                                              alone
17                                             shades
18                                              yield
19                      the best of dingdong avanzado
20                                              songs
21  la dolce vita les tubes dance italiens les cha...
22                                           elements
23                                    ãƒã âºâ¹ cd 09
24                                    jazz signatures
25                                      pomme d amour
26                      disc13 ã å â ã â ã â ¹ã â šå
27                                              golem
28                                              v8 5e
29                                               lucy
30                                 the best of gazebo
31                              assorted trance vol 8
32                                     die gute seite
33                                  nu skool breakz 2
34                              salsaenlacalleocho 96
35                                   a love like ours
36                                        12 in mixes
37                                            forever
38                          beating surviver another
39                                    custom music cd
40                              let s study phonics 2
41                          euer bester freund mix cd
42                                              dance
43                                                pod
44                                              vol 4
45                                             reason
46                                               home
47                      giant stadium 17 08 1994 cd 2
48                                       ã ã ã ã ã ã¹
49                                   cd5 chapters 8 9

                                           tracks_raw  \
0   larger than life i want it that way show me th...
1   do or die truth and reality lost soul extracto...
2   ã â ºâ ã â â ã â šå ã â žã â ã â ¹ã â â ã â ã ...
3   felicidade quando o telefone toca vem bailar o...
4   ã æ â ã æ â ã æ âªã æ â¼ ã â šâªã æ â¼ã æ â ã ...
5   temple of dehli from naw till a mornin shock a...
6   golden boy miss kittin rippin kittin norther l...
7   small hours rock a cola ohh baby teenage limbo...
8   miagetegoran yoruno hoshio woman cherish tears...
9   dj tom stevens violet steam single cut liquid ...
10  ã ã â ã â³âªâ â â ã â â â½ãƒâ ã â ã ã ãš â³âªâ...
11  i ll be with you hard rain free tender rain ra...
12  tv makes the superstar iâ m no rockefeller mys...
13  save some love wishing on the same star never ...
14
15  colonel abrams i m caught up zhana can t stop ...
16  here s that rainy day a time for love midnight...
17  enter the realm dream of fear word of trust un...
18  brain of j faithfull no way given to fly wishl...
19  ikaw lamang tatlong beinte singko maghihintay ...
20  inst ã â â ã âºâº ã æ â œã æ â ã æ â¼ã æ â ã â...
21  boys summertime love sabrina one for you one f...
22  high spirit time of destiny ã â šã â šå ã âµã ...
23  â ã â ã ã ã ã ãœ â¼â â â³â ãœ ã ã â ã â³âªâ â ...
24   duke ellington take the a train artie shaw be...
25  ouverture margot les paroles gelã es le banque...
26  ã å â ã â â ã â â ã â â ã â â½ã â ã â šã å ã â...
27  sigo viviendo leconseil lunaire naprzod vorwã ...
28  3 l f4o1b8 3 8 3 8 c 3d h z 32 3j8 88g 3j g bx...
29  lucy ã æ å¾ã æ â ã â šâ ã æ ã â šâ ã â šâ¹ã æ ...
30  i like chopin lunatic masterpiece dolce vita t...
31  1 leama requiem for a dream leama s dream mix ...
32  wie lange sollen wir noch warten komm schon ei...
33  01 jaguar odyssey 02 waveform breakers in spac...
34  1996 estamossolos jorgeluispiloto 1996 reyruiz...
35  i ve dreamed of you isn t it a pity the island...
36  rfx dr felix relax your body fpi project going...
37  intor deux forever â³âªâ â âµâ¹â¾ã âºã â¾ã â ã...
38  flash of love wild style qingdao ã âª ã â²â ã ...
39  angelina you re all that i need atlantic star ...
40  alphabet song phonics alpahbet p1 p2 p3 p4 p5 ...
41  comet intro hã nde hoch intro no transatlantic...
42  i wanna love you yum yum spacer my love slave ...
43  glorious doe happiness is a warm gun oh hellbo...
44  ma guitare hey joe san francisco mon p tit lou...
45  save us reason seviin monster take it back hel...
46  fat mama ã â šâ ã æ â ã æ â ã æ å ã æ âªã æ â³...
47  band itroduction honky tonk woman happy the wo...
48  ã ã ã ã ã ãºã ã ã ã ã ã ã ã¹ã ã ã ã ã ã ã¹ã ã ...
49  nakama 1 world languages japanese by makino ha...

                                         tracks_clean     likely_change_type  \
0   larger than life i want it that way show me th...  general normalization
1   do or die truth and reality lost soul extracto...  general normalization
2   ã â ºâ ã â â ã â šå ã â žã â ã â ¹ã â â ã â ã ...  general normalization
3   felicidade quando o telefone toca vem bailar o...  general normalization
4   ã æ â ã æ â ã æ âªã æ â¼ ã â šâªã æ â¼ã æ â ã ...  general normalization
5   temple of dehli from naw till a mornin shock a...  general normalization
6   golden boy miss kittin rippin kittin norther l...  general normalization
7   small hours rock a cola ohh baby teenage limbo...  general normalization
8   miagetegoran yoruno hoshio woman cherish tears...  general normalization
9   dj tom stevens violet steam single cut liquid ...  general normalization
10  ã ã â ã â³âªâ â â ã â â â½ãƒâ ã â ã ã ãš â³âªâ...  general normalization
11  i ll be with you hard rain free tender rain ra...  general normalization
12  tv makes the superstar iâ m no rockefeller mys...  general normalization
13  save some love wishing on the same star never ...  general normalization
14                                                     general normalization
15  colonel abrams i m caught up zhana can t stop ...  general normalization
16  here s that rainy day a time for love midnight...  general normalization
17  enter the realm dream of fear word of trust un...  general normalization
18  brain of j faithfull no way given to fly wishl...  general normalization
19  ikaw lamang tatlong beinte singko maghihintay ...  general normalization
20  inst ã â â ã âºâº ã æ â œã æ â ã æ â¼ã æ â ã â...  general normalization
21  boys summertime love sabrina one for you one f...  general normalization
22  high spirit time of destiny ã â šã â šå ã âµã ...  general normalization
23  â ã â ã ã ã ã ãœ â¼â â â³â ãœ ã ã â ã â³âªâ â ...  general normalization
24  duke ellington take the a train artie shaw beg...  general normalization
25  ouverture margot les paroles gelã es le banque...  general normalization
26  ã å â ã â â ã â â ã â â ã â â½ã â ã â šã å ã â...  general normalization
27  sigo viviendo leconseil lunaire naprzod vorwã ...  general normalization
28  3 l f4o1b8 3 8 3 8 c 3d h z 32 3j8 88g 3j g bx...  general normalization
29  lucy ã æ å¾ã æ â ã â šâ ã æ ã â šâ ã â šâ¹ã æ ...  general normalization
30  i like chopin lunatic masterpiece dolce vita t...  general normalization
31  1 leama requiem for a dream leama s dream mix ...  general normalization
32  wie lange sollen wir noch warten komm schon ei...  general normalization
33  01 jaguar odyssey 02 waveform breakers in spac...  general normalization
34  1996 estamossolos jorgeluispiloto 1996 reyruiz...  general normalization
35  i ve dreamed of you isn t it a pity the island...  general normalization
36  rfx dr felix relax your body fpi project going...  general normalization
37  intor deux forever â³âªâ â âµâ¹â¾ã âºã â¾ã â ã...  general normalization
38  flash of love wild style qingdao ã âª ã â²â ã ...  general normalization
39  angelina you re all that i need atlantic star ...  general normalization
40  alphabet song phonics alpahbet p1 p2 p3 p4 p5 ...  general normalization
41  comet intro hã nde hoch intro no transatlantic...  general normalization
42  i wanna love you yum yum spacer my love slave ...  general normalization
43  glorious doe happiness is a warm gun oh hellbo...  general normalization
44  ma guitare hey joe san francisco mon p tit lou...  general normalization
45  save us reason seviin monster take it back hel...  general normalization
46  fat mama ã â šâ ã æ â ã æ â ã æ å ã æ âªã æ â³...  general normalization
47  band itroduction honky tonk woman happy the wo...  general normalization
48  ã ã ã ã ã ãºã ã ã ã ã ã ã ã¹ã ã ã ã ã ã ã¹ã ã ...  general normalization
49  nakama 1 world languages japanese by makino ha...  general normalization

    raw_len  clean_len
0       256        255
1       141        140
2       342        341
3       301        300
4       811        810
5       113        112
6       365        364
7       202        201
8       198        197
9       462        461
10      312        311
11      162        161
12      216        215
13      158        157
14        1          0
15      359        358
16      383        382
17      128        127
18      144        143
19      203        202
20      321        320
21      285        284
22      186        185
23      502        501
24      405        403
25      183        182
26      326        325
27      182        181
28      140        139
29      369        368
30      238        237
31      578        577
32      187        186
33      395        394
34      524        523
35      220        219
36      386        385
37      210        209
38      221        220
39      306        305
40      223        222
41      817        816
42      165        164
43      133        132
44      197        196
45      126        125
46      331        330
47      161        160
48      207        206
49      528        527

In [57]:
print(con.execute("""
    SELECT
        cds_id,
        artist,
        title,
        tracks_raw,
        tracks_clean
    FROM cds_tracks_cleaned_v1
    WHERE coalesce(tracks_raw, '') <> coalesce(tracks_clean, '')
    LIMIT 20
""").fetchdf())

    cds_id                       artist  \
0    10000              backstreet boys
1   100002                    no return
2   100003      ã â â ã â ã â ºâ ã â å
3   100004                      emanuel
4   100005  ã å â ã â ºâ ã â ºâ ºã â â
5   100006             luv lite massive
6   100007              various artists
7   100008                         dmbq
8   100009                       4 p m
9   100010                      various
10  100011         â¾ã â â ã ãœ worship
11  100012           rumania montevideo
12  100014               modern talking
13  100015                        keedy
14  100016
15  100017                      various
16  100019                   bill evans
17  100020             nature destroyed
18  100021                    pearl jam
19  100022            dingdong avanzado

                                                title  \
0                                          millennium
1                                     self mutilation
2               ã æ â³ã â žã â âºã â ã â ¹ã â ã â šâ
3                                          felicidade
4   catsã â â ã â šâªã æ âªã â šâ ã æ å ã æ â ã â½...
5                                            one love
6                                           nop pop 2
7                                                dmbq
8                                          sweet soul
9                         frankfurt trance vol 05 cd1
10                                 child praise vol 1
11                                   mo better tracks
12                                            univers
13                                   chase the clouds
14                                     subway express
15                           micmac house dance party
16                                              alone
17                                             shades
18                                              yield
19                      the best of dingdong avanzado

                                           tracks_raw  \
0   larger than life i want it that way show me th...
1   do or die truth and reality lost soul extracto...
2   ã â ºâ ã â â ã â šå ã â žã â ã â ¹ã â â ã â ã ...
3   felicidade quando o telefone toca vem bailar o...
4   ã æ â ã æ â ã æ âªã æ â¼ ã â šâªã æ â¼ã æ â ã ...
5   temple of dehli from naw till a mornin shock a...
6   golden boy miss kittin rippin kittin norther l...
7   small hours rock a cola ohh baby teenage limbo...
8   miagetegoran yoruno hoshio woman cherish tears...
9   dj tom stevens violet steam single cut liquid ...
10  ã ã â ã â³âªâ â â ã â â â½ãƒâ ã â ã ã ãš â³âªâ...
11  i ll be with you hard rain free tender rain ra...
12  tv makes the superstar iâ m no rockefeller mys...
13  save some love wishing on the same star never ...
14
15  colonel abrams i m caught up zhana can t stop ...
16  here s that rainy day a time for love midnight...
17  enter the realm dream of fear word of trust un...
18  brain of j faithfull no way given to fly wishl...
19  ikaw lamang tatlong beinte singko maghihintay ...

                                         tracks_clean
0   larger than life i want it that way show me th...
1   do or die truth and reality lost soul extracto...
2   ã â ºâ ã â â ã â šå ã â žã â ã â ¹ã â â ã â ã ...
3   felicidade quando o telefone toca vem bailar o...
4   ã æ â ã æ â ã æ âªã æ â¼ ã â šâªã æ â¼ã æ â ã ...
5   temple of dehli from naw till a mornin shock a...
6   golden boy miss kittin rippin kittin norther l...
7   small hours rock a cola ohh baby teenage limbo...
8   miagetegoran yoruno hoshio woman cherish tears...
9   dj tom stevens violet steam single cut liquid ...
10  ã ã â ã â³âªâ â â ã â â â½ãƒâ ã â ã ã ãš â³âªâ...
11  i ll be with you hard rain free tender rain ra...
12  tv makes the superstar iâ m no rockefeller mys...
13  save some love wishing on the same star never ...
14
15  colonel abrams i m caught up zhana can t stop ...
16  here s that rainy day a time for love midnight...
17  enter the realm dream of fear word of trust un...
18  brain of j faithfull no way given to fly wishl...
19  ikaw lamang tatlong beinte singko maghihintay ...

In [58]:
import duckdb
import pandas as pd
import difflib

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

df = con.execute("""
    SELECT
        cds_id,
        artist,
        title,
        tracks_raw,
        tracks_clean
    FROM cds_tracks_cleaned_v1
    WHERE coalesce(tracks_raw, '') <> coalesce(tracks_clean, '')
    LIMIT 20
""").fetchdf()

def word_diff(a, b):
    a_words = str(a).split()
    b_words = str(b).split()
    diff = difflib.ndiff(a_words, b_words)
    return " ".join(diff)

df["diff"] = df.apply(lambda r: word_diff(r["tracks_raw"], r["tracks_clean"]), axis=1)

pd.set_option("display.max_colwidth", 1000)
df[["cds_id", "artist", "title", "diff"]]

Connected ✅

,cds_id,artist,title,diff
0,10000,backstreet boys,millennium,larger than life i want it that way show me the meaning of being lonely it s gotta be you i need you tonight don t want you back don t wanna lose you now the one back to your heart spanish eyes no one else comes close the perfect fan i ll be there for you
1,100002,no return,self mutilation,do or die truth and reality lost soul extractor sadistic desire the true way fanatic mind individualistic ideal one life trail of blood sect
2,100003,ã â â ã â ã â ºâ ã â å,ã æ â³ã â žã â âºã â ã â ¹ã â ã â šâ,ã â ºâ ã â â ã â šå ã â žã â ã â ¹ã â â ã â ã â¼å ã â ã å ã âªã â šâ ã â â ã â ã âªã â žã â â ã å ã â ã å ã â ã å ã â žã â ž ã âµã â šå ã â šã â ž ã â šã â š ã â ã ëœâ ã â âºã å ã â ã â ã â â ã â â½ã â žã â â ã å å¾ã â â ã â ã â ã â šâ ã â žã â â šã â â ã â å ã â å ã ë â ã â å ã â šã âªã å ã â šâ ã â žâ ºã â ã â šâ ¹ã â ã â ã ëœâ ã â²â ã â
3,100004,emanuel,felicidade,felicidade quando o telefone toca vem bailar o tic tic quero que sejas minha e de mais ninguem eu sei que me amas o melhor que hã minha vizinha deixa me a bater mal s joã o ã foliã o sã³ quero o teu carinho tudo farei para ter a tua paixã o serã s sempre minha vem bailar o tic tic verã ã o dance mix
4,100005,ã å â ã â ºâ ã â ºâ ºã â â,catsã â â ã â šâªã æ âªã â šâ ã æ å ã æ â ã â½â ã â šâ ã æ â ã â šâ¹ã æ ë,ã æ â ã æ â ã æ âªã æ â¼ ã â šâªã æ â¼ã æ â ã â šâ ã æ ã æ â ã â šâ ã â šâ ã â šâ ã æ âªã â šâ ã æ â ã â šâ½ã æ â³ã â šâ ã æ ã æ â¼ã æ å ã æ â³ã â šâ ã æ â ã â šâªã æ â ã æ â ã â šâ ã æ â ã æ æ ã æ â ž ã ë â ã å â ã â ã ã â šâ ã â šâ ã æ â ¹ã â šâ ã æ â ¹ã æ â ã æ æ ã æ â ž ã ë â ã å ã â ã â ã â šâ œã å â ã æ â ã æ â ã æ â ã â šâ ã æ â ã æ â ã â šâ ã â šâ ã æ â¼ ã ë â ã â ã â ã â ã â šå ã å â ã â šâ ã æ âªã â šâ ã æ â ã æ â ã ë â ã â â¼ã â â ã å â ã æ ã â šâ¹ã æ ë ã æ â ã â šâ ã æ â¼ã â šâ ã æ â ã æ â¼ã æ â³ã â šâº ã ë â ã...
5,100006,luv lite massive,one love,temple of dehli from naw till a mornin shock afghani lick you bad freestyle fiki fuko i m here yeah ww5 one love
6,100007,various artists,nop pop 2,golden boy miss kittin rippin kittin norther lite treat me better peaches lovertits mã rtini brã s flash kristall das leben im jetzt slam lifetimes autotune capital killers e man animal skin marc verbos special friend lasse lundmark coca bass flash und gordon frauen in autos dan maxem vs polygen tiefoderhoch green velvet la la land frank mã¼ller vs takkyu ishino
7,100008,dmbq,dmbq,small hours rock a cola ohh baby teenage limbo little leaf i movement little leaf ii swell little leaf iii etude sayonara no season altered rock can peace migrate to midnight e means eternal data track
8,100009,4 p m,sweet soul,miagetegoran yoruno hoshio woman cherish tears in heaven so much in love christmas eve too much heaven i left my heart in san francisco the lady in my life christmas medley the star spangled banner
9,100010,various,frankfurt trance vol 05 cd1,dj tom stevens violet steam single cut liquid child diving faces original mix vimana we came edit lac terra after dark fridge vs vectrex remix steve baltes thoughts original mix star party i m in love ferry corsten robert smit rmx gate iv give all you got radio edit dj stigma baby sunshine stig s original club mix synchronic minds all i need club mix astral inc remember green court edit x trance friends 2000 tom stevens rmx ravelab send me an angel club mix
10,100011,â¾ã â â ã ãœ worship,child praise vol 1,ã ã â ã â³âªâ â â ã â â â½ãƒâ ã â ã ã ãš â³âªâ ã â¹ã ã â½ã â â ãž â ã â ã ã ã â½ã ã ã â³âªâ ã give thanks â â¹â¼ã â ã â ã ã ã â½ã ã âº â ã â â ã ã â²â² â ã â âµã ã â ã â â â ã âµãž â¼ã â ã ã â â ã âºã ãƒãÿâ¼ã â¼â ãˆâ â ãªâ³âª ã ã â ã ã ã â½ãƒâ â â â â¼â â ã½â ã â ãº ã ã ã âº ãƒâµâ ã âµã â ã â ã â¼ã ã ã¹â¾ã ã ã
11,100012,rumania montevideo,mo better tracks,i ll be with you hard rain free tender rain rain sleeper life style taxi take my pain away my life album version all by myself start all over again album version
12,100014,modern talking,univers,tv makes the superstar iâ m no rockefeller mystery eyerybody needs somebody heart of an angel who will be there knocking on my door should i would i could i blackbird life is so short nothing but the truth superstar
13,100015,keedy,chase the clouds,save some love wishing on the same star never neverland sorry only your heart gettin around don t turn away pretty boy mama lazy day save some love hot remix
14,100016,,subway express,
15,100017,various,micmac house dance party,colonel abrams i m caught up zhana can t stop dancin camille my love will set you free bmc a night at the m vol 2 no joke feel the music house factor movin and groovin diva diva boy i told you so hippie culture accelerator can you feel it mixmaster love machine d j professor runner supreme mind it s over now motivation featuring lee truesdale keep in touch
16,100019,bill evans,alone,here s that rainy day a time for love midnight mood on a clear day you can see forever never let me go the two lonely people aka the man and the woman here s that rainy day alternative take a time for love alternative take midnight mood alternative take on a clear day you can see forever alternative take never let me go alternative take medley all the things you are midnight mood
17,100020,nature destroyed,shades,enter the realm dream of fear word of trust unforeseen desire shades bound imprisoned cold vengeance disease leaving the shadow
18,100021,pearl jam,yield,brain of j faithfull no way given to fly wishlist pilate do the evolution untitled mfc low light in hiding push me pull me all those yesterdays
19,100022,dingdong avanzado,the best of dingdong avanzado,ikaw lamang tatlong beinte singko maghihintay sa yo makapiling ka sana break kung break love at first sight basta t kasama kita paano sasabihin here i am i think i love you bakit hangang ngayon say amen

In [59]:
print(con.execute("""
    SELECT
        cds_id,
        artist,
        title,
        tracks_raw,
        tracks_clean
    FROM cds_tracks_cleaned_v1
    WHERE coalesce(tracks_raw, '') <> coalesce(tracks_clean, '')
    LIMIT 20
""").fetchdf())

    cds_id                       artist  \
0    10000              backstreet boys
1   100002                    no return
2   100003      ã â â ã â ã â ºâ ã â å
3   100004                      emanuel
4   100005  ã å â ã â ºâ ã â ºâ ºã â â
5   100006             luv lite massive
6   100007              various artists
7   100008                         dmbq
8   100009                       4 p m
9   100010                      various
10  100011         â¾ã â â ã ãœ worship
11  100012           rumania montevideo
12  100014               modern talking
13  100015                        keedy
14  100016
15  100017                      various
16  100019                   bill evans
17  100020             nature destroyed
18  100021                    pearl jam
19  100022            dingdong avanzado

                                                                         title  \
0                                                                   millennium
1                                                              self mutilation
2                                        ã æ â³ã â žã â âºã â ã â ¹ã â ã â šâ
3                                                                   felicidade
4   catsã â â ã â šâªã æ âªã â šâ ã æ å ã æ â ã â½â ã â šâ ã æ â ã â šâ¹ã æ ë
5                                                                     one love
6                                                                    nop pop 2
7                                                                         dmbq
8                                                                   sweet soul
9                                                  frankfurt trance vol 05 cd1
10                                                          child praise vol 1
11                                                            mo better tracks
12                                                                     univers
13                                                            chase the clouds
14                                                              subway express
15                                                    micmac house dance party
16                                                                       alone
17                                                                      shades
18                                                                       yield
19                                               the best of dingdong avanzado

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     tracks_raw  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              larger than life i want it that way show me the meaning of being lonely it s gotta be you i need you tonight don t want you back don t wanna lose you now the one back to your heart spanish eyes no one else comes close the perfect fan i ll be there for you
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 do or die truth and reality lost soul extractor sadistic desire the true way fanatic mind individualistic ideal one life trail of blood sect
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ã â ºâ ã â â ã â šå ã â žã â ã â ¹ã â â ã â ã â¼å ã â ã å ã âªã â šâ ã â â ã â ã âªã â žã â â ã å ã â ã å ã â ã å ã â žã â ž ã âµã â šå ã â šã â ž ã â šã â š ã â ã ëœâ ã â âºã å ã â ã â ã â â ã â â½ã â žã â â ã å å¾ã â â ã â ã â ã â šâ ã â žã â â šã â â ã â å ã â å ã ë â ã â å ã â šã âªã å ã â šâ ã â žâ ºã â ã â šâ ¹ã â ã â ã ëœâ ã â²â ã â
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 felicidade quando o telefone toca vem bailar o tic tic quero que sejas minha e de mais ninguem eu sei que me amas o melhor que hã minha vizinha deixa me a bater mal s joã o ã foliã o sã³ quero o teu carinho tudo farei para ter a tua paixã o serã s sempre minha vem bailar o tic tic verã ã o dance mix
4   ã æ â ã æ â ã æ âªã æ â¼ ã â šâªã æ â¼ã æ â ã â šâ ã æ ã æ â ã â šâ ã â šâ ã â šâ ã æ âªã â šâ ã æ â ã â šâ½ã æ â³ã â šâ ã æ ã æ â¼ã æ å ã æ â³ã â šâ ã æ â ã â šâªã æ â ã æ â ã â šâ ã æ â ã æ æ ã æ â ž ã ë â ã å â ã â ã ã â šâ ã â šâ ã æ â ¹ã â šâ ã æ â ¹ã æ â ã æ æ ã æ â ž ã ë â ã å ã â ã â ã â šâ œã å â ã æ â ã æ â ã æ â ã â šâ ã æ â ã æ â ã â šâ ã â šâ ã æ â¼ ã ë â ã â ã â ã â ã â šå ã å â ã â šâ ã æ âªã â šâ ã æ â ã æ â ã ë â ã â â¼ã â â ã å â ã æ ã â šâ¹ã æ ë ã æ â ã â šâ ã æ â¼ã â šâ ã æ â ã æ â¼ã æ â³ã â šâº ã ë â ã â â ã âºâºã â â ã â¼å ã æ å¾ã æ â³ã â šâ ã â šâ ã â šâ ã æ âªã æ â¼ã â ã æ â ã æ â³ã æ å ã æ â ã æ â ã â šâ ã æ â¼ã â šâ ã ë â ã â ã â³â ã â â ã æ â ã æ â ã æ ë ã æ â ã æ å½ã æ å ã æ â¼ ã ë â ã â â ã â ã å â ã â šâ ã â šâ ã æ âªã â šâ ã æ â ã ë å¾ã â ã â¼å ã æ â ã æ â ã æ âªã æ â¼
5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             temple of dehli from naw till a mornin shock afghani lick you bad freestyle fiki fuko i m here yeah ww5 one love
6                                                                                                                                                                                                                                                                                                                                                                                                                                                                 golden boy miss kittin rippin kittin norther lite treat me better peaches lovertits mã rtini brã s flash kristall das leben im jetzt slam lifetimes autotune capital killers e man animal skin marc verbos special friend lasse lundmark coca bass flash und gordon frauen in autos dan maxem vs polygen tiefoderhoch green velvet la la land frank mã¼ller vs takkyu ishino
7                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    small hours rock a cola ohh baby teenage limbo little leaf i movement little leaf ii swell little leaf iii etude sayonara no season altered rock can peace migrate to midnight e means eternal data track
8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        miagetegoran yoruno hoshio woman cherish tears in heaven so much in love christmas eve too much heaven i left my heart in san francisco the lady in my life christmas medley the star spangled banner
9                                                                                                                                                                                                                                                                                                                                                                dj tom stevens violet steam single cut liquid child diving faces original mix vimana we came edit lac terra after dark fridge vs vectrex remix steve baltes thoughts original mix star party i m in love ferry corsten robert smit rmx gate iv give all you got radio edit dj stigma baby sunshine stig s original club mix synchronic minds all i need club mix astral inc remember green court edit x trance friends 2000 tom stevens rmx ravelab send me an angel club mix
10                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ã ã â ã â³âªâ â â ã â â â½ãƒâ ã â ã ã ãš â³âªâ ã â¹ã ã â½ã â â ãž â ã â ã ã ã â½ã ã ã â³âªâ ã give thanks â â¹â¼ã â ã â ã ã ã â½ã ã âº â ã â â ã ã â²â² â ã â âµã ã â ã â â â ã âµãž â¼ã â ã ã â â ã âºã ãƒãÿâ¼ã â¼â ãˆâ â ãªâ³âª ã ã â ã ã ã â½ãƒâ â â â â¼â â ã½â ã â ãº ã ã ã âº ãƒâµâ ã âµã â ã â ã â¼ã ã ã¹â¾ã ã ã
11                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           i ll be with you hard rain free tender rain rain sleeper life style taxi take my pain away my life album version all by myself start all over again album version
12                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     tv makes the superstar iâ m no rockefeller mystery eyerybody needs somebody heart of an angel who will be there knocking on my door should i would i could i blackbird life is so short nothing but the truth superstar
13                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               save some love wishing on the same star never neverland sorry only your heart gettin around don t turn away pretty boy mama lazy day save some love hot remix
14
15                                                                                                                                                                                                                                                                                                                                                                                                                                                                      colonel abrams i m caught up zhana can t stop dancin camille my love will set you free bmc a night at the m vol 2 no joke feel the music house factor movin and groovin diva diva boy i told you so hippie culture accelerator can you feel it mixmaster love machine d j professor runner supreme mind it s over now motivation featuring lee truesdale keep in touch
16                                                                                                                                                                                                                                                                                                                                                                                                                                              here s that rainy day a time for love midnight mood on a clear day you can see forever never let me go the two lonely people aka the man and the woman here s that rainy day alternative take a time for love alternative take midnight mood alternative take on a clear day you can see forever alternative take never let me go alternative take medley all the things you are midnight mood
17                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             enter the realm dream of fear word of trust unforeseen desire shades bound imprisoned cold vengeance disease leaving the shadow
18                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             brain of j faithfull no way given to fly wishlist pilate do the evolution untitled mfc low light in hiding push me pull me all those yesterdays
19                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ikaw lamang tatlong beinte singko maghihintay sa yo makapiling ka sana break kung break love at first sight basta t kasama kita paano sasabihin here i am i think i love you bakit hangang ngayon say amen

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  tracks_clean

In [60]:
#missing tracks 
import duckdb

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

print(con.execute("""
    SELECT COUNT(*) AS missing_tracks
    FROM cds
    WHERE tracks IS NULL
       OR trim(tracks) = ''
""").fetchdf())

Connected ✅
   missing_tracks
0               1

In [61]:
import duckdb

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

print(con.execute("""
    SELECT COUNT(*) AS missing_artist
    FROM cds
    WHERE artist IS NULL
       OR trim(artist) = ''
""").fetchdf())

Connected ✅
   missing_artist
0               7

In [62]:
import duckdb

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

print(con.execute("""
    SELECT COUNT(*) AS missing_title
    FROM cds
    WHERE title IS NULL
       OR trim(title) = ''
""").fetchdf())

Connected ✅
   missing_title
0             11

In [63]:
import duckdb

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

print(con.execute("""
    SELECT COUNT(*) AS missing_year
    FROM cds
    WHERE cds_year IS NULL
       OR trim(title) = ''
""").fetchdf())

Connected ✅
   missing_year
0          4561

In [64]:
import duckdb

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

print(con.execute("""
    SELECT
        COUNT(*) AS total_weak_rows,
        SUM(CASE WHEN is_mojibake = 1 THEN 1 ELSE 0 END) AS mojibake_rows,
        SUM(CASE WHEN is_mojibake = 0 THEN 1 ELSE 0 END) AS non_mojibake_rows,
        ROUND(
            100.0 * SUM(CASE WHEN is_mojibake = 1 THEN 1 ELSE 0 END) / COUNT(*),
            2
        ) AS mojibake_pct
    FROM cds_only_enrichment_weak_v1
""").fetchdf())

Connected ✅
   total_weak_rows  mojibake_rows  non_mojibake_rows  mojibake_pct
0              196            0.0              196.0           0.0

In [67]:
import duckdb

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

print(con.execute("""
    SELECT
        COUNT(*) AS total_rows,
        SUM(CASE WHEN is_mojibake = 1 THEN 1 ELSE 0 END) AS mojibake_rows
    FROM cds_unmatched_working_v6
""").fetchdf())

Connected ✅
   total_rows  mojibake_rows
0        5555          509.0

In [68]:
print(con.execute("""
    SELECT
        cds_id,
        artist,
        title,
        is_mojibake
    FROM cds_unmatched_working_v6
    WHERE is_mojibake = 1
    LIMIT 30
""").fetchdf())

    cds_id                                    artist  \
0   100003                   ã â â ã â ã â ºâ ã â å
1   100005               ã å â ã â ºâ ã â ºâ ºã â â
2   100011                      â¾ã â â ã ãœ worship
3   100014                            modern talking
4   100027                                       v a
5   100030                      ã â â ã â ã â â¾ã âµ
6   100034                   ã â šã å â ã å å ã â â¾
7   100042                                      deux
8   100043                                      v a
9   100051           ã â â ã â å½ã â¾ã â ã â šë ã â
10  100057                     ã ë â ã å â ã â šã â
11  100059                    ã å â ã â²â ã â â ã â
12  100067                      â â ã ã â½âºã ã ã â
13  100071                          â ã ã ãÿâ ã ãˆâ¹
14  100074                            ã ã ã ã ã ã ãª
15  100083  â¼â¼â¹ãœã ã â¼ã â â â â¹â¾ã â¼â â â³â ãœ
16  100096                                       epo
17  100120                      ã â ã â ã â¾ã â ã â
18  100124                           various artists
19  100153                           various artists
20  100184                               â ã â ã â j
21  100216                      â â¹â¼ã ã ã¼âµâµâ ãœ
22  100218                           various artists
23  100229                          piotr szczepanik
24  100280                             jorge negrete
25  100308                           various artists
26  100311                    various native artists
27  100338                                   â½â²âµ
28  100368                    sevillanas histã³ricas
29  100379                                     junco

                                                                         title  \
0                                        ã æ â³ã â žã â âºã â ã â ¹ã â ã â šâ
1   catsã â â ã â šâªã æ âªã â šâ ã æ å ã æ â ã â½â ã â šâ ã æ â ã â šâ¹ã æ ë
2                                                           child praise vol 1
3                                                                      univers
4                                                              ãƒã âºâ¹ cd 09
5                                                disc13 ã å â ã â ã â ¹ã â šå
6                                                                         lucy
7                                                                      forever
8                                                    beating surviver another
9                                                                         home
10                                                     infinity eighteen vol 1
11                              super live ã â â ã å â ã â â ã â œã â â disc 1
12                                                                         8th
13                                   â ãµâºâ â ã âµâµâ â ã â ã ã â ã ã â½â¾ã 6
14                                                        absolutã ã ã ã ãˆã 2
15                                                        â¼â¼â¹ãœã ã â¼ã â â
16                                                                   poptracks
17                                        ã â â ã âºâºã â â¾ã â å ã â â ã âºå
18                                         zlote przeboje polskiego socjalizmu
19                                     ã â â ã â³â ã â ã â šâ ã song library 1
20                                                             â sâ â â ã â ãº
21                                                                    ã ã â ã
22                           euro darkness 1 ã â å the early days of sebã â å
23                                                         najwieksze przeboje
24                                                   lo mejor de jorge negrete
25                                                        platinum folk live 2
26                                               global celebration gatherings
27                                     â½â²âµ âªã â ã¹â lâ â³ã¼â â ã â²pâºqâ k
28                                            sevillanas histã³ricas volumen i
29                                                                       junco

    is_mojibake
0             1
1             1
2             1
3             1
4             1
5             1
6             1
7             1
8             1
9             1
10            1
11            1
12            1
13            1
14            1
15            1
16            1
17            1
18            1
19            1
20            1
21            1
22            1
23            1
24            1
25            1
26            1
27            1
28            1
29            1

In [69]:
#trace mojibake stage by stage
import duckdb

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

tables = [
    "cds_unmatched_after_v6",
    "cds_unmatched_profiled_v6",
    "cds_unmatched_working_v6",
    "cds_unmatched_curated_v1",
    "cds_only_enrichment_candidates_v1",
    "cds_only_enrichment_scored_v1",
    "cds_only_enrichment_safe_v1",
    "cds_only_enrichment_review_v1",
    "cds_only_enrichment_weak_v1"
]

rows = []
for t in tables:
    try:
        q = f"""
            SELECT
                '{t}' AS table_name,
                COUNT(*) AS total_rows,
                SUM(CASE WHEN is_mojibake = 1 THEN 1 ELSE 0 END) AS mojibake_rows,
                ROUND(
                    100.0 * SUM(CASE WHEN is_mojibake = 1 THEN 1 ELSE 0 END) / COUNT(*),
                    2
                ) AS mojibake_pct
            FROM {t}
        """
        rows.append(con.execute(q).fetchdf())
    except Exception as e:
        print(f"Skipped {t}: {e}")

result = rows[0]
for r in rows[1:]:
    result = result._append(r, ignore_index=True)

print(result)

Connected ✅
Skipped cds_unmatched_after_v6: Binder Error: Referenced column "is_mojibake" not found in FROM clause!
Candidate bindings: "artist_key", "title_key", "artist_clean", "cds_year", "artist"

LINE 5:                 SUM(CASE WHEN is_mojibake = 1 THEN 1 ELSE 0 END) AS mojibake_rows,
                                      ^
Skipped cds_only_enrichment_candidates_v1: Binder Error: Referenced column "is_mojibake" not found in FROM clause!
Candidate bindings: "artist_key_clean", "cds_year", "curation_route", "title_key_clean", "artist"

LINE 5:                 SUM(CASE WHEN is_mojibake = 1 THEN 1 ELSE 0 END) AS mojibake_rows,
                                      ^
                      table_name  total_rows  mojibake_rows  mojibake_pct
0      cds_unmatched_profiled_v6        5555          509.0          9.16
1       cds_unmatched_working_v6        5555          509.0          9.16
2       cds_unmatched_curated_v1        5015            0.0          0.00
3  cds_only_enrichment_scored_v1        4916            0.0          0.00
4    cds_only_enrichment_safe_v1        1652            0.0          0.00
5  cds_only_enrichment_review_v1        3068            0.0          0.00
6    cds_only_enrichment_weak_v1         196            0.0          0.00

In [70]:
print(con.execute("""
    SELECT
        cds_id,
        artist,
        title,
        tracks,
        is_mojibake
    FROM cds_unmatched_working_v6
    WHERE is_mojibake = 1
    LIMIT 30
""").fetchdf())

    cds_id                                    artist  \
0   100003                   ã â â ã â ã â ºâ ã â å
1   100005               ã å â ã â ºâ ã â ºâ ºã â â
2   100011                      â¾ã â â ã ãœ worship
3   100014                            modern talking
4   100027                                       v a
5   100030                      ã â â ã â ã â â¾ã âµ
6   100034                   ã â šã å â ã å å ã â â¾
7   100042                                      deux
8   100043                                      v a
9   100051           ã â â ã â å½ã â¾ã â ã â šë ã â
10  100057                     ã ë â ã å â ã â šã â
11  100059                    ã å â ã â²â ã â â ã â
12  100067                      â â ã ã â½âºã ã ã â
13  100071                          â ã ã ãÿâ ã ãˆâ¹
14  100074                            ã ã ã ã ã ã ãª
15  100083  â¼â¼â¹ãœã ã â¼ã â â â â¹â¾ã â¼â â â³â ãœ
16  100096                                       epo
17  100120                      ã â ã â ã â¾ã â ã â
18  100124                           various artists
19  100153                           various artists
20  100184                               â ã â ã â j
21  100216                      â â¹â¼ã ã ã¼âµâµâ ãœ
22  100218                           various artists
23  100229                          piotr szczepanik
24  100280                             jorge negrete
25  100308                           various artists
26  100311                    various native artists
27  100338                                   â½â²âµ
28  100368                    sevillanas histã³ricas
29  100379                                     junco

                                                                         title  \
0                                        ã æ â³ã â žã â âºã â ã â ¹ã â ã â šâ
1   catsã â â ã â šâªã æ âªã â šâ ã æ å ã æ â ã â½â ã â šâ ã æ â ã â šâ¹ã æ ë
2                                                           child praise vol 1
3                                                                      univers
4                                                              ãƒã âºâ¹ cd 09
5                                                disc13 ã å â ã â ã â ¹ã â šå
6                                                                         lucy
7                                                                      forever
8                                                    beating surviver another
9                                                                         home
10                                                     infinity eighteen vol 1
11                              super live ã â â ã å â ã â â ã â œã â â disc 1
12                                                                         8th
13                                   â ãµâºâ â ã âµâµâ â ã â ã ã â ã ã â½â¾ã 6
14                                                        absolutã ã ã ã ãˆã 2
15                                                        â¼â¼â¹ãœã ã â¼ã â â
16                                                                   poptracks
17                                        ã â â ã âºâºã â â¾ã â å ã â â ã âºå
18                                         zlote przeboje polskiego socjalizmu
19                                     ã â â ã â³â ã â ã â šâ ã song library 1
20                                                             â sâ â â ã â ãº
21                                                                    ã ã â ã
22                           euro darkness 1 ã â å the early days of sebã â å
23                                                         najwieksze przeboje
24                                                   lo mejor de jorge negrete
25                                                        platinum folk live 2
26                                               global celebration gatherings
27                                     â½â²âµ âªã â ã¹â lâ â³ã¼â â ã â²pâºqâ k
28                                            sevillanas histã³ricas volumen i
29                                                                       junco

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                tracks  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ã â ºâ ã â â ã â šå ã â žã â ã â ¹ã â â ã â ã â¼å ã â ã å ã âªã â šâ ã â â ã â ã âªã â žã â â ã å ã â ã å ã â ã å ã â žã â ž ã âµã â šå ã â šã â ž ã â šã â š ã â ã ëœâ ã â âºã å ã â ã â ã â â ã â â½ã â žã â â ã å å¾ã â â ã â ã â ã â šâ ã â žã â â šã â â ã â å ã â å ã ë â ã â å ã â šã âªã å ã â šâ ã â žâ ºã â ã â šâ ¹ã â ã â ã ëœâ ã â²â ã â
1                                                                                                                                                                                          ã æ â ã æ â ã æ âªã æ â¼ ã â šâªã æ â¼ã æ â ã â šâ ã æ ã æ â ã â šâ ã â šâ ã â šâ ã æ âªã â šâ ã æ â ã â šâ½ã æ â³ã â šâ ã æ ã æ â¼ã æ å ã æ â³ã â šâ ã æ â ã â šâªã æ â ã æ â ã â šâ ã æ â ã æ æ ã æ â ž ã ë â ã å â ã â ã ã â šâ ã â šâ ã æ â ¹ã â šâ ã æ â ¹ã æ â ã æ æ ã æ â ž ã ë â ã å ã â ã â ã â šâ œã å â ã æ â ã æ â ã æ â ã â šâ ã æ â ã æ â ã â šâ ã â šâ ã æ â¼ ã ë â ã â ã â ã â ã â šå ã å â ã â šâ ã æ âªã â šâ ã æ â ã æ â ã ë â ã â â¼ã â â ã å â ã æ ã â šâ¹ã æ ë ã æ â ã â šâ ã æ â¼ã â šâ ã æ â ã æ â¼ã æ â³ã â šâº ã ë â ã â â ã âºâºã â â ã â¼å ã æ å¾ã æ â³ã â šâ ã â šâ ã â šâ ã æ âªã æ â¼ã â ã æ â ã æ â³ã æ å ã æ â ã æ â ã â šâ ã æ â¼ã â šâ ã ë â ã â ã â³â ã â â ã æ â ã æ â ã æ ë ã æ â ã æ å½ã æ å ã æ â¼ ã ë â ã â â ã â ã å â ã â šâ ã â šâ ã æ âªã â šâ ã æ â ã ë å¾ã â ã â¼å ã æ â ã æ â ã æ âªã æ â¼
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ã ã â ã â³âªâ â â ã â â â½ãƒâ ã â ã ã ãš â³âªâ ã â¹ã ã â½ã â â ãž â ã â ã ã ã â½ã ã ã â³âªâ ã give thanks â â¹â¼ã â ã â ã ã ã â½ã ã âº â ã â â ã ã â²â² â ã â âµã ã â ã â â â ã âµãž â¼ã â ã ã â â ã âºã ãƒãÿâ¼ã â¼â ãˆâ â ãªâ³âª ã ã â ã ã ã â½ãƒâ â â â â¼â â ã½â ã â ãº ã ã ã âº ãƒâµâ ã âµã â ã â ã â¼ã ã ã¹â¾ã ã ã
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             tv makes the superstar iâ m no rockefeller mystery eyerybody needs somebody heart of an angel who will be there knocking on my door should i would i could i blackbird life is so short nothing but the truth superstar
4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               â ã â ã ã ã ã ãœ â¼â â â³â ãœ ã ã â ã â³âªâ â â ã â â â½ãƒâ ã â ã ã ãšâ ã ã â âµã ã ã ã ã ã ãœâ â â³ã ã ãœâ ã â â â½ãœâ¾ã ã ã ã ã â ã ã ãœ â³âªâ â ã â ã ã â â âµã ã ã âµâµâ½ãƒã ã â¹ã ã ã â ãƒâ â âºâ ã ãœ â¾ã â³ã â ãžã ã ã ãœ â â â¾ã ã ãœ â ã â ã ã ã â â â ã³ ã ã â½ãƒâ¹ã â ã â ã ã ã â½ã ã ã â ã â ã say ã ãœã â â ã â â ã ãœâ ã â â â¼ã â ã ã â â ã ã ã ã ãœâ â â ã ã ãžã â âµâ ã ã 2 â¹ãšâ ã³â³âª â³â ã ã â â â â â ã ã ãœ ã ã â ã ã ã ã âº ã ã âºãžâ âµ â³âªã ã â ã âµâµâ â ã ã²ãˆâ â³âªâ ã³ â ã â ã ã ã â ã
5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ã å â ã â â ã â â ã â â ã â â½ã â ã â šã å ã â šâ ¹ã â šã â œ ã â šâ²ã â ëœã å â ã â â ã â š ã â ã å ã å â ã â ã â žã â¾å ã â â ã â šâ ã â šâ ã â šâ ã æ â³ã â šâ ã æ â ã â â ºã â â ã â ã å ã â šå ã â â ¹ ã â â ¹ã â å ã â šã â¾ã â šå ã â šå ã â ã æ â ã æ â ã â šâ ã æ â ã æ â ã æ â ã æ â¼ 1 2 3 ã å â ã â¾å ã â ã â ã â â ã â â
6                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    lucy ã æ å¾ã æ â ã â šâ ã æ ã â šâ ã â šâ¹ã æ ë ã æ â ã æ å ã â ã â âº ã â šâ ã æ â ã â šâ ã æ â ã â šâ ã æ â ã â â ã å â ã å â ã â â ã â šå ã â ã âµâ ã â žã â šâ¹ã â šâ ã æ â¼ã æ ë life is good honey bunny tã â šâ ã æ â ã æ â ž ã â âºã â â ã â ã ëœå rule ã â â²ã â âªã â ºã âªã â žã â â ã â â ã â ã â ã â ëœã â ã â å ã â ¹ã â šâ ã å â ã â œâ ã â šâ ã å â ã â ã â šâ ¹
7                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   intor deux forever â³âªâ â âµâ¹â¾ã âºã â¾ã â ã ã ã â¾ãºâ¾ã â ã â ã ã ã â ã â ã â½ãƒ â¹â ã â âºã â¼ã â â â¼â go go go ãˆã âµã â¾ã â ã ã ã â³âªã ã â½â½ã ã â ã â â â ã â â â ã â â â â â¾ãˆâ â â¼â â¾ã ã ã â³â²ã ãš
8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        flash of love wild style qingdao ã âª ã â²â ã â â ã âºâ ¹edit quart acid to the muzik alien 3p 59 hardfloor style ã â ã â â ã â â millionaire stoic ss 1 sparker ss 2 wild 20 rebirth of beaterror edit route 135 s re birth
9                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          fat mama ã â šâ ã æ â ã æ â ã æ å ã æ âªã æ â³ ã â šâ ã æ â ã æ âª ã æ â ã æ â³ã â šâ ã æ â ã æ å ã æ â³ ã â šâ¹ã â šâ ã æ âªã æ â¼ã æ å ã æ â³ 97 ã ã â ã â ã âªã â žã â³â ã â šâ³ã æ å ã æ â ã æ â ¹ã â šâ ã â šâ¹ã â ã âµ ã æ â ã â šâ ã â ã â â ã â šâ ã ëœâ¼ã â¼â ã â one more time one more chance ã æ â ã â šâµã â â ã â ã â â home
10                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 intro identification track infinity 18 be together shadow dancing mix don t need to say good bye happy new millennium 2g mix my wish if you wanna be with me our days orchestral winter mix ã â šã â ã å ã â ã â ã â ã â¼å ã â žã â ã â ã â winter buzz night sky evidence of love breakin my heart outro vol 2 available in april
11                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 introduction ã â â ã â â ã å ã â šâ žã â ã â šâ ¹ã å ã â â ã â ã æ â ã æ â œã æ â ã å â ã â¾å ã â ã â â žã å ã â šâ ã æ â ã æ â ã æ â ã â ã â ã æ â ã â šâ ã æ ë ã â šâ ã æ â ã æ â ã â ¹â ã â žã â â ã â ¹ã â ã ë â ã â å ã â ã æ âªã æ ã æ â ã æ â¼ã æ â ã â âº ã â šâµã æ â ã â šâ ã â šâ ã â šâ ã â â¹ã â â ã æ â ã â šâ ã æ â ã æ â ã â šâ ã â šâºã æ â ã æ â ã â šâ ã æ â³ ã æ ë ã æ â ã æ â ã æ âªã æ â³ã æ â ã æ ã â šâ¹ ã â æ ã ë ã â šâ ¹ã â šâµã æ â³ã â šâ ã æ æ ã æ ë
12                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          01 â ã ã ã â ã â³â ã ãœ ã ã â¾ã 02 i can wait 4u 03 â ã â â â ã â¾ã â¼ã â³ãšâ â â ã 04 âµãž â¹ã ã â ã ãœâºâ 05 âºã â¹ã 06 ã ã â½ã 07 â³ãž ã â ã ã ã ãšâ â 08 âºâ â¾ã â â â³ãƒâ â â½â 09 honeymoon 10 âµâ ãˆâ 11 ã ã â ã â ã â ã â â â â â½âºâ ã¾ã ã 12 jr
13                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         â ã â â âºâ ã ã â¾ã â â â ã â â â ã â½ã â½ã ã ã â½ã ã ã ã ã â â â¹ã â ã³âºâ¼ã ã â ã³ â¼â¼â ã³ â ã âµã â¹ãžã â ã ãœ â¾ã ã â â³âª â³â â ã â½ã â ã âµã ã ãœâ â ã â â â â ã â¾ã â³â â ã â ã ã ã â ã â³âªã ã â¾ã â¹ã ã ã â³â â â ã âº â â â¾ãˆâ â ã ã â²â² â â â ã â ã â³âªã ã â â ã â½ã â ã â â ã â ãº â â ã ãœ â³âªã ã â â â ã â ã ã ã ã ã â ã â ã ã â ã ã ã ã â¼â ã ã â½ã ã âº â¾ã ã â â¾ãˆâ â³ â â â¾ã â â â â âµã â¾ã ã â â â ã ã ã ã ã ãžã ãšã ã â½ã ã âº

In [71]:
import duckdb

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

print(con.execute("""
    SELECT
        'cds_unmatched_profiled_v6' AS stage,
        COUNT(*) AS total_rows,
        SUM(CASE WHEN is_mojibake = 1 THEN 1 ELSE 0 END) AS mojibake_rows
    FROM cds_unmatched_profiled_v6

    UNION ALL

    SELECT
        'cds_unmatched_working_v6' AS stage,
        COUNT(*) AS total_rows,
        SUM(CASE WHEN is_mojibake = 1 THEN 1 ELSE 0 END) AS mojibake_rows
    FROM cds_unmatched_working_v6

    UNION ALL

    SELECT
        'cds_unmatched_curated_v1' AS stage,
        COUNT(*) AS total_rows,
        SUM(CASE WHEN is_mojibake = 1 THEN 1 ELSE 0 END) AS mojibake_rows
    FROM cds_unmatched_curated_v1

    UNION ALL

    SELECT
        'cds_only_enrichment_scored_v1' AS stage,
        COUNT(*) AS total_rows,
        SUM(CASE WHEN is_mojibake = 1 THEN 1 ELSE 0 END) AS mojibake_rows
    FROM cds_only_enrichment_scored_v1

    UNION ALL

    SELECT
        'cds_only_enrichment_safe_v1' AS stage,
        COUNT(*) AS total_rows,
        SUM(CASE WHEN is_mojibake = 1 THEN 1 ELSE 0 END) AS mojibake_rows
    FROM cds_only_enrichment_safe_v1

    UNION ALL

    SELECT
        'cds_only_enrichment_review_v1' AS stage,
        COUNT(*) AS total_rows,
        SUM(CASE WHEN is_mojibake = 1 THEN 1 ELSE 0 END) AS mojibake_rows
    FROM cds_only_enrichment_review_v1

    UNION ALL

    SELECT
        'cds_only_enrichment_weak_v1' AS stage,
        COUNT(*) AS total_rows,
        SUM(CASE WHEN is_mojibake = 1 THEN 1 ELSE 0 END) AS mojibake_rows
    FROM cds_only_enrichment_weak_v1
""").fetchdf())

Connected ✅
                           stage  total_rows  mojibake_rows
0      cds_unmatched_profiled_v6        5555          509.0
1       cds_unmatched_working_v6        5555          509.0
2       cds_unmatched_curated_v1        5015            0.0
3  cds_only_enrichment_scored_v1        4916            0.0
4    cds_only_enrichment_safe_v1        1652            0.0
5  cds_only_enrichment_review_v1        3068            0.0
6    cds_only_enrichment_weak_v1         196            0.0

In [72]:
print(con.execute("""
    SELECT
        cds_id,
        artist,
        title,
        is_mojibake,
        exclusion_reason
    FROM cds_unmatched_excluded_v1
    WHERE exclusion_reason = 'unrecoverable_mojibake'
    LIMIT 30
""").fetchdf())

    cds_id                                    artist  \
0   100003                   ã â â ã â ã â ºâ ã â å
1   100005               ã å â ã â ºâ ã â ºâ ºã â â
2   100011                      â¾ã â â ã ãœ worship
3   100014                            modern talking
4   100027                                       v a
5   100030                      ã â â ã â ã â â¾ã âµ
6   100034                   ã â šã å â ã å å ã â â¾
7   100042                                      deux
8   100043                                      v a
9   100051           ã â â ã â å½ã â¾ã â ã â šë ã â
10  100057                     ã ë â ã å â ã â šã â
11  100059                    ã å â ã â²â ã â â ã â
12  100067                      â â ã ã â½âºã ã ã â
13  100071                          â ã ã ãÿâ ã ãˆâ¹
14  100074                            ã ã ã ã ã ã ãª
15  100083  â¼â¼â¹ãœã ã â¼ã â â â â¹â¾ã â¼â â â³â ãœ
16  100096                                       epo
17  100120                      ã â ã â ã â¾ã â ã â
18  100124                           various artists
19  100153                           various artists
20  100184                               â ã â ã â j
21  100216                      â â¹â¼ã ã ã¼âµâµâ ãœ
22  100218                           various artists
23  100229                          piotr szczepanik
24  100280                             jorge negrete
25  100308                           various artists
26  100311                    various native artists
27  100338                                   â½â²âµ
28  100368                    sevillanas histã³ricas
29  100379                                     junco

                                                                         title  \
0                                        ã æ â³ã â žã â âºã â ã â ¹ã â ã â šâ
1   catsã â â ã â šâªã æ âªã â šâ ã æ å ã æ â ã â½â ã â šâ ã æ â ã â šâ¹ã æ ë
2                                                           child praise vol 1
3                                                                      univers
4                                                              ãƒã âºâ¹ cd 09
5                                                disc13 ã å â ã â ã â ¹ã â šå
6                                                                         lucy
7                                                                      forever
8                                                    beating surviver another
9                                                                         home
10                                                     infinity eighteen vol 1
11                              super live ã â â ã å â ã â â ã â œã â â disc 1
12                                                                         8th
13                                   â ãµâºâ â ã âµâµâ â ã â ã ã â ã ã â½â¾ã 6
14                                                        absolutã ã ã ã ãˆã 2
15                                                        â¼â¼â¹ãœã ã â¼ã â â
16                                                                   poptracks
17                                        ã â â ã âºâºã â â¾ã â å ã â â ã âºå
18                                         zlote przeboje polskiego socjalizmu
19                                     ã â â ã â³â ã â ã â šâ ã song library 1
20                                                             â sâ â â ã â ãº
21                                                                    ã ã â ã
22                           euro darkness 1 ã â å the early days of sebã â å
23                                                         najwieksze przeboje
24                                                   lo mejor de jorge negrete
25                                                        platinum folk live 2
26                                               global celebration gatherings
27                                     â½â²âµ âªã â ã¹â lâ â³ã¼â â ã â²pâºqâ k
28                                            sevillanas histã³ricas volumen i
29                                                                       junco

    is_mojibake        exclusion_reason
0             1  unrecoverable_mojibake
1             1  unrecoverable_mojibake
2             1  unrecoverable_mojibake
3             1  unrecoverable_mojibake
4             1  unrecoverable_mojibake
5             1  unrecoverable_mojibake
6             1  unrecoverable_mojibake
7             1  unrecoverable_mojibake
8             1  unrecoverable_mojibake
9             1  unrecoverable_mojibake
10            1  unrecoverable_mojibake
11            1  unrecoverable_mojibake
12            1  unrecoverable_mojibake
13            1  unrecoverable_mojibake
14            1  unrecoverable_mojibake
15            1  unrecoverable_mojibake
16            1  unrecoverable_mojibake
17            1  unrecoverable_mojibake
18            1  unrecoverable_mojibake
19            1  unrecoverable_mojibake
20            1  unrecoverable_mojibake
21            1  unrecoverable_mojibake
22            1  unrecoverable_mojibake
23            1  unrecoverable_mojibake
24            1  unrecoverable_mojibake
25            1  unrecoverable_mojibake
26            1  unrecoverable_mojibake
27            1  unrecoverable_mojibake
28            1  unrecoverable_mojibake
29            1  unrecoverable_mojibake

In [73]:
import duckdb
import pandas as pd

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Clean mojibake only in cds_tracklist inside the enriched final table
# ------------------------------------------------------------
# Comments:
# - We do NOT delete rows.
# - We only blank the cds_tracklist field when it looks unreadable.
# - The rule below is heuristic:
#     1) obvious mojibake marker sequences like "ã", "â", "ð", "�"
#     2) repeated corrupted-looking fragments
# - If flagged, we replace cds_tracklist with NULL.
print("Creating cds_to_mb_final_mapping_v9_enriched_cleantrack_v1...")

con.execute(r"""
    CREATE OR REPLACE TABLE cds_to_mb_final_mapping_v9_enriched_cleantrack_v1 AS
    SELECT
        * EXCLUDE (cds_tracklist),

        CASE
            WHEN cds_tracklist IS NULL OR trim(cds_tracklist) = '' THEN NULL

            -- obvious mojibake markers
            WHEN regexp_matches(lower(cds_tracklist), '(ã|â|ð|�)') THEN NULL

            -- common broken UTF-8 / Latin-1 style patterns
            WHEN regexp_matches(lower(cds_tracklist),
                '(ã[a-z0-9]|â[a-z0-9]|ð[a-z0-9]|[a-z]ã[a-z]|[a-z]â[a-z])'
            ) THEN NULL

            -- suspicious density of non-alnum junk characters
            WHEN length(regexp_replace(coalesce(cds_tracklist, ''), '[A-Za-z0-9 ]', '', 'g')) > 0.20 * length(coalesce(cds_tracklist, ''))
                THEN NULL

            ELSE cds_tracklist
        END AS cds_tracklist

    FROM cds_to_mb_final_mapping_v9_enriched
""")

print("✅ Table created: cds_to_mb_final_mapping_v9_enriched_cleantrack_v1")

print("\n--- Count of rows where cds_tracklist was blanked ---")
print(con.execute(r"""
    SELECT COUNT(*) AS n
    FROM cds_to_mb_final_mapping_v9_enriched_cleantrack_v1 t
    JOIN cds_to_mb_final_mapping_v9_enriched s
      ON t.cds_id = s.cds_id
    WHERE s.cds_tracklist IS NOT NULL
      AND trim(s.cds_tracklist) <> ''
      AND t.cds_tracklist IS NULL
""").fetchdf())

print("\n--- Preview: rows where cds_tracklist was blanked ---")
print(con.execute(r"""
    SELECT
        t.cds_id,
        t.cds_artist,
        t.cds_title,
        s.cds_tracklist AS original_cds_tracklist,
        t.cds_tracklist AS cleaned_cds_tracklist
    FROM cds_to_mb_final_mapping_v9_enriched_cleantrack_v1 t
    JOIN cds_to_mb_final_mapping_v9_enriched s
      ON t.cds_id = s.cds_id
    WHERE s.cds_tracklist IS NOT NULL
      AND trim(s.cds_tracklist) <> ''
      AND t.cds_tracklist IS NULL
    LIMIT 30
""").fetchdf())

Connected ✅
Creating cds_to_mb_final_mapping_v9_enriched_cleantrack_v1...
✅ Table created: cds_to_mb_final_mapping_v9_enriched_cleantrack_v1

--- Count of rows where cds_tracklist was blanked ---
     n
0  671

--- Preview: rows where cds_tracklist was blanked ---
    cds_id             cds_artist  \
0   100001                various
1   100024                   175r
2   100026     day after tomorrow
3   100031                spartak
4   100037   sportfreunde stiller
5   100087          tschou zã me
6   100089        various artists
7   100099     fabienne thibeault
8   100101                various
9   100114          gerardo peã a
10  100116      stefan sundstrã m
11  100141              mã ra per
12  100143                clannad
13  100180           albin berger
14  100191                gem boy
15  100207        poems for laila
16  100225  paquita la del barrio
17  100236          terje tysland
18  100244       jari sillanpã ã
19  100246            bluatschink
20  100260                 ghymes
21  100267              at tambur
22  100275          kaj og andrea
23  100297                 ghymes
24  100302                 hector
25  100321                   ichu
26  100326                maã a s
27  100332           carlos vives
28  100337              la tordue
29  100344         juliette greco

                                             cds_title  \
0                          frankfurt trance vol 04 cd1
1                                                songs
2                                             elements
3                                                golem
4                                       die gute seite
5                                            wã ge dir
6                                       dorival caymmi
7                      les plus belles chansons cd 2 2
8                                ich hab schlager lieb
9                                                 nada
10                                            babyland
11                                       minnesmã rken
12                                                anam
13                                         wahre liebe
14                            il triangolo nei bermuda
15                             frã¼hstã¼ck in budapest
16                                        azul celeste
17                                         det goe liv
18                                    jari sillanpã ã
19                                         bluatschink
20                                       smaragdvã ros
21                                           at tambur
22                                        pã nt goddag
23                          az ifjãºsã g sã³lyommadã r
24                                               hidas
25                                                ichu
26                                     mariachi andino
27                                la tierra del olvido
28                                         champ libre
29  aimez vous les uns les autres ou bien disparaissez

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 original_cds_tracklist  \
0                                                                           dj tom stevens vs fridge outface 2000 radio mix alice deejay better off alone signum remix tillmann uhrmacher feat peter ries bassfly original mix dj 2 l 8 too late time square invisible girl future breeze remix cirillo across the soundline dj leon jam x hold it sean dexter synthetica extended mix dj bjã rn on a mission original mix 8voice music hypnotizes 2000 alex apollo jahr 2000 headroom utopia radio mix
1                                                                                                                                                                     inst ã â â ã âºâº ã æ â œã æ â ã æ â¼ã æ â ã â šâ ã æ â ã æ â ã æ â ã â šâ ã â šâº album version party ã æ ã æ æ ã æ â ã æ â¼ã æ â ã â šâ ã æ â ã â ã â šâ ã â ã â ¹ã âºâº ã æ â ã â ã â â album version ã â âºã â ã â â žã ë ã â end ofã â â ã â å ã â â ¹ã â â ã â ã æ å ã æ â¼ã æ å ã â šâ¹ã æ ë ã æ â ã æ æ ã â šâ cccd data
2                                                                                                                                                                                                                                                                                                            high spirit time of destiny ã â šã â šå ã âµã â šå ã å ã â â ã â â ã â šâ ã â ã â ã â sentence stay in my heart oval losing myself funny days morning glow grow naturally flower of youth
3                                                                                                                                                                                                                                                                                                                sigo viviendo leconseil lunaire naprzod vorwã rts tiden seerã uberjenny pour le grec i hate you excited body beat elven song f the army love letter for michelle ciao ciao ceaussescu
4                                                                                                                                                                                                                                                                                                           wie lange sollen wir noch warten komm schon ein kompliment sportbeat auf der guten seite independent international 7 tage 7 nã chte tage wie dieser der fortschritt 10 1 hurra wir fliegen
5                                                                                                                                                                                                                                                                                                                                                                                         daheim botti alte mã nsch forscherlã be kaktus troum wã ge dir boum chilegmeinsversammlig grat vã geli rã si
6                                                toquinho e vinicius dora agostinho dos santos saudade de itapoa maria creuza joao valentao pocho eu nao tenho onde morar ana lucia acalanto paulinho nogueira histã²ria de pescadores maria creuza saudade da bahia cauby peixoto sã² louco maria creuza marina agostinho dos santos nao tem soluã ao paulinho nogueira lã vem a baiana thereza tinoco sabado em copacabana toquinho vamos chamar o vento orchestra coro rge o que ã que a baiana tem
7                                                                                                                                                                                                                                                     je suis nã e ce matin je voudrais faire cette chanson le goã t du miel c est en hiver bon voyage histoire d amour les filles comme moi les choses de ma vie le coeur voyageur music hall je ne suis plus lã les gens de mon pays chaleur humaine
8   guildo horn guildo hat euch lieb jã¼rgen marcus eine neue liebe ist wie ein neues leben werner leismann mendocino franz k marmor stein und eisen bricht temudschin dschinghis khan susi s schlagersextett speedy gonzales peter orloff schlagerparty klaus lage band 1000 und 1 nacht zoom spider murphy gang skandal im sperbezirk de hã hner pizza wundaba lothar f ich zahle keine steuern mehr josie josie original buam herzilein palast orchester gesang max raabe kein schwein ruft mich an
9                                                                                                                                                                                                                                                                                                                                                      aguacero el sapo entre comillas adiccion te quiero y ya el gigante yo soy buenos vecinos â quien quiere jugar la revolucion canto de abril nada
10                                                                                                                                                                                                                                                              sabinas sjã tte sã ng babyland blã ljusvals flã der onda barn under isen ligger himlen boy oboy hjã rtat tar aldrig semester hur sabina gã r en konst utav att gã tyst minut fã r felsorterade sopor sopvisa fã r jan banan data track
11                                                                                                                                                                                                                                                                                                                           med fã tterna fã rst en skã tsam jã kel tid hatten hej ã hã det ã r du klockan fyra sã ndamã ran lã gg benen pã ryggen gammelpiga raj raj rosita minnesmã rken extraspã r
12                                                                                                                                                                                                                                                                                                     rã na cruinne in a lifetime anam in fortune s hand the poison glen wilderness instrumental harry s game why worry ãširchill an chreagã in love and affection you re the one dobhar instrumental
13                                                                                                                                                                                                        wahre liebe ich streichel in gedanken deine seele wintertrã ume du hallo ich hab dich vermisst manjana ich weiss du wirst noch da sein weich wie wachs die wahrheit ist tief unter meiner haut bring mich zu dir nach haus maria bonita wenn du einsam bist heut nacht aus irgendeinem grund
14                                                                                                                                                                                                                                                                                   i fantastici 4 voglio farla finita ridammelo lorena microscopio oh nonna cappuccetto rotto il guardone ombre asta la vista uno quattro quattro la mia donna ã un estetista 2001 odissea nello spizio cotton fiock
15                                                                                                                                                                                                                                                                                                   vielleicht arsch aus berlin alles wird gut wã¼rdelos und frei nicht vorbei kã¼ss ich deinen mund umgestalten suche nach dem glã¼ck annes song sun is on the roof weiãÿt du noch entspanntes outro
16                                                                                                                                                                                                                                                                                                                         azul celeste cuã nto pagas anhelo te parto el alma da lo mismo donde caigo te lo dejo todo la que se fue cã³mo me voy a ir fallaste corazã³n hoy me voy nomã s por tu culpa
17                                                                                                                                                                                                                                                              det goe liv veit kor du finn mã fra bã rgefjell sommersang samme gammle leksa over lik for dã ã e fra trã ndelag likevel gla i dã fint nã r du gã r no e det forbi har aldri gjort nã n vondt gonatt gonatt drã mmen om d instrumental
18                                                                                                                                                                                                                                                                                            punainen taivas satulinna oot tã ydellinen olen luonasi aina kirjoitettu tã htiin haavoitettu siellã missã nyt oot kulku ihmisen kaduilla tuulee sun luo tuulina kã yn tã ssã kaikki on pariisi helsinki
19                                                                                                                                                                                                                                                                                             d r bluatschink a schalele kaffee anti streãÿ jodler vorbei und er marschiert oa nota samba knou mah a haschreck im lecht l a guater freind da fohrt d r zug drib r loãÿ sie reda a wunder und a schond
20                                                                                                                                                                                                                                                                                                         a pã nz szaga kelet nyugati ã tjã rã³ smaragdvã ros pirula szã rnyaskezã szeretãµk jã zuska kiscsizmã ja tã¼zet viszek szã ztallã ros vetkãµzãµs dal ã szaki szã l duna partjã n kã tszaxis
21                                                                                                                                                                                                                                                                                      arabesca jig horizonto danã a do urso d fernando sanfoneiro bourrã les poules houppã es chotiã a swingada folhinha de salgueiro sorrizo d ã ngela valsa de 5 tempos sonho the lazy philosopher israelita sueca
22                                                                                                                                                                                                                                                                                     gensyns duet andrea s sang hvis hunde ku synge kaj s rap vrã vl dikke dikke dikke snus kaj og andrea s duet tja tja tja ugesangen kaj s sang hvad vi dog siger hã jre venstre bakke snagvent jeg er en frã mand
23                                                                                                                                                                                                                       apor lã zã r tã nca csallã³kã zi tã ncok madari bã jti leã nytã nc martosi tã ncok csallã³kã zi ugrã³sok ipoly menti nã pdalok szã ztallã ros katonã nak zobor vidã ki nã pdalok nyitra vidã ki dudanã³tã k ã ji nã pdalok bodrogkã zi ugrã³s tã ncok a szilicei fennsã krã³l
24                                                                                                                                                                                                                                                                             kaikki pã ã see taivaaseen hã n on mun nainen tahdon kaljalle kunhan meet yksi pieni ihme nuoruus sitã tai tã tã muistinko kertoa jos lukisit kuin kirjaa ei ole aikaa love is the only way elã mã n ja kuoleman tanssi
25                                                                                                                                                                                                                                                                                                                                                             toyos tarkeada kena kena sacsayhuamanpi sol y luna bailecito sicuriada ollantay cueca tu orgullo leã o verde kena solo dpt folk bolivia
26                                                                                                                                                                                                                                         asã fue cã³mo te voy a olvidar abrã zame la mitad que me faltaba deja que salga la luna por mujeres cã³mo tãº te sigo amando me voy a quitar de enmedio no sã olvidar si tãº supieras si nos dejan voy a apagar la luz cã³mo iba a pensar acã bame de matar
27                                                                                                                                                                                                                                                                                                                                                                           pa mayte fidelina la tierra del olvido zoila rosa acua la cachucha bacana diosa coronada la puya puyã ella jam en jukumey
28                                                                                                                                                                                                                                                                                                                                             l heureux mix une chanson paranoya la vie c est dingue la muerte cap tain naimo compte in is god a dog le zã le des iles contre vous je tombe le petrin
29                                                                                                                                                                                                                                                                 je jouais sous un banc l amour flou pour vous aimer il et elle deux au monde au temps oã¹ un peu moins que tout ã l heure couvre feu comme si de rien n etait mãªme adieu bohã me la rose et le rã sã da dã jeuner la mer se retire

   cleaned_cds_tracklist
0                   None
1                   None
2                   None
3                   None
4                   None
5                   None
6                   None
7                   None
8                   None
9                   None
10                  None
11                  None
12                  None
13                  None
14                  None
15                  None
16                  None
17                  None
18                  None
19                  None
20                  None
21                  None
22                  None
23                  None
24                  None
25                  None
26                  None
27                  None
28                  None
29                  None

In [74]:
import os

os.makedirs("../data_processed/exports", exist_ok=True)

out_path = "../data_processed/exports/cds_to_mb_final_mapping_v9_enriched_cleantrack_v1.csv"

con.execute(f"""
    COPY cds_to_mb_final_mapping_v9_enriched_cleantrack_v1
    TO '{out_path}'
    WITH (HEADER, DELIMITER ',')
""")

print(f"✅ Exported: {out_path}")

✅ Exported: ../data_processed/exports/cds_to_mb_final_mapping_v9_enriched_cleantrack_v1.csv

In [75]:
import duckdb
import pandas as pd

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Build thesis-friendly enriched review-candidate table
# ------------------------------------------------------------
# Comments:
# - This keeps the MB review candidates
# - and adds CDS-side metadata from the original cds table:
#     category, genre, tracks
# - It should be interpreted as:
#     plausible MB enrichment candidates requiring review
print("Creating cds_to_mb_review_candidates_v6_round2_enriched...")

con.execute("""
    CREATE OR REPLACE TABLE cds_to_mb_review_candidates_v6_round2_enriched AS
    SELECT
        -- ----------------------------------------------------
        -- CDS-side metadata
        -- ----------------------------------------------------
        r.cds_id,
        c.artist AS cds_artist,
        c.title AS cds_title,
        c.cds_year,
        c.category,
        c.genre,
        c.tracks AS cds_tracklist,

        -- ----------------------------------------------------
        -- Review-candidate linkage fields
        -- ----------------------------------------------------
        r.release_id,
        r.release_title,
        r.main_artist_name,
        r.artist_credit_full,
        r.total_tracks,
        r.barcode,
        r.mb_year,

        -- ----------------------------------------------------
        -- Review / scoring metadata
        -- ----------------------------------------------------
        r.artist_sim,
        r.title_sim,
        r.score_gap,
        r.best_score,
        r.second_best_score,
        'matched_review_candidate' AS match_status

    FROM cds_to_mb_review_candidates_v6_round2 r
    LEFT JOIN cds c
      ON r.cds_id = c.cds_id
""")

print("✅ Table created: cds_to_mb_review_candidates_v6_round2_enriched")

print("\n--- Row count ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM cds_to_mb_review_candidates_v6_round2_enriched
""").fetchdf())

print("\n--- Preview ---")
print(con.execute("""
    SELECT *
    FROM cds_to_mb_review_candidates_v6_round2_enriched
    LIMIT 20
""").fetchdf())

Connected ✅
Creating cds_to_mb_review_candidates_v6_round2_enriched...
✅ Table created: cds_to_mb_review_candidates_v6_round2_enriched

--- Row count ---
    n
0  64

--- Preview ---
    cds_id           cds_artist                               cds_title  \
0   100415       vã ctor herdia                          vã ctor herdia
1   100504          mary bergin                           feadoga stain
2   100837       billie holiday             1949 52 radio tv broadcasts
3   100881                scarp                                   scarp
4   100911       nellie lutcher       nellie lutcher her rhythm 2 of 4
5   101041          lada kerndl                            evergreens 2
6   101111        george benson                         jazz masters 21
7   101143   samla mammas manna                                  maltid
8   101220      louis armstrong  the great chicago concert 1956 disc 2
9   101632          bill bryson     in a sunburned country disc 7 of 10
10  101685    rolf just nielsen                          barnas viser 2
11  101751  christopher peacock                            simple gifts
12  101836          the beatles               the beatles 1962 1966 cd2
13  101868      placido domingo                    songs of love disk 1
14  101870       alen vitasovic                          gusti su gusti
15  101998          abbacadabra                       abbasalute disk 1
16  102025              orbital                    orbital green album
17  102027          jules verne    20 000 leagues under the sea disk 1
18  102080        beth carvalho                        cd duplo 1 de 2
19  102104           land synir                        alveg eins og pu

    cds_year category         genre  \
0       1991     folk      folklore
1       1979     folk          folk
2       <NA>     jazz          jazz
3       1994     jazz    avantgarde
4       <NA>     jazz        oldies
5       1999     jazz          jazz
6       <NA>     jazz          None
7       <NA>     jazz          None
8       1997     jazz          jazz
9       <NA>     misc          None
10      <NA>     misc          None
11      <NA>     misc          None
12      1993     misc  classic rock
13      <NA>     misc          None
14      1994     misc      pop folk
15      1999     misc           pop
16      1991     misc          None
17      <NA>     misc          None
18      <NA>     misc          None
19      1998     misc          rock

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           cds_tracklist  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           cuando se deja querer carbonero la lluviosa corazã³n enamorado vaya a saber que me pasa campesino zamba para mi rã o canciã³n del picapedrero septiembre desde mi guitarra te voy a traer al vino la arenosa la palabra paz
1   rileanna ril gan ainm ah surely the union reel rileanna miss johnson s miko russel s poirt tom billy s the langstern pony rileanna sean reid s the drunken landlady fonn mall liam o raghallaigh rileanna mrs crehan s gerry commane s the rainy day poirt port sean seosamh sean thiobraid arann the wheels of the w orld rileanna the blackberry blossom maud miller i wish i never saw y ou up to your knees in sand cornphiopai garrai na bhfeileoig miss galvin rileanna the lady on the island the concert reel the hut in theb og fonn mall mo mhuirnin ban rileanna mick hand s the reel of mullinavat poirt the monaghan jig nora chrionna rileanna kitty gone a milking last night s fun the wind that sh akes the barley
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           my man miss brown to you keeps on a rainin lover man i cover the waterfront all of me you re my thrill he s funny that way billie s blues miss brown to you my man tenderly
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     lepont dobermann goatkiller abbotts bond in cairo with culleen meerkat and desert rat crows and les poules huppees grinme duet sansonette and skin job duet2 eight years with bunty and the eagle
4                                                                                                                                                                        without a song wish i was in walla walla life is like that a maid s prayer ditto from me to you my man mon homme i used to be dull the dog fight song lutcher s leap say a little prayer for me cool water a chicken ain t nothin but a bird princess poo poo ly has plenty papaya he sends me my little boy my new papa s got to have everything come and get it honey little sally walker to be forgotten darktown strutter s ball that will just about knock me out glad rag doll april in paris only you kiss me sweet baby please stop and think about me
5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          brazilian love song good morning heartache i ll never fall in love again september in the rain diana if my baby just cares for me since i fell for you gotta see baby tonight for the good times on a slow boat to china when i fall in love
6                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      thunder walk sack o woe tuxedo junction billie s bounce something octopus s garden what s new shape of things to come the boss out of the blue low down and dirty i remember wes
7                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               dundrets fr jder of rutsedd f rlossning den aterupplivade laten folkvisa i morse syster system t rningen svackorpo ngen minareten vaerelseds tilbud minareten ii circus apparatha probably the probably
8                                                                                                                                                                                                                                                                                                                                                                                                                                                          rockin chair bucket s got a hole in it perdido clarinet marmalade mack the knife medley tenderly you ll never walk alone stompin at the savoy margie big mama s back in town that s my desire ko ko mo i love you so when the saints go marching in the star spangled banner
9                                                                                                                                                                                                                                                                                                                                                                                                        in a sunburned country 07 01 in a sunburned country 07 02 in a sunburned country 07 03 in a sunburned country 07 04 in a sunburned country 07 05 in a sunburned country 07 06 in a sunburned country 07 07 in a sunburned country 07 08 in a sunburned country 07 09 in a sunburned country 07 10 in a sunburned country 07 11
10                         i skogen skulle vã re fest flã y en liten blã fugl blã mann blã mann bukken min bro bro brille der bor en baker det satt to katter pã et bord attekatte noa fader jacop fingrene vã re haren uti grasset jeg gikk en tur pã stien jeg satte brillene pã min nese ã tenk at grã pus har fire smã lille lotte lille postbud min due lille persille i hagen stã r lisa gikk til skolen med krã llet hale nã r en liten mus skal ut og gã ole dole doff per spelmann vã re kjoler er i alle farger min elskede dukke sã stã du er ta den ring tornerose tre katter smã ã jeg vet en seter nã r trollmor har lagt sine elleve smã troll ute pã den grã nne eng pitt pott nã tt den fã rste lille grisen lillebror
11                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               silver bells the christmas song simple gifts deck the halls ave maria grown up christmas list first noel skating jingle bells prelude silent night in dulci jubilo we three kings white christmas i wonder as i wander
12                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          help you ve got to hide your love away we can work it out day tripper drive my car norwegian woods this bird has flown nowhere man michelle in my life girl paperback writer eleanor rigby yellow submarine
13                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             spanish eyes be my love somewhere try to remember medley blue moon moon river tonight love story over the rainbow la vie en rose autumn leaves o sole mio el condor pasa
14                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               gusti su gusti jenu noc po ud mene sandra ca je gusti su gusti verzija ne moren bez nje katerina uzmi me ca ja cu cekati finilo je sve
15                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                dancing queen knowing me knowing you fernando money money money the winner takes it all take a chance on me s o s mamma mia super trouper on on on waterloo chiquitta
16                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     the moebius speed freak oolaa desert storm fahrenheit 303 steel cube idolatry high rise chime live midnight live belfast i think it s disgusting
17                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         a floating reef i form my opinion full steam ahead the narwhal in the sea rescued captain nemo a submarine forest on land mysterious confinement a burial the arabian tunnel
18                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        virada vou festejar se voce quiser toque de malicia saco de feijao salario minimo pedi ao ceu pedaco de ilusao se voce me ouvisse escasseia corda no pescoco te segura o mundo e um moniho as rosas nao falam
19                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  terlã n heimsendir ã hyggjulaus leyfã u mã r dreymir geimflaugin birtir til hver ã aã rã ã a ã startfar hvaã hef ã g gert fullkomin vã ã vastã ltur

    release_id                           release_title       main_artist_name  \
0      3901333                          Victor Heredia         Víctor Heredia
1       699853                           Feadóga Stáin            Mary Bergin
2       950274       1949-1952 Radio and TV Broadcasts         Billie Holiday
3      2529598                                 SCAR EP                   SCAR
4       104582             Nellie Lutcher & Her Rhythm         Nellie Lutcher
5       990629                            Evergreens 3            Laďa Kerndl
6      2432954                             Jazzmasters          George Benson
7        92985                                  Måltid     Samla Mammas Manna
8       484236               The Great Chicago Concert        Louis Armstrong
9      2481970                  In a Sunburned Country            Bill Bryson
10     1054093                          Barnas viser 1       Rolf Just Nilsen
11      902737                            Simple Gifts  Christopher Parkening
12     4118773  The Beatles 1962 – 1966 (2023 Edition)            The Beatles
13      150707                           Songs of Love        Plácido Domingo
14     2568493                          Gušti su gušti         Alen Vitasović
15      376867                              Abbasalute            Abbacadabra
16     4353675       Orbital: The Green Album Expanded                Orbital
17      510942            20,000 Leagues Under the Sea            Jules Verne
18      701834                       CD Duplo (2 de 2)          Beth Carvalho
19     1632829                        Alveg eins og þú          Land og synir

                    artist_credit_full  total_tracks        barcode  mb_year  \
0                       Víctor Heredia          14.0           None     2023
1                          Mary Bergin          14.0   016351790620     2016
2                       Billie Holiday          12.0  8711799930028     2017
3                                 SCAR           4.0   666017287560     2021
4                       Nellie Lutcher         105.0           None     2013
5                          Lada Kerndl          14.0           None     2012
6                        George Benson          15.0           None     2019
7                   Samla Mammas Manna          12.0  7391946054862     2012
8                      Louis Armstrong          26.0   074646511923     2018
9                          Bill Bryson         112.0  9780553502596     2022
10  Rolf Just Nilsen med Barn i studio          29.0  7023063049017     2018

In [78]:
import os

os.makedirs("../data_processed/exports", exist_ok=True)

out_path = "../data_processed/exports/cds_to_mb_review_candidates_v6_round2_enriched.csv"

con.execute(f"""
    COPY cds_to_mb_review_candidates_v6_round2_enriched
    TO '{out_path}'
    WITH (HEADER, DELIMITER ',')
""")

print(f"✅ Exported: {out_path}")

✅ Exported: ../data_processed/exports/cds_to_mb_review_candidates_v6_round2_enriched.csv

In [79]:
import duckdb
import pandas as pd

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Build one combined MB enrichment table:
# automatic matches + review matches
# ------------------------------------------------------------
# Comments:
# - We use the schema of the automatic enriched table as the reference schema.
# - Then we map review-candidate columns into that schema.
# - Any missing columns on the review side are filled with typed NULLs.
# - We also prevent duplicate cds_id rows:
#   if a CDS row is already present in the automatic table,
#   we do not add it again from the review table.
print("Reading schema of cds_to_mb_final_mapping_v9_enriched_cleantrack_v1...")

auto_schema = con.execute(
    "PRAGMA table_info('cds_to_mb_final_mapping_v9_enriched_cleantrack_v1')"
).fetchdf()

auto_cols = auto_schema["name"].tolist()
auto_types = dict(zip(auto_schema["name"], auto_schema["type"]))

# ------------------------------------------------------------
# Map review columns into the automatic schema
# ------------------------------------------------------------
review_mapping = {
    "cds_id": "r.cds_id",
    "cds_artist": "r.cds_artist",
    "cds_title": "r.cds_title",
    "cds_year": "r.cds_year",
    "category": "r.category",
    "genre": "r.genre",
    "cds_tracklist": "r.cds_tracklist",
    "release_id": "r.release_id",
    "release_title": "r.release_title",
    "main_artist_name": "r.main_artist_name",
    "artist_credit_full": "r.artist_credit_full",
    "total_tracks": "r.total_tracks",
    "barcode": "r.barcode",
    "mb_year": "r.mb_year",
    "match_type": "'matched_review_candidate'",
    "score": "r.best_score",
}

review_select_parts = []
for col in auto_cols:
    if col in review_mapping:
        review_select_parts.append(f"{review_mapping[col]} AS {col}")
    else:
        review_select_parts.append(f"NULL::{auto_types[col]} AS {col}")

review_select_sql = ",\n        ".join(review_select_parts)

print("Creating cds_mb_enrichment_combined_v1...")

con.execute(f"""
    CREATE OR REPLACE TABLE cds_mb_enrichment_combined_v1 AS

    -- --------------------------------------------------------
    -- A. Automatic enriched rows
    -- --------------------------------------------------------
    SELECT
        {", ".join(auto_cols)}
    FROM cds_to_mb_final_mapping_v9_enriched_cleantrack_v1

    UNION ALL

    -- --------------------------------------------------------
    -- B. Review enriched rows not already present automatically
    -- --------------------------------------------------------
    SELECT
        {review_select_sql}
    FROM cds_to_mb_review_candidates_v6_round2_enriched r
    WHERE NOT EXISTS (
        SELECT 1
        FROM cds_to_mb_final_mapping_v9_enriched_cleantrack_v1 a
        WHERE a.cds_id = r.cds_id
    )
""")

print("✅ Table created: cds_mb_enrichment_combined_v1")

print("\n--- Row count ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM cds_mb_enrichment_combined_v1
""").fetchdf())

print("\n--- Match type breakdown ---")
print(con.execute("""
    SELECT match_type, COUNT(*) AS n
    FROM cds_mb_enrichment_combined_v1
    GROUP BY match_type
    ORDER BY n DESC
""").fetchdf())

print("\n--- Uniqueness check by cds_id ---")
print(con.execute("""
    SELECT
        COUNT(*) AS total_rows,
        COUNT(DISTINCT cds_id) AS distinct_cds_id,
        COUNT(*) - COUNT(DISTINCT cds_id) AS duplicate_cds_id_rows
    FROM cds_mb_enrichment_combined_v1
""").fetchdf())

print("\n--- Preview ---")
print(con.execute("""
    SELECT *
    FROM cds_mb_enrichment_combined_v1
    LIMIT 20
""").fetchdf())

Connected ✅
Reading schema of cds_to_mb_final_mapping_v9_enriched_cleantrack_v1...
Creating cds_mb_enrichment_combined_v1...
✅ Table created: cds_mb_enrichment_combined_v1

--- Row count ---
      n
0  4257

--- Match type breakdown ---
                 match_type     n
0                     exact  3482
1         fuzzy_second_pass   543
2        various_title_only   183
3  matched_review_candidate    43
4     alias_enrichment_safe     3
5    enrichment_round2_auto     3

--- Uniqueness check by cds_id ---
   total_rows  distinct_cds_id  duplicate_cds_id_rows
0        4257             4257                      0

--- Preview ---
    cds_id            cds_artist                      cds_title  cds_year  \
0    10000       backstreet boys                     millennium      <NA>
1   100001               various    frankfurt trance vol 04 cd1      <NA>
2   100002             no return                self mutilation      <NA>
3   100006      luv lite massive                       one love      <NA>
4   100008                  dmbq                           dmbq      2002
5   100010               various    frankfurt trance vol 05 cd1      <NA>
6   100012    rumania montevideo               mo better tracks      <NA>
7   100015                 keedy               chase the clouds      <NA>
8   100019            bill evans                          alone      1968
9   100020      nature destroyed                         shades      <NA>
10  100021             pearl jam                          yield      1998
11  100022     dingdong avanzado  the best of dingdong avanzado      <NA>
12  100024                  175r                          songs      2003
13  100026    day after tomorrow                       elements      2003
14  100031               spartak                          golem      1990
15  100035                gazebo             the best of gazebo      <NA>
16  100037  sportfreunde stiller                 die gute seite      <NA>
17  100039               various          salsaenlacalleocho 96      <NA>
18  100040     barbara streisand               a love like ours      1999
19  100058             green day                         dookie      <NA>

        category           genre  release_id                  release_title  \
0          blues             pop        8069                     Millennium
1           data            None      190028               Frankfurt Trance
2           data            data       12737                Self Mutilation
3           data      electronic     1032522                       One Love
4           data            rock     1383710                           DMBQ
5           data            None      190028               Frankfurt Trance
6           data             pop      510936              MO' BETTER TRACKS
7           data            data       85239               Chase the Clouds
8           data            None      100846                          Alone
9           data            None      210151                         Shades
10          data       hard rock        5053                          Yield
11          data            None     5132677  The Best Of Dingdong Avanzado
12          data            jpop      435351                          Songs
13          data             pop       33014                       elements
14          data      electronic      362682                          Golem
15          data            None     1883940             The Best of Gazebo
16          data            data       37684                 Die gute Seite
17  sonytsid7008            data     2389539     Salsa en la calle Ocho '96
18          data  easy listening      667030               A Love Like Ours
19          data            None        2576                         Dookie

        main_artist_name    artist_credit_full  total_tracks        barcode  \
0        Backstreet Boys       Backstreet Boys          12.0   012414167224
1        Various Artists       Various Artists          22.0  4017866122667
2              No Return             No Return          11.0  3760053840271
3       Luv Lite Massive      Luv Lite Massive          11.0           None
4                   DMBQ                  DMBQ          12.0  4988064171996
5        Various Artists       Various Artists          22.0  4017866122667
6     rumania montevideo    rumania montevideo          12.0  4523949014809
7                  Keedy                 Keedy          10.0   078221864121
8             Bill Evans            Bill Evans          12.0   731458931928
9       Nature Destroyed      Nature Destroyed          10.0   718756222125
10             Pearl Jam             Pearl Jam          13.0   074646816424
11     Dingdong Avanzado     Dingdong Avanzado          12.0  4800626000462
12                  175R                  175R          11.0           None
13    day after tomorrow    day after tomorrow          24.0  4988064172252
14               Spartak               Spartak          11.0  4015698133523
15                Gazebo                Gazebo          16.0  4988017610893
16  Sportfreunde Stiller  Sportfreunde Stiller          13.0   731458965022
17       Various Artists       Various Artists          12.0           None
18      Barbra Streisand      Barbra Streisand          12.0   074646960127
19             Green Day             Green Day          14.0   093624552925

    mb_year          match_type       score  \
0      2016               exact   82.000000
1      2019  various_title_only  100.000000
2      2020               exact   82.000000
3      2016               exact   56.000000
4      2015               exact   82.000000
5      2019  various_title_only  100.000000
6      2009               exact   50.000000
7      2017               exact   82.000000
8      2010               exact   82.000000
9      2017               exact   82.000000
10     2017               exact   82.000000
11     2025               exact   82.000000
12     2019               exact   56.000000
13     2021               exact   82.000000
14     2020               exact   82.000000
15     2024               exact   82.000000
16     2014               exact   82.000000
17     2020  various_title_only   68.723404
18     2023   fuzzy_second_pass   98.756598
19     2023               exact   82.000000

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   cds_tracklist
0                                                                                                                                                                                                                                                                               larger than life i want it that way show me the meaning of being lonely it s gotta be you i need you tonight don t want you back don t wanna lose you now the one back to your heart spanish eyes no one else comes close the perfect fan i ll be there for you
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           None
2                                                                                                                                                                                                                                                                                                                                                                                                  do or die truth and reality lost soul extractor sadistic desire the true way fanatic mind individualistic ideal one life trail of blood sect
3                                                                                                                                                                                                                                                                                                                                                                                                                              temple of dehli from naw till a mornin shock afghani lick you bad freestyle fiki fuko i m here yeah ww5 one love
4                                                                                                                                                                                                                                                                                                                                     small hours rock a cola ohh baby teenage limbo little leaf i movement little leaf ii swell little leaf iii etude sayonara no season altered rock can peace migrate to midnight e means eternal data track
5                                                                 dj tom stevens violet steam single cut liquid child diving faces original mix vimana we came edit lac terra after dark fridge vs vectrex remix steve baltes thoughts original mix star party i m in love ferry corsten robert smit rmx gate iv give all you got radio edit dj stigma baby sunshine stig s original club mix synchronic minds all i need club mix astral inc remember green court edit x trance friends 2000 tom stevens rmx ravelab send me an angel club mix
6                                                                                                                                                                                                                                                                                                                                                                             i ll be with you hard rain free tender rain rain sleeper life style taxi take my pain away my life album version all by myself start all over again album version
7                                                                                                                                                                                                                                                                                                                                                                                 save some love wishing on the same star never neverland sorry only your heart gettin around don t turn away pretty boy mama lazy day save some love hot remix
8                                                                                                                                                here s that rainy day a time for love midnight mood on a clear day you can see forever never let me go the two lonely people aka the man and the woman here s that rainy day alternative take a time for love alternative take midnight mood alternative take on a clear day you can see forever alternative take never let me go alternative take medley all the things you are midnight mood
9                                                                                                                                                                                                                                                                                                                                                                                                               enter the realm dream of fear word of trust unforeseen desire shades bound imprisoned cold vengeance disease leaving the shadow
10                                                                                                                                                                                                                                                                                                                                                                                              brain of j faithfull no way given to fly wishlist pilate do the evolution untitled mfc low light in hiding push me pull me all those yesterdays
11                                                                                                                                                                                                                                                                                                                                   ikaw lamang tatlong beinte singko maghihintay sa yo makapiling ka sana break kung break love at first sight basta t kasama kita paano sasabihin here i am i think i love you bakit hangang ngayon say amen
12                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          None
13                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          None
14                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          None
15                                                                                                                                                                                                                                                                                                i like chopin lunatic masterpiece dolce vita telephone mama sun goes down on milky way women come women go victims in paradise god bless the moonshade the fourteenth of july dancing with the moonlit knight trotsky burger waterland tycoon
16                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          None
17  1996 estamossolos jorgeluispiloto 1996 reyruiz hastaqueteconoci juangabriel 1996 marcanthony situsupieras omaralfanno 1996 giro laguagua candidofabre 1996 celiacruz hechocadoconlavida ivetteayala 1996 titorojas apiadatedemi omaralfanno 1996 victormanuelle quemaneradequererte emiliorios 1996 gilbertosantarosa quienerestu luisenriquemejia 1996 luisenrique nuncavoyaolvidarte robertobelester 1996 india gotasdelluvia jairovalera 1996 gruponiche otropoco mariofiaz 1996 puertoricanpower rumbera donatopoveda 1996 willychirino
18                                                                                                                                                                                                                                                                                                                  i ve dreamed of you isn t it a pity the island love like ours if you ever leave me we must be loving right if i never met you it must be you just one lifetime if i didn t love you wait the music that makes me dance data
19                                                                                                                                                                                                                                                                                                                                                                  burn out having a blast chump long view welcome to paradise pulling teeth basket case she sassafras roots when i come arround coming clean emenius sleepus in the end f o d

In [80]:
import os

os.makedirs("../data_processed/exports", exist_ok=True)

out_path = "../data_processed/exports/cds_mb_enrichment_combined_v1.csv"

con.execute(f"""
    COPY cds_mb_enrichment_combined_v1
    TO '{out_path}'
    WITH (HEADER, DELIMITER ',')
""")

print(f"✅ Exported: {out_path}")

✅ Exported: ../data_processed/exports/cds_mb_enrichment_combined_v1.csv

In [82]:
import duckdb
import pandas as pd

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Post-hoc recovery:
# promote CDS-only safe rows that actually exist in MusicBrainz
# ------------------------------------------------------------
# Comments:
# - This checks whether rows in cds_only_enrichment_safe_v1 are actually
#   exact normalized artist/title matches to MB release data.
# - If yes, they should be moved from CDS-only enrichment to
#   automatic MB-linked enrichment.
print("Creating cds_only_safe_recovered_auto_v1...")

con.execute("""
    CREATE OR REPLACE TABLE cds_only_safe_recovered_auto_v1 AS
    WITH cds_safe AS (
        SELECT
            s.cds_id,
            s.artist,
            s.title,
            s.cds_year,
            s.tracks,
            s.artist_key_clean,
            s.title_key_clean
        FROM cds_only_enrichment_safe_v1 s
    ),
    mb_norm AS (
        SELECT
            r.release_id,
            r.release_title,
            r.main_artist_name,
            r.artist_credit_full,
            r.total_tracks,
            r.barcode,
            r.mb_year,
            lower(regexp_replace(coalesce(r.release_title, ''), '[^a-zA-Z0-9]+', '', 'g')) AS mb_title_key,
            lower(regexp_replace(coalesce(r.main_artist_name, ''), '[^a-zA-Z0-9]+', '', 'g')) AS mb_artist_key
        FROM mb_release_features r
    )
    SELECT
        c.cds_id,
        c.artist,
        c.title,
        c.cds_year,
        c.tracks,
        m.release_id,
        m.release_title,
        m.main_artist_name,
        m.artist_credit_full,
        m.total_tracks,
        m.barcode,
        m.mb_year,
        'recovered_exact_safe' AS match_type,
        100.0 AS score
    FROM cds_safe c
    JOIN mb_norm m
      ON c.title_key_clean = m.mb_title_key
     AND c.artist_key_clean = m.mb_artist_key
""")

print("✅ Table created: cds_only_safe_recovered_auto_v1")

print("\n--- Recovered rows count ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM cds_only_safe_recovered_auto_v1
""").fetchdf())

print("\n--- Distinct CDS rows recovered ---")
print(con.execute("""
    SELECT COUNT(DISTINCT cds_id) AS n
    FROM cds_only_safe_recovered_auto_v1
""").fetchdf())

print("\n--- Preview ---")
print(con.execute("""
    SELECT *
    FROM cds_only_safe_recovered_auto_v1
    LIMIT 30
""").fetchdf())

Connected ✅
Creating cds_only_safe_recovered_auto_v1...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

✅ Table created: cds_only_safe_recovered_auto_v1

--- Recovered rows count ---
    n
0  46

--- Distinct CDS rows recovered ---
   n
0  6

--- Preview ---
    cds_id  artist                         title  cds_year  \
0    10119  r e m   fables of the reconstruction      1986
1    10119  r e m   fables of the reconstruction      1986
2    10119  r e m   fables of the reconstruction      1986
3    10119  r e m   fables of the reconstruction      1986
4    10119  r e m   fables of the reconstruction      1986
5   101964    a ha         minor earth major sky      2000
6    10119  r e m   fables of the reconstruction      1986
7    10119  r e m   fables of the reconstruction      1986
8    10119  r e m   fables of the reconstruction      1986
9    10119  r e m   fables of the reconstruction      1986
10   10119  r e m   fables of the reconstruction      1986
11   10119  r e m   fables of the reconstruction      1986
12   10119  r e m   fables of the reconstruction      1986
13   10119  r e m   fables of the reconstruction      1986
14  100009  4 p m                     sweet soul      2001
15   10119  r e m   fables of the reconstruction      1986
16   10119  r e m   fables of the reconstruction      1986
17   10119  r e m   fables of the reconstruction      1986
18   10119  r e m   fables of the reconstruction      1986
19   10119  r e m   fables of the reconstruction      1986
20  101964    a ha         minor earth major sky      2000
21  101964    a ha         minor earth major sky      2000
22  107832   manã                 esenciales sol      2003
23  101964    a ha         minor earth major sky      2000
24   10119  r e m   fables of the reconstruction      1986
25   10119  r e m   fables of the reconstruction      1986
26   10119  r e m   fables of the reconstruction      1986
27  107832   manã                 esenciales sol      2003
28  101964    a ha         minor earth major sky      2000
29  101964    a ha         minor earth major sky      2000

                                                                                                                                                                                                                                                                 tracks  \
0                                                       feeling gravitys pull maps and legends driver 8 life and how to live it old man kensey cant get there from here green grow the rushes kohoutek auctioneer good advice wendell gee crazy burning hell bandwagon
1                                                       feeling gravitys pull maps and legends driver 8 life and how to live it old man kensey cant get there from here green grow the rushes kohoutek auctioneer good advice wendell gee crazy burning hell bandwagon
2                                                       feeling gravitys pull maps and legends driver 8 life and how to live it old man kensey cant get there from here green grow the rushes kohoutek auctioneer good advice wendell gee crazy burning hell bandwagon
3                                                       feeling gravitys pull maps and legends driver 8 life and how to live it old man kensey cant get there from here green grow the rushes kohoutek auctioneer good advice wendell gee crazy burning hell bandwagon
4                                                       feeling gravitys pull maps and legends driver 8 life and how to live it old man kensey cant get there from here green grow the rushes kohoutek auctioneer good advice wendell gee crazy burning hell bandwagon
5   minor earth major sky little black heart velvet summer moved on the sun never shone that day to let you win the company man thought that it was you i wish i cared barely hanging on you ll never get over me i won t forget her mary ellen makes the moment count
6                                                       feeling gravitys pull maps and legends driver 8 life and how to live it old man kensey cant get there from here green grow the rushes kohoutek auctioneer good advice wendell gee crazy burning hell bandwagon
7                                                       feeling gravitys pull maps and legends driver 8 life and how to live it old man kensey cant get there from here green grow the rushes kohoutek auctioneer good advice wendell gee crazy burning hell bandwagon
8                                                       feeling gravitys pull maps and legends driver 8 life and how to live it old man kensey cant get there from here green grow the rushes kohoutek auctioneer good advice wendell gee crazy burning hell bandwagon
9                                                       feeling gravitys pull maps and legends driver 8 life and how to live it old man kensey cant get there from here green grow the rushes kohoutek auctioneer good advice wendell gee crazy burning hell bandwagon
10                                                      feeling gravitys pull maps and legends driver 8 life and how to live it old man kensey cant get there from here green grow the rushes kohoutek auctioneer good advice wendell gee crazy burning hell bandwagon
11                                                      feeling gravitys pull maps and legends driver 8 life and how to live it old man kensey cant get there from here green grow the rushes kohoutek auctioneer good advice wendell gee crazy burning hell bandwagon
12                                                      feeling gravitys pull maps and legends driver 8 life and how to live it old man kensey cant get there from here green grow the rushes kohoutek auctioneer good advice wendell gee crazy burning hell bandwagon
13                                                      feeling gravitys pull maps and legends driver 8 life and how to live it old man kensey cant get there from here green grow the rushes kohoutek auctioneer good advice wendell gee crazy burning hell bandwagon
14                                                               miagetegoran yoruno hoshio woman cherish tears in heaven so much in love christmas eve too much heaven i left my heart in san francisco the lady in my life christmas medley the star spangled banner
15                                                      feeling gravitys pull maps and legends driver 8 life and how to live it old man kensey cant get there from here green grow the rushes kohoutek auctioneer good advice wendell gee crazy burning hell bandwagon
16                                                      feeling gravitys pull maps and legends driver 8 life and how to live it old man kensey cant get there from here green grow the rushes kohoutek auctioneer good advice wendell gee crazy burning hell bandwagon
17                                                      feeling gravitys pull maps and legends driver 8 life and how to live it old man kensey cant get there from here green grow the rushes kohoutek auctioneer good advice wendell gee crazy burning hell bandwagon
18                                                      feeling gravitys pull maps and legends driver 8 life and how to live it old man kensey cant get there from here green grow the rushes kohoutek auctioneer good advice wendell gee crazy burning hell bandwagon
19                                                      feeling gravitys pull maps and legends driver 8 life and how to live it old man kensey cant get there from here green grow the rushes kohoutek auctioneer good advice wendell gee crazy burning hell bandwagon
20  minor earth major sky little black heart velvet summer moved on the sun never shone that day to let you win the company man thought that it was you i wish i cared barely hanging on you ll never get over me i won t forget her mary ellen makes the moment count
21  minor earth major sky little black heart velvet summer moved on the sun never shone that day to let you win the company man thought that it was you i wish i cared barely hanging on you ll never get over me i won t forget her mary ellen makes the moment count
22                                                                  te llevarã al cielo estoy agotado buscã ndola perdido en un barco de pies a cabeza oye mi amor sã banas frias cã³mo te deseo me vale dã jame entrar tonto en la lluvia clavado en un bar hechizera
23  minor earth major sky little black heart velvet summer moved on the sun never shone that day to let you win the company man thought that it was you i wish i cared barely hanging on you ll never get over me i won t forget her mary ellen makes the moment count
24                                                      feeling gravitys pull maps and legends driver 8 life and how to live it old man kensey cant get there from here green grow the rushes kohoutek auctioneer good advice wendell gee crazy burning hell bandwagon
25                                                      feeling gravitys pull maps and legends driver 8 life and how to live it old man kensey cant get there from here green grow the rushes kohoutek auctioneer good advice wendell gee crazy burning hell bandwagon
26                                                      feeling gravitys pull maps and legends driver 8 life and how to live it old man kensey cant get there from here green grow the rushes kohoutek auctioneer good advice wendell gee crazy burning hell bandwagon
27                                                                  te llevarã al cielo estoy agotado buscã ndola perdido en un barco de pies a cabeza oye mi amor sã banas frias cã³mo te deseo me vale dã jame entrar tonto en la lluvia clavado en un bar hechizera
28  minor earth major sky little black heart velvet summer moved on the sun never shone that day to let you win the company man thought that it was you i wish i cared barely hanging on you ll never get over me i won t forget her mary ellen makes the moment count
29  minor earth major sky little black heart velvet summer moved on the sun never shone that day to let you win the company man thought that it was you i wish i cared barely hanging on you ll never get over me i won t forget her mary ellen makes the moment count

    release_id                 release_title main_artist_name  \
0      1098052  Fables of the Reconstruction           R.E.M.
1      3618327  Fables of the Reconstruction           R.E.M.
2      3573529  Fables of the Reconstruction           R.E.M.
3       713154  Fables of the Reconstruction           R.E.M.
4      4077662  Fables of the Reconstruction           R.E.M.
5      1884917       minor earth | major sky             a‐ha
6      4433995  Fables of the Reconstruction           R.E.M.
7      4433999  Fables of the Reconstruction           R.E.M.
8      4434010  Fables of the Reconstruction           R.E.M.
9      1594777  Fables of the Reconstruction           R.E.M.
10     4434016  Fables of the Reconstruction           R.E.M.
11     1779474  Fables of the Reconstruction           R.E.M.
12     1822437  Fables of the Reconstruction           R.E.M.
13      429952  Fables of the Reconstruction           R.E.M.
14     5331401                    Sweet Soul           4 P.M.
15       27409  Fables of the Reconstruction           R.E.M.
16     1698817  Fables of the Reconstruction           R.E.M.
17     4434021  Fables of the Reconstruction           R.E.M.
18     4434027  Fables of the Reconstruction           R.E.M.
19     4434030  Fables of the Reconstruction           R.E.M.
20     3023001       minor earth | major sky             a‐ha
21     4051478       minor earth | major sky             a‐ha
22     5119170               Esenciales: Sol             Maná
23     2405130       Minor Earth | Major Sky             a‐ha
24        4555  Fables of the Reconstruction           R.E.M.
25      756088  Fables of the Reconstruction           R.E.M.
26      636070  Fables of the Reconstruction           R.E.M.
27      417934               Esenciales: Sol             Maná
28       50310       Minor Earth | Major Sky             a‐ha
29      461885       minor earth | major sky             a‐ha

   artist_credit_full  total_tracks         barcode  mb_year  \
0              R.E.M.          11.0    008811901622     2012
1              R.E.M.          16.0    077771316029     2022
2              R.E.M.          11.0                     2022
3              R.E.M.          25.0   5099964607122     2014
4              R.E.M.          11.0    076732559222     2023
5                a‐ha          17.0   4943674024186     2024
6              R.E.M.          11.0  00724349347953     2024
7              R.E.M.          11.0  00602537796618     2024
8              R.E.M.          25.0  05099964607153     2024
9              R.E.M.          11.0  00602537796632     2024
10             R.E.M.          11.0  00602537796649     2024
11             R.E.M.          11.0    076732559222     2016
12             R.E.M.          11.0                     2021
13             R.E.M.          16.0    077771316029     2020
14             4 P.M.           9.0   4988013277809     2025
15             R.E.M.          11.0   5013747100310     2013
16             R.E.M.          11.0                     2015
17             R.E.M.          11.0    602465172270     2024
18             R.E.M.          11.0    602465172270     2024
19             R.E.M.          11.0    602465172331     2024
20               a‐ha          13.0    190295384388     2021
21               a‐ha          13.0    685738218325     2023
22               Maná          14.0    825646104420     2025
23               a‐ha           7.0    685738412426     2019
24             R.E.M.          11.0    076732559215     2019
25             R.E.M.          11.0    724349347922     2018
26             R.E.M.          11.0    724349347922     2017
27               Maná          14.0            None     2020
28               a‐ha           7.0            None     2016
29               a‐ha          14.0            None     2019

              match_type  score
0   recovered_exact_safe  100.0
1   recovered_exact_safe  100.0
2   recovered_exact_safe  100.0
3   recovered_exact_safe  100.0
4   recovered_exact_safe  100.0
5   recovered_exact_safe  100.0
6   recovered_exact_safe  100.0
7   recovered_exact_safe  100.0
8   recovered_exact_safe  100.0
9   recovered_exact_safe  100.0
10  recovered_exact_safe  100.0
11  recovered_exact_safe  100.0
12  recovered_exact_safe  100.0
13  recovered_exact_safe  100.0
14  recovered_exact_safe  100.0
15  recovered_exact_safe  100.0
16  recovered_exact_safe  100.0
17  recovered_exact_safe  100.0
18  recovered_exact_safe  100.0
19  recovered_exact_safe  100.0
20  recovered_exact_safe  100.0
21  recovered_exact_safe  100.0
22  recovered_exact_safe  100.0
23  recovered_exact_safe  100.0
24  recovered_exact_safe  100.0
25  recovered_exact_safe  100.0
26  recovered_exact_safe  100.0
27  recovered_exact_safe  100.0
28  recovered_exact_safe  100.0
29  recovered_exact_safe  100.0

In [83]:
import duckdb
import pandas as pd

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

print("Reclassifying recovered rows with stricter auto rules...")

con.execute("""
    CREATE OR REPLACE TABLE cds_only_safe_recovered_auto_unique_v1 AS
    SELECT *
    FROM cds_only_safe_recovered_ranked_v1
    WHERE rn = 1
      AND (
            (
                candidate_count = 1
                AND year_gap IS NOT NULL
                AND year_gap <= 5
            )
            OR (
                recovery_rank_score >= 90
                AND recovery_score_gap >= 10
                AND (year_gap IS NULL OR year_gap <= 5)
            )
          )
""")

con.execute("""
    CREATE OR REPLACE TABLE cds_only_safe_recovered_review_v1 AS
    SELECT *
    FROM cds_only_safe_recovered_ranked_v1
    WHERE rn = 1
      AND cds_id NOT IN (
          SELECT cds_id
          FROM cds_only_safe_recovered_auto_unique_v1
      )
""")

print("✅ Tables created:")
print("   - cds_only_safe_recovered_auto_unique_v1")
print("   - cds_only_safe_recovered_review_v1")

print("\n--- Recovery split summary (strict version) ---")
print(con.execute("""
    SELECT 'auto_unique' AS bucket, COUNT(*) AS n
    FROM cds_only_safe_recovered_auto_unique_v1
    UNION ALL
    SELECT 'review' AS bucket, COUNT(*) AS n
    FROM cds_only_safe_recovered_review_v1
""").fetchdf())

print("\n--- Preview: strict auto rows ---")
print(con.execute("""
    SELECT
        cds_id,
        artist,
        title,
        release_id,
        release_title,
        main_artist_name,
        cds_year,
        mb_year,
        year_gap,
        candidate_count
    FROM cds_only_safe_recovered_auto_unique_v1
""").fetchdf())

Connected ✅
Reclassifying recovered rows with stricter auto rules...
✅ Tables created:
   - cds_only_safe_recovered_auto_unique_v1
   - cds_only_safe_recovered_review_v1

--- Recovery split summary (strict version) ---
        bucket  n
0  auto_unique  0
1       review  6

--- Preview: strict auto rows ---
Empty DataFrame
Columns: [cds_id, artist, title, release_id, release_title, main_artist_name, cds_year, mb_year, year_gap, candidate_count]
Index: []

In [84]:
import duckdb
import pandas as pd

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Step 1: keep only the truly CDS-only safe rows
# ------------------------------------------------------------
# Comments:
# - cds_only_enrichment_safe_v1 currently contains some rows that were
#   later recovered as already present in MusicBrainz.
# - Those recovered rows should no longer remain in the "true CDS-only"
#   safe enrichment bucket.
print("Creating cds_only_enrichment_safe_true_unmatched_v1...")

con.execute("""
    CREATE OR REPLACE TABLE cds_only_enrichment_safe_true_unmatched_v1 AS
    SELECT *
    FROM cds_only_enrichment_safe_v1 s
    WHERE s.cds_id NOT IN (
        SELECT DISTINCT cds_id
        FROM cds_only_safe_recovered_review_v1
    )
""")

print("✅ Table created: cds_only_enrichment_safe_true_unmatched_v1")

print("\n--- Count of true CDS-only safe rows ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM cds_only_enrichment_safe_true_unmatched_v1
""").fetchdf())

# ------------------------------------------------------------
# Step 2: build master thesis enrichment table
# ------------------------------------------------------------
# Comments:
# - This is not only a mapping table.
# - It is a thesis-facing enrichment table with three outcomes:
#     1) confirmed_mb_enrichment
#     2) review_mb_enrichment
#     3) new_cds_enrichment
# - We standardize the schema so all rows can be stacked with UNION ALL.
print("\nCreating thesis_musicbrainz_enrichment_master_v1...")

con.execute("""
    CREATE OR REPLACE TABLE thesis_musicbrainz_enrichment_master_v1 AS

    -- --------------------------------------------------------
    -- A. Confirmed or review-linked MB enrichment already in
    --    cds_mb_enrichment_combined_v1
    -- --------------------------------------------------------
    SELECT
        cds_id,
        cds_artist AS artist,
        cds_title AS title,
        cds_year,
        category,
        genre,
        cds_tracklist AS tracks,

        release_id,
        release_title,
        main_artist_name,
        artist_credit_full,
        total_tracks,
        barcode,
        mb_year,

        match_type AS enrichment_route,

        CASE
            WHEN match_type = 'matched_review_candidate' THEN 'review_mb_enrichment'
            ELSE 'confirmed_mb_enrichment'
        END AS enrichment_status

    FROM cds_mb_enrichment_combined_v1

    UNION ALL

    -- --------------------------------------------------------
    -- B. Recovered MB-present rows that remain review-only
    -- --------------------------------------------------------
    SELECT
        r.cds_id,
        c.artist AS artist,
        c.title AS title,
        c.cds_year,
        c.category,
        c.genre,
        c.tracks AS tracks,

        r.release_id,
        r.release_title,
        r.main_artist_name,
        r.artist_credit_full,
        r.total_tracks,
        r.barcode,
        r.mb_year,

        'recovered_mb_presence_review' AS enrichment_route,
        'review_mb_enrichment' AS enrichment_status

    FROM cds_only_safe_recovered_review_v1 r
    LEFT JOIN cds c
      ON r.cds_id = c.cds_id

    UNION ALL

    -- --------------------------------------------------------
    -- C. True CDS-only enrichment rows not found in MB
    -- --------------------------------------------------------
    SELECT
        s.cds_id,
        s.artist,
        s.title,
        s.cds_year,
        c.category,
        c.genre,
        c.tracks,

        NULL AS release_id,
        NULL AS release_title,
        NULL AS main_artist_name,
        NULL AS artist_credit_full,
        NULL AS total_tracks,
        NULL AS barcode,
        NULL AS mb_year,

        'cds_only_safe' AS enrichment_route,
        'new_cds_enrichment' AS enrichment_status

    FROM cds_only_enrichment_safe_true_unmatched_v1 s
    LEFT JOIN cds c
      ON s.cds_id = c.cds_id
""")

print("✅ Table created: thesis_musicbrainz_enrichment_master_v1")

print("\n--- Master enrichment summary ---")
print(con.execute("""
    SELECT
        enrichment_status,
        COUNT(*) AS n,
        ROUND(100.0 * COUNT(*) / (SELECT COUNT(*) FROM thesis_musicbrainz_enrichment_master_v1), 2) AS pct
    FROM thesis_musicbrainz_enrichment_master_v1
    GROUP BY enrichment_status
    ORDER BY n DESC
""").fetchdf())

print("\n--- Breakdown by route ---")
print(con.execute("""
    SELECT
        enrichment_route,
        COUNT(*) AS n
    FROM thesis_musicbrainz_enrichment_master_v1
    GROUP BY enrichment_route
    ORDER BY n DESC
""").fetchdf())

print("\n--- Preview ---")
print(con.execute("""
    SELECT *
    FROM thesis_musicbrainz_enrichment_master_v1
    LIMIT 30
""").fetchdf())

Connected ✅
Creating cds_only_enrichment_safe_true_unmatched_v1...
✅ Table created: cds_only_enrichment_safe_true_unmatched_v1

--- Count of true CDS-only safe rows ---
      n
0  1646

Creating thesis_musicbrainz_enrichment_master_v1...
✅ Table created: thesis_musicbrainz_enrichment_master_v1

--- Master enrichment summary ---
         enrichment_status     n    pct
0  confirmed_mb_enrichment  4214  71.31
1       new_cds_enrichment  1646  27.86
2     review_mb_enrichment    49   0.83

--- Breakdown by route ---
               enrichment_route     n
0                         exact  3482
1                 cds_only_safe  1646
2             fuzzy_second_pass   543
3            various_title_only   183
4      matched_review_candidate    43
5  recovered_mb_presence_review     6
6         alias_enrichment_safe     3
7        enrichment_round2_auto     3

--- Preview ---
    cds_id                artist                            title  cds_year  \
0    10000       backstreet boys                       millennium      <NA>
1   100001               various      frankfurt trance vol 04 cd1      <NA>
2   100002             no return                  self mutilation      <NA>
3   100006      luv lite massive                         one love      <NA>
4   100008                  dmbq                             dmbq      2002
5   100010               various      frankfurt trance vol 05 cd1      <NA>
6   100012    rumania montevideo                 mo better tracks      <NA>
7   100015                 keedy                 chase the clouds      <NA>
8   100019            bill evans                            alone      1968
9   100020      nature destroyed                           shades      <NA>
10  100021             pearl jam                            yield      1998
11  100022     dingdong avanzado    the best of dingdong avanzado      <NA>
12  100024                  175r                            songs      2003
13  100026    day after tomorrow                         elements      2003
14  100031               spartak                            golem      1990
15  100035                gazebo               the best of gazebo      <NA>
16  100037  sportfreunde stiller                   die gute seite      <NA>
17  100039               various            salsaenlacalleocho 96      <NA>
18  100040     barbara streisand                 a love like ours      1999
19  100058             green day                           dookie      <NA>
20  100064                savage                          tonight      <NA>
21  100065      atmo brtschitsch                 change your life      <NA>
22  100066            del amitri                          twisted      1995
23  100082         barry mcguire               eve of destruction      1985
24  100087         tschou zã me                         wã ge dir      <NA>
25  100088         clive gregson                  comfort and joy      <NA>
26  100089       various artists                   dorival caymmi      <NA>
27  100094            keri noble                         fearless      2004
28  100097           north cregg                summer at my feet      2003
29  100099    fabienne thibeault  les plus belles chansons cd 2 2      <NA>

        category           genre  \
0          blues             pop
1           data            None
2           data            data
3           data      electronic
4           data            rock
5           data            None
6           data             pop
7           data            data
8           data            None
9           data            None
10          data       hard rock
11          data            None
12          data            jpop
13          data             pop
14          data      electronic
15          data            None
16          data            data
17  sonytsid7008            data
18          data  easy listening
19          data            None
20          data            None
21          data            None
22          data            rock
23          folk          oldies
24          folk            None
25          folk            None
26          folk            folk
27          folk             pop
28          folk            folk
29          folk            None

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          tracks  \
0                                                                                                                                                                                                                                                                               larger than life i want it that way show me the meaning of being lonely it s gotta be you i need you tonight don t want you back don t wanna lose you now the one back to your heart spanish eyes no one else comes close the perfect fan i ll be there for you
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           None
2                                                                                                                                                                                                                                                                                                                                                                                                  do or die truth and reality lost soul extractor sadistic desire the true way fanatic mind individualistic ideal one life trail of blood sect
3                                                                                                                                                                                                                                                                                                                                                                                                                              temple of dehli from naw till a mornin shock afghani lick you bad freestyle fiki fuko i m here yeah ww5 one love
4                                                                                                                                                                                                                                                                                                                                     small hours rock a cola ohh baby teenage limbo little leaf i movement little leaf ii swell little leaf iii etude sayonara no season altered rock can peace migrate to midnight e means eternal data track
5                                                                 dj tom stevens violet steam single cut liquid child diving faces original mix vimana we came edit lac terra after dark fridge vs vectrex remix steve baltes thoughts original mix star party i m in love ferry corsten robert smit rmx gate iv give all you got radio edit dj stigma baby sunshine stig s original club mix synchronic minds all i need club mix astral inc remember green court edit x trance friends 2000 tom stevens rmx ravelab send me an angel club mix
6                                                                                                                                                                                                                                                                                                                                                                             i ll be with you hard rain free tender rain rain sleeper life style taxi take my pain away my life album version all by myself start all over again album version
7                                                                                                                                                                                                                                                                                                                                                                                 save some love wishing on the same star never neverland sorry only your heart gettin around don t turn away pretty boy mama lazy day save some love hot remix
8                                                                                                                                                here s that rainy day a time for love midnight mood on a clear day you can see forever never let me go the two lonely people aka the man and the woman here s that rainy day alternative take a time for love alternative take midnight mood alternative take on a clear day you can see forever alternative take never let me go alternative take medley all the things you are midnight mood
9                                                                                                                                                                                                                                                                                                                                                                                                               enter the realm dream of fear word of trust unforeseen desire shades bound imprisoned cold vengeance disease leaving the shadow
10                                                                                                                                                                                                                                                                                                                                                                                              brain of j faithfull no way given to fly wishlist pilate do the evolution untitled mfc low light in hiding push me pull me all those yesterdays
11                                                                                                                                                                                                                                                                                                                                   ikaw lamang tatlong beinte singko maghihintay sa yo makapiling ka sana break kung break love at first sight basta t kasama kita paano sasabihin here i am i think i love you bakit hangang ngayon say amen
12                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          None
13                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          None
14                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          None
15                                                                                                                                                                                                                                                                                                i like chopin lunatic masterpiece dolce vita telephone mama sun goes down on milky way women come women go victims in paradise god bless the moonshade the fourteenth of july dancing with the moonlit knight trotsky burger waterland tycoon
16                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          None
17  1996 estamossolos jorgeluispiloto 1996 reyruiz hastaqueteconoci juangabriel 1996 marcanthony situsupieras omaralfanno 1996 giro laguagua candidofabre 1996 celiacruz hechocadoconlavida ivetteayala 1996 titorojas apiadatedemi omaralfanno 1996 victormanuelle quemaneradequererte emiliorios 1996 gilbertosantarosa quienerestu luisenriquemejia 1996 luisenrique nuncavoyaolvidarte robertobelester 1996 india gotasdelluvia jairovalera 1996 gruponiche otropoco mariofiaz 1996 puertoricanpower rumbera donatopoveda 1996 willychirino
18                                                                                                                                                                                                                                                                                                                  i ve dreamed of you isn t it a pity the island love like ours if you ever leave me we must be loving right if i never met you it must be you just one lifetime if i didn t love you wait the music that makes me dance data
19                                                                                                                                                                                                                                                                                                                                                                  burn out having a blast chump long view welcome to paradise pulling teeth basket case she sassafras roots when i come arround coming clean emenius sleepus in the end f o d
20                                                                                                                                                                                                                                                                                                                                   radio a love again fugitive tonight a love again remix don t cry tonight computerized love only you turn around time magic carillon instrumental don t cry tonight extended don t cry tonight instrumental
21                                                                                                                                                                                                                                                                                                                                                                                         everyday morningsun sittin green plane rockstar black sea some girls lucky people image stop taking always smiling coming home around me every night
22                                                                                                                                                                                                                                                                                                                    food for songs start with me here and now one thing left to do tell her this being somebody else roll to me crashing down it might as well be you never enough it s never too late to be alone driving with the brakes on
23                                                                                                                                                                                                                                                         eve of destruction she belongs to me you never had it so good sloop john b baby blue the sins of a family try to remember mr man on the street act one you were on my mind ain t no way i m gonna change my mind what exactly s the matter with me why not stop dig it while you can
24                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          None
25                                                                                                                                                                                                                                                                                                                                  frances o connor antidote fingerless gloves i m there for you it s you i want to hold if i was your lover catholic girl white suit of notes riding on a bus pretty peggy o string of pearls comfort and joy
26                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          None
27                                                                                                                                                                                                                                                                                                                                                                            look at me talk to me piece of my heart a dream about you about me let it rain falling love is all i know answered prayer bartender i won t if no one will listen

In [85]:
import os

os.makedirs("../data_processed/exports/final_thesis_outputs", exist_ok=True)

out_path = "../data_processed/exports/final_thesis_outputs/thesis_musicbrainz_enrichment_master_v1.csv"

con.execute(f"""
    COPY thesis_musicbrainz_enrichment_master_v1
    TO '{out_path}'
    WITH (HEADER, DELIMITER ',')
""")

print(f"✅ Exported: {out_path}")

✅ Exported: ../data_processed/exports/final_thesis_outputs/thesis_musicbrainz_enrichment_master_v1.csv

In [86]:
import duckdb
import pandas as pd

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Step 1: Recover MB-present rows from cds_only_enrichment_review_v1
# ------------------------------------------------------------
# Comments:
# - We check whether rows currently in the CDS-only review table
#   are actually present in MusicBrainz by exact normalized
#   artist-title agreement.
# - This is the same recovery idea we used earlier on the safe table.
print("Creating cds_only_review_recovered_mb_v1...")

con.execute("""
    CREATE OR REPLACE TABLE cds_only_review_recovered_mb_v1 AS
    WITH cds_review AS (
        SELECT
            r.cds_id,
            r.artist,
            r.title,
            r.cds_year,
            r.tracks,
            r.artist_key_clean,
            r.title_key_clean
        FROM cds_only_enrichment_review_v1 r
    ),
    mb_norm AS (
        SELECT
            m.release_id,
            m.release_title,
            m.main_artist_name,
            m.artist_credit_full,
            m.total_tracks,
            m.barcode,
            m.mb_year,
            lower(regexp_replace(coalesce(m.main_artist_name, ''), '[^a-zA-Z0-9]+', '', 'g')) AS mb_artist_key,
            lower(regexp_replace(coalesce(m.release_title, ''), '[^a-zA-Z0-9]+', '', 'g')) AS mb_title_key
        FROM mb_release_features m
    )
    SELECT
        c.cds_id,
        c.artist,
        c.title,
        c.cds_year,
        c.tracks,
        c.artist_key_clean,
        c.title_key_clean,
        m.release_id,
        m.release_title,
        m.main_artist_name,
        m.artist_credit_full,
        m.total_tracks,
        m.barcode,
        m.mb_year
    FROM cds_review c
    JOIN mb_norm m
      ON c.artist_key_clean = m.mb_artist_key
     AND c.title_key_clean = m.mb_title_key
""")

print("✅ Table created: cds_only_review_recovered_mb_v1")

print("\n--- Recovered candidate rows ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM cds_only_review_recovered_mb_v1
""").fetchdf())

print("\n--- Distinct CDS rows recovered ---")
print(con.execute("""
    SELECT COUNT(DISTINCT cds_id) AS n
    FROM cds_only_review_recovered_mb_v1
""").fetchdf())

print("\n--- Preview recovered rows ---")
print(con.execute("""
    SELECT *
    FROM cds_only_review_recovered_mb_v1
    LIMIT 20
""").fetchdf())

# ------------------------------------------------------------
# Step 2: Rank recovered rows using year evidence only
# ------------------------------------------------------------
# Comments:
# - We do NOT use track-gap because CDS tracks are text, not numeric count.
# - We rank by:
#     * year agreement
#     * barcode presence
#     * stable tie-break by release_id
print("\nCreating cds_only_review_recovered_ranked_v1...")

con.execute("""
    CREATE OR REPLACE TABLE cds_only_review_recovered_ranked_v1 AS
    WITH scored AS (
        SELECT
            r.*,

            CASE
                WHEN r.cds_year IS NOT NULL AND r.mb_year IS NOT NULL
                    THEN abs(r.cds_year - r.mb_year)
                ELSE NULL
            END AS year_gap,

            CASE
                WHEN r.barcode IS NOT NULL AND trim(r.barcode) <> '' THEN 1
                ELSE 0
            END AS has_barcode,

            CASE
                WHEN r.cds_year IS NOT NULL AND r.mb_year IS NOT NULL
                     AND abs(r.cds_year - r.mb_year) = 0 THEN 100
                WHEN r.cds_year IS NOT NULL AND r.mb_year IS NOT NULL
                     AND abs(r.cds_year - r.mb_year) = 1 THEN 90
                WHEN r.cds_year IS NOT NULL AND r.mb_year IS NOT NULL
                     AND abs(r.cds_year - r.mb_year) <= 3 THEN 75
                WHEN r.cds_year IS NOT NULL AND r.mb_year IS NOT NULL
                     AND abs(r.cds_year - r.mb_year) <= 5 THEN 60
                WHEN r.cds_year IS NOT NULL AND r.mb_year IS NULL THEN 40
                WHEN r.cds_year IS NULL AND r.mb_year IS NOT NULL THEN 30
                ELSE 20
            END
            +
            CASE
                WHEN r.barcode IS NOT NULL AND trim(r.barcode) <> '' THEN 5
                ELSE 0
            END AS recovery_rank_score
        FROM cds_only_review_recovered_mb_v1 r
    ),
    ranked AS (
        SELECT
            *,
            ROW_NUMBER() OVER (
                PARTITION BY cds_id
                ORDER BY
                    recovery_rank_score DESC,
                    year_gap ASC NULLS LAST,
                    has_barcode DESC,
                    mb_year ASC NULLS LAST,
                    release_id
            ) AS rn,

            COUNT(*) OVER (
                PARTITION BY cds_id
            ) AS candidate_count,

            LEAD(recovery_rank_score) OVER (
                PARTITION BY cds_id
                ORDER BY
                    recovery_rank_score DESC,
                    year_gap ASC NULLS LAST,
                    has_barcode DESC,
                    mb_year ASC NULLS LAST,
                    release_id
            ) AS second_score
        FROM scored
    )
    SELECT
        *,
        recovery_rank_score - coalesce(second_score, 0) AS recovery_score_gap
    FROM ranked
""")

print("✅ Table created: cds_only_review_recovered_ranked_v1")

print("\n--- Candidate count by CDS row ---")
print(con.execute("""
    SELECT
        cds_id,
        artist,
        title,
        candidate_count
    FROM cds_only_review_recovered_ranked_v1
    WHERE rn = 1
    ORDER BY candidate_count DESC, cds_id
""").fetchdf())

# ------------------------------------------------------------
# Step 3: classify recovered review rows into auto vs review
# ------------------------------------------------------------
# Comments:
# - We are strict:
#   auto only if unique and year-plausible, or clearly dominant
print("\nCreating cds_only_review_recovered_auto_v1 and cds_only_review_recovered_review_v1...")

con.execute("""
    CREATE OR REPLACE TABLE cds_only_review_recovered_auto_v1 AS
    SELECT *
    FROM cds_only_review_recovered_ranked_v1
    WHERE rn = 1
      AND (
            (
                candidate_count = 1
                AND year_gap IS NOT NULL
                AND year_gap <= 5
            )
            OR (
                recovery_rank_score >= 90
                AND recovery_score_gap >= 10
                AND (year_gap IS NULL OR year_gap <= 5)
            )
          )
""")

con.execute("""
    CREATE OR REPLACE TABLE cds_only_review_recovered_review_v1 AS
    SELECT *
    FROM cds_only_review_recovered_ranked_v1
    WHERE rn = 1
      AND cds_id NOT IN (
          SELECT cds_id
          FROM cds_only_review_recovered_auto_v1
      )
""")

print("✅ Tables created:")
print("   - cds_only_review_recovered_auto_v1")
print("   - cds_only_review_recovered_review_v1")

print("\n--- Recovery split summary ---")
print(con.execute("""
    SELECT 'auto' AS bucket, COUNT(*) AS n
    FROM cds_only_review_recovered_auto_v1
    UNION ALL
    SELECT 'review' AS bucket, COUNT(*) AS n
    FROM cds_only_review_recovered_review_v1
""").fetchdf())

print("\n--- Preview: recovered auto rows ---")
print(con.execute("""
    SELECT
        cds_id,
        artist,
        title,
        release_id,
        release_title,
        main_artist_name,
        cds_year,
        mb_year,
        year_gap,
        recovery_rank_score,
        recovery_score_gap,
        candidate_count
    FROM cds_only_review_recovered_auto_v1
    ORDER BY cds_id
    LIMIT 20
""").fetchdf())

print("\n--- Preview: recovered review rows ---")
print(con.execute("""
    SELECT
        cds_id,
        artist,
        title,
        release_id,
        release_title,
        main_artist_name,
        cds_year,
        mb_year,
        year_gap,
        recovery_rank_score,
        recovery_score_gap,
        candidate_count
    FROM cds_only_review_recovered_review_v1
    ORDER BY cds_id
    LIMIT 20
""").fetchdf())

Connected ✅
Creating cds_only_review_recovered_mb_v1...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

✅ Table created: cds_only_review_recovered_mb_v1

--- Recovered candidate rows ---
     n
0  344

--- Distinct CDS rows recovered ---
    n
0  88

--- Preview recovered rows ---
    cds_id             artist                               title  cds_year  \
0   106128               2pac   r u still down remember me disc 2      1997
1   101723               2pac  r u still down remember me disc 1       1997
2   104191                afi                     sing the sorrow      2003
3   107319                dig           defenders of the universe      <NA>
4   109049  leonard bernstein    bernstein conducts bernstein cd5      <NA>
5   106128               2pac   r u still down remember me disc 2      1997
6   101723               2pac  r u still down remember me disc 1       1997
7   108252    various artists      winter solstice on ice disc 1       1999
8     7898                ash                     free all angels      2001
9   107469    various artists                    house party vol5      2000
10  107814    various artists         the blues collection disk 6      1996
11  106865    various artists                   guitar heroes cd2      2000
12    7898                ash                     free all angels      2001
13  101229    various artists                     jazz moods cd 2      <NA>
14  103365                m2m                        the big room      2002
15  106128               2pac   r u still down remember me disc 2      1997
16  101723               2pac  r u still down remember me disc 1       1997
17  104191                afi                     sing the sorrow      2003
18  108324               a ha                     the best disk 1      <NA>
19    7898                ash                     free all angels      2001

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           tracks  \
0                                                                                                                                                                                                                                                ready 4 whatever when i get free hold on be strong i m losin it fake ass bitches do for love enemies with me nothin but love 16 on death row i wonder if heaven got a ghetto hip hop version when i get free ii black starry night interlude only fear of death
1                                                                                                                                                                                                                                                              redemption open fire r u still down remeber me hellrazor thug style where do we go from here interlude i wonder if heaven got a ghetto nothing to lose i m gettin money lie to kick it f k all y all let them thangs go definition of a thug n ga
2                                                                                                                                                                                                                                               miseria cantare the beginning the leaving song pt ii bleed black silver and cold dancing through sunday girl s not grey death of seasons the great disappointment paper airplanes makeshift wings this celluloid dream the leaving song but home is nowhere data
3                                                                                                                                                                                                                                                                                                                                             whose side you on detune song for liars little pill stop holding your breath e l o mood elevator electric cord wall socket white sabbath bashing in your head opus
4                                    divertimento for orchestra i sennets and tuckets divertimento for orchestra ii waltz divertimento for orchestra iii mazurka divertimento for orchestra iv samba divertimento for orchestra v turkey trot divertimento for orchestra vi sphinxes divertimento for orchestra vii blues divertimento for orchestra viii march a musical toast slava three meditations from mass i lento assai molto sostenu to three meditations ii andante three meditations iii presto halil
5                                                                                                                                                                                                                                                ready 4 whatever when i get free hold on be strong i m losin it fake ass bitches do for love enemies with me nothin but love 16 on death row i wonder if heaven got a ghetto hip hop version when i get free ii black starry night interlude only fear of death
6                                                                                                                                                                                                                                                              redemption open fire r u still down remeber me hellrazor thug style where do we go from here interlude i wonder if heaven got a ghetto nothing to lose i m gettin money lie to kick it f k all y all let them thangs go definition of a thug n ga
7                                               ensemble magic forest liz story joy to the world w g snuffy walden yesterday s rain george winston skating angels of venice o holy night mark snow joy ride l a guitar quartet 4 variations on twinkle twinkle little star schonertz scott little drummer boy jim brickman bittersweet micheal o domhnaill paddy glacklin sweeney s buttermilk george winston nigh bethlehem sean harkness first noel janis ian we three kings michael hedges what child is this
8                                                                                                                                                                                                                                                                                                                                                    walking barefoot shining light burn baby burn candy cherry bomb submission someday pacific palisades shark sometimes nicole there s a star world domination
9            modjo lady 12 version groovejet spiller radio mix kenny blake tom dinner s club mix sting desert rose club mix heroes magic orgasm backroom kaki mcs bombfunk freestylers alternative mix lonyo summer of love original ext afro medusa pasilda knee deep mix artfull dodger feat craig david women trouble sunship boombastic kylie minogue spinning around sharp vocal mix moby porcelece original mix lil louis french kiss original version josh wink lil louis how s your evening so far uk 12
10                                                                                                                   john lee hooker maudie ray charles misery and blues ray charles i can t be satisfied elmore james i done somebody wrong elmore james i believe bo diddley mess around john lee hooker wednesday evening blues b b king all aboard joe liggins the honeydripper pee wee crayton in the evening billie holiday miss brown to you john lee hooker crawling king snake elmore james coming home
11  santana soul sacrifice the yardbirds heartful of soul jimi hendrix the sunshine of your love short version john mayall mama talk to your daughter johnny winter out of sight eric clapton jimmy page miles road the booze brothers feat m knopfler where are you tonight the yardbirds with jeff beck jeff s blues santana with a little help from my friends jimi hendrix she s so fine the yardbirds train kept a rolling jimi hendrix uranus rock john mayall lost and gone johnny winter going down slow
12                                                                                                                                                                                                                                                                                                                                                   walking barefoot shining light burn baby burn candy cherry bomb submission someday pacific palisades shark sometimes nicole there s a star world domination
13                                                                                                                                                                                                                                                                                             rose room nature boy old devil moon perdido street blues countin the blues fiesta but not for me i cant get started blue rondo a la turk trouble in mind all the things you are some other time wade in the water
14                                                                                                                                                                                                                                                                                                                                                              everything jennifer don t payphone what you do about me love left for me miss popular wanna be where you are leave me alone sometimes eventually
15                                                                                                                                                                                                                                               ready 4 whatever when i get free hold on be strong i m losin it fake ass bitches do for love enemies with me nothin but love 16 on death row i wonder if heaven got a ghetto hip hop version when i get free ii black starry night interlude only fear of death
16                                                                                                                                                                                                                                                             redemption open fire r u still down remeber me hellrazor thug style where do we go from here interlude i wonder if heaven got a ghetto nothing to lose i m gettin money lie to kick it f k all y all let them thangs go definition of a thug n ga
17                                                                                                                                                                                                                                              miseria cantare the beginning the leaving song pt ii bleed black silver and cold dancing through sunday girl s not grey death of seasons the great disappointment paper airplanes makeshift wings this celluloid dream the leaving song but home is nowhere data
18                                                                                                                                                                                                                                        stay on these roads october and you tell me burry home out of blue comes green hunting high and low you are the one the blood that moves the body you ll end up crying manhattan skyline the sun always shines on tv the swing of things there s never a forever thing
19                                                                                                                                                                                                                                                                                                                                                   walking barefoot shining light burn baby burn candy cherry bomb submission someday pacific palisades shark sometimes nicole there s a star world domination

    artist_key_clean             title_key_clean  release_id  \
0               2pac       rustilldownrememberme     2614867
1               2pac       rustilldownrememberme     2614867
2                afi               singthesorrow      362179
3                dig      defendersoftheuniverse     2926967
4   leonardbernstein  bernsteinconductsbernstein     1959019
5               2pac       rustilldownrememberme     5392921
6               2pac       rustilldownrememberme     5392921
7     variousartists         wintersolsticeonice     1893167
8                ash               freeallangels      125377
9     variousartists                  houseparty     1701037
10    variousartists          thebluescollection     1972449
11    variousartists                guitarheroes     1367831
12               ash               freeallangels     1921098
13    variousartists                   jazzmoods      819805
14               m2m                  thebigroom     1924850
15              2pac       rustilldownrememberme       27252
16              2pac       rustilldownrememberme       27252
17               afi               singthesorrow       14285
18               aha                     thebest     4218321
19               ash               freeallangels      280734

                    release_title   main_artist_name  \
0   R U Still Down? [Remember Me]               2Pac
1   R U Still Down? [Remember Me]               2Pac
2                 Sing the Sorrow                AFI
3       Defenders of the Universe                Dig
4    Bernstein conducts Bernstein  Leonard Bernstein
5   R U Still Down? (Remember Me)               2Pac
6   R U Still Down? (Remember Me)               2Pac
7          Winter Solstice on Ice    Various Artists
8                 Free All Angels                Ash
9                     House Party    Various Artists
10           The Blues Collection    Various Artists
11                  Guitar Heroes    Various Artists
12                Free All Angels                Ash
13                     Jazz Moods    Various Artists
14                   The Big Room                M2M
15  R U Still Down? (Remember Me)               2Pac
16  R U Still Down? (Remember Me)               2Pac
17                Sing the Sorrow                AFI
18                       The Best               a‐ha
19                Free All Angels                Ash

                  artist_credit_full  total_tracks        barcode  mb_year
0                               2Pac          26.0   777495152056     2020
1                               2Pac          26.0   777495152056     2020
2                                AFI          12.0   600445038028     2024
3                                Dig          12.0           None     2021
4   Bernstein; New York Philharmonic          25.0   696998904361     2020
5                               2Pac          26.0           None     2025
6                               2Pac          26.0           None     2025
7                    Various Artists          12.0   618322103424     2017
8                                Ash          16.0           None     2017
9                    Various Artists          60.0  5051275080322     2020
10                   Various Artists          20.0  5033606007154     2017
11                   Various Artists          33.0  8712155065545     2017
12                               Ash          15.0  4988009244211     2017
13                   Various Artists          21.0  5014469527225     2022
14                               M2M          12.0  9325583014598     2017
15                              2Pac          26.0   012414162823     2023
16                              2Pac          26.0   012414162823     2023
17                               AFI          14.0   600445044821     2025
18                              a‐ha          12.0           None     2025
19                               Ash          14.0  5026854010007     2025

Creating cds_only_review_recovered_ranked_v1...
✅ Table created: cds_only_review_recovered_ranked_v1

--- Candidate count by CDS row ---
    cds_id           artist                              title  \
0   100810              him                 razorblade romance
1   104191              afi                    sing the sorrow
2   105917              jet                           get born
3   109695      fats waller           ain t misbehavin disc 1
4   102604  various artists  memories are made of this disc 2
..     ...              ...                                ...
83  107240              roh                        rohmantisch
84  107385              guz                       we do wie du
85  107770  various artists           road trippin blues vol 1
86  108709  various artists       en riktig svensk jul disc 2
87  109064  various artists         classical collection vol 3

    candidate_count
0                19
1                17
2                15
3                15
4                11
..              ...
83                1
84                1
85                1
86                1
87                1

[88 rows x 4 columns]

Creating cds_only_review_recovered_auto_v1 and cds_only_review_recovered_review_v1...
✅ Tables created:
   - cds_only_review_recovered_auto_v1
   - cds_only_review_recovered_review_v1

--- Recovery split summary ---
   bucket   n
0    auto   0
1  review  88

--- Preview: recovered auto rows ---
Empty DataFrame
Columns: [cds_id, artist, title, release_id, release_title, main_artist_name, cds_year, mb_year, year_gap, recovery_rank_score, recovery_score_gap, candidate_count]
Index: []

--- Preview: recovered review rows ---
    cds_id           artist                                title  release_id  \
0     6740              ivy                        long distance      342949
1     7898              ash                      free all angels     1921098
2     9193              ivy                        long distance      342949
3   100196              eko                              celtica      932980
4   100293              bzn                        crystal gazer      289706
5   100314         trovante                uma noite sã³ disc 2       818118
6   100810              him                   razorblade romance       45256
7   100850  various artists          ska the third wave volume 5      438781
8   100863  various artists          hed kandi back to love cd2      2193551
9   101229  various artists                      jazz moods cd 2      819805
10  101470  various artists             best of love songs vol 2      114169
11  101580              tru                    tru 2 da game cd2      626678
12  101659  various artists          christmas favourites disc 2      626486
13  101723             2pac   r u still down remember me disc 1      1848237
14  101792           e c m                             blechreiz     1796194
15  101821  various artists                   this is trance cd1     3632926
16  101904             ira                       entre seus rins      204832
17  101940  various artists  the power of love heartbeat disc 1      3985922
18  102133  various artists                  latin mix usa vol 2     2375142
19  102221  various artists                      mega fãªte cd 4     3085606

                    release_title main_artist_name  cds_year  mb_year  \
0                   Long Distance              Ivy      2000     2016
1                 Free All Angels              Ash      2001     2017
2                   Long Distance              Ivy      2002     2016
3                         Celtica              Eko      <NA>     2011
4                   Crystal Gazer              BZN      1989     2010
5                    Uma Noite Só         Trovante      2000     2019

In [87]:
import duckdb
import pandas as pd

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Step 1: Reclassify recovered CDS-only review rows
# ------------------------------------------------------------
# Comments:
# - cds_only_review_recovered_review_v1 contains CDS rows that were
#   originally in the CDS-only review bucket, but were later found
#   to already exist in MusicBrainz.
# - These rows should therefore move to MB review enrichment.
# - The remaining rows in cds_only_enrichment_review_v1 stay as
#   true CDS-only review enrichment candidates.
print("Creating cds_mb_enrichment_review_v1...")

con.execute("""
    CREATE OR REPLACE TABLE cds_mb_enrichment_review_v1 AS
    SELECT
        r.cds_id,
        c.artist AS cds_artist,
        c.title AS cds_title,
        c.cds_year,
        c.category,
        c.genre,
        c.tracks AS cds_tracklist,

        r.release_id,
        r.release_title,
        r.main_artist_name,
        r.artist_credit_full,
        r.total_tracks,
        r.barcode,
        r.mb_year,

        r.year_gap,
        r.recovery_rank_score,
        r.recovery_score_gap,
        r.candidate_count,

        'recovered_mb_presence_review' AS match_type,
        'review_mb_enrichment' AS enrichment_status
    FROM cds_only_review_recovered_review_v1 r
    LEFT JOIN cds c
      ON r.cds_id = c.cds_id
""")

print("✅ Table created: cds_mb_enrichment_review_v1")

print("\nCreating cds_only_enrichment_review_true_unmatched_v1...")

con.execute("""
    CREATE OR REPLACE TABLE cds_only_enrichment_review_true_unmatched_v1 AS
    SELECT *
    FROM cds_only_enrichment_review_v1 r
    WHERE r.cds_id NOT IN (
        SELECT DISTINCT cds_id
        FROM cds_mb_enrichment_review_v1
    )
""")

print("✅ Table created: cds_only_enrichment_review_true_unmatched_v1")

print("\n--- Reclassification summary ---")
print(con.execute("""
    SELECT 'mb_review_enrichment' AS bucket, COUNT(*) AS n
    FROM cds_mb_enrichment_review_v1
    UNION ALL
    SELECT 'true_cds_only_review' AS bucket, COUNT(*) AS n
    FROM cds_only_enrichment_review_true_unmatched_v1
""").fetchdf())

print("\n--- Preview: MB review enrichment rows ---")
print(con.execute("""
    SELECT *
    FROM cds_mb_enrichment_review_v1
    LIMIT 20
""").fetchdf())

print("\n--- Preview: true CDS-only review rows ---")
print(con.execute("""
    SELECT
        cds_id,
        artist,
        title,
        cds_year,
        tracks,
        curation_route,
        enrichment_priority_v6,
        cds_enrichment_type
    FROM cds_only_enrichment_review_true_unmatched_v1
    LIMIT 20
""").fetchdf())

Connected ✅
Creating cds_mb_enrichment_review_v1...
✅ Table created: cds_mb_enrichment_review_v1

Creating cds_only_enrichment_review_true_unmatched_v1...
✅ Table created: cds_only_enrichment_review_true_unmatched_v1

--- Reclassification summary ---
                 bucket     n
0  mb_review_enrichment    88
1  true_cds_only_review  2980

--- Preview: MB review enrichment rows ---
    cds_id       cds_artist                                 cds_title  \
0   100196              eko                                   celtica
1   100293              bzn                             crystal gazer
2   100314         trovante                     uma noite sã³ disc 2
3   100810              him                        razorblade romance
4   100850  various artists               ska the third wave volume 5
5   100863  various artists               hed kandi back to love cd2
6   101229  various artists                           jazz moods cd 2
7   101470  various artists                  best of love songs vol 2
8   101580              tru                         tru 2 da game cd2
9   101659  various artists               christmas favourites disc 2
10  101723             2pac        r u still down remember me disc 1
11  101792           e c m                                  blechreiz
12  101821  various artists                        this is trance cd1
13  101904             ira                            entre seus rins
14  101940  various artists       the power of love heartbeat disc 1
15  102133  various artists                       latin mix usa vol 2
16  102221  various artists                           mega fãªte cd 4
17  102281  various artists    hits of the seventies volume 1 disc 2
18  102371              trf                                     unite
19  102390  various artists  the spirit of the underground vol 1 cd2

    cds_year category           genre  \
0       <NA>     folk            None
1       1989     folk             pop
2       2000     folk   national folk
3       2000     folk     gothic rock
4       <NA>     jazz            None
5       1999     jazz           house
6       <NA>     jazz            None
7       <NA>     misc            None
8       1997     misc     gangsta rap
9       <NA>     misc  symphonic rock
10      1997     misc             rap
11      <NA>     misc            None
12      <NA>     misc            None
13      2001     misc            rock
14      <NA>     misc            None
15      1999     misc           latin
16      <NA>     misc         ambient
17      1989     misc            rock
18      1998     misc             pop
19      <NA>     misc            None

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      cds_tracklist  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  carrigafoyle relativity celtica intro to night ferry rosie o connor across the water the craic faith jack barry s trap intro to dublin to delhi
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        aloha hã bandolero crystal gazer if i had only a change she s a queen sailor s delight el cordobes my heart yearns over you life is not a bed of roses l anniversaire my everlasting love throw me a line
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                um caso mais aerograma timor perdidamente 125 azul saudade bye bye blackout linha das fronteiras balada das sete saias sorriso prima da chula fim
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            i love you poison girl join me in death right here in my arms gone with the sin razorblade kiss bury me deep inside your heart heaven tonight death is in love with us resurrection one last time sigillum diaboli the 9th circle olt
4                                                                                                                                                                                                                                                                                                                                                                royal crown revue the walkin blues skavoovie the epitones she sure can cook my man friday monkey business unsteady one for the road undercover s k a dr kildare royal crown revue the rise and fall of the great mondello new morty show caldonia scofflaws groovin up live dave s big deluxe what i used to be allstonians walking in the sand scofflaws parish seven foot politic old gold hipster daddy o and the handgrenades
5                                                                                                                                        zoe sunshine on a rainy day original 12 version the family stand ghetto heaven original soul ii soul 12 re mix with jazzy b diana brown and barrie k sharpe the masterplan extended ver sion young disciples apparently nothin original 12 mix mantronix got to have your love 12 club with bonus beats lisa lisa and cult jam let the beat hit em brand new super pumped up paul simpson feat adeva and carman marie musical freedom 1 2 mix rufus chaka khan ain t nobody original version richie haven going back to my roots original version gwen mccrae all this love that i m giving original version sounds of blackness optimistic album version
6                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                rose room nature boy old devil moon perdido street blues countin the blues fiesta but not for me i cant get started blue rondo a la turk trouble in mind all the things you are some other time wade in the water
7                                                                                                                                                                                                                                                                                                                                         chances are johnny mathis theme from a summer place percy faith unforgettable dinah washington since i fell for you lenny welch the way we were try to remeber gladys knight the pips wind beneath my wings garry morris feelings morris albert my eyes adored you frankie valli precious and few climax only you and you alone the platters goin out of my head little anthony the imperials it s all in the game tommy edwards sleep walk santo johnny
8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ghetto cheese heaven for a gangsta tru remix tru 2 da game featuring big ed and mr serv on freak hoes and mia x tru s 1nce upon a time featuring c loc pop goes my nine featuring kane abel it s my time torcher chamber they can t stop us the lord is testing me no limit soldier club mix final ride
9                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           alleluia di natale ii est ne le divin enfant the holly and the ivy from heaven on high good christian men rejoice hallelujah for unto us a child is born amen as with gladness men of old angel from the realm of glory the infant king deck the halls
10                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               redemption open fire r u still down remeber me hellrazor thug style where do we go from here interlude i wonder if heaven got a ghetto nothing to lose i m gettin money lie to kick it f k all y all let them thangs go definition of a thug n ga
11                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  gift transition instrument heart w rmespender alternate reality vengeance sohn des idiots gott decay suicide kopfschussdynamik
12                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   chicane feat maire brennan saltwater atb 9pm till i come tall paul be there nexus the next level enforcer terminal velocity mike koglin feat beatrice on my way insomnia freebase tilt invisible paradise breakneck zero one give it to you acetate substance
13                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    o bom e velho rock n roll entre seus rins milhas e milhas naftalina superficial como um espinho para ser humano homem de neanderthal um homem sã³ mistã rio pecado o tempo a vida por um fio
14                                                                                                                                                                                                                                                                                                                                                                                                                                          foreigner i want to know what love is reo speedwagon can t fight this feeling mr mister broken wings richard marx right here waiting bangles eternal flame far corporation stairway to heaven christopher cross sailing john waite missing you styx babe air supply all out of love peter cetera glory of love bonnie tyler total eclipse of the heart
15                                                                                                                                                                                                                                     ricky martin livin la vida loca scissorhands english radio mix elvis crespo suavemente hot head mix chavanne salomã pablo flores club mix radio edit mdo groove with me tonight pablo flores spanglish remix will smith miami mix ivy queen featuring wyclef jean in the zone king sahpreem remix shakira ciega sordomuda 12 single edit dlg dark latin groove magdalena mi amore quimbara fey dã selo con flores house mix jennifer delgado que tu tienes grupo mania bome baila radio mix jennifer lopez duet with marc anthony no me ames ballad version
16  gloria gaynor i will survive marc laferriã re hello dolly andrã blot tu verras montmartre aparecida pepito gilberto gil aquele abracao maurice larcange un clair de lune ã maubeuge louis corchia mantilla angelo de morales pepe rodriguez la cumparsita les fãªtards si tu va ã rio michel pruvot la java bleue jesse green nice n slow little richard long tall sally aparecida bamboleo valto latinen ain t she sweet andrã blot la valse brune julio cortazon el choclo sabroso miquel brown so many men so little time perez prado havana hippolyte lafleur sans chemise sans pantalon luis mendoza et son orchestre bolero transatlantic swing band in the mood rico cortena steel band hot carnaval max marino ca c est paris raphaele concert orchestra cancan max marino espana cani
17                                                                                                                                                                                                                                                                                                                                                                                         edgar winter group frankenstein looking glass brandy your a fine girl loggins messina your mama don t dance martha the muffins echo beach blue oyster cult don t fear the reaper david essex rock on redbone come and get your love argent hold your head up nick lowe cruel to be kind s o s band take your time do it right three degrees when will i see you again johnny nash i can see clearly now
18                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           realize frisky a go go sunset boulevard mix frame in the move to be darkscape earl grey try or cry meltin you future shock friends it s my time get up stand up unity unite the night
19                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      jambo drumattack a t s baa daa laa resistance d eclipse tranceporter open up your mind casseopaya trance theme zero gravity the crave microbots the sound plasma the sound the melody the concert hole in 1 x paradise jetstream seriously

    release_id                  release_title main_artist_name  \
0       932980                        Celtica              Eko
1       289706                  Crystal Gazer              BZN
2       818118                   Uma Noite Só         Trovante
3        45256             Razorblade Romance              HIM
4       438781            Ska: The Third Wave  Various Artists
5      2193551         Hed Kandi Back to Love  Various Artists
6       819805                     Jazz Moods  Various Artists
7       114169             Best of Love Songs  Various Artists
8       626678                  TRU 2 da Game              TRU
9       626486           Christmas Favourites  Various Artists
10     1848237  R U Still Down? [Remember Me]             2Pac
11     1796194                      Blechreiz           E.C.M.
12     3632926                 This Is Trance  Various Artists
13      204832                Entre Seus Rins             Ira!
14     3985922   The Power of Love: Heartbeat  Various Artists
15     2375142                  Latin Mix USA  Various Artists
16     3085606                      Mega Fête  Various Artists

In [88]:
#delete this cell

In [89]:
import duckdb
import pandas as pd

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Step 2: Build final thesis enrichment master table
# ------------------------------------------------------------
# Comments:
# - This table now integrates all usable enrichment outputs:
#   1) confirmed_mb_enrichment
#   2) review_mb_enrichment
#   3) new_cds_enrichment_safe
#   4) new_cds_enrichment_review
# - Recovered MB-present rows from the CDS-only review branch are now
#   included as review-level MB enrichment.
print("Creating thesis_musicbrainz_enrichment_master_v3...")

con.execute("""
    CREATE OR REPLACE TABLE thesis_musicbrainz_enrichment_master_v3 AS

    -- --------------------------------------------------------
    -- A. Confirmed MB enrichment + already included MB review
    -- --------------------------------------------------------
    SELECT
        cds_id,
        cds_artist AS artist,
        cds_title AS title,
        cds_year,
        category,
        genre,
        cds_tracklist AS tracks,

        release_id,
        release_title,
        main_artist_name,
        artist_credit_full,
        total_tracks,
        barcode,
        mb_year,

        match_type AS enrichment_route,
        CASE
            WHEN match_type = 'matched_review_candidate' THEN 'review_mb_enrichment'
            ELSE 'confirmed_mb_enrichment'
        END AS enrichment_status
    FROM cds_mb_enrichment_combined_v1

    UNION ALL

    -- --------------------------------------------------------
    -- B. Additional MB review enrichment recovered from
    --    CDS-only review rows
    -- --------------------------------------------------------
    SELECT
        cds_id,
        cds_artist AS artist,
        cds_title AS title,
        cds_year,
        category,
        genre,
        cds_tracklist AS tracks,

        release_id,
        release_title,
        main_artist_name,
        artist_credit_full,
        total_tracks,
        barcode,
        mb_year,

        match_type AS enrichment_route,
        enrichment_status
    FROM cds_mb_enrichment_review_v1
    WHERE cds_id NOT IN (
        SELECT DISTINCT cds_id
        FROM cds_mb_enrichment_combined_v1
    )

    UNION ALL

    -- --------------------------------------------------------
    -- C. True CDS-only safe enrichment
    -- --------------------------------------------------------
    SELECT
        s.cds_id,
        s.artist,
        s.title,
        s.cds_year,
        c.category,
        c.genre,
        c.tracks,

        NULL AS release_id,
        NULL AS release_title,
        NULL AS main_artist_name,
        NULL AS artist_credit_full,
        NULL AS total_tracks,
        NULL AS barcode,
        NULL AS mb_year,

        'cds_only_safe' AS enrichment_route,
        'new_cds_enrichment_safe' AS enrichment_status
    FROM cds_only_enrichment_safe_true_unmatched_v1 s
    LEFT JOIN cds c
      ON s.cds_id = c.cds_id

    UNION ALL

    -- --------------------------------------------------------
    -- D. True CDS-only review enrichment
    -- --------------------------------------------------------
    SELECT
        r.cds_id,
        r.artist,
        r.title,
        r.cds_year,
        c.category,
        c.genre,
        c.tracks,

        NULL AS release_id,
        NULL AS release_title,
        NULL AS main_artist_name,
        NULL AS artist_credit_full,
        NULL AS total_tracks,
        NULL AS barcode,
        NULL AS mb_year,

        'cds_only_review' AS enrichment_route,
        'new_cds_enrichment_review' AS enrichment_status
    FROM cds_only_enrichment_review_true_unmatched_v1 r
    LEFT JOIN cds c
      ON r.cds_id = c.cds_id
""")

print("✅ Table created: thesis_musicbrainz_enrichment_master_v3")

print("\n--- Final enrichment summary ---")
print(con.execute("""
    SELECT
        enrichment_status,
        COUNT(*) AS n,
        ROUND(100.0 * COUNT(*) / (SELECT COUNT(*) FROM thesis_musicbrainz_enrichment_master_v3), 2) AS pct
    FROM thesis_musicbrainz_enrichment_master_v3
    GROUP BY enrichment_status
    ORDER BY n DESC
""").fetchdf())

print("\n--- Breakdown by route ---")
print(con.execute("""
    SELECT
        enrichment_route,
        COUNT(*) AS n
    FROM thesis_musicbrainz_enrichment_master_v3
    GROUP BY enrichment_route
    ORDER BY n DESC
""").fetchdf())

print("\n--- Preview ---")
print(con.execute("""
    SELECT *
    FROM thesis_musicbrainz_enrichment_master_v3
    LIMIT 30
""").fetchdf())

Connected ✅
Creating thesis_musicbrainz_enrichment_master_v3...
✅ Table created: thesis_musicbrainz_enrichment_master_v3

--- Final enrichment summary ---
           enrichment_status     n    pct
0    confirmed_mb_enrichment  4214  46.97
1  new_cds_enrichment_review  2980  33.22
2    new_cds_enrichment_safe  1646  18.35
3       review_mb_enrichment   131   1.46

--- Breakdown by route ---
               enrichment_route     n
0                         exact  3482
1               cds_only_review  2980
2                 cds_only_safe  1646
3             fuzzy_second_pass   543
4            various_title_only   183
5  recovered_mb_presence_review    88
6      matched_review_candidate    43
7         alias_enrichment_safe     3
8        enrichment_round2_auto     3

--- Preview ---
    cds_id                artist                            title  cds_year  \
0    10000       backstreet boys                       millennium      <NA>
1   100001               various      frankfurt trance vol 04 cd1      <NA>
2   100002             no return                  self mutilation      <NA>
3   100006      luv lite massive                         one love      <NA>
4   100008                  dmbq                             dmbq      2002
5   100010               various      frankfurt trance vol 05 cd1      <NA>
6   100012    rumania montevideo                 mo better tracks      <NA>
7   100015                 keedy                 chase the clouds      <NA>
8   100019            bill evans                            alone      1968
9   100020      nature destroyed                           shades      <NA>
10  100021             pearl jam                            yield      1998
11  100022     dingdong avanzado    the best of dingdong avanzado      <NA>
12  100024                  175r                            songs      2003
13  100026    day after tomorrow                         elements      2003
14  100031               spartak                            golem      1990
15  100035                gazebo               the best of gazebo      <NA>
16  100037  sportfreunde stiller                   die gute seite      <NA>
17  100039               various            salsaenlacalleocho 96      <NA>
18  100040     barbara streisand                 a love like ours      1999
19  100058             green day                           dookie      <NA>
20  100064                savage                          tonight      <NA>
21  100065      atmo brtschitsch                 change your life      <NA>
22  100066            del amitri                          twisted      1995
23  100082         barry mcguire               eve of destruction      1985
24  100087         tschou zã me                         wã ge dir      <NA>
25  100088         clive gregson                  comfort and joy      <NA>
26  100089       various artists                   dorival caymmi      <NA>
27  100094            keri noble                         fearless      2004
28  100097           north cregg                summer at my feet      2003
29  100099    fabienne thibeault  les plus belles chansons cd 2 2      <NA>

        category           genre  \
0          blues             pop
1           data            None
2           data            data
3           data      electronic
4           data            rock
5           data            None
6           data             pop
7           data            data
8           data            None
9           data            None
10          data       hard rock
11          data            None
12          data            jpop
13          data             pop
14          data      electronic
15          data            None
16          data            data
17  sonytsid7008            data
18          data  easy listening
19          data            None
20          data            None
21          data            None
22          data            rock
23          folk          oldies
24          folk            None
25          folk            None
26          folk            folk
27          folk             pop
28          folk            folk
29          folk            None

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          tracks  \
0                                                                                                                                                                                                                                                                               larger than life i want it that way show me the meaning of being lonely it s gotta be you i need you tonight don t want you back don t wanna lose you now the one back to your heart spanish eyes no one else comes close the perfect fan i ll be there for you
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           None
2                                                                                                                                                                                                                                                                                                                                                                                                  do or die truth and reality lost soul extractor sadistic desire the true way fanatic mind individualistic ideal one life trail of blood sect
3                                                                                                                                                                                                                                                                                                                                                                                                                              temple of dehli from naw till a mornin shock afghani lick you bad freestyle fiki fuko i m here yeah ww5 one love
4                                                                                                                                                                                                                                                                                                                                     small hours rock a cola ohh baby teenage limbo little leaf i movement little leaf ii swell little leaf iii etude sayonara no season altered rock can peace migrate to midnight e means eternal data track
5                                                                 dj tom stevens violet steam single cut liquid child diving faces original mix vimana we came edit lac terra after dark fridge vs vectrex remix steve baltes thoughts original mix star party i m in love ferry corsten robert smit rmx gate iv give all you got radio edit dj stigma baby sunshine stig s original club mix synchronic minds all i need club mix astral inc remember green court edit x trance friends 2000 tom stevens rmx ravelab send me an angel club mix
6                                                                                                                                                                                                                                                                                                                                                                             i ll be with you hard rain free tender rain rain sleeper life style taxi take my pain away my life album version all by myself start all over again album version
7                                                                                                                                                                                                                                                                                                                                                                                 save some love wishing on the same star never neverland sorry only your heart gettin around don t turn away pretty boy mama lazy day save some love hot remix
8                                                                                                                                                here s that rainy day a time for love midnight mood on a clear day you can see forever never let me go the two lonely people aka the man and the woman here s that rainy day alternative take a time for love alternative take midnight mood alternative take on a clear day you can see forever alternative take never let me go alternative take medley all the things you are midnight mood
9                                                                                                                                                                                                                                                                                                                                                                                                               enter the realm dream of fear word of trust unforeseen desire shades bound imprisoned cold vengeance disease leaving the shadow
10                                                                                                                                                                                                                                                                                                                                                                                              brain of j faithfull no way given to fly wishlist pilate do the evolution untitled mfc low light in hiding push me pull me all those yesterdays
11                                                                                                                                                                                                                                                                                                                                   ikaw lamang tatlong beinte singko maghihintay sa yo makapiling ka sana break kung break love at first sight basta t kasama kita paano sasabihin here i am i think i love you bakit hangang ngayon say amen
12                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          None
13                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          None
14                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          None
15                                                                                                                                                                                                                                                                                                i like chopin lunatic masterpiece dolce vita telephone mama sun goes down on milky way women come women go victims in paradise god bless the moonshade the fourteenth of july dancing with the moonlit knight trotsky burger waterland tycoon
16                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          None
17  1996 estamossolos jorgeluispiloto 1996 reyruiz hastaqueteconoci juangabriel 1996 marcanthony situsupieras omaralfanno 1996 giro laguagua candidofabre 1996 celiacruz hechocadoconlavida ivetteayala 1996 titorojas apiadatedemi omaralfanno 1996 victormanuelle quemaneradequererte emiliorios 1996 gilbertosantarosa quienerestu luisenriquemejia 1996 luisenrique nuncavoyaolvidarte robertobelester 1996 india gotasdelluvia jairovalera 1996 gruponiche otropoco mariofiaz 1996 puertoricanpower rumbera donatopoveda 1996 willychirino
18                                                                                                                                                                                                                                                                                                                  i ve dreamed of you isn t it a pity the island love like ours if you ever leave me we must be loving right if i never met you it must be you just one lifetime if i didn t love you wait the music that makes me dance data
19                                                                                                                                                                                                                                                                                                                                                                  burn out having a blast chump long view welcome to paradise pulling teeth basket case she sassafras roots when i come arround coming clean emenius sleepus in the end f o d
20                                                                                                                                                                                                                                                                                                                                   radio a love again fugitive tonight a love again remix don t cry tonight computerized love only you turn around time magic carillon instrumental don t cry tonight extended don t cry tonight instrumental
21                                                                                                                                                                                                                                                                                                                                                                                         everyday morningsun sittin green plane rockstar black sea some girls lucky people image stop taking always smiling coming home around me every night
22                                                                                                                                                                                                                                                                                                                    food for songs start with me here and now one thing left to do tell her this being somebody else roll to me crashing down it might as well be you never enough it s never too late to be alone driving with the brakes on
23                                                                                                                                                                                                                                                         eve of destruction she belongs to me you never had it so good sloop john b baby blue the sins of a family try to remember mr man on the street act one you were on my mind ain t no way i m gonna change my mind what exactly s the matter with me why not stop dig it while you can
24                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          None
25                                                                                                                                                                                                                                                                                                                                  frances o connor antidote fingerless gloves i m there for you it s you i want to hold if i was your lover catholic girl white suit of notes riding on a bus pretty peggy o string of pearls comfort and joy
26                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          None
27                                                                                                                                                                                                                                                                                                                                                                            look at me talk to me piece of my heart a dream about you about me let it rain falling love is all i know answered prayer bartender i won t if no one will listen

In [90]:
#delete this cell

In [91]:
import duckdb
import pandas as pd

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Rename the recovered review route label inside the final thesis table
# ------------------------------------------------------------
# Comments:
# - We keep the table structure the same.
# - We only replace the route name with a cleaner thesis-facing label.
print("Updating enrichment_route label in thesis_musicbrainz_enrichment_master_v3...")

con.execute("""
    UPDATE thesis_musicbrainz_enrichment_master_v3
    SET enrichment_route = 'review_mb_enrichment_recovered'
    WHERE enrichment_route = 'recovered_mb_presence_review'
""")

print("✅ Route label updated")

print("\n--- Updated route breakdown ---")
print(con.execute("""
    SELECT
        enrichment_route,
        COUNT(*) AS n
    FROM thesis_musicbrainz_enrichment_master_v3
    GROUP BY enrichment_route
    ORDER BY n DESC
""").fetchdf())

Connected ✅
Updating enrichment_route label in thesis_musicbrainz_enrichment_master_v3...
✅ Route label updated

--- Updated route breakdown ---
                 enrichment_route     n
0                           exact  3482
1                 cds_only_review  2980
2                   cds_only_safe  1646
3               fuzzy_second_pass   543
4              various_title_only   183
5  review_mb_enrichment_recovered    88
6        matched_review_candidate    43
7           alias_enrichment_safe     3
8          enrichment_round2_auto     3

In [92]:
import os

os.makedirs("../data_processed/exports/final_thesis_outputs", exist_ok=True)

out_path = "../data_processed/exports/final_thesis_outputs/thesis_musicbrainz_enrichment_master_v3.csv"

con.execute(f"""
    COPY thesis_musicbrainz_enrichment_master_v3
    TO '{out_path}'
    WITH (HEADER, DELIMITER ',')
""")

print(f"✅ Exported: {out_path}")

✅ Exported: ../data_processed/exports/final_thesis_outputs/thesis_musicbrainz_enrichment_master_v3.csv

In [93]:
import duckdb

# Connect to your database
con = duckdb.connect("../data_processed/thesis.duckdb")

out_path = "../data_processed/exports/final_thesis_outputs/thesis_musicbrainz_enrichment_master_v3.csv"
con.execute(f"""
    COPY thesis_musicbrainz_enrichment_master_v3
    TO '{out_path}'
    WITH (
        HEADER,
        DELIMITER ',',
        QUOTE '"',
        ESCAPE '"'
    )
""")

print(f"✅ Exported clean CSV: {out_path}")

✅ Exported clean CSV: ../data_processed/exports/final_thesis_outputs/thesis_musicbrainz_enrichment_master_v3.csv

In [94]:
import duckdb
import pandas as pd

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Build corrected thesis_musicbrainz_enrichment_master_v3
# ------------------------------------------------------------
# Comments:
# - Start from thesis_musicbrainz_enrichment_master_v1, because it already
#   contains the original recovered_mb_presence_review = 5 rows.
# - Rename that old route label to the cleaner thesis-facing name:
#     review_mb_enrichment_recovered
# - Then append only NEW recovered MB-review rows from
#   cds_mb_enrichment_review_v1 that are not already in v1.
# - Then append only the remaining true CDS-only review rows that are not
#   already present in v1.
print("Creating corrected thesis_musicbrainz_enrichment_master_v3...")

con.execute("""
    CREATE OR REPLACE TABLE thesis_musicbrainz_enrichment_master_v3 AS

    -- --------------------------------------------------------
    -- A. Start from v1 and rename the old recovered route label
    -- --------------------------------------------------------
    SELECT
        cds_id,
        artist,
        title,
        cds_year,
        category,
        genre,
        tracks,
        release_id,
        release_title,
        main_artist_name,
        artist_credit_full,
        total_tracks,
        barcode,
        mb_year,

        CASE
            WHEN enrichment_route = 'recovered_mb_presence_review'
                THEN 'review_mb_enrichment_recovered'
            ELSE enrichment_route
        END AS enrichment_route,

        enrichment_status
    FROM thesis_musicbrainz_enrichment_master_v1

    UNION ALL

    -- --------------------------------------------------------
    -- B. Add NEW recovered MB review rows not already in v1
    -- --------------------------------------------------------
    SELECT
        r.cds_id,
        r.cds_artist AS artist,
        r.cds_title AS title,
        r.cds_year,
        r.category,
        r.genre,
        r.cds_tracklist AS tracks,
        r.release_id,
        r.release_title,
        r.main_artist_name,
        r.artist_credit_full,
        r.total_tracks,
        r.barcode,
        r.mb_year,
        'review_mb_enrichment_recovered' AS enrichment_route,
        'review_mb_enrichment' AS enrichment_status
    FROM cds_mb_enrichment_review_v1 r
    WHERE r.cds_id NOT IN (
        SELECT DISTINCT cds_id
        FROM thesis_musicbrainz_enrichment_master_v1
    )

    UNION ALL

    -- --------------------------------------------------------
    -- C. Add remaining true CDS-only review rows not already in v1
    -- --------------------------------------------------------
    SELECT
        r.cds_id,
        r.artist,
        r.title,
        r.cds_year,
        c.category,
        c.genre,
        c.tracks,
        NULL AS release_id,
        NULL AS release_title,
        NULL AS main_artist_name,
        NULL AS artist_credit_full,
        NULL AS total_tracks,
        NULL AS barcode,
        NULL AS mb_year,
        'cds_only_review' AS enrichment_route,
        'new_cds_enrichment_review' AS enrichment_status
    FROM cds_only_enrichment_review_true_unmatched_v1 r
    LEFT JOIN cds c
      ON r.cds_id = c.cds_id
    WHERE r.cds_id NOT IN (
        SELECT DISTINCT cds_id
        FROM thesis_musicbrainz_enrichment_master_v1
    )
""")

print("✅ Table created: thesis_musicbrainz_enrichment_master_v3")

print("\n--- Final enrichment summary ---")
print(con.execute("""
    SELECT
        enrichment_status,
        COUNT(*) AS n,
        ROUND(100.0 * COUNT(*) / (SELECT COUNT(*) FROM thesis_musicbrainz_enrichment_master_v3), 2) AS pct
    FROM thesis_musicbrainz_enrichment_master_v3
    GROUP BY enrichment_status
    ORDER BY n DESC
""").fetchdf())

print("\n--- Breakdown by route ---")
print(con.execute("""
    SELECT
        enrichment_route,
        COUNT(*) AS n
    FROM thesis_musicbrainz_enrichment_master_v3
    GROUP BY enrichment_route
    ORDER BY n DESC
""").fetchdf())

print("\n--- Check recovered-review rows specifically ---")
print(con.execute("""
    SELECT
        enrichment_route,
        COUNT(*) AS n
    FROM thesis_musicbrainz_enrichment_master_v3
    WHERE enrichment_route = 'review_mb_enrichment_recovered'
    GROUP BY enrichment_route
""").fetchdf())

print("\n--- Preview ---")
print(con.execute("""
    SELECT *
    FROM thesis_musicbrainz_enrichment_master_v3
    LIMIT 30
""").fetchdf())

Connected ✅
Creating corrected thesis_musicbrainz_enrichment_master_v3...
✅ Table created: thesis_musicbrainz_enrichment_master_v3

--- Final enrichment summary ---
           enrichment_status     n    pct
0    confirmed_mb_enrichment  4214  46.96
1  new_cds_enrichment_review  2977  33.17
2         new_cds_enrichment  1646  18.34
3       review_mb_enrichment   137   1.53

--- Breakdown by route ---
                 enrichment_route     n
0                           exact  3482
1                 cds_only_review  2977
2                   cds_only_safe  1646
3               fuzzy_second_pass   543
4              various_title_only   183
5  review_mb_enrichment_recovered    94
6        matched_review_candidate    43
7           alias_enrichment_safe     3
8          enrichment_round2_auto     3

--- Check recovered-review rows specifically ---
                 enrichment_route   n
0  review_mb_enrichment_recovered  94

--- Preview ---
    cds_id                artist                            title  cds_year  \
0    10000       backstreet boys                       millennium      <NA>
1   100001               various      frankfurt trance vol 04 cd1      <NA>
2   100002             no return                  self mutilation      <NA>
3   100006      luv lite massive                         one love      <NA>
4   100008                  dmbq                             dmbq      2002
5   100010               various      frankfurt trance vol 05 cd1      <NA>
6   100012    rumania montevideo                 mo better tracks      <NA>
7   100015                 keedy                 chase the clouds      <NA>
8   100019            bill evans                            alone      1968
9   100020      nature destroyed                           shades      <NA>
10  100021             pearl jam                            yield      1998
11  100022     dingdong avanzado    the best of dingdong avanzado      <NA>
12  100024                  175r                            songs      2003
13  100026    day after tomorrow                         elements      2003
14  100031               spartak                            golem      1990
15  100035                gazebo               the best of gazebo      <NA>
16  100037  sportfreunde stiller                   die gute seite      <NA>
17  100039               various            salsaenlacalleocho 96      <NA>
18  100040     barbara streisand                 a love like ours      1999
19  100058             green day                           dookie      <NA>
20  100064                savage                          tonight      <NA>
21  100065      atmo brtschitsch                 change your life      <NA>
22  100066            del amitri                          twisted      1995
23  100082         barry mcguire               eve of destruction      1985
24  100087         tschou zã me                         wã ge dir      <NA>
25  100088         clive gregson                  comfort and joy      <NA>
26  100089       various artists                   dorival caymmi      <NA>
27  100094            keri noble                         fearless      2004
28  100097           north cregg                summer at my feet      2003
29  100099    fabienne thibeault  les plus belles chansons cd 2 2      <NA>

        category           genre  \
0          blues             pop
1           data            None
2           data            data
3           data      electronic
4           data            rock
5           data            None
6           data             pop
7           data            data
8           data            None
9           data            None
10          data       hard rock
11          data            None
12          data            jpop
13          data             pop
14          data      electronic
15          data            None
16          data            data
17  sonytsid7008            data
18          data  easy listening
19          data            None
20          data            None
21          data            None
22          data            rock
23          folk          oldies
24          folk            None
25          folk            None
26          folk            folk
27          folk             pop
28          folk            folk
29          folk            None

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          tracks  \
0                                                                                                                                                                                                                                                                               larger than life i want it that way show me the meaning of being lonely it s gotta be you i need you tonight don t want you back don t wanna lose you now the one back to your heart spanish eyes no one else comes close the perfect fan i ll be there for you
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           None
2                                                                                                                                                                                                                                                                                                                                                                                                  do or die truth and reality lost soul extractor sadistic desire the true way fanatic mind individualistic ideal one life trail of blood sect
3                                                                                                                                                                                                                                                                                                                                                                                                                              temple of dehli from naw till a mornin shock afghani lick you bad freestyle fiki fuko i m here yeah ww5 one love
4                                                                                                                                                                                                                                                                                                                                     small hours rock a cola ohh baby teenage limbo little leaf i movement little leaf ii swell little leaf iii etude sayonara no season altered rock can peace migrate to midnight e means eternal data track
5                                                                 dj tom stevens violet steam single cut liquid child diving faces original mix vimana we came edit lac terra after dark fridge vs vectrex remix steve baltes thoughts original mix star party i m in love ferry corsten robert smit rmx gate iv give all you got radio edit dj stigma baby sunshine stig s original club mix synchronic minds all i need club mix astral inc remember green court edit x trance friends 2000 tom stevens rmx ravelab send me an angel club mix
6                                                                                                                                                                                                                                                                                                                                                                             i ll be with you hard rain free tender rain rain sleeper life style taxi take my pain away my life album version all by myself start all over again album version
7                                                                                                                                                                                                                                                                                                                                                                                 save some love wishing on the same star never neverland sorry only your heart gettin around don t turn away pretty boy mama lazy day save some love hot remix
8                                                                                                                                                here s that rainy day a time for love midnight mood on a clear day you can see forever never let me go the two lonely people aka the man and the woman here s that rainy day alternative take a time for love alternative take midnight mood alternative take on a clear day you can see forever alternative take never let me go alternative take medley all the things you are midnight mood
9                                                                                                                                                                                                                                                                                                                                                                                                               enter the realm dream of fear word of trust unforeseen desire shades bound imprisoned cold vengeance disease leaving the shadow
10                                                                                                                                                                                                                                                                                                                                                                                              brain of j faithfull no way given to fly wishlist pilate do the evolution untitled mfc low light in hiding push me pull me all those yesterdays
11                                                                                                                                                                                                                                                                                                                                   ikaw lamang tatlong beinte singko maghihintay sa yo makapiling ka sana break kung break love at first sight basta t kasama kita paano sasabihin here i am i think i love you bakit hangang ngayon say amen
12                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          None
13                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          None
14                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          None
15                                                                                                                                                                                                                                                                                                i like chopin lunatic masterpiece dolce vita telephone mama sun goes down on milky way women come women go victims in paradise god bless the moonshade the fourteenth of july dancing with the moonlit knight trotsky burger waterland tycoon
16                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          None
17  1996 estamossolos jorgeluispiloto 1996 reyruiz hastaqueteconoci juangabriel 1996 marcanthony situsupieras omaralfanno 1996 giro laguagua candidofabre 1996 celiacruz hechocadoconlavida ivetteayala 1996 titorojas apiadatedemi omaralfanno 1996 victormanuelle quemaneradequererte emiliorios 1996 gilbertosantarosa quienerestu luisenriquemejia 1996 luisenrique nuncavoyaolvidarte robertobelester 1996 india gotasdelluvia jairovalera 1996 gruponiche otropoco mariofiaz 1996 puertoricanpower rumbera donatopoveda 1996 willychirino
18                                                                                                                                                                                                                                                                                                                  i ve dreamed of you isn t it a pity the island love like ours if you ever leave me we must be loving right if i never met you it must be you just one lifetime if i didn t love you wait the music that makes me dance data
19                                                                                                                                                                                                                                                                                                                                                                  burn out having a blast chump long view welcome to paradise pulling teeth basket case she sassafras roots when i come arround coming clean emenius sleepus in the end f o d
20                                                                                                                                                                                                                                                                                                                                   radio a love again fugitive tonight a love again remix don t cry tonight computerized love only you turn around time magic carillon instrumental don t cry tonight extended don t cry tonight instrumental
21                                                                                                                                                                                                                                                                                                                                                                                         everyday morningsun sittin green plane rockstar black sea some girls lucky people image stop taking always smiling coming home around me every night
22                                                                                                                                                                                                                                                                                                                    food for songs start with me here and now one thing left to do tell her this being somebody else roll to me crashing down it might as well be you never enough it s never too late to be alone driving with the brakes on
23                                                                                                                                                                                                                                                         eve of destruction she belongs to me you never had it so good sloop john b baby blue the sins of a family try to remember mr man on the street act one you were on my mind ain t no way i m gonna change my mind what exactly s the matter with me why not stop dig it while you can
24                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          None
25                                                                                                                                                                                                                                                                                                                                  frances o connor antidote fingerless gloves i m there for you it s you i want to hold if i was your lover catholic girl white suit of notes riding on a bus pretty peggy o string of pearls comfort and joy
26                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          None
27                                                                                                                                                                                                                                                                                                                                                                            look at me talk to me piece of my heart a dream about you about me let it rain falling love is all i know answered prayer bartender i won t if no one will listen

In [95]:
print(con.execute("""
    SELECT enrichment_status, COUNT(*) AS n
    FROM thesis_musicbrainz_enrichment_master_v3
    GROUP BY enrichment_status
    ORDER BY n DESC
""").fetchdf())

print(con.execute("""
    SELECT enrichment_route, COUNT(*) AS n
    FROM thesis_musicbrainz_enrichment_master_v3
    GROUP BY enrichment_route
    ORDER BY n DESC
""").fetchdf())

           enrichment_status     n
0    confirmed_mb_enrichment  4214
1  new_cds_enrichment_review  2977
2         new_cds_enrichment  1646
3       review_mb_enrichment   137
                 enrichment_route     n
0                           exact  3482
1                 cds_only_review  2977
2                   cds_only_safe  1646
3               fuzzy_second_pass   543
4              various_title_only   183
5  review_mb_enrichment_recovered    94
6        matched_review_candidate    43
7          enrichment_round2_auto     3
8           alias_enrichment_safe     3

In [96]:
import duckdb
import pandas as pd

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Verify exactly which cds_id values were excluded
# ------------------------------------------------------------
# Logic:
# - Naive expectation for v3 was:
#     rows in v1
#   + rows in cds_mb_enrichment_review_v1
#   + rows in cds_only_enrichment_review_true_unmatched_v1
# - But v3 excludes cds_id values already present in v1.
# - This cell shows exactly which overlapping cds_id values caused
#   the final total to be 4 rows lower than the naive sum.
print("--- Overlapping cds_id values excluded from later additions ---")

excluded_ids = con.execute("""
    WITH v1_ids AS (
        SELECT DISTINCT cds_id
        FROM thesis_musicbrainz_enrichment_master_v1
    ),
    later_additions AS (
        SELECT DISTINCT cds_id, 'cds_mb_enrichment_review_v1' AS source
        FROM cds_mb_enrichment_review_v1

        UNION ALL

        SELECT DISTINCT cds_id, 'cds_only_enrichment_review_true_unmatched_v1' AS source
        FROM cds_only_enrichment_review_true_unmatched_v1
    )
    SELECT
        l.cds_id,
        string_agg(l.source, ', ' ORDER BY l.source) AS overlapping_source
    FROM later_additions l
    JOIN v1_ids v
      ON l.cds_id = v.cds_id
    GROUP BY l.cds_id
    ORDER BY l.cds_id
""").fetchdf()

print(excluded_ids)

print(f"\nNumber of excluded overlapping cds_id values: {len(excluded_ids)}")

Connected ✅
--- Overlapping cds_id values excluded from later additions ---
   cds_id                            overlapping_source
0  103932  cds_only_enrichment_review_true_unmatched_v1
1  105165  cds_only_enrichment_review_true_unmatched_v1
2  108945  cds_only_enrichment_review_true_unmatched_v1

Number of excluded overlapping cds_id values: 3

In [97]:
print("--- Excluded cds_id values with CDS context ---")

print(con.execute("""
    WITH excluded_ids AS (
        WITH v1_ids AS (
            SELECT DISTINCT cds_id
            FROM thesis_musicbrainz_enrichment_master_v1
        ),
        later_additions AS (
            SELECT DISTINCT cds_id
            FROM cds_mb_enrichment_review_v1

            UNION

            SELECT DISTINCT cds_id
            FROM cds_only_enrichment_review_true_unmatched_v1
        )
        SELECT l.cds_id
        FROM later_additions l
        JOIN v1_ids v
          ON l.cds_id = v.cds_id
    )
    SELECT
        e.cds_id,
        c.artist,
        c.title,
        c.cds_year
    FROM excluded_ids e
    LEFT JOIN cds c
      ON e.cds_id = c.cds_id
    ORDER BY e.cds_id
""").fetchdf())

--- Excluded cds_id values with CDS context ---
   cds_id      artist               title  cds_year
0  103932  zã ramalho    grandes sucessos      <NA>
1  105165        gang  le radici e le ali      <NA>
2  108945     vivaldi    the four seasons      <NA>

In [98]:
import duckdb
import pandas as pd

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

print("--- Row count ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM cds_only_enrichment_weak_v1
""").fetchdf())

print("\n--- Preview ---")
print(con.execute("""
    SELECT *
    FROM cds_only_enrichment_weak_v1
    LIMIT 30
""").fetchdf())

print("\n--- Basic quality profile ---")
print(con.execute("""
    SELECT
        SUM(CASE WHEN artist IS NULL OR trim(artist) = '' THEN 1 ELSE 0 END) AS missing_artist,
        SUM(CASE WHEN title IS NULL OR trim(title) = '' THEN 1 ELSE 0 END) AS missing_title,
        SUM(CASE WHEN lower(coalesce(artist, '')) LIKE '%ã%'
               OR lower(coalesce(title, '')) LIKE '%ã%'
               OR lower(coalesce(tracks, '')) LIKE '%ã%'
            THEN 1 ELSE 0 END) AS obvious_mojibake_like,
        SUM(CASE WHEN length(coalesce(artist_key_clean, '')) < 3 THEN 1 ELSE 0 END) AS short_artist_key,
        SUM(CASE WHEN length(coalesce(title_key_clean, '')) < 3 THEN 1 ELSE 0 END) AS short_title_key
    FROM cds_only_enrichment_weak_v1
""").fetchdf())

print("\n--- Breakdown by route / type ---")
print(con.execute("""
    SELECT
        curation_route,
        cds_enrichment_type,
        COUNT(*) AS n
    FROM cds_only_enrichment_weak_v1
    GROUP BY curation_route, cds_enrichment_type
    ORDER BY n DESC
""").fetchdf())

Connected ✅
--- Row count ---
     n
0  196

--- Preview ---
    cds_id               artist                                    title  \
0   100048         the breeders                                      pod
1   100049      johnny hallyday                                    vol 4
2   100070          perseguidos                                      iii
3   100136            joan baez                                        5
4   100144             doe maar                                      4us
5   100224           edith piaf                                      n 3
6   100248         wilbury clan                                     live
7   100257               yarkin                                      ten
8   100270        dara bubamara                                     2001
9   100333  minstrels of mayhem                                      now
10  100371        pierre perret                                 ã ui lã
11  100390     mannik grigorian                                      van
12  100455    lucã a de la cruz                                    vol 0
13  100511    lucinho e luciano                                 volume 4
14  100539       enzo avitabile                                    addã²
15  100880   the big swing band                                    live
16  100923            soulciety                                    s t p
17  101096           boz scaggs                                      dig
18  101340     jazz at midnight                                     cd 5
19  101406      metallica live                                s m disk 2
20  101408                 v a            pisnicky jaroslava jezka a v w
21  101419      off road tracks                                   vol 71
22  101462              various  ã ã ã ã ãºãªãœ ã ã ã ã ã ã½ã ã ã ã ã ã²
23  101525            foreigner                                        4
24  101531               kohann                                      don
25  101600       book of mormon                                  disk 23
26  101602        ralph stanley                                   disc 4
27  101620       dance classics                                    vol 8
28  101645                  s h              jak hurvinek potkal mozarta
29  101709       bailar pegados                                     cd 2

    cds_year  \
0       1990
1       <NA>
2       2004
3       <NA>
4       <NA>
5       <NA>
6       <NA>
7       <NA>
8       2001
9       <NA>
10      2002
11      <NA>
12      <NA>
13      2001
14      1996
15      1998
16      <NA>
17      <NA>
18      2000
19      1999
20      <NA>
21      2003
22      1997
23      1981
24      2001
25      1995
26      1971
27      1997
28      2002
29      <NA>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    tracks  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    glorious doe happiness is a warm gun oh hellbound when i was a painter fortunately gone iris opened only in 3 s lime house metal man
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ma guitare hey joe san francisco mon p tit loup je serai lã je te promets noã l interdit je veux te graver dans ma vie aussi dur que du bois les mauvais garã ons ne me quitte pas oh ma jolie sarah
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       una aventura perdoname todo no me dejes quererla dejame te quiero de que forma si no te amara un siglo sin ti no le tengas compasion te he querido olvidar que voy a hacer contigo sigo loco data
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 there but for fortune stewball it ain t me babe the death of queen jane child no 170 bachianas brasileiras n 5 go way from my window i still miss someone when you hear them cuckoos hollerin birmingham sunday so we ll go no more a roving o cangaceiro the unquiet grave child no 78
4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               doe maar net alsof je loopt je lul achterna lajeninaja nooit meer slapen nachtzuster zoek het zelf maar maar uit 1 nacht alleen bang heroine pa alles gaat voorbij walska
5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           la goulante de pouvre jean t es beau tu sais les croix cri du coeur padam padam c est un homme terrible exodus mea culpa je me souviens d une chanson et pourtant le ã a ira mon menage a moi
6                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       part of me part of you sweet sweet smile but i do jagged edge of a broken heart subteranean homesick blues himbeereis zum frã¼hstã¼ck comes the time mary janes last dance driving my live away it s all over now baby blue helpless bye bye love
7                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     bulmaca rã ngala ã ster 1 kayip kã mlã k vakasi zeybek hã ha hu ã ster 2 gã z gã rãœãžmeyelã m sã s
8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              01dvojnica 02oko stola 03ako pozelis 04 7 gora 7 mora 05samo napred 06jace jace 07aj odlazi 08spremaj srce 09kilometri tuge 10sto zivota 11svi su tu 12dunav 13multimedija
9                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            johnny jump up hey ho she sails lannigan s ball keno blues wednesday mourn katie sings john barleycorn blue moon loch tay boat song pausa fermata karubushka
10                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cui lã la vivouza je te tue parfois l amour c est comme jã sus dealer le monsieur qui vend des canons la charcuterie mourir du tabac la mondialisation je ne suis jamais allã aux putes pour faire une bonne guerre loulou une minute de soleil en plus
11                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   kele lao anoush vatan aman maro maratouk astvadzadzin karabaghi ororotsayin krougner sourmalou bartsr sarer nino matis matnike dle yaman vardani mor voghbe lorik vana yergeri sharg
12                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               frente a frente tãº tienes la tristeza perdã³n por adorarte yo soy si me amaras si estarã s pensando en mi popurri de valses jaraneros envenenada celaje mis celos la pasionaria yo perdã el corazã³n pasito a pasito otra vez jaranero popurri de polkas maã anita lucerito gracia y donaire el palmero
13                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       o especialista deus ã justiã a o crente na fornalha calabouã o deus de elias coroa de espinho salmo 23 o povo de deus escarlate corinhos de fogo hora de deus convite para jesus
14                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  addo aizetã version vaco e vengo nun se jetta l ammore a pe isse terun acqua nfunn a via vogli o sole asteco e cielo lassol o ji aizete addã² version
15                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          l o v e splanky they say tennessee waltz the song is you what a difference a day made in the still of the night angel eyes american patrol canadian sunset i hear a rhapsody teach me tonight
16                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    intro get on the groove untitled break down with stp eaze back polymobil break stp express wicky wacky untitled break comin out to getcha make it phunkee t break trouble i ve seen
17                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     payday sarah miss riddle i just go get on the natch desire call that love king of el paso you re not vanishing point thanks to you
18                                                                                                                                                                                                                                                                                                                                                            ike qubec the man i love kenny burrell gee baby ain t i good to you george shearing when sunny gets blue lee konitz the gerry mulligan quartet too marvelous for words ike quebec how long has this been going on gerry mulligan quartet stardust herbie hancock and what if i don t know jay jay johnson it s you or no one mccoy tyner search for peace miles davis yesterday john coltrane i m old fashioned stanley turrentine a child is born sonny rollins namely you
19                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     nothing else matters until it sleeps for whom the bell tolls human wherever i may roam outlaw torn sad but true one enter sandman battery smashing pumpkins tonight tonight smashing pumpkins zero

In [99]:
import duckdb
import pandas as pd

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Salvage readable rows from the weak bucket
# ------------------------------------------------------------
# Comments:
# - Do NOT trust the whole weak table.
# - Keep only rows that are still readable and structurally usable enough
#   for manual review-level enrichment.
print("Creating cds_only_enrichment_weak_salvaged_v1...")

con.execute(r"""
    CREATE OR REPLACE TABLE cds_only_enrichment_weak_salvaged_v1 AS
    SELECT *
    FROM cds_only_enrichment_weak_v1
    WHERE
        artist IS NOT NULL
        AND trim(artist) <> ''
        AND title IS NOT NULL
        AND trim(title) <> ''
        AND length(coalesce(artist_key_clean, '')) >= 3
        AND length(coalesce(title_key_clean, '')) >= 3

        -- exclude obvious mojibake-like corruption
        AND NOT regexp_matches(lower(coalesce(artist, '')), '(ã|â|ð|�)')
        AND NOT regexp_matches(lower(coalesce(title, '')), '(ã|â|ð|�)')
        AND NOT regexp_matches(lower(coalesce(tracks, '')), '(ã|â|ð|�)')

        -- exclude ultra-generic weak titles
        AND lower(trim(coalesce(title, ''))) NOT IN (
            'vol 1', 'vol 2', 'vol 3', 'disc 1', 'disc 2', 'cd 1', 'cd 2'
        )
""")

print("✅ Table created: cds_only_enrichment_weak_salvaged_v1")

print("\n--- Salvaged weak rows ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM cds_only_enrichment_weak_salvaged_v1
""").fetchdf())

print("\n--- Preview salvaged weak rows ---")
print(con.execute("""
    SELECT
        cds_id,
        artist,
        title,
        cds_year,
        curation_route,
        enrichment_priority_v6,
        cds_enrichment_type
    FROM cds_only_enrichment_weak_salvaged_v1
    LIMIT 30
""").fetchdf())

Connected ✅
Creating cds_only_enrichment_weak_salvaged_v1...
✅ Table created: cds_only_enrichment_weak_salvaged_v1

--- Salvaged weak rows ---
    n
0  47

--- Preview salvaged weak rows ---
    cds_id                artist     title  cds_year  \
0   100048          the breeders       pod      1990
1   100070           perseguidos       iii      2004
2   100144              doe maar       4us      <NA>
3   100270         dara bubamara      2001      2001
4   100333   minstrels of mayhem       now      <NA>
5   100390      mannik grigorian       van      <NA>
6   100923             soulciety     s t p      <NA>
7   101096            boz scaggs       dig      <NA>
8   101957       antonio palombo       lui      <NA>
9   102155                  hint      dys       <NA>
10  102374          wave in head       you      2002
11  102551             jiri korn       tep      2002
12  102565     harry connick jr        she      <NA>
13  102697             section 3       now      1996
14  103222            yuji oniki       tvi      2001
15  103320                wiches     3 4 1      1994
16  103567            braindance       now      <NA>
17  103780            kid safari      wow       <NA>
18  103986           hungry lucy  glo cd1       2003
19  103996        franska bvnder      hon       <NA>
20  104166       young dubliners       red      2000
21  104203            faith hill       cry      <NA>
22  104278        maria bethania       mel      <NA>
23  104517              fishhook       red      <NA>
24  104603         peter gabriel       ovo      <NA>
25  104748              visitors       two      <NA>
26  104795                mansun       six      <NA>
27  104883           ali primera       ali      <NA>
28  104917              bee gees     e s p      1987
29  104969  michael stanley band       msb      <NA>

               curation_route enrichment_priority_v6   cds_enrichment_type
0                       other                    low  metadata_plus_tracks
1                       other                    low  metadata_plus_tracks
2                       other                    low     title_artist_only
3         standard_enrichment                   high  metadata_plus_tracks
4                       other                    low     title_artist_only
5                       other                    low     title_artist_only
6         standard_enrichment                   high     title_artist_only
7                       other                    low     title_artist_only
8                       other                    low     title_artist_only
9                       other                    low     title_artist_only
10                      other                    low  metadata_plus_tracks
11                      other                    low  metadata_plus_tracks
12                      other                    low     title_artist_only
13                      other                    low  metadata_plus_tracks
14                      other                    low  metadata_plus_tracks
15        standard_enrichment                   high  metadata_plus_tracks
16                      other                    low     title_artist_only
17                      other                    low     title_artist_only
18  special_disc_cd_vol_route                 medium  metadata_plus_tracks
19                      other                    low     title_artist_only
20                      other                    low  metadata_plus_tracks
21                      other                    low     title_artist_only
22                      other                    low     title_artist_only
23                      other                    low     title_artist_only
24                      other                    low     title_artist_only
25                      other                    low     title_artist_only
26                      other                    low     title_artist_only
27                      other                    low     title_artist_only
28        standard_enrichment                   high  metadata_plus_tracks
29                      other                    low     title_artist_only

In [100]:
import duckdb
import pandas as pd

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Weak-bucket handling:
# 1) try to recover MB presence from salvaged weak rows
# 2) keep recovered rows only as MB REVIEW enrichment
# 3) keep non-recovered salvaged rows as CDS-only REVIEW enrichment
# 4) put the rest back into excluded weak
# ------------------------------------------------------------
# Comments:
# - We do NOT create automatic enrichment from the weak bucket.
# - Even if a weak row is found in MusicBrainz, it stays review-only.
# - This is the conservative thesis-safe treatment.

# ------------------------------------------------------------
# Step 1: Recover MB-present rows from salvaged weak rows
# ------------------------------------------------------------
print("Creating cds_only_weak_recovered_mb_v1...")

con.execute("""
    CREATE OR REPLACE TABLE cds_only_weak_recovered_mb_v1 AS
    WITH weak_salvaged AS (
        SELECT
            w.cds_id,
            w.artist,
            w.title,
            w.cds_year,
            w.tracks,
            w.artist_key_clean,
            w.title_key_clean,
            w.curation_route,
            w.enrichment_priority_v6,
            w.cds_enrichment_type
        FROM cds_only_enrichment_weak_salvaged_v1 w
    ),
    mb_norm AS (
        SELECT
            m.release_id,
            m.release_title,
            m.main_artist_name,
            m.artist_credit_full,
            m.total_tracks,
            m.barcode,
            m.mb_year,
            lower(regexp_replace(coalesce(m.main_artist_name, ''), '[^a-zA-Z0-9]+', '', 'g')) AS mb_artist_key,
            lower(regexp_replace(coalesce(m.release_title, ''), '[^a-zA-Z0-9]+', '', 'g')) AS mb_title_key
        FROM mb_release_features m
    )
    SELECT
        w.cds_id,
        w.artist,
        w.title,
        w.cds_year,
        w.tracks,
        w.artist_key_clean,
        w.title_key_clean,
        w.curation_route,
        w.enrichment_priority_v6,
        w.cds_enrichment_type,

        m.release_id,
        m.release_title,
        m.main_artist_name,
        m.artist_credit_full,
        m.total_tracks,
        m.barcode,
        m.mb_year
    FROM weak_salvaged w
    JOIN mb_norm m
      ON w.artist_key_clean = m.mb_artist_key
     AND w.title_key_clean = m.mb_title_key
""")

print("✅ Table created: cds_only_weak_recovered_mb_v1")

print("\n--- Recovered candidate rows from salvaged weak ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM cds_only_weak_recovered_mb_v1
""").fetchdf())

print("\n--- Distinct CDS rows recovered from salvaged weak ---")
print(con.execute("""
    SELECT COUNT(DISTINCT cds_id) AS n
    FROM cds_only_weak_recovered_mb_v1
""").fetchdf())

# ------------------------------------------------------------
# Step 2: Rank recovered weak rows
# ------------------------------------------------------------
# Comments:
# - No track-gap is used because CDS tracks are text, not numeric count.
# - Rank by year plausibility + barcode presence.
print("\nCreating cds_only_weak_recovered_ranked_v1...")

con.execute("""
    CREATE OR REPLACE TABLE cds_only_weak_recovered_ranked_v1 AS
    WITH scored AS (
        SELECT
            r.*,

            CASE
                WHEN r.cds_year IS NOT NULL AND r.mb_year IS NOT NULL
                    THEN abs(r.cds_year - r.mb_year)
                ELSE NULL
            END AS year_gap,

            CASE
                WHEN r.barcode IS NOT NULL AND trim(r.barcode) <> '' THEN 1
                ELSE 0
            END AS has_barcode,

            CASE
                WHEN r.cds_year IS NOT NULL AND r.mb_year IS NOT NULL
                     AND abs(r.cds_year - r.mb_year) = 0 THEN 100
                WHEN r.cds_year IS NOT NULL AND r.mb_year IS NOT NULL
                     AND abs(r.cds_year - r.mb_year) = 1 THEN 90
                WHEN r.cds_year IS NOT NULL AND r.mb_year IS NOT NULL
                     AND abs(r.cds_year - r.mb_year) <= 3 THEN 75
                WHEN r.cds_year IS NOT NULL AND r.mb_year IS NOT NULL
                     AND abs(r.cds_year - r.mb_year) <= 5 THEN 60
                WHEN r.cds_year IS NOT NULL AND r.mb_year IS NULL THEN 40
                WHEN r.cds_year IS NULL AND r.mb_year IS NOT NULL THEN 30
                ELSE 20
            END
            +
            CASE
                WHEN r.barcode IS NOT NULL AND trim(r.barcode) <> '' THEN 5
                ELSE 0
            END AS recovery_rank_score
        FROM cds_only_weak_recovered_mb_v1 r
    ),
    ranked AS (
        SELECT
            *,
            ROW_NUMBER() OVER (
                PARTITION BY cds_id
                ORDER BY
                    recovery_rank_score DESC,
                    year_gap ASC NULLS LAST,
                    has_barcode DESC,
                    mb_year ASC NULLS LAST,
                    release_id
            ) AS rn,

            COUNT(*) OVER (
                PARTITION BY cds_id
            ) AS candidate_count,

            LEAD(recovery_rank_score) OVER (
                PARTITION BY cds_id
                ORDER BY
                    recovery_rank_score DESC,
                    year_gap ASC NULLS LAST,
                    has_barcode DESC,
                    mb_year ASC NULLS LAST,
                    release_id
            ) AS second_score
        FROM scored
    )
    SELECT
        *,
        recovery_rank_score - coalesce(second_score, 0) AS recovery_score_gap
    FROM ranked
""")

print("✅ Table created: cds_only_weak_recovered_ranked_v1")

print("\n--- Candidate count by CDS row ---")
print(con.execute("""
    SELECT
        cds_id,
        artist,
        title,
        candidate_count
    FROM cds_only_weak_recovered_ranked_v1
    WHERE rn = 1
    ORDER BY candidate_count DESC, cds_id
""").fetchdf())

# ------------------------------------------------------------
# Step 3: Weak rows found in MB -> REVIEW only
# ------------------------------------------------------------
print("\nCreating cds_mb_enrichment_weak_review_v1...")

con.execute("""
    CREATE OR REPLACE TABLE cds_mb_enrichment_weak_review_v1 AS
    SELECT
        r.cds_id,
        c.artist AS cds_artist,
        c.title AS cds_title,
        c.cds_year,
        c.category,
        c.genre,
        c.tracks AS cds_tracklist,

        r.release_id,
        r.release_title,
        r.main_artist_name,
        r.artist_credit_full,
        r.total_tracks,
        r.barcode,
        r.mb_year,

        r.year_gap,
        r.recovery_rank_score,
        r.recovery_score_gap,
        r.candidate_count,

        'weak_mb_review_recovered' AS match_type,
        'review_mb_enrichment' AS enrichment_status
    FROM cds_only_weak_recovered_ranked_v1 r
    LEFT JOIN cds c
      ON r.cds_id = c.cds_id
    WHERE r.rn = 1
""")

print("✅ Table created: cds_mb_enrichment_weak_review_v1")

print("\n--- Weak rows reclassified to MB review enrichment ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM cds_mb_enrichment_weak_review_v1
""").fetchdf())

# ------------------------------------------------------------
# Step 4: Salvaged weak rows not found in MB -> CDS-only REVIEW
# ------------------------------------------------------------
print("\nCreating cds_only_enrichment_weak_review_v1...")

con.execute("""
    CREATE OR REPLACE TABLE cds_only_enrichment_weak_review_v1 AS
    SELECT *
    FROM cds_only_enrichment_weak_salvaged_v1 s
    WHERE s.cds_id NOT IN (
        SELECT DISTINCT cds_id
        FROM cds_mb_enrichment_weak_review_v1
    )
""")

print("✅ Table created: cds_only_enrichment_weak_review_v1")

print("\n--- Salvaged weak rows kept as CDS-only review enrichment ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM cds_only_enrichment_weak_review_v1
""").fetchdf())

# ------------------------------------------------------------
# Step 5: Remaining weak rows stay excluded
# ------------------------------------------------------------
print("\nCreating cds_only_enrichment_weak_excluded_v2...")

con.execute("""
    CREATE OR REPLACE TABLE cds_only_enrichment_weak_excluded_v2 AS
    SELECT *
    FROM cds_only_enrichment_weak_v1 w
    WHERE w.cds_id NOT IN (
        SELECT DISTINCT cds_id
        FROM cds_mb_enrichment_weak_review_v1
    )
    AND w.cds_id NOT IN (
        SELECT DISTINCT cds_id
        FROM cds_only_enrichment_weak_review_v1
    )
""")

print("✅ Table created: cds_only_enrichment_weak_excluded_v2")

print("\n--- Final weak split summary ---")
print(con.execute("""
    SELECT 'mb_review_enrichment' AS bucket, COUNT(*) AS n
    FROM cds_mb_enrichment_weak_review_v1
    UNION ALL
    SELECT 'cds_only_review' AS bucket, COUNT(*) AS n
    FROM cds_only_enrichment_weak_review_v1
    UNION ALL
    SELECT 'excluded' AS bucket, COUNT(*) AS n
    FROM cds_only_enrichment_weak_excluded_v2
""").fetchdf())

print("\n--- Preview: weak MB review enrichment ---")
print(con.execute("""
    SELECT
        cds_id,
        cds_artist,
        cds_title,
        release_id,
        release_title,
        main_artist_name,
        cds_year,
        mb_year,
        year_gap,
        candidate_count,
        recovery_rank_score
    FROM cds_mb_enrichment_weak_review_v1
    ORDER BY cds_id
    LIMIT 20
""").fetchdf())

print("\n--- Preview: weak CDS-only review enrichment ---")
print(con.execute("""
    SELECT
        cds_id,
        artist,
        title,
        cds_year,
        curation_route,
        enrichment_priority_v6,
        cds_enrichment_type
    FROM cds_only_enrichment_weak_review_v1
    ORDER BY cds_id
    LIMIT 20
""").fetchdf())

print("\n--- Preview: weak excluded rows ---")
print(con.execute("""
    SELECT
        cds_id,
        artist,
        title,
        cds_year,
        curation_route,
        enrichment_priority_v6,
        cds_enrichment_type
    FROM cds_only_enrichment_weak_excluded_v2
    ORDER BY cds_id
    LIMIT 20
""").fetchdf())

Connected ✅
Creating cds_only_weak_recovered_mb_v1...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

✅ Table created: cds_only_weak_recovered_mb_v1

--- Recovered candidate rows from salvaged weak ---
    n
0  87

--- Distinct CDS rows recovered from salvaged weak ---
    n
0  23

Creating cds_only_weak_recovered_ranked_v1...
✅ Table created: cds_only_weak_recovered_ranked_v1

--- Candidate count by CDS row ---
    cds_id                artist  title  candidate_count
0   104203            faith hill    cry               12
1   104917              bee gees  e s p               12
2   100048          the breeders    pod               10
3   104795                mansun    six               10
4   106992             testament    low                7
5     6374               maxwell    now                6
6   100144              doe maar    4us                5
7   104603         peter gabriel    ovo                4
8   101096            boz scaggs    dig                3
9   102565     harry connick jr     she                3
10  105990            fur patrol    pet                2
11  108506         goo goo dolls    jed                2
12  100390      mannik grigorian    van                1
13  102155                  hint   dys                 1
14  102374          wave in head    you                1
15  103780            kid safari   wow                 1
16  104748              visitors    two                1
17  104969  michael stanley band    msb                1
18  105153          betty legler   now                 1
19  107001                  home    xiv                1
20  107192           varius manx    elf                1
21  107981            toni price    hey                1
22  108492       reinhard lakomy    aer                1

Creating cds_mb_enrichment_weak_review_v1...
✅ Table created: cds_mb_enrichment_weak_review_v1

--- Weak rows reclassified to MB review enrichment ---
    n
0  23

Creating cds_only_enrichment_weak_review_v1...
✅ Table created: cds_only_enrichment_weak_review_v1

--- Salvaged weak rows kept as CDS-only review enrichment ---
    n
0  24

Creating cds_only_enrichment_weak_excluded_v2...
✅ Table created: cds_only_enrichment_weak_excluded_v2

--- Final weak split summary ---
                 bucket    n
0  mb_review_enrichment   23
1       cds_only_review   24
2              excluded  149

--- Preview: weak MB review enrichment ---
    cds_id            cds_artist cds_title  release_id release_title  \
0     6374               maxwell       now      468105           Now
1   100048          the breeders       pod      549432           Pod
2   100144              doe maar       4us     1845096           4US
3   100390      mannik grigorian       van      814701           Van
4   101096            boz scaggs       dig      328216           Dig
5   102155                  hint      dys      1021190          Dys-
6   102374          wave in head       you      211318           You
7   102565     harry connick jr        she     1334546           She
8   103780            kid safari      wow       976538           Wow
9   104203            faith hill       cry     1269782           Cry
10  104603         peter gabriel       ovo      143383           OVO
11  104748              visitors       two     3021450           Two
12  104795                mansun       six       25243           Six
13  104917              bee gees     e s p      167806         E•S•P
14  104969  michael stanley band       msb       85136           MSB
15  105153          betty legler      now       380754          NOW!
16  105990            fur patrol       pet      175654           Pet
17  106992             testament       low     1467564           Low
18  107001                  home       xiv      152443           XIV
19  107192           varius manx       elf       24526           Elf

        main_artist_name  cds_year  mb_year  year_gap  candidate_count  \
0                Maxwell      2001     2019        18                6
1           The Breeders      1990     2011        21               10
2               Doe Maar      <NA>     2021      <NA>                5
3       Mannik Grigorian      <NA>     2011      <NA>                1
4             Boz Scaggs      <NA>     2021      <NA>                3
5                   Hint      <NA>     2016      <NA>                1
6           Wave in Head      2002     2017        15                1
7     Harry Connick, Jr.      <NA>     2020      <NA>                3
8             Kid Safari      <NA>     2025      <NA>                1
9             Faith Hill      <NA>     2016      <NA>               12
10         Peter Gabriel      <NA>     2025      <NA>                4
11              Visitors      <NA>     2021      <NA>                1
12                Mansun      <NA>     2012      <NA>               10
13              Bee Gees      1987     2018        31               12
14  Michael Stanley Band      <NA>     <NA>      <NA>                1
15          Betty Legler      <NA>     <NA>      <NA>                1
16            Fur Patrol      2000     2014        14                2
17             Testament      1994     2014        20                7
18                  Home      <NA>     2025      <NA>                1
19           Varius Manx      1995     2015        20                1

    recovery_rank_score
0                    25
1                    25
2                    35
3                    30
4                    35
5                    30
6                    25
7                    35
8                    30
9                    35
10                   35
11                   30
12                   35
13                   25
14                   20
15                   20
16                   20
17                   25
18                   35
19                   25

--- Preview: weak CDS-only review enrichment ---
    cds_id               artist     title  cds_year  \
0     7061      the descendents       all      <NA>
1     7469      the descendents       all      1987
2   100070          perseguidos       iii      2004
3   100270        dara bubamara      2001      2001
4   100333  minstrels of mayhem       now      <NA>
5   100923            soulciety     s t p      <NA>
6   101957      antonio palombo       lui      <NA>
7   102551            jiri korn       tep      2002
8   102697            section 3       now      1996
9   103222           yuji oniki       tvi      2001
10  103320               wiches     3 4 1      1994
11  103567           braindance       now      <NA>
12  103986          hungry lucy  glo cd1       2003
13  103996       franska bvnder      hon       <NA>
14  104166      young dubliners       red      2000
15  104278       maria bethania       mel      <NA>
16  104517             fishhook       red      <NA>
17  104883          ali primera       ali      <NA>
18  106198  gum pat mastelotto        gum      1999
19  107309   the rolling stones       now      1965

               curation_route enrichment_priority_v6   cds_enrichment_type
0                       other                    low     title_artist_only
1                       other                    low  metadata_plus_tracks
2                       other                    low  metadata_plus_tracks
3         standard_enrichment                   high  metadata_plus_tracks
4                       other                    low     title_artist_only
5         standard_enrichment                   high     title_artist_only
6                       other                    low     title_artist_only
7                       other                    low  metadata_plus_tracks
8                       other                    low  metadata_plus_tracks
9                       other                    low  metadata_plus_tracks
10        standard_enrichment                   high  metadata_plus_tracks
11                      other                    low     title_artist_only
12  special_disc_cd_vol_route                 medium  metadata_plus_tracks
13                      other                    low     title_artist_only
14                      other                    low  metadata_plus_tracks
15                      other                    low     title_artist_only
16                      other                    low     title_artist_only
17                      other                    low     title_artist_only
18                      other                    low  metadata_plus_tracks
19                      other                    low  metadata_plus_tracks

--- Preview: weak excluded rows ---
    cds_id                         artist                           title  \
0     2252  ãœã³ã ã ã ã ãªã international                ãœã³ã ã ã ã ãªã
1     4733  ãœã³ã ã ã ã ãªã international                ãœã³ã ã ã ã ãªã
2     8901         the five great guitars                            live
3     8919                            y t            yesterday today live
4     9083                            y t            yesterday today live
5    11008        hollywood film classics                          disk 1
6    11150         the five great guitars                            live
7   100049                johnny hallyday                           vol 4
8   100136                      joan baez                               5
9   100224                     edith piaf                             n 3
10  100248                   wilbury clan                            live
11  100257                         yarkin                             ten
12  100371                  pierre perret                        ã ui lã
13  100455              lucã a de la cruz                           vol 0
14  100511              lucinho e luciano                        volume 4
15  100539                 enzo avitabile                           addã²
16  100880             the big swing band                           live
17  101340               jazz at midnight                            cd 5
18  101406                metallica live                       s m disk 2
19  101408                           v a   pisnicky jaroslava jezka a v w

    cds_year             curation_route enrichment_priority_v6  \
0       2003        standard_enrichment                   high
1       2003        standard_enrichment                   high
2       2003         careful_enrichment                 medium
3       1991                      other                    low
4       1991                      other                    low
5       <NA>  special_disc_cd_vol_route                 medium
6       2003         careful_enrichment                 medium
7       <NA>  special_disc_cd_vol_route                 medium
8       <NA>                      other                    low
9       <NA>                      other                    low
10      <NA>         careful_enrichment                 medium
11      <NA>                      other                    low
12      2002        standard_enrichment                   high
13      <NA>  special_disc_cd_vol_route                 medium
14      2001  special_disc_cd_vol_route                 medium
15      1996        standard_enrichment                   high
16      1998         careful_enrichment                 medium
17      2000  special_disc_cd_vol_route                 medium
18      1999  special_disc_cd_vol_route                 medium
19      <NA>      special_various_route                    low

     cds_enrichment_type
0   metadata_plus_tracks
1   metadata_plus_tracks
2   metadata_plus_tracks
3   metadata_plus_tracks
4   metadata_plus_tracks
5      title_artist_only
6   metadata_plus_tracks
7      title_artist_only
8      title_artist_only
9      title_artist_only
10     title_artist_only
11     title_artist_only
12  metadata_plus_tracks
13     title_artist_only
14  metadata_plus_tracks
15  metadata_plus_tracks
16  metadata_plus_tracks
17  metadata_plus_tracks
18  metadata_plus_tracks
19     title_artist_only

In [101]:
import duckdb
import pandas as pd

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Extend the thesis master enrichment table with weak-review buckets
# ------------------------------------------------------------
# Comments:
# - We keep excluded weak rows OUTSIDE the final enrichment table.
# - We add only:
#     1) weak MB review enrichment
#     2) weak CDS-only review enrichment
# - This gives a fuller thesis-facing enrichment output without
#   pretending weak rows are safe or automatic.
print("Creating thesis_musicbrainz_enrichment_master_v4...")

con.execute("""
    CREATE OR REPLACE TABLE thesis_musicbrainz_enrichment_master_v4 AS

    -- --------------------------------------------------------
    -- A. Keep everything already present in v3
    -- --------------------------------------------------------
    SELECT *
    FROM thesis_musicbrainz_enrichment_master_v3

    UNION ALL

    -- --------------------------------------------------------
    -- B. Add weak rows that are present in MusicBrainz
    --    -> review-level MB enrichment only
    -- --------------------------------------------------------
    SELECT
        w.cds_id,
        w.cds_artist AS artist,
        w.cds_title AS title,
        w.cds_year,
        w.category,
        w.genre,
        w.cds_tracklist AS tracks,

        w.release_id,
        w.release_title,
        w.main_artist_name,
        w.artist_credit_full,
        w.total_tracks,
        w.barcode,
        w.mb_year,

        'review_mb_enrichment_weak' AS enrichment_route,
        'review_mb_enrichment_weak' AS enrichment_status
    FROM cds_mb_enrichment_weak_review_v1 w
    WHERE w.cds_id NOT IN (
        SELECT DISTINCT cds_id
        FROM thesis_musicbrainz_enrichment_master_v3
    )

    UNION ALL

    -- --------------------------------------------------------
    -- C. Add weak rows still not found in MusicBrainz
    --    -> review-level CDS-only enrichment
    -- --------------------------------------------------------
    SELECT
        w.cds_id,
        w.artist,
        w.title,
        w.cds_year,
        c.category,
        c.genre,
        c.tracks,

        NULL AS release_id,
        NULL AS release_title,
        NULL AS main_artist_name,
        NULL AS artist_credit_full,
        NULL AS total_tracks,
        NULL AS barcode,
        NULL AS mb_year,

        'cds_only_review_weak' AS enrichment_route,
        'new_cds_enrichment_review_weak' AS enrichment_status
    FROM cds_only_enrichment_weak_review_v1 w
    LEFT JOIN cds c
      ON w.cds_id = c.cds_id
    WHERE w.cds_id NOT IN (
        SELECT DISTINCT cds_id
        FROM thesis_musicbrainz_enrichment_master_v3
    )
""")

print("✅ Table created: thesis_musicbrainz_enrichment_master_v4")

print("\n--- Final enrichment summary ---")
print(con.execute("""
    SELECT
        enrichment_status,
        COUNT(*) AS n,
        ROUND(100.0 * COUNT(*) / (SELECT COUNT(*) FROM thesis_musicbrainz_enrichment_master_v4), 2) AS pct
    FROM thesis_musicbrainz_enrichment_master_v4
    GROUP BY enrichment_status
    ORDER BY n DESC
""").fetchdf())

print("\n--- Breakdown by route ---")
print(con.execute("""
    SELECT
        enrichment_route,
        COUNT(*) AS n
    FROM thesis_musicbrainz_enrichment_master_v4
    GROUP BY enrichment_route
    ORDER BY n DESC
""").fetchdf())

print("\n--- Total rows in v4 ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM thesis_musicbrainz_enrichment_master_v4
""").fetchdf())

print("\n--- Weak additions actually included ---")
print(con.execute("""
    SELECT 'mb_weak_review_added' AS bucket, COUNT(*) AS n
    FROM thesis_musicbrainz_enrichment_master_v4
    WHERE enrichment_route = 'review_mb_enrichment_weak'

    UNION ALL

    SELECT 'cds_weak_review_added' AS bucket, COUNT(*) AS n
    FROM thesis_musicbrainz_enrichment_master_v4
    WHERE enrichment_route = 'cds_only_review_weak'
""").fetchdf())

Connected ✅
Creating thesis_musicbrainz_enrichment_master_v4...
✅ Table created: thesis_musicbrainz_enrichment_master_v4

--- Final enrichment summary ---
                enrichment_status     n    pct
0         confirmed_mb_enrichment  4214  46.71
1       new_cds_enrichment_review  2977  33.00
2              new_cds_enrichment  1646  18.25
3            review_mb_enrichment   137   1.52
4  new_cds_enrichment_review_weak    24   0.27
5       review_mb_enrichment_weak    23   0.25

--- Breakdown by route ---
                  enrichment_route     n
0                            exact  3482
1                  cds_only_review  2977
2                    cds_only_safe  1646
3                fuzzy_second_pass   543
4               various_title_only   183
5   review_mb_enrichment_recovered    94
6         matched_review_candidate    43
7             cds_only_review_weak    24
8        review_mb_enrichment_weak    23
9           enrichment_round2_auto     3
10           alias_enrichment_safe     3

--- Total rows in v4 ---
      n
0  9021

--- Weak additions actually included ---
                  bucket   n
0   mb_weak_review_added  23
1  cds_weak_review_added  24

In [102]:
import os

os.makedirs("../data_processed/exports/final_thesis_outputs", exist_ok=True)

out_path = "../data_processed/exports/final_thesis_outputs/thesis_musicbrainz_enrichment_master_v4.csv"

con.execute(f"""
    COPY thesis_musicbrainz_enrichment_master_v4
    TO '{out_path}'
    WITH (HEADER, DELIMITER ',', QUOTE '"', ESCAPE '"')
""")

print(f"✅ Exported: {out_path}")

✅ Exported: ../data_processed/exports/final_thesis_outputs/thesis_musicbrainz_enrichment_master_v4.csv

In [103]:
import duckdb
from pathlib import Path

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Export all final thesis tables
# ------------------------------------------------------------
# Comments:
# - These are the final tables supporting the thesis results.
# - The exports are written as CSV files to a dedicated folder.
# - QUOTE/ESCAPE are set explicitly for safer CSV output.
export_dir = Path("../data_processed/exports/final_thesis_outputs")
export_dir.mkdir(parents=True, exist_ok=True)

final_tables = [
    
    "cds_mb_enrichment_review_v1",
    "cds_only_enrichment_safe_true_unmatched_v1",
    "cds_only_enrichment_review_true_unmatched_v1",
    "cds_mb_enrichment_weak_review_v1",
    "cds_only_enrichment_weak_review_v1",
    "cds_only_enrichment_weak_excluded_v2"
]

print("Exporting final thesis tables...\n")

for table in final_tables:
    out_path = export_dir / f"{table}.csv"
    con.execute(f"""
        COPY {table}
        TO '{out_path.as_posix()}'
        WITH (
            HEADER,
            DELIMITER ',',
            QUOTE '"',
            ESCAPE '"'
        )
    """)
    print(f"✅ Exported: {out_path.name}")

print("\nDone ✅")
print(f"Folder: {export_dir}")

Connected ✅
Exporting final thesis tables...

✅ Exported: cds_mb_enrichment_review_v1.csv
✅ Exported: cds_only_enrichment_safe_true_unmatched_v1.csv
✅ Exported: cds_only_enrichment_review_true_unmatched_v1.csv
✅ Exported: cds_mb_enrichment_weak_review_v1.csv
✅ Exported: cds_only_enrichment_weak_review_v1.csv
✅ Exported: cds_only_enrichment_weak_excluded_v2.csv

Done ✅
Folder: ..\data_processed\exports\final_thesis_outputs

In [104]:
import duckdb
from pathlib import Path

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Export all final thesis tables
# ------------------------------------------------------------
# Comments:
# - These are the final tables supporting the thesis results.
# - The exports are written as CSV files to a dedicated folder.
# - QUOTE/ESCAPE are set explicitly for safer CSV output.
export_dir = Path("../data_processed/exports")
export_dir.mkdir(parents=True, exist_ok=True)

final_tables = [
    
    "cds_unmatched_excluded_v1",
  
]


for table in final_tables:
    out_path = export_dir / f"{table}.csv"
    con.execute(f"""
        COPY {table}
        TO '{out_path.as_posix()}'
        WITH (
            HEADER,
            DELIMITER ',',
            QUOTE '"',
            ESCAPE '"'
        )
    """)
    print(f"✅ Exported: {out_path.name}")

print("\nDone ✅")
print(f"Folder: {export_dir}")

Connected ✅
✅ Exported: cds_unmatched_excluded_v1.csv

Done ✅
Folder: ..\data_processed\exports

In [132]:
import duckdb
import pandas as pd

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Build a MusicBrainz-centered release table enriched from CDS
# ------------------------------------------------------------
# Comments:
# - Base table: mb_release_features
# - Enrichment evidence: thesis_musicbrainz_enrichment_master_v4
# - We only use rows already linked to a MusicBrainz release
#   (release_id IS NOT NULL).
# - Since multiple CDS-derived enrichment rows may point to the same
#   MusicBrainz release, we choose exactly one "best" enrichment row
#   per release_id using a conservative ranking policy:
#       1) confirmed MB enrichment before review MB enrichment
#       2) non-weak routes before weak review routes
#       3) richer metadata preferred (genre/category/tracks/year)
#       4) stable tie-break by cds_id
# - Important correction:
#   enrichment_source and is_enriched_from_cds must only be set when
#   a CDS enrichment row actually exists for that release.
print("Creating corrected musicbrainz_release_enriched_from_cds_v1...")

con.execute("""
    CREATE OR REPLACE TABLE musicbrainz_release_enriched_from_cds_v1 AS
    WITH mb_evidence AS (
        SELECT
            e.*,

            -- ----------------------------------------------------
            -- Route priority:
            -- confirmed enrichment is strongest,
            -- then normal review,
            -- then weak review
            -- ----------------------------------------------------
            CASE
                WHEN e.enrichment_status = 'confirmed_mb_enrichment' THEN 1
                WHEN e.enrichment_status = 'review_mb_enrichment' THEN 2
                WHEN e.enrichment_status = 'review_mb_enrichment_weak' THEN 3
                ELSE 9
            END AS status_priority,

            -- ----------------------------------------------------
            -- Metadata richness:
            -- prefer rows that actually contribute more information
            -- ----------------------------------------------------
            (
                CASE WHEN e.category IS NOT NULL AND trim(e.category) <> '' THEN 1 ELSE 0 END +
                CASE WHEN e.genre IS NOT NULL AND trim(e.genre) <> '' THEN 1 ELSE 0 END +
                CASE WHEN e.tracks IS NOT NULL AND trim(e.tracks) <> '' THEN 1 ELSE 0 END +
                CASE WHEN e.cds_year IS NOT NULL THEN 1 ELSE 0 END
            ) AS metadata_richness

        FROM thesis_musicbrainz_enrichment_master_v4 e
        WHERE e.release_id IS NOT NULL
    ),
    ranked AS (
        SELECT
            *,
            ROW_NUMBER() OVER (
                PARTITION BY release_id
                ORDER BY
                    status_priority ASC,
                    metadata_richness DESC,
                    cds_year ASC NULLS LAST,
                    cds_id ASC
            ) AS rn,

            COUNT(*) OVER (
                PARTITION BY release_id
            ) AS source_record_count

        FROM mb_evidence
    )
    SELECT
        -- --------------------------------------------------------
        -- Original MusicBrainz release fields
        -- --------------------------------------------------------
        mb.release_id,
        mb.release_title,
        mb.barcode,
        mb.artist_credit_id,
        mb.artist_credit_full,
        mb.main_artist_name,
        mb.mb_year,
        mb.total_tracks,

        -- --------------------------------------------------------
        -- CDS-derived enrichment fields
        -- --------------------------------------------------------
        r.cds_id AS enrichment_cds_id,
        r.artist AS source_artist,
        r.title AS source_title,
        r.cds_year AS source_year,
        r.category AS enriched_category,
        r.genre AS enriched_genre,
        r.tracks AS external_tracklist,

        -- --------------------------------------------------------
        -- Provenance / enrichment metadata
        -- Only set if enrichment really exists
        -- --------------------------------------------------------
        r.enrichment_route,
        r.enrichment_status,

        CASE
            WHEN r.cds_id IS NOT NULL THEN 'CDS'
            ELSE NULL
        END AS enrichment_source,

        CASE
            WHEN r.cds_id IS NOT NULL THEN r.source_record_count
            ELSE NULL
        END AS source_record_count,

        CASE
            WHEN r.cds_id IS NOT NULL THEN TRUE
            ELSE FALSE
        END AS is_enriched_from_cds

    FROM mb_release_features mb
    LEFT JOIN ranked r
      ON mb.release_id = r.release_id
     AND r.rn = 1
""")

print("✅ Table created: musicbrainz_release_enriched_from_cds_v1")

print("\n--- Row count / uniqueness check ---")
print(con.execute("""
    SELECT
        COUNT(*) AS total_rows,
        COUNT(DISTINCT release_id) AS distinct_release_id,
        COUNT(*) - COUNT(DISTINCT release_id) AS duplicate_release_rows
    FROM musicbrainz_release_enriched_from_cds_v1
""").fetchdf())

print("\n--- Enrichment coverage report ---")
print(con.execute("""
    SELECT
        COUNT(*) AS mb_total_releases,
        COUNT(*) FILTER (WHERE is_enriched_from_cds = TRUE) AS mb_releases_with_cds_enrichment,
        ROUND(
            100.0 * COUNT(*) FILTER (WHERE is_enriched_from_cds = TRUE) / COUNT(*),
            4
        ) AS pct_enriched_from_cds
    FROM musicbrainz_release_enriched_from_cds_v1
""").fetchdf())

print("\n--- Preview: non-enriched rows should now have NULL source and FALSE flag ---")
print(con.execute("""
    SELECT
        release_id,
        release_title,
        enrichment_cds_id,
        enrichment_source,
        source_record_count,
        is_enriched_from_cds
    FROM musicbrainz_release_enriched_from_cds_v1
    WHERE enrichment_cds_id IS NULL
    LIMIT 20
""").fetchdf())

print("\n--- Preview: enriched rows ---")
print(con.execute("""
    SELECT
        release_id,
        release_title,
        main_artist_name,
        enriched_category,
        enriched_genre,
        enrichment_source,
        source_record_count,
        is_enriched_from_cds
    FROM musicbrainz_release_enriched_from_cds_v1
    WHERE is_enriched_from_cds = TRUE
    LIMIT 20
""").fetchdf())

Connected ✅
Creating corrected musicbrainz_release_enriched_from_cds_v1...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

✅ Table created: musicbrainz_release_enriched_from_cds_v1

--- Row count / uniqueness check ---
   total_rows  distinct_release_id  duplicate_release_rows
0     5309878              5309878                       0

--- Enrichment coverage report ---
   mb_total_releases  mb_releases_with_cds_enrichment  pct_enriched_from_cds
0            5309878                             4200                 0.0791

--- Preview: non-enriched rows should now have NULL source and FALSE flag ---
    release_id  \
0      2608361
1      2794510
2      2608364
3      2608363
4      2608362
5      1644640
6       463456
7      2608365
8      2782819
9      2787252
10     2788717
11     2787253
12     2777624
13     2750291
14     4965994
15     2766859
16     2785878
17     2608366
18     2912117
19     3237600

                                                                                       release_title  \
0                                                                               Farawaybutstillclose
1                                                                                    Tears of Winter
2                                                                                Humorous Intentions
3                                                                                       NOW or Never
4                                                                                               Song
5   Debussy: Cuarteto de cuerdas en sol menor, op. 10 / Zemlinsky: Cuarteto de cuerdas n.º 2, op. 15
6                                                                                            Forever
7                                                                                     King of Enigma
8                                                                                     I know, right?
9                                                                                         Party Girl
10                                                                                Cold in the Summer
11                                                                                    Do Not Disturb
12                                                                                          Stardust
13                                                                         Rip It Up 5 Track Sampler
14                                                                              This Game Needs Guns
15                                                                               Project 11 Volume 1
16                                                                                           Harbors
17                                                I Lost My Body: Original Motion Picture Soundtrack
18                                                                                           Corpsex
19                                                                                       Humans Fall

    enrichment_cds_id enrichment_source  source_record_count  \
0                <NA>              None                 <NA>
1                <NA>              None                 <NA>
2                <NA>              None                 <NA>
3                <NA>              None                 <NA>
4                <NA>              None                 <NA>
5                <NA>              None                 <NA>
6                <NA>              None                 <NA>
7                <NA>              None                 <NA>
8                <NA>              None                 <NA>
9                <NA>              None                 <NA>
10               <NA>              None                 <NA>
11               <NA>              None                 <NA>
12               <NA>              None                 <NA>
13               <NA>              None                 <NA>
14               <NA>              None                 <NA>
15               <NA>              None                 <NA>
16               <NA>              None                 <NA>
17               <NA>              None                 <NA>
18               <NA>              None                 <NA>
19               <NA>              None                 <NA>

    is_enriched_from_cds
0                  False
1                  False
2                  False
3                  False
4                  False
5                  False
6                  False
7                  False
8                  False
9                  False
10                 False
11                 False
12                 False
13                 False
14                 False
15                 False
16                 False
17                 False
18                 False
19                 False

--- Preview: enriched rows ---
    release_id                      release_title          main_artist_name  \
0      2924753  Festliche Panflöte zu Weihnachten            Paul Goldheart
1      2929619                    Das Taschentuch               Mike Krüger
2      2771631                       Forever Live                    Vaughn
3       372678                           So Close              Dina Carroll
4       946957       Superhero Swinger Undercover          Eight to the Bar
5      4406410                       Headin' Home  The Marty Warburton Band
6      1029331              A Legendary Performer             Woody Guthrie
7      2606270                       On the Rocks            The Byron Band
8      1031653                 The Silver Beatles               The Beatles
9       877999                      Disco Montego             Disco Montego
10     2922724    This Christmas I Spend with You             Robert Goulet
11     2617920                  The Main Language               René Shuman
12        2373            Duty Now for the Future                      DEVO
13      314501                   Back to Broadway          Barbra Streisand
14     2747638                        In the Mood           Various Artists
15      448784                       The Take Off                Solid Base
16      582406                       Past Masters               The Beatles
17     2771968                       The Best Of…                 Tom Jones
18      650805                        Blind Drive            Frank Carlberg
19      931253                  A & M Gold Series            Chuck Mangione

   enriched_category  enriched_genre enrichment_source  source_record_count  \
0          classical          gospel               CDS                    1
1               misc            None               CDS                    1
2               rock       hard rock               CDS                    1
3               rock             pop               CDS                    1
4               misc            None               CDS                    1
5               misc       bluegrass               CDS                    1
6               folk            None               CDS                    1
7               rock            rock               CDS                    1
8               rock        rock pop               CDS                    1
9             newage             pop               CDS                    1
10              rock  easy listening               CDS                    1
11              misc            None               CDS                    1
12              rock            None               CDS                    1
13              misc            None               CDS                    1
14              misc             r b               CDS                    1
15              rock           dance               CDS                    1
16              misc            None               CDS                    1
17        soundtrack             pop               CDS                    1
18              jazz            None               CDS                    1
19             blues            jazz               CDS                    1

    is_enriched_from_cds
0                   True
1                   True
2                   True
3                   True
4                   True
5                   True
6                   True
7                   True
8                   True
9                   True
10                  True
11                  True
12                  True
13                  True
14                  True
15                  True
16                  True
17                  True
18                  True
19                  True

In [133]:
import duckdb
con = duckdb.connect("../data_processed/thesis.duckdb")

# True enrichment count (no indentation)
result = con.execute("""
    SELECT 
        COUNT(*) AS total_releases,
        COUNT(*) FILTER (WHERE enrichment_status IS NOT NULL) AS actually_enriched,
        ROUND(100.0 * COUNT(*) FILTER (WHERE enrichment_status IS NOT NULL) / COUNT(*), 4) AS pct
    FROM musicbrainz_release_enriched_from_cds_v1
""").fetchdf()

print(result)

   total_releases  actually_enriched     pct
0         5309878               4200  0.0791

In [134]:
import duckdb
import pandas as pd

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Build a residual external enrichment table for CDS-only rows
# ------------------------------------------------------------
# Comments:
# - This table keeps enrichment evidence from CDS that could not be
#   safely linked to an existing MusicBrainz release.
# - These rows are still useful for the thesis because they represent
#   potential new external music-enrichment evidence.
# - We only use rows from the thesis master enrichment table where
#   release_id IS NULL, i.e. no confirmed MusicBrainz release link.
# - This table is separate from the MusicBrainz-centered enriched
#   release table because these records are not safe to merge directly
#   into mb_release_features.
print("Creating musicbrainz_external_residual_enrichment_v1...")

con.execute("""
    CREATE OR REPLACE TABLE musicbrainz_external_residual_enrichment_v1 AS
    SELECT
        -- --------------------------------------------------------
        -- External source identifiers / metadata
        -- --------------------------------------------------------
        cds_id AS external_record_id,
        artist AS external_artist,
        title AS external_title,
        cds_year AS external_year,
        category AS external_category,
        genre AS external_genre,
        tracks AS external_tracklist,

        -- --------------------------------------------------------
        -- Enrichment status / provenance
        -- --------------------------------------------------------
        enrichment_route,
        enrichment_status,
        'CDS' AS enrichment_source,

        -- --------------------------------------------------------
        -- Target-side placeholders:
        -- no confirmed MusicBrainz release was found
        -- --------------------------------------------------------
        NULL::BIGINT AS release_id,
        NULL::VARCHAR AS release_title,
        NULL::VARCHAR AS main_artist_name,
        NULL::VARCHAR AS artist_credit_full,
        NULL::BIGINT AS total_tracks,
        NULL::VARCHAR AS barcode,
        NULL::INTEGER AS mb_year,

        FALSE AS is_linked_to_musicbrainz

    FROM thesis_musicbrainz_enrichment_master_v4
    WHERE release_id IS NULL
""")

print("✅ Table created: musicbrainz_external_residual_enrichment_v1")

print("\n--- Row count ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM musicbrainz_external_residual_enrichment_v1
""").fetchdf())

print("\n--- Breakdown by enrichment status ---")
print(con.execute("""
    SELECT
        enrichment_status,
        COUNT(*) AS n
    FROM musicbrainz_external_residual_enrichment_v1
    GROUP BY enrichment_status
    ORDER BY n DESC
""").fetchdf())

print("\n--- Breakdown by enrichment route ---")
print(con.execute("""
    SELECT
        enrichment_route,
        COUNT(*) AS n
    FROM musicbrainz_external_residual_enrichment_v1
    GROUP BY enrichment_route
    ORDER BY n DESC
""").fetchdf())

print("\n--- Preview ---")
print(con.execute("""
    SELECT
        external_record_id,
        external_artist,
        external_title,
        external_year,
        external_category,
        external_genre,
        enrichment_route,
        enrichment_status,
        enrichment_source,
        is_linked_to_musicbrainz
    FROM musicbrainz_external_residual_enrichment_v1
    LIMIT 30
""").fetchdf())

Connected ✅
Creating musicbrainz_external_residual_enrichment_v1...
✅ Table created: musicbrainz_external_residual_enrichment_v1

--- Row count ---
      n
0  4647

--- Breakdown by enrichment status ---
                enrichment_status     n
0       new_cds_enrichment_review  2977
1              new_cds_enrichment  1646
2  new_cds_enrichment_review_weak    24

--- Breakdown by enrichment route ---
       enrichment_route     n
0       cds_only_review  2977
1         cds_only_safe  1646
2  cds_only_review_weak    24

--- Preview ---
    external_record_id                               external_artist  \
0               100004                                       emanuel
1               100028                               jazz signatures
2               100045                               matsuka phonics
3               100046                                    kool savas
4               100050                                       phallus
5               100062                            in vanity we trust
6               100069                             nikos hatzopoulos
7               100075                                buster b jones
8               100077                                 franz lambert
9               100085                                        primus
10              100090                                     gauchesco
11              100091                                 marco pereira
12              100095                                 peder persson
13              100100                                 sofi marinova
14              100106                                      dunaways
15              100110                                       ciãºnas
16              100111                                 isle of light
17              100112                                    holly near
18              100115                                      lj booth
19              100123                     eugene cole and persuaded
20              100127  franco bleve canto antico della nostra terra
21              100129                                   fnac choice
22              100142                                 garth wilwand
23              100145                                        guzman
24              100147                                  flipper dave
25              100154                                   james durst
26              100155                                   konstantina
27              100157                                  ivy markaity
28              100158                                     cucunandy
29              100162                                  daily planet

                              external_title  external_year external_category  \
0                                 felicidade           1998              data
1                            jazz signatures           1998              data
2                      let s study phonics 2           2002              data
3                  euer bester freund mix cd           2004              data
4                                     reason           2003              data
5                                       posh           1999              data
6                          the aegean violin           1996              data
7                       ballads barn burners           1999              folk
8   franz lambert spielt beliebte evergreens           1977              folk
9                                  juletoner           1995              folk
10                                 mano lima           2002              folk
11                                    elegia           1990              folk
12                               fã dselfest           2001              folk
13                            osadena liubov           2002              folk
14                             beautiful day           2003              folk
15                              celtic tiger           2001              folk
16                           winters welcome           2002              folk
17                      simply love disc one           2000              folk
18                the ox that pulls the cart           2002              folk
19                       he will work it out           1999              folk
20                        canzoni brindisine           1989              folk
21                           salute flamenco           2003              folk
22                     eyes of the hurricane           2001              folk
23                            guzmã n y cã a           1998              folk
24                              flipper dave           1995              folk
25                             like the wind           2000              folk
26                   i kaliteres stigmes mou           1997              folk
27                    world s not big enough           1997              folk
28                           contented minds           2001              folk
29                             the big scoop           1998              folk

   external_genre enrichment_route   enrichment_status enrichment_source  \
0            data    cds_only_safe  new_cds_enrichment               CDS
1            data    cds_only_safe  new_cds_enrichment               CDS
2            data    cds_only_safe  new_cds_enrichment               CDS
3     deutsch rap    cds_only_safe  new_cds_enrichment               CDS
4           metal    cds_only_safe  new_cds_enrichment               CDS
5        synthpop    cds_only_safe  new_cds_enrichment               CDS
6          ethnic    cds_only_safe  new_cds_enrichment               CDS
7            folk    cds_only_safe  new_cds_enrichment               CDS
8    instrumental    cds_only_safe  new_cds_enrichment               CDS
9          gospel    cds_only_safe  new_cds_enrichment               CDS
10           folk    cds_only_safe  new_cds_enrichment               CDS
11           folk    cds_only_safe  new_cds_enrichment               CDS
12           folk    cds_only_safe  new_cds_enrichment               CDS
13       pop folk    cds_only_safe  new_cds_enrichment               CDS
14         gospel    cds_only_safe  new_cds_enrichment               CDS
15          irish    cds_only_safe  new_cds_enrichment               CDS
16         celtic    cds_only_safe  new_cds_enrichment               CDS
17           folk    cds_only_safe  new_cds_enrichment               CDS
18           folk    cds_only_safe  new_cds_enrichment               CDS
19         gospel    cds_only_safe  new_cds_enrichment               CDS
20       folklore    cds_only_safe  new_cds_enrichment               CDS
21            pop    cds_only_safe  new_cds_enrichment               CDS
22      folk rock    cds_only_safe  new_cds_enrichment               CDS
23            pop    cds_only_safe  new_cds_enrichment               CDS
24           folk    cds_only_safe  new_cds_enrichment               CDS
25           folk    cds_only_safe  new_cds_enrichment               CDS
26           None    cds_only_safe  new_cds_enrichment               CDS
27           None    cds_only_safe  new_cds_enrichment               CDS
28         celtic    cds_only_safe  new_cds_enrichment               CDS
29       folklore    cds_only_safe  new_cds_enrichment               CDS

    is_linked_to_musicbrainz
0                      False
1                      False
2                      False
3                      False
4                      False
5                      False
6                      False
7                      False
8                      False
9                      False
10                     False
11                     False
12                     False
13                     False
14                     False
15                     False
16                     False
17                     False
18                     False
19                     False
20                     False
21                     False
22                     False
23                     False
24                     False
25                     False
26                     False
27                     False
28                     False
29                     False

In [135]:
import duckdb
import pandas as pd

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Build one unified base table for the next WebTable enrichment step
# ------------------------------------------------------------
# Comments:
# - This table combines:
#     1) MusicBrainz releases already enriched from CDS
#     2) MusicBrainz releases not enriched from CDS
#     3) residual external enrichment rows not yet linked to MusicBrainz
# - Goal:
#   create a single input table for the next WebTable enrichment phase.
# - Important correction:
#   rows coming from musicbrainz_release_enriched_from_cds_v1 are NOT all
#   "linked_mb_release". Some are enriched from CDS, others are simply
#   untouched MusicBrainz releases.
print("Creating corrected music_enrichment_base_for_webtables_v1...")

con.execute("""
    CREATE OR REPLACE TABLE music_enrichment_base_for_webtables_v1 AS

    -- --------------------------------------------------------
    -- A. All MusicBrainz release rows
    --    distinguish enriched vs not enriched
    -- --------------------------------------------------------
    SELECT
        CAST(release_id AS BIGINT) AS base_record_id,

        release_id,
        release_title,
        main_artist_name,
        artist_credit_full,
        barcode,
        mb_year,
        total_tracks,

        enrichment_cds_id AS external_record_id,
        source_artist AS external_artist,
        source_title AS external_title,
        source_year AS external_year,
        enriched_category AS external_category,
        enriched_genre AS external_genre,
        external_tracklist,

        enrichment_route,
        enrichment_status,
        enrichment_source,
        is_enriched_from_cds AS is_linked_to_musicbrainz,

        CASE
            WHEN is_enriched_from_cds = TRUE THEN 'mb_release_enriched_from_cds'
            ELSE 'mb_release_not_enriched'
        END AS base_record_status

    FROM musicbrainz_release_enriched_from_cds_v1

    UNION ALL

    -- --------------------------------------------------------
    -- B. External residual rows not linked to MusicBrainz
    -- --------------------------------------------------------
    SELECT
        CAST(external_record_id AS BIGINT) AS base_record_id,

        release_id,
        release_title,
        main_artist_name,
        artist_credit_full,
        barcode,
        mb_year,
        total_tracks,

        external_record_id,
        external_artist,
        external_title,
        external_year,
        external_category,
        external_genre,
        external_tracklist,

        enrichment_route,
        enrichment_status,
        enrichment_source,
        is_linked_to_musicbrainz,

        'external_residual' AS base_record_status

    FROM musicbrainz_external_residual_enrichment_v1
""")

print("✅ Table created: music_enrichment_base_for_webtables_v1")

print("\n--- Row count ---")
print(con.execute("""
    SELECT COUNT(*) AS n
    FROM music_enrichment_base_for_webtables_v1
""").fetchdf())

print("\n--- Breakdown by base record status ---")
print(con.execute("""
    SELECT
        base_record_status,
        COUNT(*) AS n
    FROM music_enrichment_base_for_webtables_v1
    GROUP BY base_record_status
    ORDER BY n DESC
""").fetchdf())

print("\n--- Linked vs not linked to MusicBrainz ---")
print(con.execute("""
    SELECT
        is_linked_to_musicbrainz,
        COUNT(*) AS n
    FROM music_enrichment_base_for_webtables_v1
    GROUP BY is_linked_to_musicbrainz
    ORDER BY n DESC
""").fetchdf())

print("\n--- Preview ---")
print(con.execute("""
    SELECT
        base_record_id,
        base_record_status,
        release_id,
        release_title,
        main_artist_name,
        external_record_id,
        external_artist,
        external_title,
        enrichment_status,
        enrichment_source,
        is_linked_to_musicbrainz
    FROM music_enrichment_base_for_webtables_v1
    LIMIT 30
""").fetchdf())

Connected ✅
Creating corrected music_enrichment_base_for_webtables_v1...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

✅ Table created: music_enrichment_base_for_webtables_v1

--- Row count ---
         n
0  5314525

--- Breakdown by base record status ---
             base_record_status        n
0       mb_release_not_enriched  5305678
1             external_residual     4647
2  mb_release_enriched_from_cds     4200

--- Linked vs not linked to MusicBrainz ---
   is_linked_to_musicbrainz        n
0                     False  5310325
1                      True     4200

--- Preview ---
    base_record_id       base_record_status  release_id  \
0          2608361  mb_release_not_enriched     2608361
1          2794510  mb_release_not_enriched     2794510
2          2608364  mb_release_not_enriched     2608364
3          2608363  mb_release_not_enriched     2608363
4          2608362  mb_release_not_enriched     2608362
5          1644640  mb_release_not_enriched     1644640
6           463456  mb_release_not_enriched      463456
7          2608365  mb_release_not_enriched     2608365
8          2782819  mb_release_not_enriched     2782819
9          2787252  mb_release_not_enriched     2787252
10         2788717  mb_release_not_enriched     2788717
11         2787253  mb_release_not_enriched     2787253
12         2777624  mb_release_not_enriched     2777624
13         2750291  mb_release_not_enriched     2750291
14         4965994  mb_release_not_enriched     4965994
15         2766859  mb_release_not_enriched     2766859
16         2785878  mb_release_not_enriched     2785878
17         2608366  mb_release_not_enriched     2608366
18         2912117  mb_release_not_enriched     2912117
19         3237600  mb_release_not_enriched     3237600
20         2608379  mb_release_not_enriched     2608379
21         2608370  mb_release_not_enriched     2608370
22         2792348  mb_release_not_enriched     2792348
23         2926812  mb_release_not_enriched     2926812
24         2779363  mb_release_not_enriched     2779363
25         2924743  mb_release_not_enriched     2924743
26         2608371  mb_release_not_enriched     2608371
27         4558665  mb_release_not_enriched     4558665
28         2773643  mb_release_not_enriched     2773643
29         2608375  mb_release_not_enriched     2608375

                                                                                       release_title  \
0                                                                               Farawaybutstillclose
1                                                                                    Tears of Winter
2                                                                                Humorous Intentions
3                                                                                       NOW or Never
4                                                                                               Song
5   Debussy: Cuarteto de cuerdas en sol menor, op. 10 / Zemlinsky: Cuarteto de cuerdas n.º 2, op. 15
6                                                                                            Forever
7                                                                                     King of Enigma
8                                                                                     I know, right?
9                                                                                         Party Girl
10                                                                                Cold in the Summer
11                                                                                    Do Not Disturb
12                                                                                          Stardust
13                                                                         Rip It Up 5 Track Sampler
14                                                                              This Game Needs Guns
15                                                                               Project 11 Volume 1
16                                                                                           Harbors
17                                                I Lost My Body: Original Motion Picture Soundtrack
18                                                                                           Corpsex
19                                                                                       Humans Fall
20                                                                                          Panamint
21                                                                                        Les Femmes
22                                                                                 Kaks Selget Silma
23                                                                                         演武 Ián-Bú
24                                                                                           Déjà Vu
25                                                                        The Best Reggae Hits Ever!
26                                                               Don't Let Nerds Take Over Your Life
27                                                                                      Dream Castle
28                                                                                             10002
29                                                                                   Alternate Takes

                         main_artist_name  external_record_id external_artist  \
0                                   Shoop                <NA>            None
1                  Colossal Trailer Music                <NA>            None
2   Tim Whitmer & The Kansas City Express                <NA>            None
3                             Taz Mondega                <NA>            None
4                               Kidstreet                <NA>            None
5                          Claude Debussy                <NA>            None
6                                  Smokie                <NA>            None
7                                   Sybyr                <NA>            None
8                               ayutthaya                <NA>            None
9                                   R3HAB                <NA>            None
10                              Young Guv                <NA>            None
11           Glands of External Secretion                <NA>            None
12                              Ike Moriz                <NA>            None
13                 Manic Street Preachers                <NA>            None
14                          She is Legend                <NA>            None
15                              Ellee Ven                <NA>            None
16                          Ellen Fullman                <NA>            None
17                               Dan Levy                <NA>            None
18                      Corpsefucking Art                <NA>            None
19                        Solemn Assembly                <NA>            None
20                                Ave Eva                <NA>            None
21                                  Esken                <NA>            None
22                           Velly Joonas                <NA>            None
23                               ChthoniC                <NA>            None
24           Crosby, Stills, Nash & Young                <NA>            None
25                        Various Artists                <NA>            None
26                           Prinzenallee                <NA>            None
27                          Tanning Salon                <NA>            None
28                              Donn Murk                <NA>            None
29                          Sonny Rollins                <NA>            None

   external_title enrichment_status enrichment_source  \
0            None              None              None
1            None              None              None
2            None              None              None
3            None              None              None
4            None              None              None
5            None              None              None
6            None              None              None
7            None              None              None
8            None              None              None
9            None              None              None
10           None              None              None
11           None              None              None
12           None              None              None
13           None              None              None
14           None              None              None
15           None              None              None
16           None              None              None
17           None              None              None
18           None              None              None
19           None              None              None
20           None              None              None
21           None              None              None
22           None              None              None
23           None              None              None
24           None              None              None
25           None              None              None
26           None              None              None
27           None              None              None
28           None              None              None
29           None              None              None

    is_linked_to_musicbrainz
0                      False
1                      False
2                      False
3                      False
4                      False
5                      False
6                      False
7                      False
8                      False
9                      False
10                     False
11                     False
12                     False
13                     False
14                     False
15                     False
16                     False
17                     False
18                     False
19                     False
20                     False
21                     False
22                     False
23                     False
24                     False
25                     False
26                     False
27                     False
28                     False
29                     False

In [136]:
import duckdb
from pathlib import Path

con = duckdb.connect("../data_processed/thesis.duckdb")
print("Connected ✅")

# ------------------------------------------------------------
# Export all final thesis tables
# ------------------------------------------------------------
# Comments:
# - These are the final tables supporting the thesis results.
# - The exports are written as CSV files to a dedicated folder.
# - QUOTE/ESCAPE are set explicitly for safer CSV output.
export_dir = Path("../data_processed/exports")
export_dir.mkdir(parents=True, exist_ok=True)

final_tables = [
    
    "musicbrainz_external_residual_enrichment_v1",
    "musicbrainz_release_enriched_from_cds_v1",
    "music_enrichment_base_for_webtables_v1"

  
]


for table in final_tables:
    out_path = export_dir / f"{table}.csv"
    con.execute(f"""
        COPY {table}
        TO '{out_path.as_posix()}'
        WITH (
            HEADER,
            DELIMITER ',',
            QUOTE '"',
            ESCAPE '"'
        )
    """)
    print(f"✅ Exported: {out_path.name}")

print("\nDone ✅")
print(f"Folder: {export_dir}")

Connected ✅
✅ Exported: musicbrainz_external_residual_enrichment_v1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

✅ Exported: musicbrainz_release_enriched_from_cds_v1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

✅ Exported: music_enrichment_base_for_webtables_v1.csv

Done ✅
Folder: ..\data_processed\exports

In [137]:
print(con.execute("""
    SELECT
        COUNT(*) AS overlap_n
    FROM music_enrichment_base_for_webtables_v1 a
    JOIN music_enrichment_base_for_webtables_v1 b
      ON a.base_record_id = b.base_record_id
    WHERE a.base_record_status = 'mb_release_enriched_from_cds'
      AND b.base_record_status = 'external_residual'
""").fetchdf())

   overlap_n
0         24

In [138]:
print(con.execute("""
    SELECT
        base_record_status,
        COUNT(*) AS n,
        SUM(CASE WHEN release_id IS NULL THEN 1 ELSE 0 END) AS rows_with_null_release_id,
        SUM(CASE WHEN release_id IS NOT NULL THEN 1 ELSE 0 END) AS rows_with_real_release_id
    FROM music_enrichment_base_for_webtables_v1
    GROUP BY base_record_status
    ORDER BY n DESC
""").fetchdf())

             base_record_status        n  rows_with_null_release_id  \
0       mb_release_not_enriched  5305678                        0.0
1             external_residual     4647                     4647.0
2  mb_release_enriched_from_cds     4200                        0.0

   rows_with_real_release_id
0                  5305678.0
1                        0.0
2                     4200.0

In [139]:
print(con.execute("""
    SELECT 'mb_linked_in_master_v4' AS bucket, COUNT(*) AS n
    FROM thesis_musicbrainz_enrichment_master_v4
    WHERE release_id IS NOT NULL

    UNION ALL

    SELECT 'external_residual_in_master_v4' AS bucket, COUNT(*) AS n
    FROM thesis_musicbrainz_enrichment_master_v4
    WHERE release_id IS NULL
""").fetchdf())

                           bucket     n
0          mb_linked_in_master_v4  4374
1  external_residual_in_master_v4  4647

In [140]:
print(con.execute("""
SELECT 
    COUNT(*) AS enriched_count,
FROM music_enrichment_base_for_webtables_v1
WHERE base_record_status = 'mb_release_enriched_from_cds';
""").fetchdf())

   enriched_count
0            4200

In [141]:
print(con.execute("""
    SELECT *
    FROM musicbrainz_release_enriched_from_cds_v1
    WHERE release_id = 1726393
""").fetchdf())

   release_id release_title barcode  artist_credit_id    artist_credit_full  \
0     1726393      Die Hard    None           1127198  The Wolves of Avalon

       main_artist_name  mb_year  total_tracks  enrichment_cds_id  \
0  The Wolves of Avalon     2016           2.0               <NA>

  source_artist source_title  source_year enriched_category enriched_genre  \
0          None         None         <NA>              None           None

  external_tracklist enrichment_route enrichment_status enrichment_source  \
0               None             None              None              None

   source_record_count  is_enriched_from_cds
0                 <NA>                 False

In [142]:
print(con.execute("""
    SELECT *
    FROM music_enrichment_base_for_webtables_v1
    WHERE release_id = 1726393
""").fetchdf())

   base_record_id  release_id release_title      main_artist_name  \
0         1726393     1726393      Die Hard  The Wolves of Avalon

     artist_credit_full barcode  mb_year  total_tracks  external_record_id  \
0  The Wolves of Avalon    None     2016           2.0                <NA>

  external_artist external_title  external_year external_category  \
0            None           None           <NA>              None

  external_genre external_tracklist enrichment_route enrichment_status  \
0           None               None             None              None

  enrichment_source  is_linked_to_musicbrainz       base_record_status
0              None                     False  mb_release_not_enriched

In [143]:
print(con.execute("""
    SELECT release_id, release_title, main_artist_name, mb_year, barcode, total_tracks
    FROM mb_release_features
    WHERE release_id IN (1726393, 726393)
""").fetchdf())

   release_id         release_title      main_artist_name  mb_year  \
0     1726393              Die Hard  The Wolves of Avalon     2016
1      726393  Ghost in the Machine            The Police     2026

        barcode  total_tracks
0          None           2.0
1  606949365523          12.0

In [144]:
print(con.execute("""
    SELECT
        release_id,
        release_title,
        main_artist_name,
        barcode,
        mb_year,
        total_tracks,
        enriched_category,
        enriched_genre,
        is_enriched_from_cds
    FROM musicbrainz_release_enriched_from_cds_v1
    WHERE lower(release_title) = 'ghost in the machine'
      AND lower(main_artist_name) = 'the police'
    ORDER BY release_id
""").fetchdf())

    release_id         release_title main_artist_name         barcode  \
0         7907  Ghost in the Machine       The Police     07502137302
1       397051  Ghost in the Machine       The Police    606949359829
2       577748  Ghost in the Machine       The Police    075021373020
3       577749  Ghost in the Machine       The Police    075021373020
4       726393  Ghost in the Machine       The Police    606949365523
5      1099303  Ghost in the Machine       The Police   4988005501851
6      1156586  Ghost in the Machine       The Police
7      1268744  Ghost in the Machine       The Police    606949364625
8      1271585  Ghost in the Machine       The Police    082839373029
9      1282532  Ghost in the Machine       The Police
10     1726073  Ghost in the Machine       The Police   4988005329875
11     1885651  Ghost in the Machine       The Police
12     2215274  Ghost in the Machine       The Police
13     2328216  Ghost in the Machine       The Police   4988013357631
14     2370119  Ghost in the Machine       The Police
15     3154912  Ghost in the Machine       The Police            None
16     3446944  Ghost in the Machine       The Police
17     3493447  Ghost in the Machine       The Police  00602577828232
18     3498310  Ghost in the Machine       The Police    082839373029
19     3628455  Ghost in the Machine       The Police   4988031436332
20     3879391  Ghost in the Machine       The Police
21     3965290  Ghost in the Machine       The Police    602508046155
22     4045293  Ghost in the Machine       The Police  00600753731734
23     4359395  Ghost in the Machine       The Police
24     4434373  Ghost in the Machine       The Police    602445732487
25     4714472  Ghost in the Machine       The Police

    mb_year  total_tracks enriched_category enriched_genre  \
0      2024          11.0              misc           None
1      2015          11.0              None           None
2      2011          11.0              None           None
3      2011          11.0              None           None
4      2026          12.0              None           None
5      2023          11.0              None           None
6      2025          11.0              None           None
7      2015          22.0              None           None
8      2024          11.0              None           None
9      2015          11.0              None           None
10     2016          11.0              None           None
11     2021          11.0              None           None
12     2019          11.0              None           None
13     2019          11.0              None           None
14     2019          11.0              None           None
15     2023          11.0              None           None
16     2022          11.0              None           None
17     2023          11.0              None           None
18     2022          11.0              None           None
19     2023          11.0              None           None
20     2023          11.0              None           None
21     2024          11.0              None           None
22     2023          11.0              None           None
23     2024          11.0              None           None
24     2024          14.0              None           None
25     2024          11.0              None           None

    is_enriched_from_cds
0                   True
1                  False
2                  False
3                  False
4                  False
5                  False
6                  False
7                  False
8                  False
9                  False
10                 False
11                 False
12                 False
13                 False
14                 False
15                 False
16                 False
17                 False
18                 False
19                 False
20                 False
21                 False
22                 False
23                 False
24                 False
25                 False

In [145]:
con.close()

In [5]:
import duckdb

# Connect to your database
con = duckdb.connect("../data_processed/thesis.duckdb")

# Show all tables
tables_df = con.execute("SHOW TABLES;").fetchdf()
print(tables_df)

con.close()

                                  name
0                   best_fuzzy_per_cds
1                                  cds
2           cds_artist_alias_bridge_v1
3                      cds_enriched_v6
4                      cds_enriched_v7
..                                 ...
98                            mb_norm3
99                          mb_release
100                mb_release_features
101              mb_title_only_cleaned
102  mb_various_title_integration_view

[103 rows x 1 columns]

In [3]:
import duckdb

# Connect to your thesis database
con = duckdb.connect("../data_processed/thesis.duckdb")

# Query DuckDB's internal system to show all tables and their estimated row counts
query = """
    SELECT 
        table_name, 
        estimated_size AS row_count
    FROM duckdb_tables()
    ORDER BY estimated_size DESC;
"""

# Fetch the results as a pandas DataFrame and print it
tables_df = con.execute(query).fetchdf()
print(tables_df)

# Always good practice to close the connection!
con.close()

                                  table_name  row_count
0                         cds_mb_fuzzy_pairs   11904344
1                    cds_mb_enrichment_pairs   11873845
2          cds_mb_enrichment_pairs_v6_round2    9898596
3               cds_mb_curated_main_pairs_v1    8796214
4                      mb_artist_credit_name    6642750
..                                       ...        ...
82             cds_generic_scored_candidates         14
83                 cds_generic_mb_candidates         14
84  cds_to_mb_best_enrichment_v6_round2_auto          5
85           cds_to_mb_generic_title_safe_v1          4
86                    cds_generic_best_match          3

[87 rows x 2 columns]